### ISSUE TITLE
Hover events on SVG overlay

### ISSUE THREAD

**Issue by erikguntner** [visgl/react-map-gl#1014]
I am currently working on an application where I am using the SVGOverlay component to draw a path from an array of coordinates. I am trying to access the map context to retrieve the point on the map when I either Hover/MouseOver the path, but currently it looks like this isn't available for SVG Overlays. Is there a way to accomplish this using the SVG Overlay? Or do I need to render the path a different way?

Thanks.

**Comment by Pessimistress** [comment]
You can construct a [WebMercatorViewport](http://visgl.github.io/react-map-gl/docs/api-reference/web-mercator-viewport) to perform unprojection.
