### ISSUE TITLE
[QUESTION] Clustering non-numeric markers

### ISSUE THREAD

**Issue by angelod1as** [visgl/react-map-gl#1016]
I have a map with a few markers on it.

![image](https://user-images.githubusercontent.com/13950513/73949001-8cc3cf00-48d8-11ea-89e8-a03f1e8b61b8.png)

When I zoom out they get over each other.

![image](https://user-images.githubusercontent.com/13950513/73949039-99482780-48d8-11ea-9221-f127d5f177b9.png)

Is there a way to cluster these (for example, choosing one of them or a custom symbol with a number of "inside markers")?

**Comment by Pessimistress** [comment]
#507

**Comment by Pessimistress** [comment]
@MarkLyck it is moved to a Discussion thread, please follow the link on the issue. We no longer use issues to track open discussions.
