### ISSUE TITLE
Open Ring GeoJSON Inconsistent Rendering

### ISSUE THREAD

**Issue by DrewWeth** [visgl/react-map-gl#1019]
Im trying to render a GeoJSON source, but some of the data Im rendering contains coordinates with an open ring (coordinates don't start and end with the same values). When the map re-renders from zooming it and out, it switches between rendering broken and valid polygons.

Is there a helper method I can use to close rings in all the GeoJSON types? I can't find methods in react-map-gl or turf.

The polygon breaks when zooming in and out.
<img width="515" alt="Screen Shot 2020-02-06 at 11 03 32 PM" src="https://user-images.githubusercontent.com/4162957/74003293-b8c26d00-4937-11ea-856d-0fe7be066da8.png">
<img width="672" alt="Screen Shot 2020-02-06 at 11 03 38 PM" src="https://user-images.githubusercontent.com/4162957/74003295-bb24c700-4937-11ea-96fd-c3d9948d64e2.png">

**Comment by Pessimistress** [comment]
react-map-gl doesn't handle GeoJSON. It is directly passed to mapbox-gl.

You may need to normalize your polygons yourself. I believe only the `Polygon` and `MultiPolygon` geometry types need this.
