### ISSUE TITLE
NavigationControl Compass update bearing and pitch

### ISSUE THREAD

**Issue by mohridwanhdp** [visgl/react-map-gl#1026]
How can I use compass to change my map pitch / bearing like compass in mapbox Navigation Control.

Because the current version just resetting the map view.

Anyone have an idea?

**Comment by bilafish** [comment]
@mohridwanhdp Seems that the main Mapbox map canvas already allows changing of pitch and bearing already by default. Currently, the implementation in react-map-gl for the compass button doesn't support drag events I believe (See src/components/navigation-control.js of react-map-gl repo) as there's no event listeners for drag events.
