### ISSUE TITLE
Map becomes blank when click a icon to zoom ?

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [visgl/react-map-gl#1034]
Hi,

I made a drill down map. It shows the state-wise count. While clicking the marker it drills down and shows the city-wise count. After clicking the city-wise count I am not passing any data to it. so there is no zoom value. so it picks the previous zoom count and breaks the view of the map. 

please visit this URL : ```https://codesandbox.io/s/mapbox-test-ojunc```

I made a sample drill down map with sample data.

Please help me with that.

Thanks

**Comment by DhanushkumarSivaji** [comment]
Any way to handle zoom dynamically?

**Comment by 97morningstar** [comment]
How did you fixed this?

**Comment by DhanushkumarSivaji** [comment]
please visit the above mentioned codepen. u can find the code..

**Comment by DhanushkumarSivaji** [comment]
> How did you fixed this?

please visit the above mentioned codesandbox. u can find the code..
