### ISSUE TITLE
Can't get right lngLat coordinates - NextJs

### ISSUE THREAD

**Issue by DanyDes** [visgl/react-map-gl#1043]
I want to add markers when click over the map. I can get de lngLat after handling the onClick event, but the longitude and latitude that I get are out of range. For example, the longitude when clicked in Sri Lanka above the Indian Ocean has the value of 297.28125080466083 and I consider is out of -180 to 180.

This is the code, I don't know if I'm missing something.

```javascript
import React, { useState } from 'react';
import InteractiveMap, { Marker } from 'react-map-gl';

const Token = 'pk.eyJ1Ijoic3A0cmytokenhereCuL1fBm1qkIQ';
const App = () => {
    const [viewport, setViewport] = useState({
        latitude: -16.503729,
        longitude: -68.135209,
        zoom: 1
    });
    const [markers, setMarkers] = React.useState([]);
    const handleClick = ({ lngLat: [longitude, latitude] }) => {
        console.log(longitude, latitude);
        setMarkers(markers => [...markers, { longitude, latitude }]);
    };

    return (
        <InteractiveMap
            viewState={viewport}
            width='100vw'
            height='100vh'
            onViewportChange={newViewport => setViewport(newViewport)}
            onClick={handleClick}
            mapboxApiAccessToken={Token}
        >
            {markers.map((m, i) => (
                <Marker {...m} key={i}>
                    click
                </Marker>
            ))}
        </InteractiveMap>
    );
};

export default App;
```

My dependencies:
```json
"dependencies": {
    "next": "9.2.2",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-map-gl": "^5.2.3",
  }
```

**Comment by bounouidarhamza** [comment]
Hello Dany,
Can i make a pull-request to see if i can ifure out what's going on :)

**Comment by DanyDes** [comment]
Sure, I would really appreciate your help.

https://github.com/DanyDes/next-mapbox-example.git

**Comment by Pessimistress** [comment]
You can add/remove 360 from the longitude to bring it into range. This happens when multiple copies of the world are rendered and some users need this behavior to tell which copy has been clicked.

**Comment by DanyDes** [comment]
Is there any way to disable that behavior? Latitude also takes other values that don't correspond.

**Comment by Pessimistress** [comment]
Latitude should always be between -90 and 90. If you are seeing otherwise can you make a Code Sandbox example?

**Comment by garretteklof** [comment]
@Pessimistress I'm running into the same issue with nonsensical latitude and longitude values from `e.lngLat`. I'm too using Next.js, however the issue seems to derive from using `viewState` and `onViewStateChange` as opposed to `onViewportChange`. Here is a CodeSandbox that logs values to the console on Map click. Note that switching to the `onViewportChange` pattern gives the correct values.

https://codesandbox.io/s/prod-http-puhmy

I've recently adopted this library, and was under the impression that `viewState` was synonymous, however if this is incorrect please let me know. Thank you!

**Comment by Pessimistress** [comment]
Fixed in 5.3.8/6.1.8

**Comment by garretteklof** [comment]
Many 🙏  for the expediency!

**Comment by garretteklof** [comment]
Many 🙏 for the expeditiousness!

**Comment by jalalmanafi** [comment]
@DanyDes I know it is too let to warn, but do not share your token, it is dangerous :)
