### ISSUE TITLE
AutoSizer Over Rendering Due to Prop Reassignment

### ISSUE THREAD

**Issue by ctaylor4874** [visgl/react-map-gl#1048]
It seems that this bit of code is over-rendering because its children are being redefined on every render, causing props to change and the component to update. 

 https://github.com/uber/react-map-gl/blob/68aa89d311f32008d49af1403f69fbabd07adec7/src/components/static-map.js#L311-L318

Here are the results from using `@welldone-software/why-did-you-render`.

![Screen Shot 2020-03-11 at 3 53 48 PM](https://user-images.githubusercontent.com/8881198/76462926-81b8fe80-63b0-11ea-96d6-e35ee1c6c4d1.png)

**Comment by Pessimistress** [comment]
This is intentional. The content of the AutoSizer needs to be rerendered on any prop change, not just resize. Otherwise, anything in the overlays will not update until you resize the window.
