### ISSUE TITLE
Map is not always responsive to pinch zooming on mobile

### ISSUE THREAD

**Issue by Gopid** [visgl/react-map-gl#1054]
[mapbox-gl](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/) runs just fine but when I add a map using react-map-gl the map is not always responsive to pinch zooming. Not trying to render anything crazy, can see this happening with the [getting started example](https://uber.github.io/react-map-gl/docs/get-started/get-started)

**Comment by davidnx** [comment]
@Gopid I tracked this down to an issue in Mjolnir.js. I reported a bug and suggested a fix here: https://github.com/uber-web/mjolnir.js/issues/57

**Comment by axleun** [comment]
I have the same issue, except that in my case not only is pinch zooming not always responsive, even when I try to pan it will freeze every few times I try, any ideas?

**Comment by axleun** [comment]
> @Gopid I tracked this down to an issue in Mjolnir.js. I reported a bug and suggested a fix here: [uber-web/mjolnir.js#57](https://github.com/uber-web/mjolnir.js/issues/57)

I tried this approach, I didn't seem to solve the issue. I can't pinch zoom, any ideas?

**Comment by Pessimistress** [comment]
The proposed change is published in mjolnir.js@2.4.1. @axleun Can you try remove your local lock file, reinstall dependencies and see if the behavior is improved?

**Comment by alex-dolbik** [comment]
@Pessimistress Nothing changed for me as well. I updated packages. I'm using mjolnir.js@2.4.1 and see @davidnx changes in the file

![image](https://user-images.githubusercontent.com/10628158/80690985-409fb980-8ad8-11ea-89e4-503bf781827a.png)

**Comment by davidnx** [comment]
@Pessimistress thanks, the fix worked great for me and I've been able to remove the work-around I had prior. Verified on `react-map-gl@5.2.5`
