### ISSUE TITLE
How to dynamically change label language with react-map-gl?

### ISSUE THREAD

**Issue by oahmaro** [visgl/react-map-gl#1055]
What is the recommended way I should follow if I want to dynamically change the label language for my maps using this library?

**Comment by MindfulMe** [comment]
https://github.com/mapbox/mapbox-gl-language/blob/master/examples/ru.html

**Comment by MindfulMe** [comment]
this works fairly well https://stackoverflow.com/questions/44972570/how-to-switch-mapboxgl-language-in-deckgl
