### ISSUE TITLE
Double-click on map does not produce isZooming: true

### ISSUE THREAD

**Issue by alexdao3** [visgl/react-map-gl#1058]
Hi there, I am logging the arguments to the `onInteractionStateChange` handler  and noticed that when I double-click to zoom on the map, the object that is returned contains `{ isZooming: false }`. In the `onViewportChange` handler, the first `viewState` argument shows updated `latitude` and `longitude` coordinates based on where I'm clicking in the map, but the `zoom` value remains constant.

Based on the documentation, I would expect `onInteractionStateChange` to capture the double-click as an interaction state, but perhaps I am mistaken. Could you help clarify?

On a related note: I am using the `onInteractionStateChange` handler as the source of truth for when a user is interacting with the map (zoom, drag, etc) vs. the map being programmatically updated. Is that the correct API for this use case? Thanks!

**Comment by Pessimistress** [comment]
Fixed in 5.2.5
