### ISSUE TITLE
How to get a smooth zooming experience when scrolling?

### ISSUE THREAD

**Issue by jordymeow** [visgl/react-map-gl#1060]
It's not smooth on any of the [official examples](https://uber.github.io/react-map-gl/examples) of react-map-gl.

However, it's the default behavior of MapGL, as you can see in this [example](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/).

I am also using the latest versions (with mapbox-gl@1.9.0).

**Comment by Bubbleinpit** [comment]
Check this: #241 . [This comment](https://github.com/uber/react-map-gl/issues/241#issuecomment-536932911) may help.

**Comment by jordymeow** [comment]
Thanks for your reply, @Bubbleinpit. Yes, I thought of mentioning this in my first message, I have tried it but it didn't work, unfortunately.

**Comment by Bubbleinpit** [comment]
@jordymeow It's actually a big problem I think. You can alternatively try react-mapbox-gl.

**Comment by jordymeow** [comment]
@Bubbleinpit Actually, I used to work with react-mapbox-gl, and my experience with it was much better than with react-map-gl. However... I started using NextJS, and it has troubles with react-mapbox-gl, which is I am trying this library. I thought this library was more raw and direct to the MapBox GL Lib, but apparently... not really, and there seems to be no support (or no interest).

**Comment by Pessimistress** [comment]
Keyboard navigation has smooth transition by setting the transition props:
https://github.com/uber/react-map-gl/blob/master/src/utils/map-controller.js#L464

We can achieve similar effect by setting the transition duration here:
https://github.com/uber/react-map-gl/blob/master/src/utils/map-controller.js#L324

@jordymeow This library is maintained by volunteers. You are welcome to open a PR.

**Comment by Pessimistress** [comment]
This will be addressed in v5.3/v6.1. Currently available in `6.1.0-beta.1`.
