### ISSUE TITLE
draw-polygon example cannot compile

### ISSUE THREAD

**Issue by syk543277780** [visgl/react-map-gl#1062]
ERROR in ./node_modules/@nebula.gl/edit-modes/dist-es6/lib/measure-angle-mode.js
Module not found: Error: Can't resolve '@deck.gl/core' in '/Users/sw/Downloads/react-map-gl-5.2-release/examples/draw-polygon/node_modules/@nebula.gl/edit-modes/dist-es6/lib'
 @ ./node_modules/@nebula.gl/edit-modes/dist-es6/lib/measure-angle-mode.js 12:12-36
 @ ./node_modules/@nebula.gl/edit-modes/dist-es6/index.js
 @ ./node_modules/react-map-gl-draw/dist-es6/mode-handler.js
 @ ./node_modules/react-map-gl-draw/dist-es6/editor.js
 @ ./node_modules/react-map-gl-draw/dist-es6/index.js
 @ ./src/app.js

ERROR in ./node_modules/@nebula.gl/edit-modes/dist-es6/lib/measure-distance-mode.js
Module not found: Error: Can't resolve '@deck.gl/core' in '/Users/sw/Downloads/react-map-gl-5.2-release/examples/draw-polygon/node_modules/@nebula.gl/edit-modes/dist-es6/lib'
 @ ./node_modules/@nebula.gl/edit-modes/dist-es6/lib/measure-distance-mode.js 10:12-36
 @ ./node_modules/@nebula.gl/edit-modes/dist-es6/index.js
 @ ./node_modules/react-map-gl-draw/dist-es6/mode-handler.js
 @ ./node_modules/react-map-gl-draw/dist-es6/editor.js
 @ ./node_modules/react-map-gl-draw/dist-es6/index.js
 @ ./src/app.js

**Comment by Pessimistress** [comment]
@supersonicclay @xintongxia Looks like there a dependency contamination in the latest react-map-gl-draw release.
