### ISSUE TITLE
How to disable double tap zoom and scroll zoom? 

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [visgl/react-map-gl#1070]
Hi, i want the map to be zoom in only on clicking the marker apart from that. Map shouldn't zoom on double tap, Mousescroll etc... How to do this.. Any idea?

**Comment by apakbaz** [comment]
you can disable scroll zoom using [scrollZoom](https://uber.github.io/react-map-gl/docs/api-reference/interactive-map#scrollzoom)
you can find more example here: 
https://uber.github.io/react-map-gl/examples/interaction

**Comment by MedElBoudali** [comment]
try this:

const [settings, setsettings] = useState({
    dragPan: false,
    dragRotate: false,
    scrollZoom: false,
    touchZoom: false,
    touchRotate: false,
    keyboard: false,
    doubleClickZoom: false
});

<ReactMapGL
     {...viewPort}
     {...settings} ...

**Comment by htimran** [comment]
> try this:
> 
> const [settings, setsettings] = useState({
> dragPan: false,
> dragRotate: false,
> scrollZoom: false,
> touchZoom: false,
> touchRotate: false,
> keyboard: false,
> doubleClickZoom: false
> });
> 
> <ReactMapGL
> {...viewPort}
> {...settings} ...

this works fine for me, thanks
