### ISSUE TITLE
Map disappears after wrapping <MapGl> in <div> </div> 

### ISSUE THREAD

**Issue by jeffreyqdd** [visgl/react-map-gl#1071]
I am learning how to use react-map-gl in my code from here: https://github.com/uber/react-map-gl/tree/5.2-release/examples/controls. After downloading the code, everything works. After I wrap MapGl into the div block, the map disappears.

  render() {
    const {viewport} = this.state;

    return (
      <div>

        <MapGL
          {...viewport}
          width="100%"
          height="100%"
          mapStyle="mapbox://styles/mapbox/dark-v9"
          onViewportChange={this._updateViewport}
          mapboxApiAccessToken={TOKEN}
        >
       /* code is the same*/
        </div>
    );
  }
}

I'm sorry this might be a simple question, but I appreciate your support.

**Comment by Pessimistress** [comment]
You are responsible of setting the container div's size in css.

**Comment by jeffreyqdd** [comment]
Thanks for the quick response. Just tried. 

Changed the above code to 
  <div className="full">
        <MapGL......
  (omitted)
         .../>
  </div>

Added the following to app.css
div.full {
  width: 100%;
  margin: auto;
  border: 3px solid #73AD21;
}

Now I can see the div border. but the map still disappeared. Once I remove the <div> block, everything works.

**Comment by apakbaz** [comment]
you need to set height as well depending on your container div's.

**Comment by saadsaifse** [comment]
It is because `width=100%` and `height=100%` are not working. If change then to `100vw` and `100vh` respectively, it should fix it. But this is still an issue as I would want percentages to work.

**Comment by Pessimistress** [comment]
The container must have `position: relative;` if you want the map size to be relative to the div. `width` and `height` props are assigned to the map as CSS properties.

**Comment by saadsaifse** [comment]
I just made some changes. Now I have a following hierarchy.

- div with `position:absolute` `width:100%` `height=100%` `top=0` `left=0`
    - ReactMapGL with `position: relative`

at this point setting `width=100%` `height=100%` to `ReactMapGL` component works fine and the map takes the dimensions of its container.

However, I have another problem with this on mobile devices. If the virtual keyboard is opened when any text input is in focus. It immediately disappears. Any thoughts?
