### ISSUE TITLE
Zoom is prevented while user is panning

### ISSUE THREAD

**Issue by axleun** [visgl/react-map-gl#1072]
While the user is panning, zooming is disabled which causes an unpleasant issue which is: when the user on mobile doesn't put 2 fingers on the map simultaneously (for example 1 finger slightly after the other) then try to zoom by pinching, it won't let them. Any solution to this?

**Comment by Pessimistress** [comment]
Is this the same issue as https://github.com/uber/react-map-gl/issues/1054?
