### ISSUE TITLE
Rect-Map-Gl webpage down

### ISSUE THREAD

**Issue by ShlomoLove** [visgl/react-map-gl#1079]
The React-Map-Gl page on https://uber.github.io/react-map-gl/#/ serves a 404 File Not Found page. Is this down permanently?

**Comment by ShlomoLove** [comment]
It looks like the page moved. I am assuming Uber is not overseeing the project directly any longer. I found the documentation here: https://visgl.github.io/react-map-gl/

**Comment by Pessimistress** [comment]
That is correct. react-map-gl is now part of vis.gl, a Linux Foundation project.

**Comment by fpoljcic** [comment]
Is the new website https://visgl.github.io/react-map-gl/ currently down? No content is showing up on the page.

**Comment by xintongxia** [comment]
@fpoljcic website should be back.
