### ISSUE TITLE
React.lazy crashes the app

### ISSUE THREAD

**Issue by AlexSlo-Dev** [visgl/react-map-gl#1084]
When I try to use  const ReactMapGL = React.lazy(() => import("react-map-gl"));
App crashes with Unknown error

I use latest version of Create React App & react-map-gl in my project

**Comment by etc-tiago** [comment]
Try use `react-imported-component` instead `React.lazy`.
```js
import importComponent from 'react-imported-component';

const ReactMapGL = importComponent(() => import("react-map-gl"));
```
