### ISSUE TITLE
Permit `padding` in transitions

### ISSUE THREAD

**Issue by harto** [visgl/react-map-gl#1085]
[Mapbox GL JS 1.9](https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.9.0) added support for `padding` in camera functions `flyTo`, `jumpTo`, etc.: https://github.com/mapbox/mapbox-gl-js/pull/8638.

It would be great if a similar option was made available through this library. Our use case is that we need to adjust the target viewport based on the width of a sidebar.

**Comment by Pessimistress** [comment]
This is already supported in [WebMercatorViewport.fitBounds](https://visgl.github.io/react-map-gl/docs/api-reference/web-mercator-viewport#fitboundsbounds-options)

**Comment by mayteio** [comment]
See https://github.com/visgl/react-map-gl/issues/1099#issuecomment-629953112 for a function that returns a new viewport with padding, accounting for edge cases.
