### ISSUE TITLE
Cannot select/copy text inside a Popup

### ISSUE THREAD

**Issue by kukiel** [visgl/react-map-gl#1089]
When using a Popup component there is no way to select and copy a text inside. Check the example here:
http://visgl.github.io/react-map-gl/examples/controls

![image](https://user-images.githubusercontent.com/16286018/80362566-24570f00-8883-11ea-9c33-2cff432dfcd8.png)

Text selection could be fixed with setting `user-select: text;` on `mapboxgl-popup-content` class but contextmenu is blocked probably somewhere deeper. I couldn't find a way to unblock it using available API. Is there a way to enable that?

**Comment by karlkristopher** [comment]
@kukiel Did you ever find a fix to this?
I'm trying to do something similar. 
Also, do you have a way to be able to click the "Wikipedia" link and be directed to a new site? I was also having difficulty making this function.

**Comment by Pessimistress** [comment]
https://visgl.github.io/react-map-gl/docs/api-reference/interactive-map#oncontextmenu
