### ISSUE TITLE
Popups Overlap Each Other

### ISSUE THREAD

**Issue by azilvitis** [visgl/react-map-gl#1091]
Hi. I have popups that are attached to markers' onClick that are intended to show useful information about the marker selected. When I select a marker that is too close to another selected marker, the popups overlap each other and I can no longer compare the information associated with each location. Here is an example:

![image](https://user-images.githubusercontent.com/26912285/80763906-663abc00-8af4-11ea-8067-bdfbeba99f55.png)

Is there some way to prevent overlap of popups? I assume that something like the dynamicPosition could be useful, but I can't figure out how to change the anchor position based on whether another popup is already in that position. Please let me know if there are any features that might help, thank you!

**Comment by Pessimistress** [comment]
Popups are not aware of each other. You can disable `dynamicPosition` and set `anchor` manually.
