### ISSUE TITLE
please add minZoom and maxZoom props

### ISSUE THREAD

**Issue by chiho13** [visgl/react-map-gl#1100]

**Comment by Pessimistress** [comment]
https://visgl.github.io/react-map-gl/docs/api-reference/interactive-map#maxzoom

**Comment by chiho13** [comment]
Thanks, but maxBounds is missing. I’d like to restrict the panning

**Comment by Pessimistress** [comment]
https://visgl.github.io/react-map-gl/docs/get-started/state-management
