### ISSUE TITLE
Map Screen is not re rendering after updating state using hooks?

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [visgl/react-map-gl#1101]
Hi , i am showing a map where the color is loaded  on initial load . After a button click i am modifying the colorJson file. But the changes are not reflected in map. Map is not re rendering. Here i am sharing the code sandbox file of what i have done.Please help me with that

https://codesandbox.io/s/mapboxdynamiccolorupdate-sfiku?file=/src/Map.js

**Comment by Pessimistress** [comment]
You need to create a new state object instead of mutating the existing one.

**Comment by DhanushkumarSivaji** [comment]
Could you please explain how to do that?
