### ISSUE TITLE
Add prop to override provided Mapbox CSS

### ISSUE THREAD

**Issue by kthyer** [visgl/react-map-gl#1102]
In https://github.com/visgl/react-map-gl/blob/master/src/mapbox/mapbox.js starting at line 463 there is code that automatically fetches the CSS from the mapbox servers.

There are use cases where the developer would need to override the CSS with a particular version or a file that is hosted on a local network.

**Comment by Pessimistress** [comment]
The CSS is only attached if one is not found. If you include your custom stylesheet before initializing the map then the default one will not be used.

**Comment by kthyer** [comment]
I apologize, I didn't realize that was how it worked! Perfect, thank you so much for the quick reply and apologies for wasting any time.
