### ISSUE TITLE
Map color is not changing after updating the geoJson file in the Source

### ISSUE THREAD

**Issue by DhanushkumarSivaji** [visgl/react-map-gl#1105]
Hi,

I am showing a map where it shows a colour that is rendered from the geoJson data . I am passing this geoJson data into ```<Source/>``` . On initial render colour is updated. On a button click i am changing the colour value into the geoJson file and passing it into the ```<Source/>```. colour value has changed inside the geoJson file.But it's not reflected in the map. For reference i have passed the colour value in the button . On initial render it's ```1```, after clicking it becomes ```4```. That is the value passing in to ```<Source/>``` module.

Is there any way to rerender the ```<Source/>``` so that the colour value gets updated. Pls help me with this.

here i am sharing the code of what i have done [https://codesandbox.io/s/mapboxdynamiccolorupdate-sfiku?file=/src/Map.js](url)

**Comment by Pessimistress** [comment]
`<Source>` updates when one or more of its props change shallowly. React cannot detect nested changes.

**Comment by DhanushkumarSivaji** [comment]
Hi Pessimistress, Thanks for the reply . Is there any way to achieve ? Plese help me with this.

**Comment by DhanushkumarSivaji** [comment]
> `<Source>` updates when one or more of its props change shallowly. React cannot detect nested changes.

But some how it rerenders..only the source is not updating

**Comment by Pessimistress** [comment]
`<Source>` is a [PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent). After the first render, it does not update unless props shallowly change, i.e. `oldValue !== newValue`. When you mutate your json data, it is still the same object, so its change is not detected by React.

The easy way to fix this is to always `return {...colorData}` in your `updateColor`.

**Comment by DhanushkumarSivaji** [comment]
> `<Source>` is a [PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent). After the first render, it does not update unless props shallowly change, i.e. `oldValue !== newValue`. When you mutate your json data, it is still the same object, so its change is not detected by React.
> 
> The easy way to fix this is to always `return {...colorData}` in your `updateColor`.

Hi , i have done like , what u have said. No luck. could please help me out. Here i have shared my code.

```
import React, { useEffect, useState } from "react";
import ReactMapGL, { Source, Layer } from "react-map-gl";
import { data } from "./data/ApiData1";
import { data2 } from "./data/ApiData2";
import { GeneralFunction } from "./Utility";
import colorData from "./TamilNadu.json";
const TOKEN =
  "pk.eyJ1IjoiZGhhbnVzaDE5OTUiLCJhIjoiY2thYXk3Ynk5MDdhajMxbzhkcDJwOGk2NiJ9.ZTdqZn5nJh8PCtS6eFQX-Q";

function App() {
  const [colorJson, setColorJson] = useState({
    colorsData: null
  });

  const [viewport, setViewport] = useState({
    latitude: 21.28,
    longitude: 79.67,
    width: "100%",
    height: "100vh",
    zoom: 3.7
  });

  const viewportChange = viewports => {
    setViewport(viewports);
  };

  function updateColorValue(colorJsonObject, colorValue) {
    let updatedProperties = {
      ...colorJsonObject.properties,
      color: colorValue
    };
    colorJsonObject.properties = updatedProperties;
    return colorJsonObject;
  }

  useEffect(() => {
    let range = GeneralFunction(data2);
    function updateColor() {
      colorData.features.map(colorObject =>
        data2.map(apiData => {
          if (
            colorObject.properties.stateId === apiData?.latestMetric?.stateId
          ) {
            range.map(i => {
              if (
                apiData?.latestMetric?.numberOfProjects >= i.Minimum &&
                apiData?.latestMetric?.numberOfProjects <= i.Maximum
              ) {
                updateColorValue(colorObject, i.color);
              }
            });
          }
        })
      );
      return { ...colorData };
    }
    let x = updateColor();

    setColorJson({
      ...colorJson,
      colorsData: x
    });
  }, []);

  const checkColor = async () => {
    let range = await GeneralFunction(data);
    function updateColor() {
      function updateColorValue(colorJsonObject, colorValue) {
        let updatedProperties = {
          ...colorJsonObject.properties,
          color: colorValue
        };
        colorJsonObject.properties = updatedProperties;
        return colorJsonObject;
      }

      colorData.features.map(colorObject =>
        data.map(apiData => {
          if (
            colorObject.properties.stateId === apiData?.latestMetric?.stateId
          ) {
            range.map(i => {
              if (
                apiData?.latestMetric?.numberOfProjects >= i.Minimum &&
                apiData?.latestMetric?.numberOfProjects <= i.Maximum
              ) {
                updateColorValue(colorObject, i.color);
              }
            });
          }
        })
      );
      return { ...colorData };
    }
    let x = await updateColor();
    setColorJson(oldColor => ({
      ...oldColor,
      colorsData: x
    }));
  };

  return (
    <div style={{ width: "100%" }}>
      <ReactMapGL
        {...viewport}
        mapboxApiAccessToken={TOKEN}
        onViewportChange={viewportChange}
        width="100%"
      >
        <button onClick={checkColor}>
          Change Color{" "}
          {colorJson?.colorsData?.features?.map(i => i.properties.color)}
        </button>
        {JSON.stringify(Math.random())}
        <Source type="geojson" data={colorJson?.colorsData}>
          <Layer
            id="data"
            type="fill"
            paint={{
              "fill-color": {
                property: "color",
                stops: [
                  [1, "#EC4849"],
                  [2, "#019031"],
                  [3, "#75DA8B"],
                  [4, "#43BE31"]
                ]
              },
              "fill-opacity": 0.8
            }}
          />
        </Source>
      </ReactMapGL>
    </div>
  );
}

export default App;
```

codeSand box link : https://codesandbox.io/s/mapboxdynamiccolorupdate-sfiku?file=/src/Map.js:0-3675

**Comment by Pessimistress** [comment]
```js
    colorJsonObject.properties = updatedProperties;
    return { ...colorJsonObject };
```

You are still mutating the old object. To let the prop comparison do its job you need to NOT touch the old geoJSON and only write the updated values into a new one:

```js
const newData = {...oldData};
newData.features = newData.features.map(f => {
  if (needsUpdate) {
    return {...f, properties: newProperties};
  }
  return f;
});
```

You can read about object mutation in articles such as https://slemgrim.com/mutate-or-not-to-mutate/.

**Comment by DhanushkumarSivaji** [comment]
> ```js
>     colorJsonObject.properties = updatedProperties;
>     return { ...colorJsonObject };
> ```
> 
> You are still mutating the old object. To let the prop comparison do its job you need to NOT touch the old geoJSON and only write the updated values into a new one:
> 
> ```js
> const newData = {...oldData};
> newData.features = newData.features.map(f => {
>   if (needsUpdate) {
>     return {...f, properties: newProperties};
>   }
>   return f;
> });
> ```
> 
> You can read about object mutation in articles such as https://slemgrim.com/mutate-or-not-to-mutate/.

apart from this, any other option is available?

**Comment by lymine1996** [comment]
I had the exact same issue while trying to pass a geoJSON object saved in a React state. The solution that solves the problem is to force a re-render of the `<Source>` component:

    import React, { useState } from 'react';
    import Map, { Source } from 'react-map-gl';
    
    const MyMap = () => {
      const [geojson, setGeojson] = useState(initialGeojson);
      const [key, setKey] = useState(0);
    
      // Function to update GeoJSON
      const updateGeojson = (newGeojson) => {
        setGeojson(newGeojson);
        setKey(key + 1); // Increment key to force re-render
      };
    
      return (
        <Map {...viewport}>
          <Source id="my-data" type="geojson" data={geojson} key={key}>
            {/* Add your layers here */}
          </Source>
        </Map>
      );
    };

Or you could also use a package like `uuid` to generate random keys for each re-render.
