### ISSUE TITLE
Latest react-map-gl doesn't have inertia

### ISSUE THREAD

**Issue by Dmitri801** [visgl/react-map-gl#1107]
The latest update to the Mapbox GL JS library adds inertia when moving the map, i've updated to the latest version of react-map-gl at 5.2.5 and the inertia effect is not there yet. Could I possibly get an update on when we could be expecting that ( The mapbox-gl-js dev dependancy does show v1.10.0 which should include the inertia on move effect), or if there is something that needs to be done to activate it . I would be happy to include a Codesandbox if needed. Thanks!

**Comment by Pessimistress** [comment]
Duplicate of #574
