### ISSUE TITLE
Can not use onHover for Heatmap layer

### ISSUE THREAD

**Issue by Khangng7** [visgl/react-map-gl#1110]
I have already displayed heatmap successfully. However, I want to show tooltip whenever the mouse is hovered onto an area. 
I use this example as a reference: https://github.com/visgl/react-map-gl/blob/5.2-release/examples/geojson/src/app.js 
In the _onHover function, features is always empty when I hovered in heatmap layer.

Please help me!!!

**Comment by Pessimistress** [comment]
`onHover` calls [queryRenderedFeatures](https://docs.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures). Does mapbox-gl support querying a heatmap layer?

**Comment by Khangng7** [comment]
Sorry Mr.Chen. I have already searched about your question but There is no
relevant information.

**Comment by Pessimistress** [comment]
My understanding is that you can only query GeoJSON features with `queryRenderedFeatures`. Please ask in the [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js/) repo if you need new features from mapbox.

**Comment by Khangng7** [comment]
Thank you for your email
