### ISSUE TITLE
GeolocateControl - showAccuracyCircle is not exposed

### ISSUE THREAD

**Issue by yurivangeffen** [visgl/react-map-gl#1111]
Mapbox exposes the option to show the accuracy circle used in many applications ([docs](https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol)). It provides valuable feedback to the user.
A similar feature would be much appreciated (and probably very easy to do).

**Comment by Pessimistress** [comment]
This is fixed in 6.1.0-alpha. Will be part of 5.3.0 and 6.1.0.
