### ISSUE TITLE
Is there any way to have the buildings lot size shown in the map like in the image?

### ISSUE THREAD

**Issue by viganzeqiri** [visgl/react-map-gl#1112]
<img width="668" alt="Screen Shot 2020-05-26 at 9 55 29 AM" src="https://user-images.githubusercontent.com/27159364/82917372-a2d2c980-9f73-11ea-9597-4faa2ff5e4ef.png">

**Comment by Pessimistress** [comment]
react-map-gl is a wrapper of mapbox-gl. It does not provide any data service. If you want additional information shown on the map, see https://visgl.github.io/react-map-gl/docs/get-started/adding-custom-data
