### ISSUE TITLE
Make a hover effect on a Layer made with a geojson

### ISSUE THREAD

**Issue by estellegresillon** [visgl/react-map-gl#1113]
I have a map displaying a set of polygons with a FeatureCollection geojson like this :

```
<MapGL
      {...viewport}
      width={'100%'}
      height={'100%'}
      ref={mapRef}
      onViewportChange={setViewport}
      mapStyle={mapStyle}
      dragRotate={true}
      onClick={onClick}
      onHover={onHover}
    >
      <Source type="geojson" data={featureCollection}>
        <Layer {...dataLayer} />
      </Source>
      {renderTooltip()}
    </MapGL>
```

Is it possible to change the color/opacity of a polygon on hover ?

I tried to use this paint property for the <Layer />
`'fill-opacity': [ 'case', ['boolean', ['feature-state', 'hover'], false], 1, 0.5 ]`
It was supposed to let me use the function setFeatureState afterwards but I get an error "No overload matches this call"

Thanks by advance !

**Comment by Pessimistress** [comment]
How are you calling `setFeatureState`?

**Comment by estellegresillon** [comment]
I don't. I found this use case on mapboxgl docs as an example to create a hover effect and the fill-opacity value I mentioned returns the error "no overload matches this call".

**Comment by Pessimistress** [comment]
If the error originates from mapbox-gl, the mapbox-gl-js repo may have a better idea what it is about.

**Comment by estellegresillon** [comment]
Okay thanks, I'll do that.
