### ISSUE TITLE
Markers not staying in place when moving while pitch!=0

### ISSUE THREAD

**Issue by gilneto8** [visgl/react-map-gl#1117]
Hi everyone.

I'm facing an issue to which I can't seem to find the solution, neither here nor anywhere else.

I'm trying to create a map where I can place markers and, later on, draw a line between them. I could probably use deck.gl for the latter, but since I'm still starting, I wanted to get the hang of this before moving forward. I was already able to insert markers on the map and showing pop-ups for them, but when the map is tilted and I move around, the markers change place (in a rather predictable way). 

I'll try to create a gif where I recreate this problem, but for now, I'll leave an image for the same marker, with pitching and without pitching:
![image](https://user-images.githubusercontent.com/15315355/83357935-97164700-a367-11ea-8478-c89772994c3f.png)
![image](https://user-images.githubusercontent.com/15315355/83357937-9e3d5500-a367-11ea-8e2e-6def7713bc55.png)

I'll put in some code snippets later if needed. As for the technologies, I'm using:
```
    "react": "^16.13.1",
    "react-map-gl": "^5.2.5",
```

Thanks.

**Comment by gilneto8** [comment]
I made an example GIF, where you can see the marker (in the middle of the circle) moving up and down as the pitch changes. Of course, this shouldn't happen.


![ezgif com-crop](https://user-images.githubusercontent.com/15315355/83401458-b6ab7f00-a3fc-11ea-8a07-474e3af58b18.gif)

**Comment by Pessimistress** [comment]
Please check:

- You are not overriding the `altutude` prop of `<MapGL>`
- `offsetLeft` and `offsetTop` are set so that the marker's bottom center is anchored

**Comment by gilneto8** [comment]
@Pessimistress 

I was overriding the `altitude` prop on `<MapGL>`. I didn't know the influence it had on the markers themselves, but it fixed as soon as I removed it. 
Thank you so much!
