### ISSUE TITLE
Add Image for Layer

### ISSUE THREAD

**Issue by AndriusCvetkovas** [visgl/react-map-gl#1118]
Is it possible to add custom pin image for the cluster layer? This is what I tried and no luck

```
const image = new Image(50, 50);
image.src = './myPin.svg';
const images = ["myPin", image];
...
<Layer {...unclusteredPointLayer} images={images} layout={{ 'icon-image': 'myPin'}} />
```

**Comment by AndriusCvetkovas** [comment]
Found a solution.
<ReactMapGL
  onLoad={() => {
    if (!this.map) return
    const map = this.map.getMap()
    map.loadImage('./myPin.svg' , (error, image) => {
      if (error) return
      map.addImage('myPin', image)
    })
} }
>

**Comment by markjackson02** [comment]
Using a functional component & hooks, I'm doing it like this: 
```
const _mapRef = createRef();
useEffect(() => {
    const map = _mapRef.current.getMap();
    map.loadImage('/map-pin.png', (error, image) => {
        if (error) throw error;
        if (!map.hasImage('map-pin')) map.addImage('map-pin', image, { sdf: true });
    });
}, [_mapRef]);
return (
    <ReactMapGL
        ref={_mapRef}
    >
);
```

**Comment by FrancoisTaisne** [comment]
Hello, none of the above methods works with me, would you know where I could find more information?

**Comment by achen187** [comment]
Is this still the best way to do this? There's no native support for "map.addImage" in react-map-gl?

**Comment by chriszrc** [comment]
The above examples work, but I was seeing missing image errors because the layers were loading and the image wasn't ready yet. I think the fastest way to get a verified instance of the map is with a callbackRef:

https://medium.com/@teh_builder/ref-objects-inside-useeffect-hooks-eb7c15198780

Only then could I load the image fast enough before the layers started looking for the images-

**Comment by MaximilianLloyd** [comment]
```tsx
import React from 'react';

type UseMapImageOptions = {
  mapRef: React.MutableRefObject<any>;
  url: string;
  name: string;
}

export function useMapImage({ mapRef, url, name }: UseMapImageOptions) {
  React.useEffect(() => {
    if (mapRef.current) {
      const map = mapRef.current.getMap();

      map.loadImage(url, (error, image) => {
        if (error) throw error;
        if (!map.hasImage(name)) map.addImage(name, image, { sdf: true });
      });
    }
  }, [mapRef.current]);
}
```

Then in your compontent
```tsx
  useMapImage({
    mapRef,
    url: '/images/icons/out.png',
    name: 'my-arrow'
  })
```

**Comment by 2Up1Down** [comment]
> ```tsx
> import React from 'react';
> 
> type UseMapImageOptions = {
>   mapRef: React.MutableRefObject<any>;
>   url: string;
>   name: string;
> }
> 
> export function useMapImage({ mapRef, url, name }: UseMapImageOptions) {
>   React.useEffect(() => {
>     if (mapRef.current) {
>       const map = mapRef.current.getMap();
> 
>       map.loadImage(url, (error, image) => {
>         if (error) throw error;
>         if (!map.hasImage(name)) map.addImage(name, image, { sdf: true });
>       });
>     }
>   }, [mapRef.current]);
> }
> ```
> 
> Then in your compontent
> 
> ```tsx
>   useMapImage({
>     mapRef,
>     url: '/images/icons/out.png',
>     name: 'my-arrow'
>   })
> ```

Hi Maximilian,

Thanks for your help with your code snippet. Now I was finaly able to render an image to the map.  Here are the problems I encountered with that approach:

If I'm using a png file and the options for addImage are as described by you { sdf: true }, I only get a black images on the screen, see image below. When I put { sdf: false } it rendered the image correctly with colors.

![example](https://user-images.githubusercontent.com/39255639/206645571-60913f47-4ae3-48cc-94ef-4b5a03e59aa2.PNG)

If I'm using a svg file, I get the following error. Any idea on how to import an svg?
![error](https://user-images.githubusercontent.com/39255639/206646048-23ef9aa2-ad94-4b63-882e-c4b5fcd7e5b3.PNG)

**Comment by MaximilianLloyd** [comment]
Hi! You can modify to hook to take an sdf argument.
```tsx
import React from 'react';

type UseMapImageOptions = {
  mapRef: React.MutableRefObject<any>;
  url: string;
  name: string;
  sdf?: boolean;
}

export function useMapImage({ mapRef, url, name, sdf = false }: UseMapImageOptions) {
  React.useEffect(() => {
    if (mapRef.current) {
      const map = mapRef.current.getMap();

      map.loadImage(url, (error, image) => {
        if (error) throw error;
        if (!map.hasImage(name)) map.addImage(name, image, { sdf });
      });
    }
  }, [mapRef.current]);
}```

SVGs are not supported in mapbox with addImage, you need to "rasterize" it. More on that here.h ttps://stackoverflow.com/questions/62889716/how-to-add-svg-as-marker-in-mapbox-using-loadimage. You can however upload it as a symbol and then mapbox will handle that on it's backend.

https://docs.mapbox.com/studio-manual/examples/custom-icon/

**Comment by danpe** [comment]
> The above examples work, but I was seeing missing image errors because the layers were loading and the image wasn't ready yet. I think the fastest way to get a verified instance of the map is with a callbackRef:
> 
> https://medium.com/@teh_builder/ref-objects-inside-useeffect-hooks-eb7c15198780
> 
> Only then could I load the image fast enough before the layers started looking for the images-

Can you provide an example of using useRef?

**Comment by chriszrc** [comment]
Here's the code, I could post a sandbox if you need more-

```
import RmglInteractiveMap from "react-map-gl";
...typescript
const mapRef = useRef<MapRef | null>(null);
const mapRefCallback = useCallback((ref: MapRef | null) => {
  if (ref !== null) {
        //Set the actual ref we use elsewhere
        mapRef.current = ref;
        const map = ref;
 
        const loadImage = () => {
          if (!map.hasImage("store-icon")) {
            //NOTE This is really how are you load an SVG for mapbox
            let img = new Image(24, 24);
            img.crossOrigin = "Anonymous"; //it's not cross origin, but this quiets the canvas error
            img.onload = () => {
              map.addImage("store-icon", img, { sdf: true });
            };
            img.src = MarkerIconSvg;
  
            //NOTE ref for adding local image instead
            // map.loadImage("./static/img/shop-15.png", (error, image) => {
            //   if (error || image === undefined) throw error;
            //   map.addImage("store-icon", image, { sdf: true });
            // });
          }
        };
  
        loadImage();
  
        //TODO need this?
        map.on("styleimagemissing", (e) => {
          const id = e.id; // id of the missing image
          console.log(id);
          loadImage();
        });
      }
  }, []);

...
<RmglInteractiveMap
        mapStyle="mapbox://styles/mapbox/light-v11"
        ref={mapRefCallback}
        style={{
          width: "100%",
          height: "100%",
          backgroundColor: "transparent",
        }}
      >
...
```

**Comment by janisii** [comment]
> ```tsx
> useMapImage({
>     mapRef,
>     url: '/images/icons/out.png',
>     name: 'my-arrow'
>   })
> ```

@chriszrc  Sandbox example would be awsome. 
Thanks.

**Comment by chriszrc** [comment]
@janisii https://codesandbox.io/s/charming-worker-w5d7wj?file=/src/App.tsx

**Comment by janisii** [comment]
Thanks! One more question? Is it possible to load different icons for points? I have to create map with clusters and different icons for points/markers in the map. Is it possible to load them from geojson (for example, by type)?

**Comment by chriszrc** [comment]
@janisii you should post that kind of question on StackOverflow. But yes, of course you can have different icons-

**Comment by kauly** [comment]
> [#1118 (comment)](https://github.com/visgl/react-map-gl/issues/1118#issuecomment-1421252137)
> 
> @chriszrc shared code is perfect starting point. my two cents, for those who struggle to show different icons for different points on map.
> 
> 1. create layer for each type of icons (set unique id for `<Layer>`).
> 2. filter data by icon type. add respecting data to Feature object `properties { icon: "marker-icon-2"}` and then in `<Layer>` `filter: ["==", ["get", "icon"], "marker-icon-2"]` all points by icon type.
> 3. load marker-icon-2 in the same way as marker-icon.svg (`map.addImage(..)`).

you can put your icons in a sprite-sheet, add a prop `iconName` in your source features geojson, and use only one layer

**Comment by azeemkhan2012** [comment]
i am using html to image to take image of the map but it capturing / downloading blank without map

**Comment by wattsmith** [comment]
Does anyone have any experience getting this working on NextJS? @chriszrc sandbox doesn't replicate on my app, while trying to load a local png shows up as black rectangles.

**Comment by chriszrc** [comment]
@wattsmith make sure to try both sdf set to true and to false, sdf only supports basic svgs, that you can then style with things like "icon-color"-
