### ISSUE TITLE
Map is not responsive when user rotate view on Iphone Chrome

### ISSUE THREAD

**Issue by intelcoder** [visgl/react-map-gl#1119]
"react-map-gl": "5.2.5"

browser: iPhone - Google Chrome.

Steps to Trigger Behavior
Map container width: 100%, height: 100%, fill whole browser window.
Open on iPhone on Chrome browser.
Rotate multiple time phone to switch portrait to landscape mode.

I think is issue has been resolved on mapbox-gl-js.

Is there fix for react-map-gl ? 

[related issue from mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js/issues/9639)

**Comment by Pessimistress** [comment]
react-map-gl does not listen to window resize events. It is resized when its parent component's size changes. If your layout parent is the document, then it's recommended to use `100vw` and `100vh` as width and height.

**Comment by intelcoder** [comment]
Thanks for the quick answer!
