### ISSUE TITLE
Mouse click on overlay propagates to map as onClick

### ISSUE THREAD

**Issue by kjkurtz** [visgl/react-map-gl#1131]
When adding a card overlay within the confines of the map display area, all clicks propagate through the overlay to the map as an onClick event.

The issue is present in the example here: http://visgl.github.io/react-map-gl/examples/custom-cursor
Try clicking anywhere on the white area of the 'Custom Cursor' card that isn't a checkbox. It'll cause the onClick event from the map to fire and show the popup about what layer you clicked.

Is there any good way to prevent this when putting a fixed overlay/card within the map exactly as shown in the examples/custom-cursor? I'd expect that all clicks within that overlay card to stop and not propagate outside that given element. Thanks!

**Comment by Pessimistress** [comment]
Under the hood we use hammer.js whose click events cannot be blocked via React. You have two options:

- Add the control box as a sibling to the map, i.e., `<><MapGL /><ControlPanel /></>`
- Extend the `BaseControl` and use `captureClick: true`, see https://visgl.github.io/react-map-gl/docs/advanced/custom-components

**Comment by kjkurtz** [comment]
Excellent, thanks @Pessimistress! The sibling method worked best. I had originally tried to extend `BaseControl` but that resulted in a re-render of the overlay every time anything changed with the map (even simple things like pan or zoom). I appreciate the assistance!
