### ISSUE TITLE
Map starts clipping on smaller screen sizes.

### ISSUE THREAD

**Issue by alimuhammadtopl** [visgl/react-map-gl#1134]
**Problem**
My requirement is to show the whole world on the viewport, on large screen sizes above 512px map size or so everything seems good but below this size the map starts clipping from top. bottom and sides instead of scaling down.

This is official example from the react-map-gl repository itself and it shows this behaviour (size is 320x300)
![Screenshot from 2020-06-15 17-30-35](https://user-images.githubusercontent.com/59658904/84708212-14c48000-af2e-11ea-8054-cff29199c0f1.png)

Below is official example from documentation of Mapbox gl js. And it works as expected. No clipping of map. (size is the same 320x300)
![Screenshot from 2020-06-15 17-40-22](https://user-images.githubusercontent.com/59658904/84708965-6cafb680-af2f-11ea-8505-9092123af109.png)
[Fiddle](https://jsfiddle.net/L7v4gksf/8/)

Mapbox gl js allows negative zoom values to -2 while react-map-gl caps it to 0, but I am not sure if that will fix the issue.

How can I show the whole map on viewport if the smallest screen width I am aiming for is 320px?

**Comment by Pessimistress** [comment]
You can change these props:

[MinZoom](http://visgl.github.io/react-map-gl/docs/api-reference/interactive-map#minzoom)

[visibilityConstraints](http://visgl.github.io/react-map-gl/docs/api-reference/static-map#visibilityconstraints)
