### ISSUE TITLE
Inline conditional rendering Layer causes Source render cloneElement to fail

### ISSUE THREAD

**Issue by 123joshuawu** [visgl/react-map-gl#1135]
```javascript
<ReactMapGL>
  { features.map((feature) => (
    <Source>
      <Layer />
      {selected.zoneId === feature.id && <Layer />}
    </Source>
  ) }
</ReactMapGL>
```

Results in this error
`Error: React.cloneElement(...): The argument must be a React element, but you passed null.`

I believe it is because in the render for source, the children are iterated over using `React.children.map` as seen in lines 139 through 142. When the inline conditional is false, the resulting `React.children` element is `null`, which is then passed to `React.cloneElement`.
https://github.com/visgl/react-map-gl/blob/978dd0aa5ac5e238277e5ab39da97178356e879a/src/components/source.js#L133-L144

Here is the issue that talks about `React.children.map` and `null` values. 
https://github.com/facebook/react/issues/4867

I think a possible solution is to use `React.children.toArray` which will filter out `null` and `undefined` values.

**Comment by Pessimistress** [comment]
Fixed in 5.2.10
