### ISSUE TITLE
After interacting with the map it no longer resizes properly

### ISSUE THREAD

**Issue by MattLangsenkamp** [visgl/react-map-gl#1136]
source code can be found here: https://github.com/MattLangsenkamp/fnb-frontend/blob/master/src/components/common/MyMap.js

when the page is first loaded it looks as such. It is set to fit the width of its container.
![image](https://user-images.githubusercontent.com/14207918/85643716-ee57c080-b662-11ea-8cf8-182f5e771774.png)

shrinking the window size works as expected.
![image](https://user-images.githubusercontent.com/14207918/85643950-9c636a80-b663-11ea-9c7d-ba4186b4d965.png)

when the window size is enlarged it again works as expected, unless the map is moved. in that case it no longer resizes properly
![image](https://user-images.githubusercontent.com/14207918/85643999-bf8e1a00-b663-11ea-9c0d-e93186936e34.png)

**Comment by Pessimistress** [comment]
`<ReactMap {...viewport} width="100%" height="100%" />`
