### ISSUE TITLE
React-Map-GL

### ISSUE THREAD

**Issue by sunaryaap** [visgl/react-map-gl#1139]
Hi everyone, I want to question, It's a possible implementation react-map-gl in Angular?

Thank you.

**Comment by AndrewUsher** [comment]
Found these 2 on their site:

https://github.com/Naimikan/angular-mapboxgl-directive
https://github.com/Wykks/ngx-mapbox-gl

**Comment by ax00b3** [comment]
Considering this is a React implementation of Mapbox, my guess is you're asking the wrong people.
