### ISSUE TITLE
Support EdgeInsets / padding (Adjust the map center based on UI elements)

### ISSUE THREAD

**Issue by davidnx** [visgl/react-map-gl#1143]
## Feature request
See relevant [blog post announcement](https://blog.mapbox.com/introducing-gl-js-v1-9-0-and-the-within-expression-6268f6c32be3) (section "Adjust the map center based on UI elements") and [demo](https://jsfiddle.net/hgk4mfyL/).

> _Map padding options are now available to the camera methods Map#easeTo, Map#jumpTo, and Map#flyTo. This shifts the visual center of the map to match overlaid UI elements on your page, such as sidebars, headers, and footers. Different padding values can be specified for each side of the map for granular control._

**Comment by Pessimistress** [comment]
[Viewport transition](http://visgl.github.io/react-map-gl/docs/advanced/viewport-transition)

[padding](http://visgl.github.io/react-map-gl/docs/api-reference/web-mercator-viewport#fitboundsbounds-options)
