### ISSUE TITLE
coloring countries

### ISSUE THREAD

**Issue by hardysabs2** [visgl/react-map-gl#1144]
Not a bug - just looking for some advice.

What is the best strategy for coloring countries? Perhaps using a DeckGL layer? Do I need to look for country polygon data somewhere or is this something that is built in to react-map-gl?

Thanks.

**Comment by moclei** [comment]
Check out this Choropleth map tutorial: https://docs.mapbox.com/help/tutorials/choropleth-studio-gl-pt-1.

Yes you need to look for country polygon data. Set yourself up in Mapbox studio and they have lots of datasets that are ready to use, so you may not have to source it yourself.

Once you have your countries dataset setup in the Mapbox studio, you can get a url through there to refer to it by in your code. Then you can use the color filter properties of the maps to color the different countries as per the example above.

it would look something like:
map.setPaintProperty(
        "countries", << name of the dataset you set up in Mapbox studio, and load in our JS
        "fill-color", << style property to color the map feature
        expression << MapBox has an expression language for styling features
      );

where your expression (as defined here: https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/) is something like: 

expression = ["match", ["get", "FIPS"], "USA", "#A2A2A2", "France", "#F1F2F3"]; << or whatever, using the country ID's as specified by whatever country dataset you find, and whatever colors you want.

Hope that helps

**Comment by hardysabs2** [comment]
Thanks, appreciate that
