### ISSUE TITLE
Map does not update on source url change for 'vector' type

### ISSUE THREAD

**Issue by fdvfdv** [visgl/react-map-gl#1146]
Hello

in react redux app,
GLMap does not update vector tile when tile url changes, does not do any requests to new url
(tile url is stored in state)
the code is:
```
    render() {
        const {token, viewport, changeViewport, style, tile} = this.props;

        return <MapGL
            {...viewport}
            width="100vw"
            height="100vh"
            mapStyle={style}
            onViewportChange={viewport => changeViewport(viewport)}
            mapboxApiAccessToken={token}
            >
            <Source id='roads' type='vector' url={tile.url} />
            <Layer
                id='roads'
                type='line'
                source='roads'
                source-layer={tile.layer}
                layout={{
                    'line-join': 'round',
                    'line-cap': 'round'
                }}
                paint={{
                    'line-color': '#333333',
                    'line-width': 5
                }}
            />
        </MapGL>;
    }
```
in debug we can see that in file [source.js]( https://github.com/visgl/react-map-gl/blob/master/src/components/source.js)
  there is no case for 'vector' type:
```
    if (type === 'geojson') {
      source.setData(sourceOptions.data);
    } else if (type === 'image') {
      source.updateImage({url: sourceOptions.url, coordinates: sourceOptions.coordinates});
    } else if (
      (type === 'canvas' || type === 'video') &&
      changedKeyCount === 1 &&
      changedKey === 'coordinates'
    ) {
      source.setCoordinates(sourceOptions.coordinates);
    } else {
      // eslint-disable-next-line
      console.warn(`Unable to update <Source> prop: ${changedKey}`);
    }
```
and we go to else branch and warn (line 128)

**Comment by Pessimistress** [comment]
`mapbox-gl`'s [VectorTileSource](https://github.com/mapbox/mapbox-gl-js/blob/main/src/source/vector_tile_source.js) does not support dynamically changing URL. You have to create a new source with a new id.

**Comment by kylebarron** [comment]
FYI the most recent Mapbox GL JS, version 1.12.0, adds support for dynamically changing a vector tile's source URL.

https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.12.0

**Comment by Pessimistress** [comment]
Fixed in 5.2.9 (requires mapbox-gl@1.12.0)

**Comment by maxwell-oroark** [comment]
If I have a dynamic source that is of type "raster" there is still no way for it to update the source tiles prop right? I have to create a new source from scratch?

**Comment by elietech** [comment]
> If I have a dynamic source that is of type "raster" there is still no way for it to update the source tiles prop right? I have to create a new source from scratch?

I too am curious if there is a way to do this.  If I try to reload the source tiles using an interval, I get the following error in the console from the component: ```Unable to update <Source> prop: tiles```

**Comment by heritage-hse** [comment]
@elietech , same issue as you have and I cant solve it. Any ideas how to dynamically update source tiles prop "raster" layers?

**Comment by doldsimo** [comment]
For type 'geojson' the data can also not be updated out of the box by react-map-gl.

But I got it to work with a workaround described in [this](https://github.com/alex3165/react-mapbox-gl/issues/418) issue.
I think this will also work for type 'vector'

It makes use of the [Mapbox GL JS](https://docs.mapbox.com/mapbox-gl-js/) library which is behind react-map-gl. 
So you can use the `map.getSource('some id').setData({})` function to change the data dynamically.

I hope this helps someone

**Comment by manodupont** [comment]
Hi.

I still have issue with react-map-gl to update the Source dynamically. It may be super silly but I can't figure out whats wrong with this approach. Let's say I have multiple "tilesets" that are referenced by an id named `tileName`

`
<Map
                {...viewport}
                style={{width: '100%', height: '100%'}}
                mapStyle="mapbox://styles/mapbox/satellite-streets-v11"
                mapboxAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
            >
                <Source
                    key={`source-${props.tileName}`}
                    id={`sprayed-tiles-${props.tileName}`}  // Add id that's unique per map
                    type="vector"
                    tiles={[`${process.env.REACT_APP_TILE_SERVER_HOST}/data/${props.tileName}/{z}/{x}/{y}.pbf`]}
                    minzoom={0}
                    maxzoom={12}
                >
                    <Layer key={`layer-${props.tileName}`}
                           {...sprayedLayer} />
                </Source>
                <ScaleControl/>
            </Map>
`


It works for the first `tileName` but whenever I change dynamically the tilename, I can still see the networks fetching the tiles, the viewport is changed accordingly (so the Map component reacts), but the new Layer doesn't appear anymore.


Any help would be appreciated. Thanks

**Comment by HelNershingThapa** [comment]
I had a similar issue with dynamically updating the vector source `tiles` in `react-map-gl`, and I resolved it by passing a key prop to `Source`.

Try adding a key to the Source component that depends on `tiles`. 

```js
<Source
    key={props.tileName}
```
