### ISSUE TITLE
GeolocateControl `auto` prop invalid

### ISSUE THREAD

**Issue by kyleshepherd** [visgl/react-map-gl#1148]
Trying to implement the auto triggering on a `GeolocateControl` component and it's giving me this error:

`No overload matches this call.
  Overload 1 of 2, '(props: Readonly<GeolocateControlProps>): GeolocateControl', gave the following error.
    Type '{ auto: boolean; positionOptions: { enableHighAccuracy: true; }; onGeolocate: () => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<GeolocateControl> & Readonly<GeolocateControlProps> & Readonly<...>'.
      Property 'auto' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<GeolocateControl> & Readonly<GeolocateControlProps> & Readonly<...>'.
  Overload 2 of 2, '(props: GeolocateControlProps, context?: any): GeolocateControl', gave the following error.
    Type '{ auto: boolean; positionOptions: { enableHighAccuracy: true; }; onGeolocate: () => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<GeolocateControl> & Readonly<GeolocateControlProps> & Readonly<...>'.
      Property 'auto' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<GeolocateControl> & Readonly<GeolocateControlProps> & Readonly<...>'.  TS2769`

Here is the code for the component:
`<GeolocateControl
            auto={true}
            positionOptions={{ enableHighAccuracy: true }}
            onGeolocate={getUserCoordinates}
          />`

Does the `auto` prop actually work or have I done something wrong?

**Comment by Pessimistress** [comment]
Can you make sure you are using the latest release

**Comment by bkiac** [comment]
The component works for me, but I have the same type error. I guess it's only a missing type issue. I opened a PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46013.

**Comment by kyleshepherd** [comment]
I can confirm this is working on my end now, thanks @bkiac!
