### ISSUE TITLE
Re-Render Layer when map style changes

### ISSUE THREAD

**Issue by lucadegasperi** [visgl/react-map-gl#1149]
Hello,

I'm currently implementing a map with different layers coming from different tile servers. Rendering a layer is not an issue, the issue arise when I try to change the map's base layer from streets to satellite. In that case my layer disappears. How can I change the base map while preserving my additional layers?

```js

const [mapStyle, setMapStyle] = useState("mapbox://styles/mapbox/streets-v11");

return (<ReactMapGL
            ref={mapRef}
            {...viewport}
            width="100%"
            height="80vh"
            attributionControl={false}
            reuseMaps={true}
            mapStyle={mapStyle}
            mapboxApiAccessToken={process.env.MIX_MAPBOX_ACCESS_TOKEN}
            onViewportChange={nextViewport => setViewport(nextViewport)}
            onLoad={(e) => onMapLoaded(e)}
        >
            <Source type="vector" scheme="tms" key={lk} tiles={["https://geoserverurl/{x},{y},{z}.pbf"]} minzoom={10} maxzoom={12}>
                <Layer type="symbol" source-layer="source" layout={{
                    "icon-image": "pin",
                    "icon-size": 0.5,
                    "icon-allow-overlap": true
                }}></Layer>
            </Source>
</ReactMapGL>);
```

**Comment by littlejustinh** [comment]
By chance are you calling loadImage and addImage to add the "pin" icon? If so, you'll have to load and add those images to the style again, i believe they're actually added to the style. I had to add an effect that loads and adds images again after mapStyle changes. 

Here's what I ended up having to do:

`useEffect(() => {
    if (mapStyle && mapRef && mapRef.getMap()) {
      // icons are added to the style, so if the style changes we have to reload icons to the style
      // it takes forever for certain styles to load so we have to wait a bit
      setTimeout(() => {
        handleMapLoad(mapRef);
      }, 1);
    }
  }, [mapRef, mapStyle]);`

**Comment by Pessimistress** [comment]
I cannot reproduce this issue with the latest release. If you are still experiencing this, please provide a Code Sandbox.
