### ISSUE TITLE
Links to cross-origin destinations are unsafe, reported by lighthouse

### ISSUE THREAD

**Issue by omar-dulaimi** [visgl/react-map-gl#1154]
![Screenshot from 2020-07-22 13-00-51](https://user-images.githubusercontent.com/11743389/88163620-a1dcb200-cc1b-11ea-8bc9-b93a5215bf9b.png)

Any ways to fix this?

**Comment by Pessimistress** [comment]
These links are not generated by react-map-gl. You should report it to the Mapbox GL JS repo.
