### ISSUE TITLE
Mapbox Set Feature State/Hover Effect

### ISSUE THREAD

**Issue by sri-go** [visgl/react-map-gl#1155]
Hi, this isn't an issue. Looking more on guidance on how to accomplish this in React-Map-GL. 

I want to change the opacity of a layer to accomplish a hover effect like [this](https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/). 

Any idea on how to do this in React-Map-GL? I couldn't find any examples of React-Map-GL using setFeatureState or if that is even a method that we have access to.

**Comment by SravanKumar35** [comment]
HI @sri-go ,  were you able to acheive what you are trying to do. Even I stuck in the same issue

**Comment by sri-go** [comment]
Hi yes I was able to. 

`  const onHover = (event: PointerEvent) => {
    const {
      point,
      srcEvent: { offsetX, offsetY },
    } = event;

    //This is to return the data within the layer and change the hover opacity
    if (null !== mapRef.current) {
      const map = mapRef.current.getMap();
      const featured = map.queryRenderedFeatures(point, {
        layers: [
          "states-data",
          "county-data",
          "StateTwoWeek-ConfirmedData",
          "CountyTwoWeek-ConfirmedData",
        ],
      })[0];
      setHoveredFeature({ featured, x: offsetX, y: offsetY });
      if (featured) {
        map.setFeatureState(
          {
            source: "county-data",
            id: featured.id,
          },
          {
            hover: true,
          }
        );
        map.setFeatureState(
          {
            source: "states-data",
            id: featured.id,
          },
          {
            hover: true,
          }
        );
        setTempFeature(featured);
      }
    }
  };`
