### ISSUE TITLE
Viewport not being updated when resizing map width

### ISSUE THREAD

**Issue by fbarl** [visgl/react-map-gl#1157]
We first noticed this issue when using this amazing library in https://github.com/tmrowco/electricitymap-contrib/issues/2573 and then I managed to isolate it in [this sandboxed example](https://codesandbox.io/s/react-map-gl-width-not-updating-dx7e4):

```javascript
import React from "react";
import ReactMapGL from "react-map-gl";

class App extends React.Component {
  state = {
    viewport: {
      latitude: 37.7577,
      longitude: -122.4376,
      zoom: 8
    }
  };

  render() {
    console.log(this.state.viewport);
    return (
      <ReactMapGL
        {...this.state.viewport}
        width="100vw"
        height="100vh"
        mapStyle={{ version: 8, sources: {}, layers: [] }}
        onViewportChange={viewport => this.setState({ viewport })}
      />
    );
  }
}
```

Running this in my browser, I get a new console output whenever panning & dragging the map as well as resizing the viewport height, but _not_ when resizing the viewport width - it seems that `onViewportChange` is simply not called in that case.

The asymmetry between handling the viewport width and height suggests that this is a bug.

Please let me know if you need further input from me or assistance reproducing the issue :slightly_smiling_face:

**Comment by Pessimistress** [comment]
Use [onResize](http://visgl.github.io/react-map-gl/docs/api-reference/static-map#onresize)

**Comment by fbarl** [comment]
> Use `onResize`

Thanks @Pessimistress, that handler does the job for me, I don't know how I missed it :man_facepalming: 

Having said that, I still find it a bit confusing how `onViewportChange` handles _width_ updates, but not the _height_. I think it would be good if we could make the behaviour consistent - I'm even as to whether `onViewportChange` should handle _both_ dimensions or _neither_, but I think it shouldn't handle just _one_. Does that make sense? :slightly_smiling_face:

**Comment by Pessimistress** [comment]
> whether onViewportChange should handle both dimensions 

The issue is that the component does not differentiate whether the size change is due to user passing in different width/height props, or the browser window resizing. Theoretically `onViewportChange` can manipulate size and trigger an infinite loop. 

As a comparison, currently `onViewportChange` is only called if the internal controller/components "request" a viewport change, but not called if longitude/latitude is changed programmatically.
