### ISSUE TITLE
Styling Popup tip anchor css classes has no effect

### ISSUE THREAD

**Issue by markjackson02** [visgl/react-map-gl#1159]
I am trying to change the color of the Popup tip that shows up next to the Popup content on hover. **[This](https://stackoverflow.com/questions/44554692/style-a-mapbox-popups-pointer-indicator)** StackOverflow example shows a screenshot and the class names that _should_ be used to style the CSS.

But when I try to style any of the classes that have the word `anchor` in the class name, it has no effect. For example changing the border-color of `.mapboxgl-popup-tip` works, but changing the border-color of `.mapboxgl-popup-anchor-top-left .mapboxgl-popup-tip` does not.

I'm not sure how to inspect the CSS in devtools because the parent mapbox div has no children, so I'm not sure if these classes just _aren't there_ in `react-map-gl` or something else is going on.

**Comment by Pessimistress** [comment]
react-map-gl uses the same class names as mapbox-gl (hence the requirement for the Mapbox stylesheet). You can inspect it by right clicking on the pop up and select "inspect"
