### ISSUE TITLE
onDblClick function not exposing features property

### ISSUE THREAD

**Issue by markjackson02** [visgl/react-map-gl#1160]
`onClick` function exposes the `features` property but `onDblClick` does not. I would expect all the properties on the `event` object to be the same for these two functions.

**Comment by Pessimistress** [comment]
You can call [queryRenderedFeatures](https://visgl.github.io/react-map-gl/docs/api-reference/static-map#queryrenderedfeatures)

**Comment by markjackson02** [comment]
Ok that seems to be working. Thank you!

```
const _onDblClick = event => {
        const map = _mapRef.current.getMap();
        const renderedFeatures = map.queryRenderedFeatures(event.point);
    };
```
