### ISSUE TITLE
Not possible to use <Feature> component?

### ISSUE THREAD

**Issue by jethanh** [visgl/react-map-gl#1162]
I need to use a Layer/Feature combination as markers cause a bit too much FPS lag as I'm trying to render 800+ points on the map.

I am using react-map-gl as it's a bit easier to use with Geocoding. I have tried caching my markers with no prevail. Most recommendations are to use Layer/Feature, however I don't believe they're in this library.

If I can't use layer/feature, how can I reduce the lag from rendering this many markers.

**Comment by Pessimistress** [comment]
http://visgl.github.io/react-map-gl/docs/api-reference/source

**Comment by jethanh** [comment]
`          {pbdb.data.map(item => (
            <Source id={item.id} type="geojson" data={{
                type: 'FeatureCollection',
                features: [
                  {type: 'Feature', geometry: {type: 'Point', coordinates: [item.geocoding.lat, item.geocoding.long]}}
                ]
            }}>
              <Layer
                id="point"
                type="circle"
                paint={{
                  'circle-radius': 10,
                  'circle-color': '#007cbf'
                }}
              />
              
            </Source>
          ))}`

is it not possible to do something like this to render multiple features/layers

**Comment by Pessimistress** [comment]
- You should use a single source that contains multiple points, if you are rendering them with the same layer.
- If you want to use multiple layers, then they need to have unique ids.
