### ISSUE TITLE
Hard crash (white screen) when illegal lng/lat

### ISSUE THREAD

**Issue by ibgreen** [visgl/react-map-gl#1163]
WebMercator viewport throws an exception on lng/lat in the StaticMap render function causing the app to crash hard.

https://github.com/visgl/react-map-gl/blob/master/src/components/static-map.js#L269

@Pessimistress While the app is of responsible for filtering lng/lat, could it be appropriate to catch the error here and just stop rendering the base map until we get a good view state again?

**Comment by Pessimistress** [comment]
Rendering a blank div is arguably no better than just crashing. And there is no reasonable guess to what the intended lng/lat should be as a fallback. The application is responsible of providing valid props and the developer should know it when an error occurs.
