### ISSUE TITLE
Towards typescript?

### ISSUE THREAD

**Issue by ibgreen** [visgl/react-map-gl#1164]
Given rest of visgl suite is moving towards typescript, consider either:
- Adding separate `.d.ts` type files for typescript and keep flow in the code.
- migrate code from flow to typescript (nebula.gl "automated" this using a conversion tool).

**Comment by ibgreen** [comment]
nebula.gl did an automated conversion from flow to typescript, it is quite well explained in https://github.com/uber/nebula.gl/pull/377 

CC @supersonicclay @kikonejakob are you react-map-gl users? Any chance of getting help, perhaps a partial PR, for react-map-gl based on the same recipe you used for nebula.gl?

**Comment by mayteio** [comment]
If the auto conversion doesn't work as desired, I'd be happy to help with writing the declarations by hand.

**Comment by kikonejacob** [comment]
It may be possible that I can do a PR for a conversion to typescript late January

**Comment by Pessimistress** [comment]
@mayteio @kikonejacob Much appreciated! I plan to make an initial PR by the end of this week to set up the dev tools and dependencies for TypeScript development. We can definitely use some help authoring and testing the types after that!

**Comment by Pessimistress** [comment]
@mayteio @kikonejacob Just published `6.1.0-alpha.1` that includes both TypeScript and Flow typings. Would appreciate if you give it a try and report any issues!

**Comment by Pessimistress** [comment]
TypeScript typings will be available in v5.3/v6.1.
