### ISSUE TITLE
Taping on marker on mobile firing panning event very often

### ISSUE THREAD

**Issue by intelcoder** [visgl/react-map-gl#1165]
I have a lot of markers on the map and a user need to tap to see the detail information.
However, it fires panning event pretty often even though I do not see any visible movement on the map. 
That did not happen with google map so wondering if it is fixable or way to reduce the occurrence of the issue.

**Comment by Pessimistress** [comment]
A new `eventRecognizerOptions` prop will be added in v5.3/v6.1: https://github.com/visgl/react-map-gl/pull/1302

Currently available in `6.1.0-beta.1`
