### ISSUE TITLE
Question regarding ReactMapGL Component reuse

### ISSUE THREAD

**Issue by Warqus** [visgl/react-map-gl#1167]
This is not an issue, but I have looked through most of the documentation and internet questions related to this subject and I cannot find an explanation. Sorry for this post if this isn't the place where to post these questions.

I use Mapbox and the ReactMapGL component is used within CustomMap component which is used on different pages within my website. The CustomMap component is mounted/unmounted based on a toggle in another component.

In release 5.0 it states:

_The only change between the 5.0 release and the latest 4.1 release is Mapbox GL JS v1.0. By using this version, you opt into Mapbox's new pricing model, which bills per map load instead of map views._

My concern is that whenever someone toggles the map on/off or browses through my website, I get billed at Mapbox everytime the CustomMap is mounted.

My question is; 
Does the Mapbox GL JS load everytime the ReactMapGL component is mounted or does it load only at the initial load of the ReactMapGL component whereafter it can mount/unmount infinitely without being billed at Mapbox?

**Comment by Pessimistress** [comment]
You can use http://visgl.github.io/react-map-gl/docs/api-reference/static-map#reusemaps to avoid destroying the underlying map instance when the component unmounts.

Do note that this prop is mainly designed to improve resource usage and performance. Whether Mapbox charges you again when the map is detached from the DOM tree and reattached is up to Mapbox. Mapbox has ended the support for the old pricing model so you don't really have a choice if you want to use the latest features.
