### ISSUE TITLE
ScaleControl errors when child of StaticMap

### ISSUE THREAD

**Issue by Reignable** [visgl/react-map-gl#1168]
## Description
I want to add a `ScaleControl` when using `StaticMap` rather than `InteractiveMap` as it's part of a deck.gl project.
When doing this though, `ScaleControl` throws the error

```
TypeError
Cannot read property '_container' of null
```

## Reproduction
Taking examples already created for this issue https://github.com/visgl/deck.gl/issues/4726 in deck.gl

**As child of `StaticMap`**
https://codesandbox.io/s/cranky-meitner-9cd7t

**As child of `InteractiveMap`**
https://codesandbox.io/s/recursing-grothendieck-ipwdw

**Comment by Pessimistress** [comment]
The issue only appears when `width` and `height` are constants. I will put up a fix.

**Comment by Pessimistress** [comment]
A fix is landed in 5.2.8
