### ISSUE TITLE
`FullscreenControl` not working in `Deck gl`

### ISSUE THREAD

**Issue by Jenny-YJ** [visgl/react-map-gl#1170]
I checked `FullscreenControl` is working in 'examples/controls'
but when change to in a `Deck gl`   is not working.. 

Is there problem?
[https://codesandbox.io/s/react-map-teseuteu-eyee4?file=/src/App.js](https://codesandbox.io/s/react-map-teseuteu-eyee4?file=/src/App.js)

thanks

**Comment by Pessimistress** [comment]
You may need to specify the `container` prop.
