### ISSUE TITLE
mapbox-gl.css isn't injected to page in IE

### ISSUE THREAD

**Issue by bondom** [visgl/react-map-gl#1175]
IE doesn't support `ParentNode.append `, but it is used there:

https://github.com/visgl/react-map-gl/blob/master/src/mapbox/mapbox.js#L460
and 
https://github.com/visgl/react-map-gl/blob/master/src/mapbox/mapbox.js#L472

**Comment by Pessimistress** [comment]
Thank you. While we address this, it is recommended that you include the css yourself, instead of relying on the injection.

**Comment by Pessimistress** [comment]
Fixed in 5.2.9
