### ISSUE TITLE
Getting Map from DOM

### ISSUE THREAD

**Issue by marksmall** [visgl/react-map-gl#1176]
Sorry if this is the wrong place to ask this question, but I don't know where else to go.

I am doing some End-to-End testing, using cypress.io on an application that has recently moved from raw **maboxgl**, to using **react-map-gl**. Before, we were able to get the map from the map DOM object, but I don't see if or how to do this using **react-map-gl**, can anyone tell me*

1. Is this possible
2. How is it done, any examples|resources etc would be appreciated.

**Comment by Pessimistress** [comment]
[getMap](http://visgl.github.io/react-map-gl/docs/api-reference/static-map#getmap)

**Comment by marksmall** [comment]
Sorry @Pessimistress, but that doesn't explain what **DOM element** the map is attached to. I'll try to give some more context to this. I have a app that is using a map, that bit is fine and working. I also have code, that runs separately, written using `cypress.io` test runner. Now, when running the previous mapbox based codebase, we were able to get the map from the DOM, then use it within our cypress tests to do asserts on the map. I cannot find how to do this using `react-map-gl`.

**Comment by Pessimistress** [comment]
The DOM container of react-map-gl is whatever parent you wrap `<MapGL>` in. If your test framework does not support React, you should assign an identifier to the parent element yourself, e.g. `<div id="mymap"><MapGL ...></div>`.

You can find the DOM container of the Mapbox Map instance by looking for a div with the class name `mapboxgl-map`.

**Comment by marksmall** [comment]
Okay, still struggling to get the map JavaScript object from the DOM, thanks @Pessimistress for your help so far. I guess my question at it's most basic is 

> Can I get the JavaScript map object from the DOM?. If yes, then how.

I feel I haven't explained the situation very well so going to try again, as I've not been able to make the intellectual leap from what has been suggested into working code:

I have a `react-map-gl` based app running that I want to do some automated testing, e.g. 

- `Ensure map starts at lat/lon specified and the zoom`
- `Ensure when app bookmark selected, map pans and zooms to the correct location

The app being tested is a refactor from plain mapbox code, to react-map-gl, with some deck.gl layers, but don't think that really matters.

Before the refactor, we had cypress.io based End-to-End tests written, that worked perfectly well, but since the refactor have obviously broken. The main problem I am having is getting the Map JavaScript object from the DOM, so I can do assertions on it, as specified above. Previously we had a cypress custom function to get the map object from the DON:

```JavaScript
Cypress.Commands.add('getMap', (id, timeout = 10000) => {
  cy.get(`[data-testid="map-${id}"]`, { timeout: timeout })
    .should(mapContainers => {
      const { map } = mapContainers[id];
      expect(!!map).to.eql(true, 'Style loaded');
      expect(map.areTilesLoaded()).to.eql(true, 'Tiles loaded');
    })
    .then(mapContainers => mapContainers[id].map);
});
```
This function ensured the map had loaded and then returned the map JavaScript object, so it could be queried as in:

```JavaScript
cy.getMap(0, 30000).invoke('getZoom').should('eql', 16);
```

I am trying to re-implement the custom `getMap` command to retrieve the JavaScript object from the DOM and sadly, not been able to interpret @Pessimistress's points into working code.

Any further help by anyone really is very much appreciated.

**Comment by Pessimistress** [comment]
I do not believe `mapContainers[id].map` is something generated by mapbox-gl. Most likely your old code was attaching the map instance to the DOM container. If you wish to do so in react, you can listen to the [onLoad](https://visgl.github.io/react-map-gl/docs/api-reference/static-map#onload) event:

```js
<MapGL ... onLoad={onMapLoad} />

function onMapLoad(event) {
  const map =event.target;
  map._container.map = map;
}
```

**Comment by marksmall** [comment]
and now the penny drops, that is great, cheers, that did work a treat, thanks very much for your help.
