### ISSUE TITLE
Source and Layer components without Mapbox token

### ISSUE THREAD

**Issue by bkiac** [visgl/react-map-gl#1178]
ReactMapGL does not render with Source and Layer components if Mapbox token is missing.

This is an OpenStreetMaps example:
https://codesandbox.io/s/react-map-gl-without-token-yqo4v?file=/src/App.js

This is the [example from the docs](https://visgl.github.io/react-map-gl/docs/api-reference/source#source):
https://codesandbox.io/s/react-map-gl-without-token-docs-example-17kqb?file=/src/App.js

Neither renders the map, only `NO_TOKEN_WARNING` error message is displayed.

**Comment by Pessimistress** [comment]
[mapStyle](https://visgl.github.io/react-map-gl/docs/api-reference/static-map#mapstyle) defaults to `mapbox://styles/mapbox/light-v8` which requires a token.

To use an empty base map, you need to override the prop:

```js
const EMPTY_STYLE = {
  version: 8,
  sources: {},
  layers: []
};

<ReactMapGL width="100%" height="100%" mapStyle={EMPTY_STYLE} >...</ReactMapGL>
```

**Comment by bkiac** [comment]
Thanks, I haven't thought of that!
I think it would be great to include this method in the [Source](https://visgl.github.io/react-map-gl/docs/api-reference/source#source) and [Layer](https://visgl.github.io/react-map-gl/docs/api-reference/layer) docs / examples!
