### ISSUE TITLE
When scroll to zoom sometimes get low resolution of osm layer (previous tiles are resized)

### ISSUE THREAD

**Issue by KamilKucharsk1** [visgl/react-map-gl#1181]
There is example of my code. I have a problem while mouse scroll to zoom on map sometimes i get new tiles with good resolution but sometimes it only resize old ones and quality is low. I discovered that wen i double click on map to zoom every time new tiles are downloaded but when on scroll, not always? 

```
export default function App() {
  const [state, dispatch] = useReducer(reducer, initialState)
  const [viewport, setViewport] = useState({
    width: '100%',
    height: '100vh',
    latitude: 52.06,
    longitude: 19.25,
    zoom: 6,
  })

const mapStyle = {
    'version': 8,
    'name': 'OSM',
    'sources': {
      'osm': {
        'type': 'raster',
        'tiles': ['https://a.basemaps.cartocdn.com/light_all/{z}/{x}/{y}@2x.png'],
        'minzoom': 0,
        'maxzoom': 24,
        'tileSize': 256
      },

'layers': [
      {
        'id': 'osm',
        'type': 'raster',
        'source': 'osm',
      },

return (
    <ReactMapGL {...viewport} mapStyle={mapStyle} onViewportChange={(nextViewport) => setViewport(nextViewport)
    </ReactMapGL>
  )
}
```

**Comment by Pessimistress** [comment]
react-map-gl does not handle the rendering of the map itself. My suggestion is to use the latest release of mapbox-gl as your dependency. If this remains an issue, you may get better help in the [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js) repo.
