### ISSUE TITLE
Persisting tiles in ReactMapGL 

### ISSUE THREAD

**Issue by hardyb** [visgl/react-map-gl#1182]
Not an issue (bug) just looking for some guidance.

I'm using ReactMapGL with mapStyle="mapbox://styles/.../...xyz" and REACT_APP_MAPBOX_ACCESS_TOKEN env var.

I am looking to be pointed to some guidance on peristing tiles (if permissable and feasible) in some way, as distinct from caching, so accessible over an app restart and going off line.  Still for serving to the same authorized client.

Hope this makes sense.

**Comment by Pessimistress** [comment]
react-map-gl is a wrapper of mapbox-gl. For this particular use case you may get better help from the Mapbox GL JS repo.
