### ISSUE TITLE
Can not query rendered features in onMouseMove callback funtion 

### ISSUE THREAD

**Issue by wisdomG** [visgl/react-map-gl#1184]
I put the layer id into _interactiveLayerIds_ , but I still can not query rendered features in onMouseMove callback function. Here is my code 

```jsx
<MapGL
        {...viewPort}
        mapStyle="mapbox://styles/mapbox/dark-v10"
        height="100vh"
        width="100vw"
        onViewportChange={(newView: any) => setViewPort(newView)}
        mapboxApiAccessToken={token}
        interactiveLayerIds={['gps']}
        onMouseEnter={(e: any) => {
          const { lngLat } = e
          const hoverFeatures = map.queryRenderedFeatures(lngLat) // here, hoverFeatures is always empty when my mouse  enters the 'gps' layer
        }}
        ref={mapRef}
      >
        <Source type="geojson" data={{ type: 'FeatureCollection', features }}>
          <Layer
            id={'gps'}
            type="line"
            layout={...}
            paint={...}
          />
        </Source>
      </MapGL>
```

**Comment by Pessimistress** [comment]
- [queryRenderedFeatures](https://visgl.github.io/react-map-gl/docs/api-reference/static-map#queryrenderedfeatures) first argument is in screen pixel coordinates, not lngLat.
- [interactiveLayerIds](https://visgl.github.io/react-map-gl/docs/api-reference/interactive-map#interactivelayerids) do not affect `queryRenderedFeatures`. In your code sample, `event.features` should already be the features that you are trying by to query.

**Comment by wisdomG** [comment]
@Pessimistress I can get the features field from the onHover event object. But I can not get it in the onMouseEnter event. The event object looks like this.
![image](https://user-images.githubusercontent.com/11959301/94100233-a6158d80-fe5f-11ea-83dc-bb2406dbc757.png)

**Comment by Pessimistress** [comment]
See my comment above - you need something like `queryRenderedFeatures(event.point, {layers: ['gps']})`
