### ISSUE TITLE
Broken markdown table in WebMercatorViewport docs

### ISSUE THREAD

**Issue by dechristopher** [visgl/react-map-gl#1185]
I noticed this issue a few minutes ago:
![image](https://user-images.githubusercontent.com/12652694/94185406-3c06e380-fe73-11ea-89ff-314cb89b6333.png)

Since you use ocular to build static sites from your docs, I think there may have just been an issue with the most recent build. The source for WebMercatorViewport lies in the Math.GL library's docs and is pulled in at build as I'm sure you know. In that repo, the code for that table is not actually broken or malformed in a way that would cause it to not render properly. What I did notice is that all other tables in the docs have an additional line between the description of a function and a table starting.

---
```
##### `unprojectFlat(xy, scale)`

Unprojects a Web Mercator coordinate to longitude and latitude.
| Parameter | Type | Default | Description |
| -------------- | --------- | -------- | ------------------------------- |
| `xy` | `Array` | (required) | Web Mercator coordinates, `[x, y]` |
| `scale` | `number` | `this.scale` | Web Mercator scale |
```

##### `unprojectFlat(xy, scale)`

Unprojects a Web Mercator coordinate to longitude and latitude.
| Parameter | Type | Default | Description |
| -------------- | --------- | -------- | ------------------------------- |
| `xy` | `Array` | (required) | Web Mercator coordinates, `[x, y]` |
| `scale` | `number` | `this.scale` | Web Mercator scale |

---

I've opened a PR to fix the lack of a newline after the `unprojectFlat` function's description: 
https://github.com/uber-web/math.gl/pull/170

Docs site may need a redeploy after this PR is merged.

**Comment by Pessimistress** [comment]
This has been fixed. Thank you!
