### ISSUE TITLE
Popup has wrong position when it was out of view and changed it's position.

### ISSUE THREAD

**Issue by lukaszbarkowski** [visgl/react-map-gl#1186]
When popup's position (lat, lon) change when it's out the container to a position which is inside the container, the popup will be aligned to old position. See attached, the position changes on map click:
![captured](https://user-images.githubusercontent.com/40040662/94413757-cdc86680-017b-11eb-9d61-ba9a58360d7f.gif)

Demo: https://codesandbox.io/s/deckgl-1-forked-6jgc0?file=/src/App.js

**Comment by imprevo** [comment]
I have similar issue.
I noticed that the popup works correctly on the first render. Found a workaround - force remounting.
So, for you demo I just added **key** prop for remounting Popup component.
Demo: https://codesandbox.io/s/deckgl-1-forked-jjd8w?file=/src/App.js:1217-1254
More like a hack, but maybe it will work for you :)

**Comment by Pessimistress** [comment]
Closing - v6 is no longer actively maintained.
