### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by aakhan89** [visgl/react-map-gl#1187]
Is there possible localization in the map ?

**Comment by syedfasih** [comment]
I also have to change map labels (countries, cities etc...) to Arabic when application language is changed and vice versa. I have used StaticMap with functional component.

**Comment by Pessimistress** [comment]
[enable RTL](https://visgl.github.io/react-map-gl/docs/get-started/get-started#enable-right-to-left-language-support)

Follow [mapbox's example](https://docs.mapbox.com/mapbox-gl-js/example/language-switch/)

**Comment by syedfasih** [comment]
> 
> 
> [enable RTL](https://visgl.github.io/react-map-gl/docs/get-started/get-started#enable-right-to-left-language-support)
> 
> Follow [mapbox's example](https://docs.mapbox.com/mapbox-gl-js/example/language-switch/)

The labels have been translated but I have to translate all the labels. There are various labels that are shown in en but not in ar.  code is below:

`<StaticMap
                {...viewport}
                mapStyle="mapbox://styles/mapbox/streets-v11"
                mapboxApiAccessToken={mapboxKey}
                mapOptions
                onLoad={event => {
                    setLabels(event.target);
                }}
            >`
`const setLabels = map => {
    const language = localStorage.getItem('lang')
        ? JSON.parse(localStorage.getItem('lang')).code
        : 'ar';

    map.getStyle().layers.map(each => {
        if (each.hasOwnProperty('layout') && each.layout.hasOwnProperty('text-field')) {
            map.setLayoutProperty(each.id, 'text-field', ['get', `name_${language}`]);
        }
    });
};`

Please guide me what is wrong with it?

**Comment by Pessimistress** [comment]
You need to contact Mapbox for issues in their labels. react-map-gl is only a wrapper and does not provide the data service.

**Comment by chriszrc** [comment]
@Pessimistress Mapbox has a "language" option now that does the localization automatically now:

<img width="662" alt="Screen Shot 2022-10-10 at 10 13 30 AM" src="https://user-images.githubusercontent.com/25695785/194874661-fe741a70-11a1-4373-9f2d-6bf70c762f92.png">

https://docs.mapbox.com/mapbox-gl-js/api/map/

But I don't see that option in the react-mapbox-gl docs? Can we set this option?

**Comment by chriszrc** [comment]
@TripIconfont so doing i18n with mapbox is a 2 step process, you can use the locale setting for the i18n of ui components:

https://docs.mapbox.com/mapbox-gl-js/api/map/#:~:text=for%20supported%20languages.-,options.locale,-Object

Which requires adding your own translation files like this:

https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/default_locale.js#L15-L16

And then there's the language for labels used by tiles, and to change that, you need this plugin:

https://github.com/mapbox/mapbox-gl-language

**Comment by eduludi** [comment]
I found a solution using `onRender` to capture the `map` instance, and then call `map.setLanguage()` with the desired language.

```js
export default function MyMap({ language = 'en' }) {
  const mapRef = useRef()
  const [map, setMap] = useState()

  // Called only once map is rendered (async)
  const onRender = useCallback(() => {
    const mapElem = mapRef?.current
    if (!mapElem) return

    // Saves map reference to state
    setMap(mapElem)
  }, [])


  useEffect(() => {
    if (map && language) {
      map.setLanguage(language) // <= HERE IS THE KEY: This sets the language.
    }
  }, [map, language])
  
   return (
     <ReactMapGL
        ref={mapRef}
        mapboxAccessToken={`map-token-here`}
        onRender={onRender}
        // ... your other props
      />
   )
}
```
