### ISSUE TITLE
"control" example, webpack bundle failure

### ISSUE THREAD

**Issue by qiaoxin136** [visgl/react-map-gl#1189]
I am new to react-map-gl. love it very much. I have a webpack bundle problem. 

i tried "control" example. 

Use "npm start", it runs well. 

I use "webpack --config "webpack.config.js". it failed. the error message is

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "yarn" to install the CLI via "yarn add -D".
Do you want to install 'webpack-cli' (yes/no): y
Installing 'webpack-cli' (running 'yarn add -D webpack-cli')...
yarn add v1.22.4
warning package.json: No license field
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning No license field
success Saved 1 new dependency.
info Direct dependencies
└─ webpack-cli@3.3.12
info All dependencies
└─ webpack-cli@3.3.12
Done in 9.22s.
Error: Cannot find module 'webpack-cli'
Require stack:
- C:\Users\fqiao\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at C:\Users\fqiao\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:143:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: **'MODULE_NOT_FOUND',**
  requireStack: [
    'C:\\Users\\fqiao\\AppData\\Roaming\\npm\\node_modules\\webpack\\bin\\webpack.js'
  ]
}

i tried in use "npm install webpack", the result is the same. 

Can someone point out what I did wrong here? thanks.

**Comment by AndrewUsher** [comment]
You need to install webpack-close as well @qiaoxin136

**Comment by qiaoxin136** [comment]
> You need to install webpack-close as well @qiaoxin136

thank you for your response. I do not know webpack well. what is webpack-close, is it a package to install. I can not find this package. Can you provide a little more info?

**Comment by Pessimistress** [comment]
Are you using the example at https://github.com/visgl/react-map-gl/tree/master/examples/controls ? `webpack-cli` is already listed as a dev dependency.

Running `npx webpack -p` is successful on my PC without installing anything else.

**Comment by AndrewUsher** [comment]
@qiaoxin136 sorry, autocorrect :( I meant `webpack-cli`.

@Pessimistress `npx` gives me this prompt, so you may have `webpack-cli` installed elsewhere already.

![image](https://user-images.githubusercontent.com/24868644/98260457-f85ec980-1f48-11eb-85e6-19771149adb1.png)

**Comment by Pessimistress** [comment]
I am talking about running the command in the controls example, as the original issue suggests. https://github.com/visgl/react-map-gl/blob/master/examples/controls/package.json#L18

You need to provide more context if that is not your setup.
