### ISSUE TITLE
'getRTLTextPluginStatus' is not exported from 'react-map-gl'

### ISSUE THREAD

**Issue by syedfasih** [visgl/react-map-gl#1190]
I am loading setRTLTextPlugin as:
`import { StaticMap, Marker, setRTLTextPlugin, getRTLTextPluginStatus } from 'react-map-gl';`
After that I can call setRTLTextPluginto load the script to enable to work with arabic text.

I need to load this plugin once. For this I tried to import getRTLTextPluginStatus  to check the plugin status then exception occurred;
`'getRTLTextPluginStatus' is not exported from 'react-map-gl'`

Any help is appreciated.

**Comment by Pessimistress** [comment]
`getRTLTextPluginStatus` is not an export of react-map-gl. You can import it from `mapbox-gl`.

**Comment by syedfasih** [comment]
> 
> 
> `getRTLTextPluginStatus` is not an export of react-map-gl. You can import it from `mapbox-gl`.

Thanks,Problem resolved.
