### ISSUE TITLE
Prop for setting GelocateControl to true by default

### ISSUE THREAD

**Issue by Mohitbalwani26** [visgl/react-map-gl#1191]
I have added GeolocateControl component under ReactMapGL. I want to trigger Gelocatecontrol by default to true when ReactMapGL renders. I couldn't find the prop to be passed to GelocateControl.
Code looks something like this:
```javascript
<ReactMapGL
   mapboxApiAccessToken={mapboxApiKey}
   mapStyle="mapbox://styles/mapbox/streets-v11"
   {...viewport}
   {...mapStyle}
   onViewportChange={this.handle_view}
    >
     <GeolocateControl
        positionOptions={{ enableHighAccuracy: true }}
        trackUserLocation={true}
        showUserLocation={false}
        />
</ReactMapGL>
```

**Comment by Pessimistress** [comment]
[auto](https://visgl.github.io/react-map-gl/docs/api-reference/geolocate-control#auto)
