### ISSUE TITLE
GeolocateControl component not triggering automatically with track/showUserLocation set to true

### ISSUE THREAD

**Issue by DhenPadilla** [visgl/react-map-gl#1198]
I feel like I may be missing something with my logic, but I want to be able to trigger the geolocateControl to show my position upon the render of my component.

There's 2 parts to my issue, and I'm sure the first is me just missing something small

1. My current component's render function includes a GeolocateControl just as the docs recommend: 
```
        <GeolocateControl
          style={geolocateStyle}
          positionOptions={{enableHighAccuracy: true}}
          trackUserLocation={true}
          showUserLocation={true}
          onViewportChange={setViewport}
        />
```

Which does not automatically trigger my location to be shown upon render. Geolocation only shows *after* the geolocateControl is clicked

2. Once I get this to work, I want to assign a state variable to dynamically change track/showUserLocation via a stateVariable
i.e: 
`
trackUserLocation={userLocationOn}
showUserLocation={userLocationOn}
`

I've tested this, and it already works - but I just need to automatically trigger my location to display upon render, if `userLocationOn = true`.

**Comment by Pessimistress** [comment]
#1191
