### ISSUE TITLE
Usage of `viewport-mercator-project` in `react-map-gl`

### ISSUE THREAD

**Issue by wentjun** [visgl/react-map-gl#1202]
`viewport-mercator-project` is one of dependencies that is being used by `react-map-gl`. However, the package is [no longer being maintained](https://www.npmjs.com/package/viewport-mercator-project), as it has been shifted to [`@math.gl/web-mercator` ](https://preview.npmjs.com/package/@math.gl/web-mercator). 

Is there a reason why `react-map-gl` is still using `viewport-mercator-project`? If not, I'll be happy to submit a PR to fix this if the maintainers are not working on this anytime soon!

**Comment by Pessimistress** [comment]
We have not published a major release of `react-map-gl` since the shift, so the dependency is kept to avoid breaking existing applications. The latest `viewport-mercator-project` module contains literally one line:

https://unpkg.com/viewport-mercator-project@7.0.1/index.js

**Comment by wentjun** [comment]
@Pessimistress Got it! Thanks :)
