### ISSUE TITLE
Calling fitBounds does nothing

### ISSUE THREAD

**Issue by bkiac** [visgl/react-map-gl#1206]
I'm struggling with a strange behavior of the `fitBounds` method:
if I call `fitBounds` inline with the `WebMercatorViewport` constructor it works as expected, but if I try to reuse the `WebMercatorViewport` instance and call the `fitBounds` later, it does nothing.
```js
const wmv = new WebMercatorViewport({
  width,
  height,
}).fitBounds(bounds); // works as expected

// vs

const wmv2 = new WebMercatorViewport({
  width,
  height,
});
// ...
wmv2.fitBounds(bounds); // does nothing
```

I created a CodeSandbox example which is available here: https://codesandbox.io/s/react-map-gl-strange-fitbounds-ofr6b

**Comment by Pessimistress** [comment]
`fitBounds` returns a **new viewport**. It does not modify the instance that you call it with.

http://visgl.github.io/react-map-gl/docs/api-reference/web-mercator-viewport#fitboundsbounds-options-object

**Comment by bkiac** [comment]
Thanks! I knew it will be some stupid mistake because I've been staring at it for too long! :smile:
