### ISSUE TITLE
Cannot get Layer properties within a bounding box using queryRenderedFeatures in react-map and react-map-draw

### ISSUE THREAD

**Issue by mcfwesh** [visgl/react-map-gl#1207]
Firstly, I am using the mapRef to get the vanilla API for mapbox for use.
Firstly, I am using the mapRef to get the vanilla API for mapbox for use.

I am using turf.js to calculate the bbox from a polygon feature gotten when I draw a polygon on a layer using Mapbox Draw. After conversion, I use queryRenderedFeatures like so:

```
const features = drawRef && drawRef.getFeatures();
    const geometry = features && features[0];
    console.log(features);
    const bbox = geometry && turf.bbox(features[0]);

    console.log(
      bbox && map.queryRenderedFeatures({ bbox, layers: ["mexs"] })
    );
```
I constantly seem to get an empty array with the above code. However, when I replace the 'bbox' parameter with a point in the queryRenderedFeatures function, I get the layer properties. What am I doing wrong, please? Help me

**Comment by Pessimistress** [comment]
https://docs.mapbox.com/mapbox-gl-js/api/map/#map#queryrenderedfeatures

**Comment by mcfwesh** [comment]
Hi,
That was exactly the method I used (queryRenderedFeatures). Now, I reverted to using querySourceFeatures which returns all the features in my query. Now, there is the problem of varying number of features at different zoom levels. I would appreciate a work around for this since I want to get the same number of features even outside the viewport. 

Note: I do not use the Mapbox Studio, so the popular workaround of uploading and redownloading of datasets might not work for me.

**Comment by Pessimistress** [comment]
The method calls for two parameters, the first one is `geometry` and the second one is `options`. That's not what you are providing in your code snippet.

**Comment by mcfwesh** [comment]
Sorry, ignore the curly braces, around it. This is the correct one:
```
const features = drawRef && drawRef.getFeatures();
    const geometry = features && features[0];
    console.log(features);
    const bbox = geometry && turf.bbox(features[0]);

    console.log(
      bbox && map.queryRenderedFeatures(bbox, {layers: ["mexs"] })
    );
```

My code snippet has "bbox" as the first parameter and "layers" as the second. Check it again please

**Comment by Pessimistress** [comment]
You are still not passing correctly formatted parameters. turf.js returns a bbox that is a flat array. `queryRenderedFeatures` requires an array of points if you want to define a box.

**Comment by mcfwesh** [comment]
Yea, I have also tried to un-flatten the array as well and input them as parameters, yet I still get an empty array. Turfjs returns lnglat bbox array. I believe this is usable?

**Comment by Pessimistress** [comment]
Please create a Code Sandbox if you need help debugging. It's hard to tell what's wrong from your description.
