### ISSUE TITLE
PointerEvent feature geometry coordinates differ between events while ids are the same

### ISSUE THREAD

**Issue by bkiac** [visgl/react-map-gl#1208]
I was trying to implement a "zoom to bounding box" feature in my app and I noticed that the clicked feature's coordinates are not always the same between events even though the user clicks on the same feature on the map. This causes a problem for me because if the coordinates are not the same, I can't reliably fit the map to the feature's bounding box.

I'm not able to reproduce this every time, but I captured an example to show this behavior.
![Screencast-2020-10-28-101943](https://user-images.githubusercontent.com/24522620/97418328-fc676780-1908-11eb-9cc9-9836015c7f19.gif)
CodeSandbox: https://codesandbox.io/s/react-map-gl-pointerevent-feature-geometry-9yiqn?file=/src/App.js

I can work around this by copying the coordinates into properties, but I'm confused about why event coordinates don't match up regularly.

**Comment by Pessimistress** [comment]
`onClick` calls `queryRenderedFeatures` which might return a partial geometry if it's clipped by the current viewport. You can try calling `querySourceFeatures` to get the original.
