### ISSUE TITLE
Incomplete PointerEvent interface

### ISSUE THREAD

**Issue by bkiac** [visgl/react-map-gl#1209]
```ts
export interface PointerEvent extends MouseEvent {
    type: string;
    point: [number, number];
    lngLat: [number, number];
    target: any;
    srcEvent: any;
    // backward compatibility: v3 interface
    features: any[];
}
```

- `PointerEvent` interface is missing `offsetCenter` object which is used in this example: https://github.com/visgl/react-map-gl/blob/d3ede46577762e22c7010bde083ea6365635e7c4/examples/zoom-to-bounds/src/app.js#L51
- `PointerEvent` extends `MouseEvent` which has required `offsetX` and `offsetY` properties, but these are `undefined` in the object in runtime. (I'm not sure whether `offsetX` and `offsetY` are always `undefined` or they should be flagged as optional.)

![image](https://user-images.githubusercontent.com/24522620/97423014-e9579600-190e-11eb-9c26-471e7dccf0ae.png)

Packages: 
- `react-map-gl@5.2.9`
- `@types/react-map-gl@5.2.8`

**Comment by Pessimistress** [comment]
The maintainers of this repo did not work on @types/react-map-gl.
