### ISSUE TITLE
How to use open street map tiles?

### ISSUE THREAD

**Issue by ats1999** [visgl/react-map-gl#1211]
Raster style using api.
```js
const rasterStyle = {
  "version": 8,
  "sources": {
      "raster-tiles": {
          "type": "raster",
          "url": "https://api.mapbox.com/styles/v1/uma1302/ckfjjqbim55fk1arm6zgbedgs/tiles/256/{z}/{x}/{y}@2x?access_token=token..",
          "tileSize": 256
      }
  },
  "layers": [{
            // data
  }]
}
```

Raster style using open street map tiles.
```js
url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
```
Component
```js

      <ReactMapGL
        mapStyle={rasterStyle} 
        mapboxApiAccessToken={"token"}
        {...viewport}
        onViewportChange={nextViewport => setViewport(nextViewport)}
      />
```
None of the above works. It is displaying a white screen at the place of the map.
Is there anything I am doing wrong?
Thanks.

**Comment by Pessimistress** [comment]
https://docs.mapbox.com/mapbox-gl-js/example/map-tiles/

**Comment by ats1999** [comment]
> https://docs.mapbox.com/mapbox-gl-js/example/map-tiles/

Just replace the 
```js

'tiles': [
'https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg'
]
```
with
```js

                    'tiles': [
                        'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
                    ]
```
and see it's not working.

**Comment by Pessimistress** [comment]
I do not believe `{s}` is a valid template string, you may need to replace it with e.g. `a`.

Note that react-map-gl simply passes the map style to mapbox-gl. It does not handle interpretation and rendering. Your questions may be better answered in the Mapbox GL JS repo.

**Comment by ats1999** [comment]
Okey.
Thanks anyway

**Comment by Pessimistress** [comment]
> I do not believe `{s}` is a valid template string, you may need to replace it with e.g. `a`.

https://codesandbox.io/s/strange-platform-ymg14
