### ISSUE TITLE
How can we draw a circle around markers.

### ISSUE THREAD

**Issue by ats1999** [visgl/react-map-gl#1212]
![Screenshot (454)](https://user-images.githubusercontent.com/54087826/97954982-2208db00-1df9-11eb-9567-72723570fa1e.png)

```js
CircleMarker = Allpoints.map(
  (circle, Index) =>
    <Circle 
      key={Index}
      center={circle.position}
      fillColor="#E95617" 
      radius={20000}
      color= '#E95617'
      weight={1}
    >
    </Circle>
```

This is the example code from the leaflet. 
Is there any way to draw a circle around the marker?

**Comment by Pessimistress** [comment]
https://visgl.github.io/react-map-gl/docs/get-started/adding-custom-data
