### ISSUE TITLE
Is this right way of using Source and Layer component. 

### ISSUE THREAD

**Issue by ats1999** [visgl/react-map-gl#1213]
### The example is taken from [Here](https://docs.mapbox.com/mapbox-gl-js/example/geojson-line/). 
Then i created the Map for me like this.
### dataJS - ./layers
```js

export const dataJS = {
  'type': 'Feature',
  'properties': {},
  'geometry': {
      'type': 'LineString',
      'coordinates': [
        [
        [-67.13734351262877, 45.137451890638886],
        [-66.96466, 44.8097],
        [-68.03252, 44.3252],
        [-69.06, 43.98],
        [-70.11617, 43.68405],
        [-70.64573401557249, 43.090083319667144],
        [-70.75102474636725, 43.08003225358635],
        [-70.79761105007827, 43.21973948828747],
        [-70.98176001655037, 43.36789581966826],
        [-70.94416541205806, 43.46633942318431],
        [-71.08482, 45.3052400000002],
        [-70.6600225491012, 45.46022288673396],
        [-70.30495378282376, 45.914794623389355],
        [-70.00014034695016, 46.69317088478567],
        [-69.23708614772835, 47.44777598732787],
        [-68.90478084987546, 47.184794623394396],
        [-68.23430497910454, 47.35462921812177],
        [-67.79035274928509, 47.066248887716995],
        [-67.79141211614706, 45.702585354182816],
        [-67.13734351262877, 45.137451890638886]
        ]
        ]
  }
}
```

### layerDemo - ./layers
```js
export const layerDemo = {
  'id': 'route',
  'type': 'line',
  'source': 'route',
  'layout': {
      'line-join': 'round',
      'line-cap': 'round'
  },
  'paint': {
      'line-color': 'red',
      'line-width': 15
  }
}
```

### Main component
```js
import * as React from 'react';
import { useState,useRef } from 'react';
import ReactMapGL, {
    ScaleControl,GeolocateControl,FullscreenControl,NavigationControl,
    Marker,Popup,Source, Layer
} from 'react-map-gl';
import {fromJS} from 'immutable';
import {dataJS,layerDemo} from './layers';
import Markers from "./Markers";
import Popups from "./Popups";
import * as data from "./temp-data";
const mapStyle = new fromJS({
    version:8,
    sources:{
        osm:{
            type:"raster",
            tiles:["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],
            tileSize:256,
            attribution:'Map tiles by <a target="_top" rel="noopener" href="https://tile.openstreetmap.org/">OpenStreetMap tile servers</a>, under the <a target="_top" rel="noopener" href="https://operations.osmfoundation.org/policies/tiles/">tile usage policy</a>. Data by <a target="_top" rel="noopener" href="http://openstreetmap.org">OpenStreetMap</a>',
        }
    },
    layers:[{
        id: 'osm',
        type: 'raster',
        source: 'osm'
    }]
})

function MapBoxComponent() {
    const [viewport, setViewport] = useState({
      width: 800,
      height: 800,
      latitude: 37.830348,
      longitude: -122.486052,
      zoom: 15
    });
    const sourceRef = useRef(null);
    return <>
        <h1>MAP - box</h1>
        <ReactMapGL
            {...viewport}
            mapStyle={mapStyle}
            mapboxApiAccessToken="API__KEY"
            onViewportChange={nextViewport => setViewport(nextViewport)}
        >
            
        <div style={{position: 'absolute', bottom: 20, right: 20}}>
          <ScaleControl maxWidth={100} unit={"metric"}/>
        </div>
        <div style={{position:"absolute",top:5,left:5}}>
            <GeolocateControl
            positionOptions={{enableHighAccuracy: true}}
            trackUserLocation={true}
            />
        </div>
        <div style={{position: 'absolute', top: 35,left:5}}>
          <FullscreenControl 
            // container={document.querySelector('body')}
            // pass a map container insted of body
          />
        </div>
        <div style={{position: 'absolute', top: 65,left:5}}>
          <NavigationControl />
        </div>
        <Source
          type="geojson"
          data={dataJS}
          cluster={true}
          clusterMaxZoom={14}
          clusterRadius={50}
          ref={sourceRef}
        >
        <Layer {...layerDemo} />
        </Source>
        </ReactMapGL>
    </>
}

export default MapBoxComponent

```

The map is rendered correctly but it does not show a line.

### MapBox demo
![Screenshot (456)](https://user-images.githubusercontent.com/54087826/97960969-84b4a380-1e06-11eb-90c0-8120c754f8fb.png)

### My Demo
![Screenshot (455)](https://user-images.githubusercontent.com/54087826/97961119-cba29900-1e06-11eb-8379-5ce09f594105.png)

**Comment by anatolysukhanov** [comment]
coordinates should be a 2-dimensional array for LineString.

dataJS should look like this

    const dataJS = {
      type: "Feature",
      properties: {},
      geometry: {
        type: "LineString",
        coordinates: [
          [-67.13734351262877, 45.137451890638886],
          [-66.96466, 44.8097],
          [-68.03252, 44.3252],
          [-69.06, 43.98],
          [-70.11617, 43.68405],
          [-70.64573401557249, 43.090083319667144],
          [-70.75102474636725, 43.08003225358635],
          [-70.79761105007827, 43.21973948828747],
          [-70.98176001655037, 43.36789581966826],
          [-70.94416541205806, 43.46633942318431],
          [-71.08482, 45.3052400000002],
          [-70.6600225491012, 45.46022288673396],
          [-70.30495378282376, 45.914794623389355],
          [-70.00014034695016, 46.69317088478567],
          [-69.23708614772835, 47.44777598732787],
          [-68.90478084987546, 47.184794623394396],
          [-68.23430497910454, 47.35462921812177],
          [-67.79035274928509, 47.066248887716995],
          [-67.79141211614706, 45.702585354182816],
          [-67.13734351262877, 45.137451890638886]
        ]
      }
    };

**Comment by ats1999** [comment]
hi, i just used your example but, it didn't worked.
[Code sandbox](https://codesandbox.io/s/eager-albattani-frv7d?file=/src/App.js)

**Comment by anatolysukhanov** [comment]
Clustering only works for points (https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-cluster), your feature is LineString so it's not being rendered.

You just need to remove these lines:

    cluster={true}
    clusterMaxZoom={14}
    clusterRadius={50}

**Comment by ats1999** [comment]
I did what you said, but no improvement. 
[if you have time then please edit this on codesandbox](https://codesandbox.io/s/eager-albattani-frv7d?file=/src/App.js)

Thanks in advance.

**Comment by anatolysukhanov** [comment]
You just need to zoom out

![image](https://user-images.githubusercontent.com/7021042/97977169-d811fc00-1ddc-11eb-8bb0-9402b5cd531e.png)

**Comment by ats1999** [comment]
Thanks

**Comment by Pessimistress** [comment]
@ats1999 Please close your issue of your question is resolved.

**Comment by ats1999** [comment]
> @ats1999 Please close your issue of your question is resolved.

Did
