### ISSUE TITLE
Map being rendered as a white screen in component

### ISSUE THREAD

**Issue by mcshakes** [visgl/react-map-gl#1222]
What I'm using:

```
├── mapbox-gl@1.12.0
└─┬ react-map-gl@5.2.9
  └── mapbox-gl@1.12.0

"react": "^16.13.1"
```
My map component:

```
import * as React from 'react';
import { useState } from 'react';
import ReactMapGL from 'react-map-gl';

const MAPBOX_TOKEN = process.env.REACT_APP_MAPBOX_TOKEN;

const Map = (props) => {
    const [viewport, setViewPort] = useState({
        latitude: props.coordinates.data.data.coordinates.latitude,
        longitude: props.coordinates.data.data.coordinates.longitude,
        zoom: 14,
        bearing: 0,
        pitch: 0
    });

    const _onViewportChange = viewport => setViewPort({...viewport, transitionDuration: 3000 })

    return (
        <div>
            <ReactMapGL
                {...viewport}
                width="60vw"
                height="60vh"
                mapStyle="mapbox://styles/mapbox/streets-v11"
                onViewportChange={_onViewportChange}
                mapboxApiAccessToken={MAPBOX_TOKEN}
            />
        </div>
    );
}

export default Map;
```

The parent component (_only return statement_):

```
return (

    <div>
        {
            yelpData.data && <Map coordinates={yelpData} />
        }
    </div>
  )
```
Lat-Long coordinates are indeed being passed from to the state from the parent component. I double-checked to see it wasn't null in the console.

Is there something I am missing here? Let me know if more info is needed.

**Comment by Pessimistress** [comment]
Try check `viewport` and see if lon/lat are valid numbers.

**Comment by mcshakes** [comment]
@Pessimistress the lat/long numbers are being passed through as integers to viewport. Image below

![Screen Shot 2020-11-05 at 1 38 41 PM](https://user-images.githubusercontent.com/8164007/98294162-b6e01580-1f6c-11eb-8ff7-0b9ecb1591e0.png)

And I am fairly certain that is how all of them are being sent in from the backend.

**Comment by Pessimistress** [comment]
Do you see any console errors?

**Comment by mcshakes** [comment]
No errors at all, which is most confusing.

**Comment by Pessimistress** [comment]
I suggest you check your page layout CSS, e.g. the map is not behind any other components. You can search for `mapboxgl-map` in the element inspector to find the map container.

You did not say where you are running your app. If you are using an uncommon browser/OS, you can try go to https://visgl.github.io/react-map-gl/examples on your device to make sure Mapbox is supported.

If you are using Electron, there are additional configurations you need to enable, see #785

**Comment by mcshakes** [comment]
@Pessimistress Ok, I did a reinstall of modules and (I think more importantly here) updated Chrome browser from 84 to 86.0.4240.183. Maps are now being rendered successfully. I wish I had more data to show what is the exact fix, honestly. 
Thanks for the help!

**Comment by brienna** [comment]
I have the same problem, a white screen on Chrome, with the boilerplate. It works in Firefox however.

**Comment by insivika** [comment]
We're having this issue as well. 
![Screen Shot 2021-08-05 at 1 15 58 PM](https://user-images.githubusercontent.com/33808429/128400644-4a7fe6b4-ec32-4da4-8ba7-77d12fe77875.png)

**Comment by aperkaz** [comment]
Why was this issue close? I am facing the same issue...

**Comment by Oudwins** [comment]
I am also having this same issue. On firefox the map display correctly. On chrome it doesn't. This is after the change from svelte 4 to svelte 5, but no code was changed for the map component
