### ISSUE TITLE
onclick is not getting fired using react ref.

### ISSUE THREAD

**Issue by ats1999** [visgl/react-map-gl#1224]
I am using react-map-gl and Mapbox. 
I want to assign a `onclick` handler to the map using react ref.

```js
<ReactMapGL
     onClick={(e)=>console.log("I am working",e)}
  >
// ---
```

The above code works fine but it adds complexity to our application.  i want to use some thing native-like click handler. 
```
map.on('click',(e)=>{
     console.log("I am not working")
})
```

I passed `mapRef` as a prop to other components like this. 
```js
<ReactMapGL ref={mapRef}>
<Component mapRef={mapRef}/>
</ReactMapGL>
```

Then I used it like this, 
```js
function Component =({mapRef })=>{
   useEffect(()=>{
     if(mapRef && mapRef.current.getMap().loaded()){
mapRef.current.getMap().on('click', function(e) {
                console.log('A click event has occurred at ' + e.lngLat);
            });
    }
   },[])
}
```
 this is not calling when i am clicking on the map.
Although other methods like, `setCenter`, `addSource` etc are working fine.

**Comment by Pessimistress** [comment]
This library hides some of the native APIs by offering React-compliant equivalents. If there is a React prop, like `onClick`, we don't guarantee that the native Map API would work. See https://github.com/visgl/react-map-gl#limitations

**Comment by ats1999** [comment]
That means there is one one onclick event and I have to manage this event at every component.
