### ISSUE TITLE
TypeError: Cannot read property 'getMap' of null

### ISSUE THREAD

**Issue by ats1999** [visgl/react-map-gl#1227]
I have a component where i want to add some sources and layers. For that is used like this. 
I want to check if the map is loaded or not `if(!mapRef || !mapRef.current.getMap().loaded())   return;`. It givs me error `TypeError: Cannot read property 'getMap' of null`.

**Comment by Pessimistress** [comment]
`ref.current` is only populated after the component mounts. This is unrelated to react-map-gl. Please consult with React's documentation.

**Comment by ats1999** [comment]
> ref.current is only populated after the component mounts.
I am calling `ref.current` in componentDidMount()` method. It sould not rise any error.
