### ISSUE TITLE
How to add a default marker

### ISSUE THREAD

**Issue by kbarbosa5416** [visgl/react-map-gl#1232]
Hi, I want to put a default marker for a specific coordinates, how can I do it?

**Comment by Cadet-Hasib** [comment]
I also have the same Question

**Comment by Pessimistress** [comment]
This wrapper currently provides no default marker. You need to supply the content of `<Marker>` yourself.

**Comment by Cadet-Hasib** [comment]
Can you make some Example with ` <Marker> ` kindly?

**Comment by Pessimistress** [comment]
@Cadet-Hasib have you looked at http://visgl.github.io/react-map-gl/examples/controls ?
