### ISSUE TITLE
Fit Map to Markers with react map gl

### ISSUE THREAD

**Issue by nonoumasy** [visgl/react-map-gl#1246]
So for the last week, I've been trying to find a way to fit the map or viewport to the markers for each map that is in my app...https://timelinesapp.netlify.app/.

Does anyone know how to refactor this code to react-map-gl?
https://stackoverflow.com/questions/35586360/mapbox-gl-js-getbounds-fitbounds

Notes:
1. my lat and lon are not geoJSON at the moment.

Current solution is to set the lat and lon in one location and zoom out. This is not perfect:
![Screen Shot 2020-12-02 at 4 53 09 PM (2)](https://user-images.githubusercontent.com/6312676/100949412-13c4e200-34bf-11eb-8a75-c390d35cce4f.png)

Ideal Solution: map fits to the marker of the current map. Users can create different maps so this will be different each time:
![Screen Shot 2020-12-02 at 4 53 28 PM (2)](https://user-images.githubusercontent.com/6312676/100949424-1e7f7700-34bf-11eb-9de0-e71f0c7ad3f8.png)

**Comment by jamesedmonston** [comment]
@nonoumasy You can use something like the following:

```typescript
const applyToArray = (func, array) => func.apply(Math, array);

const getBounds = (markers) => {
  const lat = markers.map((property) => marker.location?.lat ?? 0); 
  const lng = markers.map((property) => marker.location?.lng ?? 0);

  const cornersLngLat = [
    [applyToArray(Math.min, lng), applyToArray(Math.min, lat)],
    [applyToArray(Math.max, lng), applyToArray(Math.max, lat)],
  ];

  const viewport = new WebMercatorViewport({
    width: 800,
    height: 600,
  }).fitBounds(cornersLngLat, { padding: 200 });

  const { longitude, latitude, zoom } = viewport;
  return { longitude, latitude, zoom };
};

const markers = ...; // however you're retrieving your markers
const bounds = getBounds(markers);

<ReactMapGL
  ...
  latitude={bounds.latitude}
  longitude={bounds.longitude}
 ...
>
  ...
</ReactMapGL>
```

**Comment by nonoumasy** [comment]
Thanks @ jamesedmonston. I haven't tried your code as I had implemented something similar. I think your code is a lot cleaner and will try it out when I do a general refactoring. However, I am switching over to geojson format and there is another solution using turf.js for geojson coords...https://visgl.github.io/react-map-gl/examples/zoom-to-bounds.
Thanks again

**Comment by nonoumasy** [comment]
@ jamesedmonston Just tried this. Totally works ! Thanks again.

**Comment by nonoumasy** [comment]
@jamesedmonston Just tried this. Totally works ! Thanks again.

> @nonoumasy You can use something like the following:
> 
> ```ts
> import ReactMapGL, {
>   Marker,
>   WebMercatorViewport,
> } from 'react-map-gl';
> 
> const applyToArray = (func, array) => func.apply(Math, array);
> 
> const getBounds = (markers) => {
>   const lat = markers.map((marker) => marker.location?.lat ?? 0); 
>   const lng = markers.map((marker) => marker.location?.lng ?? 0);
> 
>   const cornersLngLat = [
>     [applyToArray(Math.min, lng), applyToArray(Math.min, lat)],
>     [applyToArray(Math.max, lng), applyToArray(Math.max, lat)],
>   ];
> 
>   const viewport = new WebMercatorViewport({
>     width: 800,
>     height: 600,
>   }).fitBounds(cornersLngLat, { padding: 200 });
> 
>   const { longitude, latitude, zoom } = viewport;
>   return { longitude, latitude, zoom };
> };
> 
> const markers = ...; // however you're retrieving your markers
> const bounds = getBounds(markers);
> 
> <ReactMapGL
>   ...
>   latitude={bounds.latitude}
>   longitude={bounds.longitude}
>   zoom={bounds.zoom}
>  ...
> >
>   ...
> </ReactMapGL>
> ```

**Comment by nonoumasy** [comment]
@jamesedmonston I can't move the map anymore. Do I have to do something else?
