### ISSUE TITLE
Setting Language is not working

### ISSUE THREAD

**Issue by zeel91297** [visgl/react-map-gl#1252]
I'm trying to set language for Map, but it is not taking into effect. I want to change the language of Map on load using my internationalization variable in the local storage.

Can anyone help me figure out how I can implement it?

`map.setLayoutProperty('country-label-lg', 'text-field', ['get', 'name_zh']);`

`const map = mapRef.current.getMap();`
`map.addControl(new MapboxLanguage({
          defaultLanguage: 'zh',
          languageField: 'name_zh'
        }));`

I tried implementing above two methods but none of them are working.

**Comment by Pessimistress** [comment]
You're not using any functionality provided by this library. You may get better help from the mapbox-gl repo or Mapbox's own support, if you're using their data service.

**Comment by zeel91297** [comment]
> You're not using any functionality provided by this library. You may get better help from the mapbox-gl repo or Mapbox's own support, if you're using their data service.

Do you have any idea about how I can change language using this library?
Or can you share a snippet of code? 
It would be really helpful

**Comment by Pessimistress** [comment]
Your code is fine. Not all tilesets support the language that you need. You need to check with whoever is providing your data.

**Comment by zeel91297** [comment]
@Pessimistress I tried checking everything but no changes.
I also replaced `poi-label` instead of `country-label-lg` but it didn't change any language and all the poi-labels were removed from my map. Can you perform this on the https://codesandbox.io/ and share the snippet with me?

**Comment by Pessimistress** [comment]
https://codesandbox.io/s/spring-tdd-eufkv?file=/src/App.js

**Comment by zeel91297** [comment]
@Pessimistress I have a question regarding localization.
Are we able to translate everything with the help of this? For example place of interest labels
By using your above method it is only translating Country labels.

**Comment by Pessimistress** [comment]
react-map-gl is a community project, it does not provide any tile sets. Mapbox is the service that you are paying to get the map data. You need to contact Mapbox if you have any request regarding labels.
