### ISSUE TITLE
Unable to show data from vector tileset (Mapbox Studio) on Layer component

### ISSUE THREAD

**Issue by lezan** [visgl/react-map-gl#1261]
I am trying to use a vector tileset from Mapbox Studio into react-map-gl, but for now I am not able to see source-layers rendered on map.

I setup a basic example just to make sure there are not conflit between something else, but without success.

**Layers options**:
```
const scattermapLayers = {
	id: 'scattermap',
	type: 'circle',
	source: 'scattermap',
	layout: {
		visibility: 'visible',
	},
	paint: {
		'circle-radius': 8,
		'circle-color': '#007cbf',
	},
};
```

**Render method**:
```
return (
	<MapGL
		{...viewState}
		width="100%"
		height="100%"
		mapStyle={mapStyle}
		mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
	>
		<Source id="scattermap" type="vector" url="mapbox://<Tileset ID>">
			<Layer source-layer="data-bh2j6s" {...scattermapLayers} />
		</Source>
	</MapGL>
);
```

I do not see errors or warnings in console.

More info:
- I am able to see circle correcly uploaded into Mapbox Studio, so I think Tileset is ok.
- Tileset privacy is private (not public).
- Token I am using includes `TILESETS:READ` as scope .
- react-map-box version: 5.2.10.
- react: 17.0.1.
- react-dom: 17.0.1.

Am I doing something wrong with it?

**Comment by kylebarron** [comment]
`source-layer` is required on each layer when referring to a vector dataset I believe

**Comment by Pessimistress** [comment]
This works (taken from https://docs.mapbox.com/mapbox-gl-js/example/vector-source/):

```js
const layer = {
'id': 'terrain-data',
'type': 'line',
'source': 'mapbox-terrain',
'source-layer': 'contour',
'layout': {
  'line-join': 'round',
  'line-cap': 'round'
  },
'paint': {
  'line-color': '#ff69b4',
  'line-width': 1
  }
};

function App() {
  const [viewport, setViewport] = useState({
    latitude: 37.8,
    longitude: -122.4,
    zoom: 14
  });

  return (
    <MapGL
      {...viewport}
      width="100vw"
      height="100vh"
      mapStyle="mapbox://styles/mapbox/dark-v9"
      onViewportChange={nextViewport => setViewport(nextViewport)}
      mapboxApiAccessToken={MAPBOX_TOKEN}
    >
        <Source id="mapbox-terrain" type="vector" url="mapbox://mapbox.mapbox-terrain-v2">
          <Layer {...layer} />
        </Source>
    </MapGL>
  );
}
```

There might be some access/loading issues with your private dataset that Mapbox is not warning about.

**Comment by lezan** [comment]
> 
> 
> `source-layer` is required on each layer when referring to a vector dataset I believe

Thaks for your quickly answer. I am using only a layer.
I also try to include `source-layer` into `scattermapLayers` instead of spreading into Layer componet, but nothing change.



> 
> 
> This works (taken from https://docs.mapbox.com/mapbox-gl-js/example/vector-source/):
> 
> ```js
> const layer = {
> 'id': 'terrain-data',
> 'type': 'line',
> 'source': 'mapbox-terrain',
> 'source-layer': 'contour',
> 'layout': {
>   'line-join': 'round',
>   'line-cap': 'round'
>   },
> 'paint': {
>   'line-color': '#ff69b4',
>   'line-width': 1
>   }
> };
> 
> function App() {
>   const [viewport, setViewport] = useState({
>     latitude: 37.8,
>     longitude: -122.4,
>     zoom: 14
>   });
> 
>   return (
>     <MapGL
>       {...viewport}
>       width="100vw"
>       height="100vh"
>       mapStyle="mapbox://styles/mapbox/dark-v9"
>       onViewportChange={nextViewport => setViewport(nextViewport)}
>       mapboxApiAccessToken={MAPBOX_TOKEN}
>     >
>         <Source id="mapbox-terrain" type="vector" url="mapbox://mapbox.mapbox-terrain-v2">
>           <Layer {...layer} />
>         </Source>
>     </MapGL>
>   );
> }
> ```
> 
> There might be some access/loading issues with your private dataset that Mapbox is not warning about.

I put this into codesanbox and it work without problem with my public token.
However when I change to my tileset data is not present.

I also try to switch tileset from private to public, but still the same issue.

**Comment by lezan** [comment]
Found it! Issue is related to zoom level, it is not an implementation problem.
