### ISSUE TITLE
Updating to mapbox-gl@2.0.0 still includes mapbox-gl@1.13.0

### ISSUE THREAD

**Issue by RaddishIoW** [visgl/react-map-gl#1262]
I've tried updating to mapbox-gl@2.0.0, but I think because of a dependency (mapbox-gl-supported), I'm still getting mapbox-gl@1.13.0 installed, leading to BOTH being installed in my node_modules and included in my React app.

I'm using PNPM to handle dependencies, through Rush.js. I've tried just using PNPM.
I've tried uninstalling mapbox-gl and react-map-gl and reinstalling, but I'm still getting v1.13.0 installed alongside v.2.0.0.

Any ideas how I can rid myself of 1.13.0? Am I doing something wrong when I install?

**Comment by Pessimistress** [comment]
We are going to publish a new react-map-gl version that depends on mapbox-gl@2.0.0. Meanwhile you can add the following to your package.json:

```
"resolutions": {
  "mapbox-gl": "2.0.0"
}
```

**Comment by RaddishIoW** [comment]
Thank you!

I had to use PNPM Hooks instead of resolutions, but that worked.

**Comment by Pessimistress** [comment]
v6.0.0 is published: https://github.com/visgl/react-map-gl/releases/tag/v6.0.0
