### ISSUE TITLE
mapbox-gl-js v2 question about terrain

### ISSUE THREAD

**Issue by qiaoxin136** [visgl/react-map-gl#1282]
for mapbox-gl-js v2, they add a very useful terrain component, 

see the following sample code from mapbox, we may be able to add "mapbox-dem" layer, but I do not know how you can translate map.setTerrain into react-mapbox-gl format. Is it possible to use this function in react-map-gl framework? Thanks for the advice. 

map.addSource("mapbox-dem", {
    type: "raster-dem",
    url: "mapbox://mapbox.mapbox-terrain-dem-v1",
    tileSize: 512,
    maxzoom: 14,
  });
  **### // add the DEM source as a terrain layer with exaggerated height
  map.setTerrain({ source: "mapbox-dem", exaggeration: 1.5 });**

  // add a sky layer that will show when the map is highly pitched
  map.addLayer({
    id: "sky",
    type: "sky",
    paint: {
      "sky-type": "atmosphere",
      "sky-atmosphere-sun": [0.0, 0.0],
      "sky-atmosphere-sun-intensity": 15,
    },
  });

**Comment by Pessimistress** [comment]
[getMap](https://visgl.github.io/react-map-gl/docs/api-reference/static-map#getmap)

**Comment by SantosOMartinez** [comment]
How would one access these methods like getMap from a functional component?

**Comment by segheysens** [comment]
@SantosOMartinez you need a ref to the map, like [in this cluster example](https://github.com/visgl/react-map-gl/blob/master/examples/clusters/src/app.js):
- set up useRef hook: https://github.com/visgl/react-map-gl/blob/e7f1cc61fc23aa094e218a2227d7d8bfc7cbf5c1/examples/clusters/src/app.js#L25
- and the ref needs to be set on your MapGL component: https://github.com/visgl/react-map-gl/blob/e7f1cc61fc23aa094e218a2227d7d8bfc7cbf5c1/examples/clusters/src/app.js#L53

**Comment by chrisella** [comment]
@qiaoxin136 did you get anywhere with this? I'm playing around with the terrain source bits too. I'm fine setting up the ref, but interested to see if anyone else had any progress with this before going further.

**Comment by qiaoxin136** [comment]
it works as described.

https://fayetteville2dapp1.z20.web.core.windows.net/

**Comment by nonoumasy** [comment]
@qiaoxin136 your link isn't working anymore. Any chance you have the code that works somewhere else? cheers

**Comment by qiaoxin136** [comment]
please try this one,

https://nushasewerapp.z13.web.core.windows.net/

**Comment by nonoumasy** [comment]
@qiaoxin136 
Thank you. However I didn't see any 3D terrain on any of the mapstyles.

**Comment by qiaoxin136** [comment]
i can see it perfectly. I do not know why.

**Comment by nonoumasy** [comment]
@qiaoxin136 
Yes, I do see it on the initial load on some of the styles like satellite and outdoors but as soon as you switch to another Mapbox style, it disappears. Do you mind sharing the code?

**Comment by NickCarducci** [comment]
We should just be using https://www.mapbox.com/mapbox-studio/?utm_campaign=email%7Cblast%7Cmaps%7Cgl-js-v2-1-1-21-02

I'm unsure if my `map.setTerrain()` issue is with Transpiling v2 with a Create-React-App https://github.com/visgl/react-map-gl/issues/1266#issuecomment-770037878
