### ISSUE TITLE
Markers move to incorrect location after selecting overlay with tab

### ISSUE THREAD

**Issue by jangroeneveld** [visgl/react-map-gl#1285]
It seems like something is going wrong with the transforms of markers or layers when selecting a focussable element with tab that is out of view. It happened in our own project, and I managed to reproduce it in the [Markers & Popups example](https://visgl.github.io/react-map-gl/examples/controls). 

![image](https://user-images.githubusercontent.com/6150944/103527786-2f872380-4e83-11eb-997c-80b22ff1a175.png)

To reproduce, I first opened a popup by clicking on a marker, after which I zoomed in a bit and moved the map. When hitting tab until reaching the close button or the wikipedia link in the popup, all markers move, so that the highlighted element is centered.

**Comment by Pessimistress** [comment]
Fixed in 5.2.12/6.0.3
