### ISSUE TITLE
cant register onDragEnd, onDragStart and other core mapbox event on the map

### ISSUE THREAD

**Issue by ogheneovo12** [visgl/react-map-gl#1290]
I currently needed to set this events on the map, but can't seem to find a way to do so, setting the event from the map gotten from the getMap() doesn't register the events.

**Comment by Pessimistress** [comment]
We can add onDrag* callbacks to the component in the next release. What other events are you trying to use?

**Comment by ogheneovo12** [comment]
onZoomEnd, which is the only Mapbox event I could find close to google map onBoundsChange, phew my company moving over to Mapbox for its map due to some pricing issues with google, now I have to rewrite the entire map codebase, I just switched over to core mapbox-gl-js  😔😔😔, to be able to register those events, while I await next release.

**Comment by Pessimistress** [comment]
If you just want to know whether the map is dragging/zooming you can use [onInteractionStateChange](https://visgl.github.io/react-map-gl/docs/api-reference/interactive-map#oninteractionstatechange)

**Comment by ogheneovo12** [comment]
onInteractionStateChange may be fired without onViewportChange, i will need to find a workaround, around that edge cases, as am only concerned about the end of any zoom/drag event that leads to viewPort changes.

**Comment by Pessimistress** [comment]
`onViewportChange` is called with the interaction state that causes it.

**Comment by ogheneovo12** [comment]
oh sweet!!!! 😄😄😄, i think that will do. argh, it has always been in the documentation. though I was able to determine a dragEnd from the ```onInteractionStateChange``` (without being able to always relate it with changes in viewPort) but with the ```interactionState``` available in ```onViewPortChange```  am good to go. thanks for your time and quick response, I really appreciate it.
