### ISSUE TITLE
Map being called several times

### ISSUE THREAD

**Issue by Jordan-Work** [visgl/react-map-gl#1293]
I added a simple `console.log('map')` to see whats happening, see screenshot below.

When any change happens it triggers hundreds of reloads is this expected behaviour, any way to optimize this?
I have a local branch with `mapbox-gl` and this is not how things appear to be behaving.

<img width="1338" alt="Screen Shot 2021-01-11 at 9 53 08 PM" src="https://user-images.githubusercontent.com/17144389/104263774-41a32c00-5458-11eb-814d-683bad7aff38.png">

https://github.com/visgl/react-map-gl/blob/6.0-release/examples/viewport-animation/src/control-panel.js#L22-L24
This is happening without tying it to the onMove event or state unless i'm misinformed. 
```render() {
    console.log('map')
    return (
      <div className="control-panel">
        ...
    );
  }```

**Comment by Pessimistress** [comment]
> When any change happens it triggers hundreds of reloads is this expected behaviour

A React rerender is not a map reload. Map is loaded only once as long as it's mounted. Whenever your viewport changes, there will be a React rerender.

> This is happening without tying it to the onMove event or state unless i'm misinformed.

There is no `onMove` event in react-map-gl.
