### ISSUE TITLE
Markers dont retain their co-ordinates when using flyto or panTo

### ISSUE THREAD

**Issue by ogheneovo12** [visgl/react-map-gl#1294]
**Expected Behaviour**
Markers should retain their co-ordinates and position when the map flys/pan to another center.

**Behaviour**
Markers kind of move with the map, and don't retain their co-ordinates, see image below
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/49083654/104338573-f2f89f00-54f6-11eb-96ac-7aef605aedb4.gif)

**Comment by Pessimistress** [comment]
You cannot use the native API to move the map, that breaks the binding of map state with the React props. See https://visgl.github.io/react-map-gl/docs/advanced/viewport-transition

**Comment by ogheneovo12** [comment]
mehn, now I really need to go through everything in the doc, thanks to you again.
