### ISSUE TITLE
Typescript Types for Viewport Constraints (Type error)

### ISSUE THREAD

**Issue by pcwa-ahendricks** [visgl/react-map-gl#1315]
For version 6.1.1

Viewport Constraints (ex. "maxZoom") are defined as PropTypes for the InteractiveMap component in interactive-map.js. Should those types also be defined in interactive-map.d.ts ? If so, I'd be happy to open a pull request.

**Comment by Pessimistress** [comment]
Yes they should. Feel free to open a PR!

**Comment by Pessimistress** [comment]
Published 5.3.2/6.1.2
