### ISSUE TITLE
Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by greenapple112** [visgl/react-map-gl#1325]
I used 6.1.1 everything works fine but when I upgraded to 6.1.3. It happened error: Cannot read property 'version' of undefined
![image](https://user-images.githubusercontent.com/19573272/106702311-6bc7b400-65e8-11eb-9ab2-d41e36c770a9.png)
So I reverted to the old version. But it is still a similar problem.
Could you please help?

**Comment by Pessimistress** [comment]
The error happens when you call native Mapbox api from your own code. Share your code if you need help debugging.

**Comment by greenapple112** [comment]
I'm sorry for the late reply. I fixed it. Thank you very much :)

**Comment by cg-n** [comment]
@greenapple112  What was your [solution](https://xkcd.com/979/)?
