### ISSUE TITLE
Map resets viewport/viewstate to initial value when width or height changes dynamically

### ISSUE THREAD

**Issue by Antje3** [visgl/react-map-gl#1330]
How to reproduce:

- Go to this example: http://visgl.github.io/react-map-gl/examples/viewport-animation/
- The initial view shows San Francisco.
- Select another city.
- Resize the browser window (and the map size changes).
- The view resets to San Francisco, which is the initial view.

The same happens when the maps width or height changes because of a variable.

Is this behaviour expected? If so, is there a way to prevent it? Thanks!

**Comment by Pessimistress** [comment]
This has already been fixed in the latest release.

**Comment by Antje3** [comment]
Didn't expect you to be that quick. 😉 Can confirm it works on v6.1.4, thanks a lot.
