### ISSUE TITLE
GeolocateControl user marker is in wrong location if nested in parent div with position absolute

### ISSUE THREAD

**Issue by marc-slingshot** [visgl/react-map-gl#1334]
If you use the GeolocateControl (which defaults to have the user marker shown), but you nest it inside of a div (say for positioning/grouping/styling) and that div has a style of position absolute then the marker is not drawn on the map correctly.  It looks like marker is expected to be a child of the mapbox overlays container and not a child of this new absolute position div.

```jsx
import "mapbox-gl/dist/mapbox-gl.css";
import "react-map-gl-geocoder/dist/mapbox-gl-geocoder.css";
import React, { useState, useCallback } from "react";
import { render } from "react-dom";
import MapGL, { GeolocateControl } from "react-map-gl";

const MAPBOX_TOKEN = "<ADD TOKEN HERE>";

const App = () => {
  const [viewport, setViewport] = useState({
    latitude: 37.7577,
    longitude: -122.4376,
    zoom: 8
  });
  const handleViewportChange = useCallback(
    (newViewport) => setViewport(newViewport),
    []
  );

  return (
    <div style={{ height: "100vh" }}>
      <MapGL
        {...viewport}
        width="100%"
        height="100%"
        onViewportChange={handleViewportChange}
        mapboxApiAccessToken={MAPBOX_TOKEN}
        mapStyle={"mapbox://styles/mapbox/dark-v10"}
      >
        <div
          style={
            {
              position: "absolute",
              left: 0,
              bottom: 0
            }
          }
        >
          <GeolocateControl
            style={{
              position: "absolute",
              left: 0,
              bottom: 48,
              margin: 10,
              marginBotton: 36,
              marginLeft: 8
            }}
          />
        </div>
      </MapGL>
    </div>
  );
};

render(<App />, document.getElementById("root"));
```

Why does the marker get added as a child of the new div and not the overlays container?  Also why are these controls in the overlays section of mapbox elements and not in the controls containers (.mapboxgl-control-container)?

**Comment by Pessimistress** [comment]
What version are you using? This should have been fixed in v5.3/v6.1.

**Comment by marc-slingshot** [comment]
This was on 6.0.3

**Comment by Pessimistress** [comment]
Closing - issue can be fixed by upgrading to the latest release.

**Comment by marc-slingshot** [comment]
hrm... looks like upgrading to 6.1 won't be an easy transition for us.  Are there any release notes or major changes?  We have some custom controls based on the BaseControl class

Also are there any generated typescript types for 6.1? @types/react-map-gl looks like it's v5

**Comment by Pessimistress** [comment]
https://visgl.github.io/react-map-gl/docs/whats-new

`BaseControl` is kept for backward compatibility.
