### ISSUE TITLE
problem in Source component

### ISSUE THREAD

**Issue by undaBen** [visgl/react-map-gl#1340]
Hello all

When I upgrade to react-map-g 5.3.0 I get this error ....

<img width="1343" alt="Screenshot 2021-02-08 at 16 46 13" src="https://user-images.githubusercontent.com/78349285/107243321-2e6e8680-6a2d-11eb-9b0f-71c18bcf0a1c.png">

it points to my component MapBoxSourceLayer  line 11
this is that component

<img width="988" alt="Screenshot 2021-02-08 at 16 51 39" src="https://user-images.githubusercontent.com/78349285/107244121-f7e53b80-6a2d-11eb-8108-4255c505347d.png">

so it looks to me like something is broken in the react-map-gl Source in  5.3.0 
as nothing gets returned

When i downgrade to 5.2.12 everything works

**Comment by Pessimistress** [comment]
Looks like `<Source>` has an issue when it contains no children. If you move your `Layer` component inside `Source` it should work.

**Comment by Pessimistress** [comment]
Fix is landed in 5.3.6/6.1.6

**Comment by undaBen** [comment]
thanks, when i move it in as a child it does work
