### ISSUE TITLE
Running React-Map-GL in a sandbox iframe.

### ISSUE THREAD

**Issue by JG145** [visgl/react-map-gl#1342]
I am trying to run the below code with a sandboxed Iframe

https://github.com/visgl/deck.gl/tree/8.4-release/examples/website/scatterplot

Whilst the map and Layer render initially any interaction with the map results it to go blank. It also shows an error

"Not allowed to load local resource: blob:null/48adfa4c-2e1a-4ce1-87a5-120cb3fcd8cc"

Any Ideas? Just rendering the Deck Layer works fine and overlaying this into a Mapbox-gl map also works.

**Comment by Pessimistress** [comment]
I cannot reproduce this issue. I remember Mapbox fixing an iframe bug a very long time ago. Can you check the mapbox-gl version that is installed?
