### ISSUE TITLE
How can i add Mapbox wordmark attribution?

### ISSUE THREAD

**Issue by oahmaro** [visgl/react-map-gl#1346]
The Mapbox documentation mentions that wordmark and text attributions are both required, and i can't find how to add wordmark on the documentation, i am using the AttributionControl component and it only show text attribution.

https://docs.mapbox.com/help/how-mapbox-works/attribution/

**Comment by Pessimistress** [comment]
Wordmark is automatically displayed by Mapbox. You cannot turn it on or off from the API. If you are using mapbox-gl v1 (react-map-gl@5.x) then it is not shown if you are not using Mapbox tilesets.

**Comment by oahmaro** [comment]
sorry my, i had my map bottom hidden accidentally by UI, i thought it is something related with the new AttributionControl component
