### ISSUE TITLE
Custom control component in 6.x

### ISSUE THREAD

**Issue by Narcasung** [visgl/react-map-gl#1351]
I had a component in 5.x like this:

```
export default class CustomControl extends BaseControl<ICustomControlProps, HTMLDivElement> {
  static defaultProps = {
    captureScroll: true,
    captureDrag: true,
    captureClick: true,
    captureDoubleClick: true,
  }

  _render() {
    return (
      <div ref={this._containerRef} className={`mapboxgl-ctrl-custom ${this.props.className ? this.props.className : ""}`}>
        {this.props.children}
      </div>
    )
  }
}
```

Its only purpose is to be a control component with all capture props set to true, it worked fine.
I tried to upgrade to 6.x, and `BaseControl` seems to have many changes, luckily the above component still works in a dev environment.
However, it now has many typescript errors and since we're using nextjs, it prevents builds.
The main one is

![image](https://user-images.githubusercontent.com/6689651/107850445-c93adc80-6e02-11eb-83fc-eaaff8bccdde.png)

when I call the above component.
It also doesn't recognize `this.props` and `this._containerRef` in the component itself

![image](https://user-images.githubusercontent.com/6689651/107850462-f6878a80-6e02-11eb-8519-392927c5c411.png)

So I checked the documentation and `BaseControl` seems to be a legacy component, the doc advises to use `useMapControl` hook instead. I checked the existing `NavigationControl` and `FullscreenControl` components and they use this approach too.
Except react-map-gl typedefs don't export `useMapControl`, if I try to cheat my way in by importing `from 'react-map-gl/src/components/use-map-control'` directly, it throws the following webpack error:

![image](https://user-images.githubusercontent.com/6689651/107850750-0d2ee100-6e05-11eb-9b23-a02d711577d2.png)

So, my goal with this component is to have a container to make overlay elements that don't interact with the map below. What is the best approach to achieve this?

**Comment by Pessimistress** [comment]
It is exported as an experimental API, see https://visgl.github.io/react-map-gl/docs/advanced/custom-components#using-the-usemapcontrol-hook

**Comment by Narcasung** [comment]
How should I go about it then?

**Comment by Pessimistress** [comment]
There is a code example in the link above.

**Comment by chriszrc** [comment]
@Pessimistress Are you sure the docs are up to date? What I see here:

https://visgl.github.io/react-map-gl/docs/advanced/custom-components#using-the-usemapcontrol-hook

Doesn't seem to match at all what the new `useMapControl` hook is expecting, and it doesn't match how it's being used in the library itself:

https://github.com/visgl/react-map-gl/blob/db08714945b106062a9e8b87722a8c0e343eb3de/src/components/scale-control.js#L39

**Comment by Pessimistress** [comment]
@chriszrc yes it is up to date. If you need help understanding it please open a new Discussion thread.

**Comment by chriszrc** [comment]
I've opened a new thread here. The code works, but only if you ignore all the type errors- https://github.com/visgl/react-map-gl/issues/1492
