### ISSUE TITLE
Support for mobile zoom gesture double tap + hold + move up/down

### ISSUE THREAD

**Issue by Antje3** [visgl/react-map-gl#1353]
I am looking for a way to support the mobile zoom gesture where you double tap on the map, hold, and move up or down to zoom. Mapbox GL itself supports this ([`touchZoomRotate` in the Map Parameter Options](https://docs.mapbox.com/mapbox-gl-js/api/map/#map-parameters)).

I tried setting the value for the InteractiveMap via the mapOptions, but this did not work: `mapOptions={{ touchZoomRotate: true }}`.
As far as I could find, you implement all zooming yourselves, so setting it via the mapOptions probably gets overwritten?

I also saw a [deprecation warning for `touchZoomRotate`](https://github.com/visgl/react-map-gl/blob/7cd359ea146548749bffa5c339f05b05f303ac96/src/utils/deprecate-warn.js#L7), but the suggested `touchZoom` and `touchRotate` do not provide the required zoom gesture.

Am I overlooking something, and if not, do you plan to support this feature in the future? Thanks!

**Comment by Pessimistress** [comment]
This is being addressed in v7.0. Please follow #1646
