### ISSUE TITLE
Source ref is always null

### ISSUE THREAD

**Issue by StijnAmeloot** [visgl/react-map-gl#1354]
Hi, I'm trying to get the clustering example to work in my web app, but I'm having an issue when clicking on one of the clusters.

I created a functional component which which renders a Deck.gl component which contains the ReactMapGL component. Within this ReactMapGL component I added the Source component with the example layers. 
Everything is rendered correctly and works fine when opening the map.

The issue I'm facing is when clicking one of the clusters, I get the following exception:

> Uncaught TypeError: Cannot read property 'getSource' of null
>     at onClickCanvasHandler (Map.js:385)

That's on this line: 
`const mapboxSource = sourceRef.current.getSource();`

When I try to log this sourceRef variable, I also get 'null'. I have no idea why this ref stays null at the time. I'm already using other refs in the same file (e.g. a ref to the map component), which works fine.

Below you can find the code (the actual file contains much more code, but most of it is not related to the clustering example). 
It might be a stupid mistake or something that I'm not aware of. Any help would be appreciated.

```
const deckRef = useRef(null);
const mapRef = useRef(null);
const sourceRef = useRef(null);
```

```
const onClickCanvasHandler = (event) => {
    const features = mapRef.current.getMap().queryRenderedFeatures([event.x, event.y], {
      layers: ["clusters"]
    });
    if (features && features.length > 0) {
      const feature = features[0];
      const clusterId = feature.properties.cluster_id;

      const mapboxSource = sourceRef.current.getSource(); // sourceRef is always null here...

      mapboxSource.getClusterExpansionZoom(clusterId, (err, zoom) => {
        if (err) {
          return;
        }

        setLocalViewState({
          ...this.state.viewport,
          longitude: feature.geometry.coordinates[0],
          latitude: feature.geometry.coordinates[1],
          zoom,
          transitionDuration: 500
        });
      });
    }
  }
```

```
return (
    <>
      <div onClick={onClick}>
        <DeckGL
          ref={deckRef}
          width={canvasWidth}
          height={canvasHeight}
          initialViewState={localViewState}
          controller={interactable ? { dragRotate: false } : false }
          layers={[geofencesLayer, placesLayer]}
          onClick={(event) => onClickCanvasHandler(event)}
          onHover={(event) => onHoverCanvasHandler(event)}
          onViewStateChange={(event) => onViewStateChangeHandler(event)}
          getCursor={({isDragging}) => {
            if (!interactable) { return 'default'; }
            if (mapMode.mode === MODES.SELECTINGLOCATION) { return 'crosshair'; }
            return isDragging ? 'grabbing' : (hoveredPlace.placeId ? 'pointer' : 'grab')
          }}
          ContextProvider={MapContext.Provider}
        >
          <ReactMapGL
            ref={mapRef}
            mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN} 
            mapStyle={mapStyle.url}
            interactiveLayerIds={[clusterLayer.id]}
          >
            <Source
              ref={sourceRef}
              type="geojson"
              data="https://docs.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson"
              cluster={true}
              clusterMaxZoom={14}
              clusterRadius={50}
            >
              <Layer {...clusterLayer} />
              <Layer {...clusterCountLayer} />
              <Layer {...unclusteredPointLayer} />
            </Source>
          </ReactMapGL>
        </DeckGL>
      </div>
    </>
  );
```

**Comment by Pessimistress** [comment]
`getSource` is not documented API. Depending on which version you are using, see /examples/cluster on the `x.x-release` branch.

**Comment by StijnAmeloot** [comment]
Thank you for your response. 
I'm currently experimenting with the icon layer from deck.gl which also has the ability to cluster items together. 
This seems to be a better alternative because I'm already using other deck.gl layers too.
