### ISSUE TITLE
How to set max and min zoom.

### ISSUE THREAD

**Issue by achaloza** [visgl/react-map-gl#1357]
Hello Everyone,

I want to apply max and min zoom apply for map.
I have try some code but it's not working. I have attached my code snap. 
Please give me some solution ASAP. 

![image](https://user-images.githubusercontent.com/15319181/108022088-e6abb880-7045-11eb-8699-946a19ab82c9.png)

**Comment by Pessimistress** [comment]
[minZoom, maxZoom](https://visgl.github.io/react-map-gl/docs/api-reference/interactive-map#interaction-options) props

If you need help debugging, please create a CodeSandbox.
