### ISSUE TITLE
MapContext and _useMapControl exports not present in index.d.ts

### ISSUE THREAD

**Issue by donocode** [visgl/react-map-gl#1359]
The Typescript types do not include the exports MapContext or useMapControl, though they are exported by `index.js`, this means they are not easily usable in a Typescript project and will likely cause confusion for anyone following the docs while using Typescript.

I'm talking specifically of v5.3.4 https://github.com/visgl/react-map-gl/blob/v5.3.4/src/index.d.ts as that's the latest I have access to, but the exports appear to be missing from every currently released version.

**Comment by Pessimistress** [comment]
Thanks for reporting. Would you open a PR to fix this?

**Comment by cbisbee** [comment]
This is indeed a bit confusing when using TS and following the docs, glad I found this!

**Comment by Pessimistress** [comment]
Fixed in 6.1.9/5.3.9
