### ISSUE TITLE
Issue setting mix and max zoom with the <NavigationControl />

### ISSUE THREAD

**Issue by singhamritpal49** [visgl/react-map-gl#1360]
Hello There,

I am working with ReactMapGL and NavigationControl. I am able to set max & min zoom using the ReactMapGL component
< ReactMapGL /> but I am having trouble setting the max & min zoom NavigationControl <NavigationControl />.

I was looking at the Navigation Control documentation https://visgl.github.io/react-map-gl/docs/api-reference/navigation-control, it does not have any properties for minZoom/maxZoom.  Only the ReactMapGL has those properties. 
Is there any way I can get that functionally working for <NavigationControl />?

Thanks

**Comment by Pessimistress** [comment]
Do you want to use different minZoom/maxZoom settings from the InteractiveMap component? The following should already work:

```jsx
<MapGL {...viewport} minZoom={2} maxZoom={10} onViewportChange={setViewport}>
  <NavigationControl />
</MapGL>
```

**Comment by singhamritpal49** [comment]
Got it working 
thanks for the help
