### ISSUE TITLE
Typescript bindings question

### ISSUE THREAD

**Issue by Jamie5** [visgl/react-map-gl#1364]
For `MapEvent`, is it possible for `point: Array<number>,` to instead be e.g. `point: [x: number, y: number]` and similarly for `lngLat` to be `[longitude: Lng, latitude: Lat]` since we know they both just have two elements, or are there reasons against this?

EDIT: Also, should `MjolnirEvent` also have `leftButton` and `middleButton`?

**Comment by Pessimistress** [comment]
> are there reasons against this?

No. Would you open a PR to update the typings?

**Comment by Jamie5** [comment]
Do I just do it against master and then that will suffice for both 6.x and 5.x? (we still need 5.x)

**Comment by Pessimistress** [comment]
Yes, this should apply to both 6.x and 5.x.

**Comment by Jamie5** [comment]
Created #1369. It does a bit more than mentioned above, though I believe the additional changes are correct.

**Comment by VictorVelarde** [comment]
This has been included in the latest patches (6.1.10 and 5.3.10). Thx for the contribution!
