### ISSUE TITLE
Transition Interpolator crashes on initialization if controlled map is configured with transitionDuration

### ISSUE THREAD

**Issue by RyanRutkin** [visgl/react-map-gl#1366]
If ReactMapGL is initialized with `transitionDuration`, the default `TransitionInterpolator` (`LinearInterpolator`) crashes, providing the error:

```longitude must be supplied for transition```

To reproduce, provide a value for `transitionDuration`:

```
import * as React from 'react';
import ReactMapGL from 'react-map-gl';

function Map {
  const [viewport, setViewport] = React.useState({
    latitude: 37.7577,
    longitude: -122.4376,
    zoom: 8
  });

  return (
    <ReactMapGL
      {...viewport}
      transitionDuration="auto"
      width="100%"
      height="100%"
      onViewportChange={(viewport) => setViewport(viewport)}
    />
  );
}
```

`MapController` initializes `TransitionManager` in it's [constructor](https://github.com/visgl/react-map-gl/blob/master/src/utils/map-controller.js#L70), providing `onViewportChange` and `onStateChange` as `props`.

```
this._transitionManager = new TransitionManager({
    onViewportChange: this._onTransition,
    onStateChange: this._setInteractionState
});
```

When `viewport` is updated, `TransitionManager._shouldIgnoreViewportChange` is [invoked](https://github.com/visgl/react-map-gl/blob/master/src/utils/transition-manager.js#L59), comparing it's change in `props`. 

The initial props are equal to:
```
{
    onViewportChange: MapController._onTransition
    onStateChange: MapController._setInteractionState
}
```

...and the new props are equal to the newly updated `viewport` state (a valid props object for the `LinearInterpolator`).

As `transitionDuration` is provided, the [call](https://github.com/visgl/react-map-gl/blob/master/src/utils/transition-manager.js#L131) to `this._isTransitionEnabled(nextProps)` within `TransitionManager._shouldIgnoreViewportChange` returns true, causing `TransitionManager._triggerTransition` to be [invoked](https://github.com/visgl/react-map-gl/blob/master/src/utils/transition-manager.js#L86), which then [calls](https://github.com/visgl/react-map-gl/blob/master/src/utils/transition-manager.js#L156) `initializeProps` on the default transition interpolator: `LinearInterpolator`.

The value provided as `startProps` to `LinearInterpolator.initializeProps` is:

```
{
    onViewportChange: MapController._onTransition
    onStateChange: MapController._setInteractionState
}
```

As this object is clearly not a valid set of props for the `LinearInterpolator` and does not provide `longitude`, the first checked required property, `assert` is [tripped](https://github.com/visgl/react-map-gl/blob/master/src/utils/transition/linear-interpolator.js#L53) with the message: `longitude must be supplied for transition`.

I believe the true culprit is `MapController` initializing the `TransitionManager` with invalid props.

Versions:
Node: `v14.15.4`
ReactMapGL: `v6.1.9`
React: `v16.13.1`

**Comment by Pessimistress** [comment]
It crashes because there is no viewport to transition **from**. There is no reason for you to set `transitionDuration: 'auto'` at all times:

- It is only supported by `FlyToInterpolator`, which is not the default
- It will mess with transitions that are invoked by the controller (double click zoom, keyboard navigation, inertia) and NavigationControl
- You only need to set `transitionDuration` once when you want to manually trigger a viewport change, see http://visgl.github.io/react-map-gl/docs/advanced/viewport-transition#transition-and-the-onviewportchange-callback

**Comment by RyanRutkin** [comment]
> * http://visgl.github.io/react-map-gl/docs/advanced/viewport-transition#transition-and-the-onviewportchange-callback

The example I provided was only an easy way to recreate the error that I encountered. What actually occurred is that I cached the viewport value previously set from `onViewportChange` (which retains an explicit `transitionDuration: 'auto'`) then rendered the map. In my actual use case, I never set `transitionDuration`, but I found it present on the cached `viewport` value.

I think the issue is due to keeping `viewport` in a separate state, yet not maintaining a map reference. When the map is re-rendered and provided an old reference of the viewport (this is what actually caused my error), it causes a crash.

A couple questions:

- If I only need to set the "...transitionDuration once when [I] want to manually trigger a viewport change...," why is the transitionDuration value retained on the `viewport`?

- If the value is only supported by the `FlyToInterpolator`, why does the `TransitionManager` reference the existence of the value when initializing any Transition Interpolator?

I've seen this error reported and closed multiple times as it couldn't be easily reproduced. The example I provided was just a simple and easy way to reproduce it.

**Comment by hagiosofori** [comment]
I'm seeing a similar issue. except I'm using the `FlyToInterpolator`, and my error message is complaining about `latitude` instead of `longitude`

**Comment by RyanRutkin** [comment]
@Pessimistress this implementation causes the error the same way I encountered it, and does not provide `transitionDuration`.
```
import * as React from 'react';
import ReactMapGL from 'react-map-gl';

const Map = () => {
    const { viewport, setViewport } = React.useContext(ViewportContext);
    const [showMap, setShowMap] = React.useState(true);

    return (<>
        <ReactMapGL
            {...viewport}
            mapboxApiAccessToken="YOUR_MAPBOX_TOKEN"
            transitionDuration="auto"
            width="100%"
            height="100%"
            onViewportChange={(viewport) => setViewport(viewport)}
        />
        <button style={{ position: 'absolute', top: '0', left: '0' }} onClick={() => setShowMap(!showMap)} >Toggle Map</button>
    </>);
}

const App = () => (
  <div style={{ position: 'absolute', top: '0', right: '0', bottom: '0', left: '0', width: '100%', height: '100%' }} >
    <ViewportContextProvider>
        <Map />
    </ViewportContextProvider>
  </div>
)

const ViewportContext = React.createContext();

const ViewportContextProvider = (props) => {
    const [viewport, setViewport] = React.useState({
        latitude: 37.7577,
        longitude: -122.4376,
        zoom: 8
    });

    return <ViewportContext.Provider value={{viewport, setViewport}} >
        { props.children }
    </ViewportContext.Provider>
}

export default App;
```

**Comment by Pessimistress** [comment]
@RyanRutkin Thank you for the clarification. It is kept in `viewport` because the Map component is stateless. If you happened to have the viewport cached during a transition then it's possible that transition props are present.

The issue you referenced was a different bug.

I will look into blocking transition at initial mount.

**Comment by RyanRutkin** [comment]
Thanks @Pessimistress .

This code reproduces the error, in a way.

@hagiosofori is right, the error is inconsitent.
My colleague kept stating that the error was `@math.gl/web-mercator: assertion failed`, while I continually saw `longitude must be supplied for transition`.

The only error I can achieve from this basic example is `@math.gl/web-mercator: assertion failed`.

To cause the error, click the "Fly to New York" button, then click the "Toggle Map" button twice.

```
import * as React from 'react';
import ReactMapGL, { FlyToInterpolator } from 'react-map-gl';

const Map = () => {
  const { viewport, setViewport } = React.useContext(ViewportContext);
  const { showMap, setShowMap } = React.useContext(ShowMapContext);

  return (<>
    { showMap
      ? <ReactMapGL
          {...viewport}
          mapboxApiAccessToken="YOUR_MAPBOX_TOKEN"
          width="100%"
          height="100%"
          onViewportChange={(viewport) => setViewport(viewport)}
        />
      : null
    }
    <button style={{ position: 'absolute', top: '0', left: '0', zIndex: 1 }} onClick={() => {
      setViewport({
        latitude: 40.713,
        longitude: -74.006,
        zoom: 8,
        transitionDuration: 'auto',
        transitionInterpolator: new FlyToInterpolator()
      })
    }} >Fly To New York</button>
    <button style={{ position: 'absolute', top: '4rem', left: '0', zIndex: 1 }} onClick={() => setShowMap(!showMap)} >Toggle Map</button>
  </>);
}

const App = () => (
  <div style={{ position: 'absolute', top: '0', right: '0', bottom: '0', left: '0', width: '100%', height: '100%' }} >
    <ViewportContextProvider>
      <ShowMapContextProvider>
        <Map />
      </ShowMapContextProvider>
    </ViewportContextProvider>
  </div>
)

const ViewportContext = React.createContext();

const ViewportContextProvider = (props) => {
  const [viewport, setViewport] = React.useState({
    latitude: 37.7577,
    longitude: -122.4376,
    zoom: 8
  });

  return <ViewportContext.Provider value={{viewport, setViewport}} >
    { props.children }
  </ViewportContext.Provider>
}

const ShowMapContext = React.createContext();

const ShowMapContextProvider = (props) => {
  const [showMap, setShowMap] = React.useState(true);

  return <ShowMapContext.Provider value={{showMap, setShowMap}} >
    { props.children }
  </ShowMapContext.Provider>
}

export default App;
```

**Comment by VictorVelarde** [comment]
Hi @RyanRutkin 
It would be nice if you could please test this again with the latest patch (6.1.10 or 5.3.10).

**Comment by fungjj92** [comment]
I am running into this same error today, and v5.3.10 fixed the issue!

**Comment by nonoumasy** [comment]
I'm getting an error when I click on the same marker with FlyToInterpolator. I'm not sure if its related to this issue.
```
const Story = () => {

const [viewport, setViewport] = useState({
        latitude: 0,
        longitude: 0,
        zoom: 5,
        bearing: 0,
        pitch: 0,
        width: "50vw",
        height: "100vh"
    })


const flyTo = async ({ data, id }) => {
        try {
            let longitude;
            let latitude;
            const item = await data?.find(item => item.id === id)
            longitude = item?.coordinates?.longitude
            latitude = item?.coordinates?.latitude

            setViewport({
            longitude, 
            latitude,
            zoom: 11,
            pitch: 60,
            transitionInterpolator: new FlyToInterpolator({ speed: 1.5 }),
            transitionDuration: 'auto'
            });
        } catch (err) {
            console.log(err)
        }
    }
    }

const StoryMap = ({ flyTo, viewport, setViewport}) => {

return (
        <>
            <ReactMapGL
                {...viewport}
                mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
                mapStyle={mapboxStyle}
                onViewportChange={viewport => setViewport(viewport)}
                attributionControl={false}
                >
                <StoryMapMarkers />}
            </ReactMapGL>
        </>
    )

**Comment by nonoumasy** [comment]
I'm getting an error when I click on the same marker with FlyToInterpolator. I'm not sure if its related to this issue.

const Story = () => {

const [viewport, setViewport] = useState({
        latitude: 0,
        longitude: 0,
        zoom: 5,
        bearing: 0,
        pitch: 0,
        width: "50vw",
        height: "100vh"
    })


const flyTo = async ({ data, id }) => {
        try {
            let longitude;
            let latitude;
            const item = await data?.find(item => item.id === id)
            longitude = item?.coordinates?.longitude
            latitude = item?.coordinates?.latitude

            setViewport({
            longitude, 
            latitude,
            zoom: 11,
            pitch: 60,
            transitionInterpolator: new FlyToInterpolator({ speed: 1.5 }),
            transitionDuration: 'auto'
            });
        } catch (err) {
            console.log(err)
        }
    }
    }

const StoryMap = ({ flyTo, viewport, setViewport}) => {

return (
        <>
            <ReactMapGL
                {...viewport}
                mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
                mapStyle={mapboxStyle}
                onViewportChange={viewport => setViewport(viewport)}
                attributionControl={false}
                >
                <StoryMapMarkers />}
            </ReactMapGL>
        </>
    )
    
    ```
    
    The issue I'm getting is the map just blanks out(literaly). I just see a white screen.
![Screen Shot 2021-03-17 at 12 00 12 AM (2)](https://user-images.githubusercontent.com/6312676/111427872-fb668500-86b3-11eb-9741-b2f002c1d141.png)

**Comment by tonnoz** [comment]
I got the issue fixed as well with this patch! Thank you! :tada:

**Comment by Huvinesh-Rajendran-12** [comment]
I am having a similar issue but not with transitionDuration. The error only happens during trackpad navigation where if I swipe on the trackpad with two fingers, the map doesn't display and I am shown this particular error. 
![image](https://user-images.githubusercontent.com/81321926/169482010-5f7395fc-bddc-4db5-8f48-c9dbae5eebd4.png)
