### ISSUE TITLE
React map gl only displays markers

### ISSUE THREAD

**Issue by NBNARADHYA** [visgl/react-map-gl#1368]
### Context
I used `react-map-gl` to  display a map, and show markers on it. 
In local development it works perfectly fine
![localMapbox](https://user-images.githubusercontent.com/45630095/108975813-e4340900-76ac-11eb-9db6-3027e297b18a.png)

### The issue
But when the site was deployed on `netlify`, it doesn't seem to work. It doesn't display the map (only the background and makers are displayed). This is how it looks on production site hosted on `netlify`.
![netlifyMapbox](https://user-images.githubusercontent.com/45630095/108975982-13e31100-76ad-11eb-97a5-161c4cf214aa.png)

### Versions
```
"react": "^17.0.1",
"react-dom": "^17.0.1",
"react-map-gl": "^6.0.3"
```

**Comment by VictorVelarde** [comment]
Hi @NBNARADHYA, how are you dealing with mapbox access token? It looks like you might be missing your configuration in your netlify site

**Comment by NBNARADHYA** [comment]
@VictorVelarde  I have been using the same default public access token both on local development and `netlify`

**Comment by titou26140** [comment]
Up ! Same problem when building.

**Comment by VictorVelarde** [comment]
If you don't get a visual warning from Mapbox, then the token is probably fine.

You might be having the same issue as #1300.

**Comment by NBNARADHYA** [comment]
> If you don't get a visual warning from Mapbox, then the token is probably fine.
> 
> You might be having the same issue as #1300.
> For confirmation, have a look at your console and see if you find an error like `Uncaught ReferenceError: y is not defined [...]`

Thanks @VictorVelarde ! I get an error which goes like this: `ReferenceError: g is not defined`.
I will check out for a solution on issue #1266

**Comment by VictorVelarde** [comment]
Great!, please confirm that it fixes your issue, so this one can be closed

**Comment by NBNARADHYA** [comment]
Downgrading to v5.2.11 of `react-map-gl` was insufficient for my use case since I'm using Mapbox GL JS v2.x.x features (`setTerrain()` specifically)

For those out there in a similar spot, I was able to hack around things for the time being by adapting the suggestions in mapbox/mapbox-gl-js#10173:

Install `worker-loader`:

```
yarn add worker-loader
```
In your map component:
```
import ReactMapGL from "react-map-gl";
import mapboxgl from "mapbox-gl"; // This is a dependency of react-map-gl even if you didn't explicitly install it

// eslint-disable-next-line import/no-webpack-loader-syntax
mapboxgl.workerClass = require("worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker").default;
```

I hope the Mapbox team can provide a long term solution soon.

_Originally posted by @zanemountcastle in https://github.com/visgl/react-map-gl/issues/1266#issuecomment-753686953_

**Comment by NBNARADHYA** [comment]
The above solution fixes this issue for now !
