### ISSUE TITLE
Map not shown with CRA

### ISSUE THREAD

**Issue by DavideVito** [visgl/react-map-gl#1383]
#### Description

The map is not shown in the UI using Create React App

#### Repro Steps

Create a react app using the CRA tool, then use an example provided, the map will not render.

[Here is the code sandbox](https://codesandbox.io/s/keen-star-iv0jf?file=/src/App.js)

#### Environment (please complete the following information):

- Library Version: `react-map-gl` 6.1.10
- Mapbox Version: 2.1.1
- React Version: React 17.0.1
- Browser Version: Safari 14.0.3
- OS: Mac OS X 11.2

#### Logs

No errors or warning are shown in the console

**Comment by Pessimistress** [comment]
Your root div's height is 0. Add `import './styles.css';` to your index.js and you will see the map.

**Comment by DavideVito** [comment]
> Your root div's height is 0. Add `import './styles.css';` to your index.js and you will see the map.

I’m, such, an, idiot
