### ISSUE TITLE
Explore, zoom with finger on iOS is very sluggish

### ISSUE THREAD

**Issue by nicolaswurtz** [visgl/react-map-gl#1384]
#### Description

Exploring map with finger on iOS devices is very sluggish, especially on zoom/dezoom **with fingers** even in minimal installation.
When using control +/- or double tap, zoom is fluid.

Disabling inertia doesn't change anything.

#### Repro Steps

- create react app
- add react-map-gl

Code of App.js : 

```js
import * as React from 'react';
import { useState } from 'react';
import ReactMapGL from 'react-map-gl';
import 'mapbox-gl/dist/mapbox-gl.css';

function App() {
  const [viewport, setViewport] = useState({
    width: 400,
    height: 400,
    latitude: 48,
    longitude: 7,
    zoom: 8
  });

  return (
    <ReactMapGL
      {...viewport}
      height="100vh"
      width="100vw"
      mapStyle="mapbox://styles/mapbox/streets-v11"
      mapboxApiAccessToken="this is a secret"
      onViewportChange={nextViewport => setViewport(nextViewport)}
    />
  );
}

export default App;
```

#### Environment (please complete the following information):

- react-map-gl 6.1.10
- mapbox-gl 2.1.1
- React Version: 17.0.1
- Browser Version: Safari/Firefox/etc. same version of webkit is shared on iOS
- OS: iOS 14.4

**Comment by Pessimistress** [comment]
Do you experience this with the [website demos](https://visgl.github.io/react-map-gl/examples)? What device do you use?

**Comment by nicolaswurtz** [comment]
The website demos are smoother, on iPhone my example seems to be fine.
The sluggish behaviour appears on iPad.
Performances are bad too on Firefox for Android.

**Comment by Pessimistress** [comment]
Can you try setting `asyncRender={true}` on your map and see if it makes a difference?

**Comment by nicolaswurtz** [comment]
Thank you ! with `asyncRender={true}` it's a way much better : 
- moving is definitely smoother
- rotate is quite smoother
- panning (with 3 fingers) rest sluggish

**Comment by Pessimistress** [comment]
Related: #909

Thank you for helping with the test. The issue, I suspect, is that touch events fire more frequently on these devices. The way it currently works is that each touch event sets off a React state update which leads to a map rerender. We may need to denounce `onViewportChange` calls.

@VictorVelarde

**Comment by nicolaswurtz** [comment]
Thank you for your quick and efficient answers.
Indeed, putting some kind of limit to the number of tactile interactions - like we limit fps in 3D - would surely be a solution!
Thanks again.

**Comment by nicolaswurtz** [comment]
BTW you can see my implementation on https://carto.graou.info (french railroad's opendata) it's really better on iPad ! Thanks again.
