### ISSUE TITLE
Error on production build

### ISSUE THREAD

**Issue by DavideVito** [visgl/react-map-gl#1385]
#### Description

In development mode the map is shown perfectly, but after it is compiled `yarn build` it stops for some reason.

#### Repro Steps

- A Codesandblox [example](https://codesandbox.io/s/intelligent-perlman-8f8o5)

#### Environment (please complete the following information):

- Library Version: react-map-gl 6.1.10
- Mapbox Version: 2.1.1
- React Version: React 17.0.1
- Browser Version: Safari 14.0.3
- OS: Mac OS X 11.2

**Comment by kylebarron** [comment]
https://github.com/visgl/react-map-gl/issues/1266

**Comment by DavideVito** [comment]
Hi @kylebarron, I've followed the guide on the issue page you've linked, but none of the solution works, how can I solve?

**Comment by kylebarron** [comment]
https://github.com/visgl/react-map-gl/issues/1266#issuecomment-750796545. This isn't really an issue on the `react-map-gl` side; you'll have to use one of the described workarounds.
