### ISSUE TITLE
Need Help Marker Text Overlapping Issue 

### ISSUE THREAD

**Issue by singhamritpal49** [visgl/react-map-gl#1387]
($ Marker {:key     index
                                :latitude   (:Latitude location-single)
                                :longitude  (:Longitude location-single)
                                :icon       location -icon
                                :iconAllowOverlap  true,   
                                :textAllowOverlap  false,
                                :textOptional true,
                                :offsetTop  -40
                                :offsetLeft -20}
                                :data-place-id (:locationId location-single)}
(d/span {:class "text-fs-12"} (:Name location))
                               (d/img {:src location-icon :style {:width "40px" :height "40px" :margin "0 auto" :textAllowOverlap  false :textOptional true }})

<img width="436" alt="Screen Shot 2021-03-03 at 2 08 08 PM" src="https://user-images.githubusercontent.com/48744353/109861023-db9f7d80-7c2c-11eb-803d-7faf74ba73e7.png">

![Screen Shot 2021-03-03 at 2 33 41 PM](https://user-images.githubusercontent.com/48744353/109861685-9465bc80-7c2d-11eb-8ae4-dd515dfdad63.png)

**Comment by Pessimistress** [comment]
Please, only use templates to open an issue. If you have a generic question, go to [discussions](https://github.com/visgl/react-map-gl/discussions).
