### ISSUE TITLE
Map disappears when using flyToInterpolator

### ISSUE THREAD

**Issue by nonoumasy** [visgl/react-map-gl#1402]
#### Description

I'm getting an issue when I click on the same marker twice with FlyToInterpolator. The map just disappears.
I'm not sure if its related to other issue #1366.
To fix the issue from the comments I read, I commented out this property: transitionDuration: 'auto'. However, the issue is there. Actually if remove this and I click on any marker to zoom to, the map disappears immediately. With it on, I have to click on the same marker to get the issue. So it works fine just as long as I don't click on the same marker twice.

```
const Story = () => {

const [viewport, setViewport] = useState({
latitude: 0,
longitude: 0,
zoom: 5,
bearing: 0,
pitch: 0,
width: "50vw",
height: "100vh"
})

const flyTo = async ({ data, id }) => {
try {
let longitude;
let latitude;
const item = await data?.find(item => item.id === id)
longitude = item?.coordinates?.longitude
latitude = item?.coordinates?.latitude

        setViewport({
        longitude, 
        latitude,
        zoom: 11,
        pitch: 60,
        transitionInterpolator: new FlyToInterpolator({ speed: 1.5 }),
        transitionDuration: 'auto'
        });
    } catch (err) {
        console.log(err)
    }
}
}
const StoryMap = ({ flyTo, viewport, setViewport}) => {

return (
<>
<ReactMapGL
{...viewport}
mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
mapStyle={mapboxStyle}
onViewportChange={viewport => setViewport(viewport)}
attributionControl={false}
>
}

</>
)

```

#### Repro Steps

You can see the issue here on the site:
https://historymaps.netlify.app/story/l3MPWH8rXlZWJcNJtJKl

#### Environment (please complete the following information):

- Library Version: [e.g. react-map-gl 6.1.10]
- Mapbox Version: "react-map-gl": "^5.3.10"
- React Version: "^17.0.1"
- Browser Version: Version 89.0.4389.82
- OS: 11.2.2

#### Logs
![111427872-fb668500-86b3-11eb-9741-b2f002c1d141](https://user-images.githubusercontent.com/6312676/111654141-b92d6880-87c5-11eb-97b4-f05ad953c763.png)

**Comment by Pessimistress** [comment]
The code you provided is not enough to reproduce the issue. We cannot debug from a built application. Please provide a codepen link.

You can see error logs from the JavaScript console. Again we cannot debug from a screenshot.

If you are unsure whether this is a bug in the library or a bug in your own implementation, please post it in Discussions instead.
