### ISSUE TITLE
Unclustered points appear twice in onClick event features

### ISSUE THREAD

**Issue by louloueugene** [visgl/react-map-gl#1410]
#### Description

Clicking on an unclustered point leads to seeing it twice in the _features_ array of the map onClick handler.

I was able to repro in the example folder:
![image](https://user-images.githubusercontent.com/41595555/111919060-3a466300-8a45-11eb-8884-c25ef5c24879.png)

I initially noticed the problem on my own website:
https://actionpacked.co/maps
I leverage the features array to contextually show information when clicking on elements of the map

#### Repro Steps

- Clone repo
- Cd to react-map-gl-master\examples\clusters
- Yarn install
- Remove _interactiveLayerIds_ to see all layers when clicking
![image](https://user-images.githubusercontent.com/41595555/111919127-872a3980-8a45-11eb-8e50-ba6faf7f214f.png)
- Add console.log(event)to the onClick handler 
![image](https://user-images.githubusercontent.com/41595555/111919230-19cad880-8a46-11eb-9764-36388c8fde14.png)
- Yarn start
- Click on un unclustered point on the map
- Overserve the point appearing twice in features array 

#### Environment (please complete the following information):

I was able to repro the problem by cloning the example folder as of 3/21/2021.

**Comment by Pessimistress** [comment]
`features` is populated by calling [Map.queryRenderedFeatures](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#queryrenderedfeatures). You may want to report this as a bug to the Mapbox GL JS repo.

**Comment by kunKun-tx** [comment]
Can confirm that I have same issue with `onClick` on a `Marker`


https://codesandbox.io/s/romantic-goldwasser-cju9y

**Comment by kunKun-tx** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/10297
