### ISSUE TITLE
Scroll to zoom is inconsistent in fullscreen

### ISSUE THREAD

**Issue by brandonwestcott** [visgl/react-map-gl#1412]
#### Description

When entering fullscreen via the `FullscreenControl`, if the map's wrapping container is offset from 0,0 at all, then scroll / trackpad to zoom does not track the cursors current position. I've attempted to adjust the width / height settings and even force rerenders with `onResize`.

#### Repro Steps
Code:
https://codesandbox.io/s/mapbox-gl-fullscreen-bug-egx27

Example (codesandbox embedded frame does not have fullscreen capabilities):
https://egx27.csb.app/

Steps:
1) click fullscreen button
1) hover cursor over New York
1) zoom in with mouse wheel / trackpad
1) expect map to be zoomed into New York, but map is zoomed into Indiana

#### Environment (please complete the following information):

- Library Version: react-map-gl 6.1.10
- Mapbox Version: mapbox-gl 2.1.1
- React Version: react 17.0.2
- Browser Version: Chrome 88 / Firefox 87 / Safari 14 
- Mac OS X 10.15

#### Logs
None

**Comment by Pessimistress** [comment]
Thanks for reporting. This is fixed in 5.3.12/6.1.12
