### ISSUE TITLE
Map is not displayed on PRD build

### ISSUE THREAD

**Issue by agustinclarity** [visgl/react-map-gl#1421]
#### Description

When I run my app with `yarn start` using development bundle, the map is displayed perfectly on the screen. But after running `yarn build` and serving the static content, pins are placed on the map but the map is not displayed at all.

This is the app with dev bundle:
[Dev Image](https://www.dropbox.com/s/d9bhi4ga8472yvj/DEVBundle.png?dl=0)

This is tha app with prd bundle:
[Prd Image](https://www.dropbox.com/s/60jidr9z6yzd5dz/PRDBundle.png?dl=0)

#### Repro Steps

- Create a new React app using create-react-app.
- Add the altest version of react-map-gl with `yarn add react-map-gl`.
- Add a simple map from examples.
- Run the app with `yarn start` and dev bundle in place.
- Run `yarn build` and serve the static content from build folder with an http server like http-server.

#### Environment (please complete the following information):

- Library Version: 6.1.11
- Mapbox Version: 2.0.1 (based on what I took from node_modules for react-map-gl as dependencies)
- React Version: 17.0.2
- Browser Version: Chrome 89.0.4389.114
- OS: Mac OS X 11.2.3

#### Logs

Nothing wrong on the console guys. I was reading some other threads and I know you mentioned something that mapbox-gl from version 2.0 and higher is loading modules differently. With that in place, is there something you can do on your end to fix this issue? We would like to depend just on you as a wrapper to it and get all those issues solved if it is possible. Thanks in advance!

**Comment by Pessimistress** [comment]
> is there something you can do on your end to fix this issue?

This is extensively discussed in the Mapbox GL JS repo:
https://github.com/mapbox/mapbox-gl-js/issues/10173
Unfortunately this wrapper cannot just "fix" the decision made by the module that it's wrapping. Please follow the recommendations by the Mapbox team there.
