### ISSUE TITLE
popup window can not close by clicking the cross

### ISSUE THREAD

**Issue by qiaoxin136** [visgl/react-map-gl#1429]
#### Description

popup window can not close by clicking the cross

see this link, 

https://webpacktest.z13.web.core.windows.net/

if click on the point or line, the popup window can not close by clicking the cross, 

  "dependencies": {
    "deck.gl": "8.1.9",
    "react": "^16.3.0",
    "react-dom": "^16.3.0",
    "react-map-gl": "^6.1.11",
    "react-map-gl-geocoder": "2.1.3",
    "react-scripts": "3.4.1"
  }

popup code,

{popupInfo && (
          <Popup
            longitude={clickInfo.lnglat[0]}
            latitude={clickInfo.lnglat[1]}
            closeButton={true}
            closeOnClick={true}
          >
            {clickInfo.property.TYPE === 21 && (
              <div>
                <h5 style={{ color: "blue", fontWeight: "bold" }}>Manhole</h5>
                Facility ID: {clickInfo.property.FACILITYID}
                <br />
                Invert: {clickInfo.property.INVERTELEV}
                <br />
                RIM: {clickInfo.property.ELEVATION}
                <br />
              </div>
            )}
            {clickInfo.property.TYPE === 22 && (
              <div>
                <h5 style={{ color: "blue", fontWeight: "bold" }}>Pipe</h5>
                Facility ID: {clickInfo.property.FACILITYID}
                <br />
                Diameter: {clickInfo.property.DIAMETER}
                <br />
                Material: {clickInfo.property.MATERIAL}
                <br />
                Slope: {clickInfo.property.SLOPE}
                <br />
                Upstream Invert: {clickInfo.property.UPSTREAMIN}
                <br />
                Downstream Invert: {clickInfo.property.DOWNSTREAM}
                <br />
              </div>
            )}
          </Popup>
        )}

#### Environment (please complete the following information):

- Library Version: [e.g. react-map-gl 6.1.10]
- Mapbox Version: [e.g. mapbox-gl 2.1.1]
- React Version: [e.g. react 17.0.1]
- Browser Version: [e.g. Chrome 88.0]
- OS: [e.g. Mac OS X 11.2]

**Comment by Pessimistress** [comment]
Your issue cannot be reproduced from the code you share. Please create a CodeSandbox.

**Comment by qiaoxin136** [comment]
> Your issue cannot be reproduced from the code you share. Please create a CodeSandbox.

I will, thanks.

**Comment by qiaoxin136** [comment]
I made a mistake in my code. There is no bug. 

It is working now. please close this issue. Thanks for your time. 

https://webpacktest.z13.web.core.windows.net/
