### ISSUE TITLE
https://github.com/mapbox/mapbox-gl-language Control is not working with Map

### ISSUE THREAD

**Issue by hardik-satasiya** [visgl/react-map-gl#1437]
#### Description
I used ReactMapGL and I want to show map label's in the user's browser language
So I used this control as per the official Mapbox docu but seems it's not translating the label 
https://github.com/mapbox/mapbox-gl-language

#### Repro Steps
Steps to reproduce the behavior.
- A codesandbox example : [https://codesandbox.io/s/distracted-bash-jlln4?file=/src/App.js](https://codesandbox.io/s/distracted-bash-jlln4?file=/src/App.js) 

- in code sandbox labels suppose to be in the Japanese language, but it stays in English
- expected result ref link: https://mapbox.github.io/mapbox-gl-language/examples/ja.html

#### Environment 

- Library Version:  [react-map-gl: "6.1.12"]
- Mapbox Version: [mapbox-gl: "2.1.1"]
- React Version: [react: "17.0.2"]
- MapboxLanguage [@mapbox/mapbox-gl-language: "0.10.1"]
- Browser Version: [Chrome Version 89.0.4389.128 (Official Build) (64-bit)]
- OS: [Windows 10 Pro 64bit OS build 19042.928]

#### Logs
- not relevant

**Comment by Pessimistress** [comment]
I do not think this has anything to do with react-map-gl. The example you linked does not work in CodeSandbox either: https://codesandbox.io/s/great-bardeen-ygrvv

FWIW if you change the style to `mapbox://styles/mapbox/light-v9` the language does get set.

**Comment by chriszrc** [comment]
As of react-mapbox-gl v7, the plugin works exactly as advertised, get a mapref and load it:

```typescript
const mapRefCallback = useCallback((ref: MapRef | null) => {
    if (ref !== null) {
      //Set the actual ref we use elsewhere
      mapRef.current = ref;
      const map = ref;

      //Add language control that updates map text i18n based on browser preferences
      const language = new MapboxLanguage();
      map.addControl(language);

//...
 <Map
          {...mapSetting.viewState}
          ref={mapRefCallback}
 />
```
