### ISSUE TITLE
Hey I'm working with a 3rd party tiles and I had a question about this line of code in source.js

### ISSUE THREAD

**Issue by ClassicSours** [visgl/react-map-gl#1438]
https://github.com/visgl/react-map-gl/blob/6533f8dd1ec25f5031a2cc02447994c70e1fbf9d/src/components/source.js#L76

Why is && source.setUrl a part of this line?

where does source.setUrl come from, this isn't a dependency in the case that `changedKey === 'tiles'` should && source.setTiles be an additional dependency of this as well, or perhaps this check moved elsewhere?

**Comment by Pessimistress** [comment]
Please only use templates to open issues. Go to Discussions for Q&A.
