### ISSUE TITLE
Converting circular structure to JSON Error

### ISSUE THREAD

**Issue by mapsgeek** [visgl/react-map-gl#1440]
#### Description
Initializing map and navigation firing up error
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Map'
    |     property '_controls' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'dr'
    --- property '_map' closes the circle
    at JSON.stringify (<anonymous>)
```

#### Repro Steps

https://codesandbox.io/s/pensive-minsky-2vt6x
#### Environment (please complete the following information):

- Library Version :6.1.12
- Mapbox Version: [e.g. mapbox-gl 2.1.1]
- React Version: React 17.0.1
- NextJS:10.1.3
- Browser Version: 89.0.4389.128
- OS: Windows 10

**Comment by mapsgeek** [comment]
sorry, it's react-dev tools error generated, but specific with the react-map-gl component
but if you don't have the extension you don't get any error

**Comment by Pessimistress** [comment]
`Map` is from the mapbox-gl module. There is nothing we can do in this library to remove the error. Plus I don't think it's blocking anything if it's just from a dev extension.
