### ISSUE TITLE
An error occurred while parsing the WebWorker bundle

### ISSUE THREAD

**Issue by lleft17567** [visgl/react-map-gl#1451]
#### Description
I am a novice programmer, the following problem was running on create-react-app.
And happening when I  run `npm run build` in cra.
Go to the build folder, click `index.html`
![error-1](https://lleft17567.github.io/askImageHandler/erro1-1.png)
and the view on the web was
![error-4](https://lleft17567.github.io/askImageHandler/erro1-4.png)
the code is quite sample, copy  from [here](https://github.com/visgl/react-map-gl)
the token I remove first, it will appear in real execution.
![error1-3](https://lleft17567.github.io/askImageHandler/erro1-3.png)
I can be sure the condition is the same if I remove the MapTestWrapper tag
I guess it has nothing to do with styled-components.

By the way, if I run `npm run start` and watch on localhost:3000
the map is perfect without any errors.
The main problem is there's a difference when I run `npm run start` and `npm run build`

Does anyone have something idea about this issue? Thanks a lot, a lot.

#### Environment :
This is my package.json
![package](https://lleft17567.github.io/askImageHandler/erro1-2.png)

**Comment by Pessimistress** [comment]
#1266

**Comment by lleft17567** [comment]
Thanks your response, after I reference the post you give , I solve it.
Pretty appreciate your advice.
HarrisonLin

Xiaoji Chen ***@***.***> 於 2021年5月5日 週三 下午5:59寫道：
