### ISSUE TITLE
Map not growing as page width expands

### ISSUE THREAD

**Issue by achen187** [visgl/react-map-gl#1459]
#### Description

I'm setting the width in InteractiveMap to "100%", but when I inspect the element, it seems like it gets translated to the pixel value that is represented by 100%. This means that when I resize the window, it stays fixed at the pixel value and doesn't grow with the window.

#### Repro Steps

Create an InteractiveMap with Width="100%"
Start with a small window, and then expand it

#### Environment (please complete the following information):

- Library Version: 6.1.13
- React-scripts: 4.0.3, I'm also using Typescript
- Browser Version: Chrome 89.0.4389.128 

![image](https://user-images.githubusercontent.com/2522984/117366264-7ebf7e00-ae8e-11eb-996c-d9601181fcd4.png)

![image](https://user-images.githubusercontent.com/2522984/117366328-9434a800-ae8e-11eb-81f2-7e101ff5d0f0.png)

![image](https://user-images.githubusercontent.com/2522984/117366351-9d257980-ae8e-11eb-988d-a77134f45170.png)

**Comment by Pessimistress** [comment]
#1066

**Comment by achen187** [comment]
hey @Pessimistress I don't think the bug you linked answers my question.

If you look at the react I have written, I set the width to "100%". (which is what you linked recommends) However, this doesn't work.

![image](https://user-images.githubusercontent.com/2522984/117387442-ed183680-aeb6-11eb-8487-4f340dfe086d.png)

When you see the generated map component, it has the pixels hard calculated.

![image](https://user-images.githubusercontent.com/2522984/117387516-091bd800-aeb7-11eb-92ac-539ff9ff248f.png)

I'm trying to figure out why it does this calculation and how to stop it.

**Comment by Pessimistress** [comment]
The `viewport` object contains width and height in pixel values. If you want to set width and height to `100%` you need to define them after `{...viewport}`.

I suggest you install react dev tools and inspect the props that are actually sent to the map component.

**Comment by achen187** [comment]
that did the trick! thanks.
