### ISSUE TITLE
onInteractionStateChanged always returning "isZooming = true"

### ISSUE THREAD

**Issue by achen187** [visgl/react-map-gl#1468]
#### Description

At the beginning, isZooming is not even a part of the event that is being returned in onInteractionStateChange (not sure if that is intentional or not).

The bigger problem is that as soon as you zoom once, isZooming is always returning true in the event.

#### Repro Steps

Integrate an InteractiveMap, and add a log line to the onInteractionStateChange callback.
```     return (
        <InteractiveMap
            ref={mapRef}
            width="100%"
            height="100%"
            mapboxApiAccessToken={getEnvVariables().mapboxToken}
            mapStyle="mapbox://styles/mapbox/outdoors-v11"
            latitude={viewport.latitude}
            longitude={viewport.longitude}
            zoom={viewport.zoom}
            onViewportChange={(evt: any) =>
                setViewport(getRelevantViewport(evt))
            }
            onInteractionStateChange={(interactionState: any) => {
                console.log(interactionState);
                // setInteractionState(
                //     getRelevantInteractionState(interactionState)
                // );
            }}
        />
    ); 
```

See Loom recording of console logs:
https://www.loom.com/share/c08fca41577b4fe3bfd4ffdee198b870

#### Environment (please complete the following information):

- Library Version: 6.1.13
- Mapbox Version: 2.2.0
- React Version: 17.0.2

**Comment by Pessimistress** [comment]
We cannot debug from a screen recording. You can visit [this example](https://visgl.github.io/react-map-gl/examples/interaction) to see the callback in action. If you still believe there is a bug, create a CodeSandbox that reproduces your issue.

**Comment by achen187** [comment]
ok sounds good. Thanks!

**Comment by achen187** [comment]
Hey @Pessimistress thanks so much for the advice. (sorry it's my first time working with open source).

Here's a sandbox that reproduces the bug:
https://codesandbox.io/s/relaxed-wiles-enl43

**Comment by Pessimistress** [comment]
`viewport` contains transition props that are required to reset the zoom state. Follow the [example](https://github.com/visgl/react-map-gl/tree/master#example) to pass all of them to the Map component.

**Comment by achen187** [comment]
Got it. thank you!
