### ISSUE TITLE
Detecting Window resize in onInteractionStateChange

### ISSUE THREAD

**Issue by achen187** [visgl/react-map-gl#1469]
It'd be great to get a key in the "onInteractionStateChange" that tells you whether the window is currently being resized by the user.

I make a query to the API whenever the window changes its viewport (whether that's zooming, or panning etc). I check the interaction state to make sure a user is not currently "panning" so it only makes the api call when the user is done. I would love something similar for "isResizing" as well.

**Comment by achen187** [comment]
Sorry, I don't know how to change the label on this to be an enhancement.

**Comment by Pessimistress** [comment]
[onResize](https://visgl.github.io/react-map-gl/docs/api-reference/static-map#onresize)

Please only use templates to open issues. Go to Discussions for everything else.

**Comment by achen187** [comment]
OK thanks!

@Pessimistress I don't think that's what I needed. What I was proposing was adding 'isResizing" to onInteractionStateChange here: 

https://visgl.github.io/react-map-gl/docs/api-reference/interactive-map#oninteractionstatechange
