### ISSUE TITLE
Features not available in onMouseEnter event

### ISSUE THREAD

**Issue by mikeslemmer** [visgl/react-map-gl#1473]
https://github.com/visgl/react-map-gl/blob/132e8390dec9f15e421a13ece99883b74e1bc86a/src/components/interactive-map.js#L220

I think you meant to include the features on the event object regardless of whether the onHover interface is being used. As onMouseEnter currently works, you can't actually know what feature the mouse entered, so it's somewhat useless. My suggestion is to simply make the assignment on line 220 also happen if isEntering is true. It's a one-line change.

**Comment by Pessimistress** [comment]
Fix published in v5.3.16/v6.1.16
