### ISSUE TITLE
Can't pan the map after enabling geolocation

### ISSUE THREAD

**Issue by brandolori** [visgl/react-map-gl#1479]
#### Description

After activating geolocation via the GeolocateControl component, the map stops being able to be panned. It does not respond to touch or mouse events. Markers are still interactable, and the pointer still displays the interaction cursor (the hand)

#### Repro Steps

1. Open the map
2. Click / tap on the GeolocateControl
3. Wait for geolocation
4. After a position has been tracked, the viewport will sometimes move to the tracked location, sometimes not. Either way, the user can no longer change the viewport of the map, neither by dragging nor by pinch-to-zoom

Here's a repository that presents the issue:
https://github.com/brandolori/react-map-gl-repro

#### Environment (please complete the following information):

- Library Version: react-map-gl 6.1.15
- Mapbox Version: mapbox-gl 2.3.0
- React Version: react 17.0.1
- Browser Version: Chrome 90, Firefox 88
- OS: Windows 10, Android 10

#### Logs

No relevant errors or warnings in the console.

**Comment by Pessimistress** [comment]
Thanks for reporting. `GeolocateControl` triggers `onViewportChange` callback with an extra `nextViewport.onViewportChange` field which overrides your own callback. Before a fix is published you can work around this by swapping the order of your props assignment (`{...viewport} {...props}`).

**Comment by Pessimistress** [comment]
Fix published in v5.3.16/v6.1.16
