### ISSUE TITLE
The "useMapControl" hook typings are out of date, and produce errors

### ISSUE THREAD

**Issue by chriszrc** [visgl/react-map-gl#1492]
#### Description

If you implement the `useMapControl` hook exactly as specified in the documentation, the control works on the map, but you get typescript errors:

https://codesandbox.io/s/keen-panini-glujz?file=/src/components/CustomControl/custom-control.tsx

#### Repro Steps

Here is a codesandbox.io with the repo- https://codesandbox.io/s/keen-panini-glujz?file=/src/components/CustomControl/custom-control.tsx

#### Environment (please complete the following information):

- Library Version: 6.1.15
- Mapbox Version: 2.3.0
- React Version: 17.0.2
- Browser Version: Chrome 90.0
- OS: Mac OS X 10.15.7

#### Logs

No logs, just the following typescript error:
```
Argument of type '{ onDragStart: (evt: any) => void; onClick: (evt: any) => void; }' is not assignable to parameter of type 'Partial<{ 
captureScroll: boolean; 
captureDrag: boolean; 
captureClick: boolean; 
captureDoubleClick: boolean; 
capturePointerMove: boolean; 
children: any; }>'.
  Object literal may only specify known properties, and 'onDragStart' does not exist in type 'Partial<{ captureScroll: boolean; captureDrag: boolean; captureClick: boolean; captureDoubleClick: boolean; capturePointerMove: boolean; children: any; }>'.ts(2345)
```

**Comment by Pessimistress** [comment]
v5.3.17/v6.1.17
