### ISSUE TITLE
If "maxZoom" option is set on map, the map still allows zooming, and the markers move to wrong positions

### ISSUE THREAD

**Issue by chriszrc** [visgl/react-map-gl#1493]
#### Description

If you set a maxZoom on the InteractiveMap, and add a marker, and then scroll zoom, this happens:

![marker_moves](https://user-images.githubusercontent.com/25695785/120794926-d4775c80-c506-11eb-9f24-c6bf7ac3d3b9.gif)

#### Repro Steps

Here's the repro, I tried this with an svg as well, doesn't matter what is in the `Marker`, same problem-

https://codesandbox.io/s/romantic-williamson-tkulh?file=/src/App.tsx

#### Environment (please complete the following information):

- Library Version: 6.1.15
- Mapbox Version: 2.3.0
- React Version: 17.0.2
- Browser Version: Chrome 90.0
- OS: Mac OS X 10.15.7

#### Logs

No logs

**Comment by Pessimistress** [comment]
Use [maxZoom](https://visgl.github.io/react-map-gl/docs/api-reference/interactive-map#maxzoom).

As the readme [explains](https://github.com/visgl/react-map-gl#limitations), we cannot guarantee that it will work if you call a native API instead of using the React interface.

**Comment by chriszrc** [comment]
@Pessimistress Ah, thank you, I didn't realize I was using the native options, that did fix it-
