### ISSUE TITLE
Missing types

### ISSUE THREAD

**Issue by grallc** [visgl/react-map-gl#1496]
Hello,
Since migrating to react-map-gl v6.1, I can't import anymore the PointerEvent and MapLoadEvent, which I need for my function return types.
These types were previously coming from @types/react-map-gl, but they're missing in the new typings provided by react-map-gl and @types/react-map-gl does not seem to be working anymore since the package has its own typings.

How can I use these types ?

Thanks!

**Comment by Pessimistress** [comment]
Can you follow the bug template and provide expected behavior please? `@types/react-map-gl` is not authored by us.

**Comment by opyh** [comment]
#### Description

The `PointerEvent` type is missing in the type declarations. The error isn't in `@types/react-map-gl`, but in `react-map-gl` itself.

#### Repro Steps

- Have a Typescript-based React app
- `npm install react-map-gl@6.1.16`
- Write this line into a component: `import { PointerEvent } from 'react-map-gl';`
- See error `Module '"../node_modules/react-map-gl/src"' has no exported member 'PointerEvent'.`
- [CodeSandbox link](https://codesandbox.io/s/reproduce-missing-pointerevent-type-5nlkb?file=/src/App.tsx)

#### Environment (please complete the following information):

- Library Version: 6.1.16
- Mapbox Version: doesn't matter
- React Version: doesn't matter
- Browser Version: doesn't matter
- OS: doesn't matter

**Comment by Pessimistress** [comment]
We do not maintain `@types/react-map-gl`. The exported type is called `MapEvent` in v6.1.

**Comment by wentjun** [comment]
Hi! Regarding the point on type definitions, some of the types were exported in a strange manner. For instance, if we were to import `MjolnirEvent`, we to do something like `import { MjolnirEvent } from 'react-map-gl/dist/es6/utils/map-controller';`, as `MjolnirEvent` was not exported on the index. The only other thing that was imported from  `map-controller` was the default export.

**Comment by ctaylor4874** [comment]
@Pessimistress I'm working on a PR to improve the type definitions. Is there any reason to not convert fully to Typescript and begin transitioning the `.js` files to `.ts`?

**Comment by Pessimistress** [comment]
@ctaylor4874 that is the goal for the next major release. We opted for d.ts because it was less disruptive. I would appreciate some help with the full migration of the code base!

**Comment by ctaylor4874** [comment]
Will do! I will start a branch if there is not one already

**Comment by ctaylor4874** [comment]
I'm curious what work needs to be done for the auxiliary tools and build processes (babel, webpack, etc.) to compile and lint Typescripts `.ts` and `.tsx` files. I've always used [`@typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint#readme) along with [Rollup](https://rollupjs.org/guide/en/) and it works well. I'm not familiar enough with `ocular-dev-tools` and the current setup to know what is required in this environment

**Comment by Pessimistress** [comment]
@ctaylor4874 Thank you for the pointer. I've been busy lately but I will get the tooling set up as soon as I can. Would you like to become a maintainer of this repo?

**Comment by ctaylor4874** [comment]
> @ctaylor4874 Thank you for the pointer. I've been busy lately but I will get the tooling set up as soon as I can. Would you like to become a maintainer of this repo?

Yes, absolutely. I appreciate it

**Comment by Jamie5** [comment]
I ran into a few issues with the typescript bindings but if the goal is to just move to typescript fully then there isn't much point in improving the `.d.ts` files in the interim I guess.

Is there a way to get to a point in which we can just start contributing incrementally to master as time allows? In which case I and presumably others might be able to help with the conversion.

**Comment by Pessimistress** [comment]
v7.0.0 has been published and it's fully typed.
