### ISSUE TITLE
Interaction always active 

### ISSUE THREAD

**Issue by Florian-crg** [visgl/react-map-gl#1501]
#### Description

In top of my map I made two components, the problem is that the map are being drag when I do stuff on my components.

#### Repro Steps
Create an element on top of your map and try to interact with it.

      <ReactMapGL
            {...viewport}
            className="map"
            height="60vh"
            width="96vw"
            mapStyle="mapbox://styles/mapbox/streets-v11"
            mapboxApiAccessToken={process.env.NEXT_PUBLIC_MAPBOX_KEY}
            onViewportChange={setViewport}
        >
            {
                markers
            }
            <Source id="source" type="geojson" data={geojson}>
                <Layer key="1" {...layerStyle} />
            </Source>

            <DragControl handleX={handleX} />
            <SideBar />
        </ReactMapGL>

(I have tried to play with pointer-event in css to avoid this glitch. Deactivate pointer events on the map and active it on the div, which still pose problem.)

#### Environment (please complete the following information):

- Library Version: [react-map-gl 6.1.15]
- React Version: [react 17.0.2]
- Browser Version: [91.0.4472.106 ]
- OS: [Mac OS X 11.3.1]

**Comment by Florian-crg** [comment]
I, for the moment, use my components outside of ReactMapGL and use some extra css.

**Comment by Pessimistress** [comment]
The map by default captures all interactions within its root. If your controls don't need the map context, then don't render them as children of the `<ReactMapGL>` component. You can find an example in how the control panel is rendered here:  https://github.com/visgl/react-map-gl/blob/6.1-release/examples/layers/src/app.js#L19

If your component do need the map context, see the following documentation on how to implement a custom control:
https://visgl.github.io/react-map-gl/docs/advanced/custom-components

**Comment by Florian-crg** [comment]
Nice thanks
