### ISSUE TITLE
Build fails after upgrade from webpack@4 to webpack@5

### ISSUE THREAD

**Issue by denisinvader** [visgl/react-map-gl#1506]
#### Description

Webpack@5 brings new version of @babel/runtime some it's issues were [resolved in 7.12.0](https://github.com/babel/babel/issues/12169#issuecomment-708666895) but react-map-gl still uses older version in local node_modules directory (different packages in `node_modules/@babel/runtime` and `node_modules/react-map-gl/node_modules/@babel/runtime`

Seems like `@babel/runtime` dependency should be upgraded to `7.12.0` at least.

#### Repro Steps

1. Setup a project with webpack@4 and babel
2. Upgrade webpack to v5
3. Try to build webpack

#### Environment (please complete the following information):

- Library Version: 5.2.7 and above
- Mapbox Version: 1.12.0
- React Version: 16.13.1
- OS: Mac OS X 11.1

#### Logs

```
ERROR in ./node_modules/react-map-gl/node_modules/@babel/runtime/helpers/esm/slicedToArray.js 4:0-48
Module not found: Error: Can't resolve './nonIterableRest' in '/node_modules/react-map-gl/node_modules/@babel/runtime/helpers/esm'
Did you mean 'nonIterableRest.js'?
BREAKING CHANGE: The request './nonIterableRest' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./node_modules/react-map-gl/dist/esm/components/marker.js 1:0-70 66:35-49 78:32-46
 @ ./node_modules/react-map-gl/dist/esm/index.js 7:0-56 7:0-56
 ...
 ```

**Comment by Pessimistress** [comment]
There is no conflict between react-map-gl's required runtime version (^7.0.0) and 7.2.0. The reason you have two versions installed is because of the lock file left from before your webpack upgrade. Removing the lock file and reinstall would solve the problem.
