### ISSUE TITLE
onClick event listener wrong scoping

### ISSUE THREAD

**Issue by 7091lapS** [visgl/react-map-gl#1507]
I'm rendering multiple maps as such:
```
[a, b, c].map(mapObj => <ReactMapGL onClick={e => console.log(e)} />
```

and found that when I click on one of the rendered maps, the click event gets called 3 times, as many as the maps rendered in the loop, instead of just firing from the element that I actually clicked on. I think this is a bug and makes working with multiple maps quite tricky. Logging the click events shows 3 different event targets, one for each different map container.

the `onMouseDown`event behaves correctly by only firing from the map that is actually being clicked, which makes me think that the `onClick` listener might not be behaving correctly

**Comment by Pessimistress** [comment]
Please create a CodeSandbox that reproduces your issue.

**Comment by 7091lapS** [comment]
@Pessimistress here:
https://codesandbox.io/s/confident-wood-8f7f6?file=/src/App.js

it only happens on **right click**: the first time you right-click any of the 3 maps the event fires 3 times. If you do it again it then seems to behave correctly (only fires once)

**Comment by Pessimistress** [comment]
Thanks for reporting. This is fixed by `mjolnir.js@2.5.2`. You may need to remove your lock file to upgrade the dependency.
