### ISSUE TITLE
onClick is fired twice on `<Marker />` component

### ISSUE THREAD

**Issue by buesing** [visgl/react-map-gl#1510]
#### Description

I see the `onClick` event fired twice in short succession when I click a Marker. See sandbox link below.

#### Repro Steps

See code sandbox at https://codesandbox.io/s/elated-brook-94vzs?file=/src/App.tsx
* Click on any marker
* Observe 'Clicked marker' being logged twice

#### Environment (please complete the following information):

- Library Version: 6.1.16
- Mapbox Version: 2.3.1
- React Version: 17.0.2
- Browser Version: Seems to happen on any browser on my macbook pro
- OS: OSX 11.0.1

**Comment by Pessimistress** [comment]
`onClick` is technically not a public API on [Marker](http://visgl.github.io/react-map-gl/docs/api-reference/marker). While I agree this behavior is confusing, it's recommended that you add the listener to the content of Marker instead.

**Comment by Pessimistress** [comment]
Fixed in v5.3.17 / v6.1.17

**Comment by urosran** [comment]
For anyone else coming to this thread, I had a map onClick defined, and a marker onClick defined, so when you click on marker it does it's handler, and map fires it's own -- add  e.originalEvent.stopPropagation(); in the Marker onClick handler to fix.

**Comment by FutureFutureTo** [comment]
> For anyone else coming to this thread, I had a map onClick defined, and a marker onClick defined, so when you click on marker it does it's handler, and map fires it's own -- add e.originalEvent.stopPropagation(); in the Marker onClick handler to fix.

thanks, i'm guessing this just saved me about an hour :)
