### ISSUE TITLE
[QUESTION] Is there a way to display the direction arrow on user location ?

### ISSUE THREAD

**Issue by MiguelSuay** [visgl/react-map-gl#1517]
### Discussed in https://github.com/visgl/react-map-gl/discussions/1516

<div type='discussions-op-text'>

<sup>Originally posted by **MiguelSuay** July  9, 2021</sup>
I need to display the user direction on his location, and update it on real time.
Is there a way to do that ? I can't find anything on documentation.

Examples of what I want to do:

![image](https://user-images.githubusercontent.com/28256622/125067483-e7bdaf00-e0e6-11eb-9bb8-3589fc025d32.png)
</div>

**Comment by Pessimistress** [comment]
Please only open issues with templates.
