### ISSUE TITLE
Spreading markers on a same location

### ISSUE THREAD

**Issue by RicardoBrito1938** [visgl/react-map-gl#1520]
### Discussed in https://github.com/visgl/react-map-gl/discussions/1519

<div type='discussions-op-text'>

<sup>Originally posted by **RicardoBrito1938** July  9, 2021</sup>
Hello guys, my cluster is working fine, but i have some cases where two markers have the same exact location, i would like to know if there is any solution fo spread these markers, something similar to this :

![image](https://user-images.githubusercontent.com/51454097/125124325-47f42700-e0ce-11eb-9f7f-40fd50c85ed1.png)
</div>

**Comment by Pessimistress** [comment]
Please only use templates to open issues. Use Discussions for Q&A.
