### ISSUE TITLE
When setting a minZoom, and zooming all the way out, onInteractionStateChanged can get stuck on "isZooming=true"

### ISSUE THREAD

**Issue by achen187** [visgl/react-map-gl#1531]
#### Description

When setting a minZoom on InteractiveMap, and zooming all the way out, onInteractionStateChanged seems like it can sometimes get stuck on isZooming=true.
#### Repro Steps

https://codesandbox.io/s/practical-cache-bl9lb?file=/src/App.tsx:41-84

1. Open console in sandbox above
2. Zoom in
2. Aggressively zoom out
3. Pan around at the minZoom.
4. Sometimes, isZooming will get stuck at true

#### Environment (please complete the following information):

- Library Version: react-map-gl 6.1.16
- Mapbox Version: 3.3.1
- React Version: react 17.0.2

#### Logs

**Comment by achen187** [comment]
@Pessimistress Any chance you've had a chance to take a look?

**Comment by wentjun** [comment]
The issue that I am facing might be related to this open issue as well - `isZooming` is always true when I am zooming in and out using the mouse wheel.

**Comment by wentjun** [comment]
@achen187's issue can be replicated if maxZoom is defined as well FYI.

**Comment by petr-kratky** [comment]
For me the `isZooming` prop is always `false` in both `onInteractionStateChange` and `onViewStateChange`. Turn max/min zoom on/off didn't help.

This single bug is preventing me from upgrading to v6. All's good in v5.

**Comment by Pessimistress** [comment]
@petr-kratky your issue is not the same as what's reported in this thread. Interaction state is working as expected in this example: https://visgl.github.io/react-map-gl/examples/interaction

Also v5 and v6 are the same code except for the version of Mapbox dependency. If you still believe there is a bug, please open a new issue with a CodeSandbox.

**Comment by Pessimistress** [comment]
Fixed in v5.3.17 / v6.1.17

**Comment by achen187** [comment]
Thanks for fixing this @Pessimistress
