### ISSUE TITLE
LayerProps source does not have all required types

### ISSUE THREAD

**Issue by Merri** [visgl/react-map-gl#1533]
https://github.com/visgl/react-map-gl/blob/227afdbdcd47d8c036ec6ba105662171c53a8a9b/src/components/layer.d.ts#L7

During update from 6.0 to latest 6.1 I noticed a type conflict. We use `Layer` like this:

```tsx
const source = { type: 'vector', url: 'mapbox://ouraccount.tileset-identifier' };
return <Layer source={source} {...otherProps} />
```

However currently `source` is typed as `string` so TypeScript complains. Giving it only the url as string does not work. To workaround the type warning I'm using:

```tsx
const source = { type: 'vector', url: 'mapbox://ouraccount.tileset-identifier' } as unknown as string;
return <Layer source={source} {...otherProps} />
```

But it would be ideal if type for `source` would be corrected to allow for this usage without trickery.

For typing it I found this: https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/

It is a bit odd though that the docs elsewhere [claim `source` would only be a `string`](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/).

**Comment by Pessimistress** [comment]
The `Layer` component requires `source` to be a string: https://visgl.github.io/react-map-gl/docs/api-reference/layer#source

To set a vector source you should use the `Source` component then reference its id in `Layer`.
