### ISSUE TITLE
FullscreenControl button does not appear on the map

### ISSUE THREAD

**Issue by babkouew** [visgl/react-map-gl#1538]
#### Environment:
**react-map-gl version**: 6.1.16
**browser**: All versions of Firefox, Chrome and Safari
**React Version** : All versions of React

### Steps to Trigger Behavior
 1. NavigationControl button is implemented and shows on the top-left
 2. With same implementation as above the FullScreenControl button doesn't show on the top-right

### Link to Demonstration
https://codesandbox.io/s/guinea-map-75bjx

### Expected Behavior
FullscreenControl button must show on top-right

### Actual Behavior
FullscreenControl button doesn't show on top-right

**Comment by hyperloo** [comment]
Hi @babkouew, I analyzed this bug and what I observed is that, on screen resize (for eg: if you resize the browser or you open the console) the map size does not decrease itself.
What happens is the full-screen button stays on the top right corner of the map, which goes out of view on resize.

So, what I was thinking is to make the "mapboxgl-ctrl-group" of the resize button as fixed to the main window, which will always keep it on the top right.

**Comment by Pessimistress** [comment]
@babkouew  The control is hidden if fullscreen is not supported. This is not allowed in CodeSandbox, which uses an iframe.

See:

- [fullscreenEnabled](https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenEnabled)
- [checkFullscreenSupport](https://github.com/mapbox/mapbox-gl-js/blob/2e6abd7cf99c38431a5c8c832a70de984efc6e6b/src/ui/control/fullscreen_control.js#L74)
