### ISSUE TITLE
ReactMapGL Component Missing from API Reference Section

### ISSUE THREAD

**Issue by chefThomas** [visgl/react-map-gl#1539]
#### Description

The main component is missing from the API reference section.

#### Repro Steps

Go to the documentation at https://visgl.github.io/react-map-gl/docs/get-started/get-started and look in the API Reference section for the ReactMapGL component. You will not find it.

**Comment by Pessimistress** [comment]
`ReactMapGL` in the example is the default export of the package. When you import the default endpoint with `import <component> from 'react-map-gl'` it does not matter what name you give it. The default export may also be referred to as `MapGL` in some code samples in the documentation.

I have updated the table of contents to help clarify this:

![image](https://user-images.githubusercontent.com/2059298/132391429-70bb8b87-c8e2-47da-a1ca-b577d39bb2a3.png)
