### ISSUE TITLE
Type Error when using ref on <StaticMap />

### ISSUE THREAD

**Issue by noahbald** [visgl/react-map-gl#1557]
#### Description

When using ref on StaticMap I get the following type error
```
Type '{ children: Element; mapStyle: string; preventStyleDiffing: true; reuseMaps: true; ref: RefObject<MapRef>; latitude: number; longitude: number; zoom: number; mapboxApiAccessToken: string | undefined; }' is not assignable to type 'IntrinsicAttributes & { css?: Interpolation<Theme>; } & Partial<{ mapboxgl: any; container: any; gl: any; mapboxApiAccessToken: string; mapboxApiUrl: string; ... 19 more ...; mapOptions: any; }> & Partial<...>'.
Property 'ref' does not exist on type 'IntrinsicAttributes & { css?: Interpolation<Theme>; } & Partial<{ mapboxgl: any; container: any; gl: any; mapboxApiAccessToken: string; mapboxApiUrl: string; ... 19 more ...; mapOptions: any; }> & Partial<...>'.
```

StaticMap uses ForwardRef, so I should be able to use `ref: React.ForwardRef<any>` as a property of `StaticMap`

#### Repro Steps

Use `ref` as a property of `StaticMap`
``` ts
const Map: React.FunctionComponent<IMap> = ({
  ...
  const mapBox = createRef<MapRef>();
  ...
  return (
    <StaticMap
      ...
      ref={mapBox}
    />
  )
})
```

#### Environment (please complete the following information):

- Library Version: [react-map-gl 6.1.16]
- Mapbox Version: [mapbox-gl 2.4.1]
- React Version: [react 17.0.2]
- Browser Version: [N/A]
- OS: [Mac OS X 11.5.1]

**Comment by KazuNishiGitHub** [comment]
I had the same experience.

After trying various methods, I was able to solve the problem with the following method. (Note: I'm using typeScript.)
node_modules>react-map-gl>src>mapbox>mapbox.d.ts
Add ref: React.MutableRefObject<null> (or maybe React.ForwardRef<any> in your case) to the MapboxProps in.

`export type MapboxProps = Partial<{
  mapboxgl: any,
  container: any,
  gl: any,
  mapboxApiAccessToken: string,
  mapboxApiUrl: string,
  attributionControl: boolean,
  preserveDrawingBuffer: boolean,
  onLoad: Function,
  onError: Function,
  reuseMaps: boolean,
  transformRequest: Function,
  mapStyle: any,
  preventStyleDiffing: boolean,
  visible: boolean,
  asyncRender: boolean,
  width: number | string,
  height: number | string,
  viewState: ViewState,
  longitude: number,
  latitude: number,
  zoom: number,
  bearing: number,
  pitch: number,
  altitude: number,
  mapOptions: any,
  ref: React.MutableRefObject<null> //or React.ForwardRef<any>
}>;`

**Comment by noahbald** [comment]
I think the type of ref should be `React.Ref<MapBox>`.

Also I don't think `src/mapbox` is a React component and isn't actually using ref as a parameter, so the type would be incorrect.

Shouldn't we be adding this type to `StaticMapProps`, since this is the component with the ForwardRef? I think it should be something like this
``` ts
export interface MapRef {
  getMap(): any;
  queryRenderedFeatures(geometry: [number,number] | [[number,number],[number,number]], options?: any): Array<any>;
}

export type StaticMapProps = MapboxProps & Partial<{
  className: string,
  style: any,

  disableTokenWarning: boolean,
  visibilityConstraints: any,
  children: any,

  onResize: Function,
  ref: React.Ref<MapRef>
}>;
```

I'm happy to make a PR for this and check if it works when I have the time

**Comment by Pessimistress** [comment]
v5.3.17/v6.1.17
