### ISSUE TITLE
Using OSM tiles and Maplibre GL

### ISSUE THREAD

**Issue by choffa** [visgl/react-map-gl#1559]
#### Description

I am trying to use OSM tiles with MapLibre GL. However I am having some issues. I have the following code:
```jsx
import { useState } from "react";
import "./App.css";
import ReactMapGL, { NavigationControl } from "react-map-gl";

function App() {
  const style = {
    version: 8,
    sources: {
      osm: {
        type: "raster",
        tiles: ["https://a.tile.openstreetmap.org/{z}/{x}/{y}.png"],
        tileSize: 256,
        attribution: "&copy; OpenStreetMap Contributors",
        maxzoom: 19,
      },
    },
    layers: [
      {
        id: "osm",
        type: "raster",
        source: "osm",
      },
    ],
  };

  const [viewport, setViewport] = useState({
    width: "100vw",
    height: "100vh",
    latitude: 37.7577,
    longitude: -122.4376,
    zoom: 8,
  });

  return (
    <div className="App">
      <ReactMapGL
        {...viewport}
        onViewportChange={(nextViewport) => setViewport(nextViewport)}
        mapStyle={style}
      >
        <NavigationControl />
      </ReactMapGL>
    </div>
  );
}

export default App;
```
based on the create-react-app template and [this CodePen](https://codepen.io/bothness/pen/ExgwzEG). I also have added the correct alias to the webpack configuration. The problem is that nothing but the map is displayed. No attribution, nor `NavigationControl`. The interesting part is that if I remove the maplibre alias from webpack, the controls appear but obviously no map, since I do not supply an API key. 

#### Repro Steps

1. Replace `mapbox-gl` with `maplibre-gl`
2. Use OSM style
3. Add `NavigationControl`

#### Environment (please complete the following information):

- Library Version: `6.1.16`
- Maplibre Version: `1.15.2`
- React Version: `17.0.2`
- Browser Version: Chrome 92 and Safari `14.1.2`
- OS: macOS 10.15.7 Catalina

**Comment by Pessimistress** [comment]
Likely the same issue as https://github.com/visgl/react-map-gl/issues/1383

**Comment by Pessimistress** [comment]
- Map display: You are defining the map style inside the render function, so it is attempting to update the style on every render (viewport change). It should be defined as a constant.
- Navigation control: you need to import the maplibre-gl stylesheet, see http://visgl.github.io/react-map-gl/docs/get-started/get-started#styling

Adding an example here: https://github.com/visgl/react-map-gl/pull/1560
