### ISSUE TITLE
GeoJson feature and marker don't line up

### ISSUE THREAD

**Issue by e11en** [visgl/react-map-gl#1571]
#### Description

GeoJson feature and marker at the exact location don't line up 
![image](https://user-images.githubusercontent.com/855939/132540479-d915438a-91be-45fb-9104-3eb86f7d4884.png)

#### Repro Steps

```
const geojson: any = {
    type: "FeatureCollection",
    features: [
      {
        type: "Feature",
        geometry: {
          type: "Point",
          coordinates: [6.624385176148941, 52.03723664138364],
        },
        properties: {
          name: "Gateway 1",
          lastSeen: new Date().toISOString(),
          online: "Offline",
        },
      },
    ],
  };

const circleLayerStyle: any = {
    id: "point",
    type: "circle",
    paint: {
      "circle-radius": 50,
      "circle-color": "#023a4f",
      "circle-opacity": 0.5,
    },
  };

<ReactMapGL>
	<Source id="some-data" type="geojson" data={geojson}>
	  <Layer {...circleLayerStyle} />
	</Source>
	<Marker longitude={6.624385176148941} latitude={52.03723664138364}>
	  <img src={someImage} alt="marker" />
	</Marker>
</ReactMapGL>
```

#### Environment (please complete the following information):

- Library Version:"react-map-gl": "5.2.11",
- Mapbox Version: "1.13.1"
- React Version: "react": "^17.0.2",
- Browser Version: any (chrome 92.0.4515.159)
- OS: Windows

#### Logs
Don't know if this is relevant though.
![image](https://user-images.githubusercontent.com/855939/132540307-7cd75b00-4716-4092-ab97-32278b3da493.png)

**Comment by Pessimistress** [comment]
Your marker's top-left corner is positioned at the given coordinate. To use a different anchor point see [offsetLeft](http://visgl.github.io/react-map-gl/docs/api-reference/marker#offsetleft) and [offsetTop](http://visgl.github.io/react-map-gl/docs/api-reference/marker#offsettop).
