### ISSUE TITLE
Slow state update for animated GeoJSON layer when frequently zooming or on firefox desktop

### ISSUE THREAD

**Issue by karussell** [visgl/react-map-gl#1577]
Firefox (linux/desktop) has a problem to render GeoJSON animations smoothly. When you open the [geojson-animation](https://visgl.github.io/react-map-gl/examples/geojson-animation) examples with Firefox v92.0 you will not see a smooth animation - it looks like many frames are skipped. When I make the browser smaller then it is much smoother.

On mobile Firefox v92.1.1 (Android) viewing this example is fine, but as soon as you zoom in and out frequently you will get the same lagging / delay problem. With continuous zooming in+out you can basically cause that the circle stands still.

Chrome is working fine on Desktop and Android also with heavy zooming. (Maybe something the firefox team needs to investigate? I hope it is ok to ping @jrmuizel who was involved in a similar issue #909.)

In our real world applications this is a problem when we trigger viewport changes due to a transitionInterpolator which is likely identical to the "frequent zooming". I.e. then state changes are never (or only very late) transferred to the associated GeoJSON layer which can be just a circle like in the example. And this delay problem increases when the animation duration is increased.

The option asyncRender=true does not help in our case and it is no option for us as the state-to-map synchronization is important. I can try [this comment](https://github.com/visgl/react-map-gl/issues/1000#issuecomment-611774890) and see if the situation is improved, but I would need a code example :)

Is there e.g. a possibility to say that the animation changes are less important than updates to the layers?

btw: I think [here](https://github.com/visgl/react-map-gl/blob/master/test/src/utils/transition-manager.spec.js#L9) the comment should be "global.requestAnimationFrame"?

**Comment by karussell** [comment]
As a follow up I've created https://bugzilla.mozilla.org/show_bug.cgi?id=1732049

**Comment by Pessimistress** [comment]
Do you see the same issue here? https://docs.mapbox.com/mapbox-gl-js/example/animate-point-along-line/

**Comment by karussell** [comment]
Yes, indeed (But only when I open it in codepen where the map is bigger).

Still the lagging is not that severe which might be because of a smaller radius the circle goes or something else? So likely not an issue of react-map-gl?

**Comment by Pessimistress** [comment]
Performance issues are being addressed in v7.0. Please follow #1646
