### ISSUE TITLE
Styling is automatically imported but documentation says otherwise

### ISSUE THREAD

**Issue by iamdriz** [visgl/react-map-gl#1581]
#### Description

According to the Documentation here: http://visgl.github.io/react-map-gl/docs/get-started/get-started#styling

The CSS should be included like so: `import 'mapbox-gl/dist/mapbox-gl.css';` This would also allow you to easily opt-out of the standard CSS or overwrite it.

However what happens is that the CSS is included without having to do this... looking at the developer tools it's being imported from `https://api.tiles.mapbox.com/mapbox-gl-js/v2.4.1/mapbox-gl.css`.

Why is this happening, if the Documentation states it must be manually imported? And how can I stop this if I wanted to stop it from being imported (e.g. loading a custom localized one).

**Comment by Pessimistress** [comment]
It is recommended that you import the stylesheet yourself. When a map is rendered, we check if a stylesheet exists:

https://github.com/visgl/react-map-gl/blob/376dc5cc086d2bc73cbc46c52854048787cc2aac/src/mapbox/mapbox.js#L416-L420

If not then a default one is attached automatically.

> Why is this happening

There were too many complaints from users who failed to include the stylesheet in their apps and the components didn't work.

> And how can I stop this if I wanted to stop it from being imported

Your custom stylesheet should contain an entry of `.mapboxgl-map` to pass the above test. If you are using maplibre see https://github.com/visgl/react-map-gl/issues/1513.
