### ISSUE TITLE
`transformRequest` should be a property of `Source` rather than `Map`, IMO.

### ISSUE THREAD

**Issue by jayarjo** [visgl/react-map-gl#1582]
It's more of a thoughtful suggestion I guess, rather than a bug report. Having it on a Source makes so much more sense 🤷‍♂️

**Comment by Pessimistress** [comment]
Please only open issues with templates. All other topics should use Discussions.

react-map-gl is a wrapper of mapbox-gl. `transformRequest` is an API of mapbox-gl's Map class and we are simply passing the prop through. If you have suggestions about this API you should open an issue in the Mapbox repo.
