### ISSUE TITLE
Markers in the map can be touched to zoom the map, but not to drag the map

### ISSUE THREAD

**Issue by kondulak10** [visgl/react-map-gl#1584]
I am using `import ReactMapGL, { Marker } from 'react-map-gl';` on the touch devices (Same behavior is on desktop).

If there are lot of markers on the same view for example: https://mapheim.com/trondheim it is hard to navigate the map, **because you can not drag the map while touching the markers**. But it is possible to zoom the map while touching the markers.

This seems to be an inconsistent behavior. 

Is it a bug in the library, or somewhere within my implementation?

**Comment by Pessimistress** [comment]
http://visgl.github.io/react-map-gl/docs/api-reference/marker#capturedrag

Please only use templates to open issues. Use Discussions for Q&A.
