### ISSUE TITLE
Can MapController._onWheel change non-smooth zoom to use transitionDuration 0?

### ISSUE THREAD

**Issue by Jamie5** [visgl/react-map-gl#1586]
#### Description

I believe before https://github.com/visgl/react-map-gl/commit/53390c916f2c40263ce1bfb6f98cddb6bfce8195#diff-f53fd0b612f6ac98e4426c8b523b49c5b28b497f6c474cf22dec791666ff8c46 the non-smooth zoom (the only one at that point) had transitionDuration 0.

The reason for this request (besides that it preserves the previous behavior): We override `MapController._onWheel` to debounce the requests, because otherwise, on Firefox, it seems like the amount of wheel events causes significant lag. (Presumably because some handling on our end ends up being rather slow, but let's ignore that).

In this override, we collect a number of calls, adjusting the total delta, and run it each animation frame.

When trying to upgrade from 5.2.12 to 5.3.17, we experience an issue where the map will appear to zoom in and out in zigzag fashion even if the user is only zooming in with their trackpad. This seems to be (but not really sure) due to a zoom not completing before the next zoom happens, or something like that. However, changing the non-smooth transitionDuration to 0 will avoid this zig-zag motion, presumably because the zoom happens immediately and finishes before the next event comes in to be processed.

NOTE: It seems like we also have to, in the non-smooth case, eventually call the old `_onWheelEnd` as per https://github.com/visgl/react-map-gl/blob/c9daf7fb825d92ba523f59d1be52ef0991ef7a8e/src/utils/map-controller.js#L321-L328 (which would now reset panning as well)

#### Repro Steps

See above

#### Environment (please complete the following information):

- Library Version: 5.3.17
- Mapbox Version: 2.3.0 (but has been observed on others)
- React Version: [e.g. react 17.0.1]
- Browser Version: Firefox 93.0, Chrome recent
- OS: [e.g. Mac OS X 11.2]

**Comment by underfisk** [comment]
I've run into the same issue where from `5.2.11` upgrading to `5.3.0` introduces a shifting when zooming in/out and not working as intended

**Comment by Pessimistress** [comment]
MapController is being abandoned in v7.0. Please follow #1646
