### ISSUE TITLE
Exception when using WebMercatorViewport.fitBounds with padding

### ISSUE THREAD

**Issue by buddebej** [visgl/react-map-gl#1598]
#### Description

Getting exception when calling WebMercatorViewport.fitBounds with padding option.
Would be nice to have a fallback here (e.g. ignoring padding) - but at least a clear error message.

#### Repro Steps

- Very small map container size
- Big value for padding (i set it to 200)
- > leads to exception without clear error message

#### Environment (please complete the following information):

- Library Version: [e.g. react-map-gl 6.1.17]
- Mapbox Version: [e.g. mapbox-gl 2.3.0]
- React Version: [e.g. react 17.0.1]

**Comment by Pessimistress** [comment]
Closing because WebMercatorViewport no longer exists in v7. Use Map prop `padding` instead.

**Comment by iserranoe** [comment]
How can I update from using WebMercatorViewport.fitBounds in v6 to v7?
