### ISSUE TITLE
Broken with React 18 due to "Cannot redefine property: offsetWidth"

### ISSUE THREAD

**Issue by vpontis** [visgl/react-map-gl#1608]
#### Description

Example repo: https://github.com/luma-team/react-map-gl-react-18-broken

Screenshot: 

<img width="760" alt="CleanShot 2021-11-16 at 10 52 14@2x" src="https://user-images.githubusercontent.com/1319079/142047588-f0309f60-d3f0-4722-a15c-143842e377e0.png">

#### Environment (please complete the following information):

- Library Version: 6.1.17
- Mapbox Version: 2.6.0
- React Version: 18
- OS: Mac OS Monterey

**Comment by reymon359** [comment]
Hi there 👋🏽  

I am facing this issue and don't know why it is happening or how to solve it 😕

Any update about it?

Did you manage to solve it @vpontis?

Thanks in advance 😄

**Comment by Pessimistress** [comment]
This is due to React 18's chage to call `useEffect()` twice in `StrictMode`: https://github.com/reactwg/react-18/discussions/19

I'll put up a fix.

**Comment by reymon359** [comment]
> This is due to React 18's chage to call `useEffect()` twice in `StrictMode`: [reactwg/react-18#19](https://github.com/reactwg/react-18/discussions/19)
> 
> I'll put up a fix.

Thanks for the update @Pessimistress, 

I actually found the reason it was happening and fixed it on my end. 

Thanks anyway for the fix 😄

**Comment by Pessimistress** [comment]
This is fixed in v6.1.19

**Comment by LRT-stack** [comment]
Yes, I also found that Streetscape.gl is not available in React18+

**Comment by emmyzee45** [comment]
Please I'm having the same problem, how can I solve it?
