### ISSUE TITLE
interactiveLayerIds property not working as expected

### ISSUE THREAD

**Issue by prosperva** [visgl/react-map-gl#1618]
I am using the ReactMapGL plugin and I have noticed something weird going on with the `interactiveLayerIds` property as follows:

`interactiveLayerIds={['layer1', 'layer2']}`

I have different events for each layer such as click but when `layer2` is not visible, I am not able to click on `layer1`. Once `layer2` is enabled, then `layer1`'s events are working. I would like to have the events on `layer1` working even if `layer2` is not active

Do all layers in the `interactiveLayerIds` property need to be visible for the interaction to work?

**Comment by Pessimistress** [comment]
If you wish to report a bug, use the bug report template and provide steps to reproduce. Otherwise please go to Discussions.
