### ISSUE TITLE
Map is lag when rotating map (enable Inspect DevTools Chrome)

### ISSUE THREAD

**Issue by ttungbmt** [visgl/react-map-gl#1627]
#### Description

I inspect DevTools Chrome, and rotate maps => Map is lag

![image](https://user-images.githubusercontent.com/12232155/145346886-3af84fe0-6f30-46ad-b6ad-503dfa59c332.png)

**Comment by Pessimistress** [comment]
Please provide all the information asked by the issue template, including steps to reproduce, runtime environment, etc. If you need generic help please use Discussions.
