### ISSUE TITLE
Clustering property not respected on Source

### ISSUE THREAD

**Issue by g-karou** [visgl/react-map-gl#1628]
#### Description

Component `<Source/>` is not respecting `cluster:false` property when combined with `<Layer/>` of type `symbol`. 

#### Repro Steps

- Check the following  [codesandbox](https://codesandbox.io/s/disable-clustering-8s6zo?file=/src/App.js) 
- Initially only 1 icon image pin is displayed.
- Zooming in the map shows more.
- Expected behaviour would be for `cluster={false}` to disable clustering

#### Environment (please complete the following information):

- Library Version: react-map-gl 6.1.18
- React Version: react 17.0.0
- Browser Version: Chrome 96.0
- OS: Mac OS Big Sur 11.6

**Comment by Pessimistress** [comment]
See [icon-allow-overlap](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-icon-allow-overlap)

react-map-gl does not handle styling. All layer/source props are directly passed into mapbox-gl. Please refer to Mapbox documentation if you have any questions about layer behavior.
