### ISSUE TITLE
Viewport in the context is out of sync after resize

### ISSUE THREAD

**Issue by khmm12** [visgl/react-map-gl#1634]
#### Description

Viewport in the context is out of sync after resize in some cases. The issue comes here because in such cases `InteractiveMap` doesn't re-render after resize.

<details>
<summary>The reason</summary>

1. Map element height becomes 0.
2. The observer triggers `onResize` https://github.com/visgl/react-map-gl/blob/6149dd00360406961030cae06567e89c10b6011b/src/components/interactive-map.js#L393
3. `onResize` calls `updateControllerOpts` https://github.com/visgl/react-map-gl/blob/6149dd00360406961030cae06567e89c10b6011b/src/components/interactive-map.js#L396
4. `updateControllerOpts` https://github.com/visgl/react-map-gl/blob/6149dd00360406961030cae06567e89c10b6011b/src/components/interactive-map.js#L379 doesn't set new options on the controller, because height === 0.
5. Somewhere render happens outside of the component, new viewport is created.
6. Map element height returns value before it became 0.
7. 2-3, but the controller doesn't trigger viewport change because options were not changed since last time https://github.com/visgl/react-map-gl/blob/6149dd00360406961030cae06567e89c10b6011b/src/utils/map-controller.js#L209

</details>

#### Repro Steps

[codepen](https://codesandbox.io/s/twilight-firefly-goeig)

1. Open map.
2. Check "collapse" checkbox.
3. Uncheck "collapse" checkbox.

#### Environment:

- react-map-gl version: `6.1.18`/`5.3.18`

**Comment by dgattey** [comment]
Is there a workaround for this in the meantime? Thanks for the well-documented issue, running into this too.

**Comment by Pessimistress** [comment]
Closing because viewport is no longer part of the MapContext in v7.
