### ISSUE TITLE
cooperativeGestures mapOption doesn't work

### ISSUE THREAD

**Issue by pequeurb** [visgl/react-map-gl#1640]
#### Description

I found this on the mapbox website that would solve a UX issue that I'm having:
https://docs.mapbox.com/mapbox-gl-js/example/cooperative-gestures/

This would allow me to make it so that users can scroll on the map without zooming out, and for touch devices have panning only work with two fingers instead of one.

But nothing happens when I try to add it in the mapOptions (using react-map-gl version 6.1.18).
I created an example in a codesandbox here:
https://codesandbox.io/s/react-map-gl-cooperativegestures-sxw8b

Am I doing something wrong or is this a bug? (may be the same problem as issue #1353)

**Comment by TatoBig** [comment]
I'm having the same problem, It could be a bug

**Comment by Pessimistress** [comment]
react-map-gl does not use mapbox-gl's native controller. This option is currently not supported.

**Comment by Pessimistress** [comment]
This feature is not going to be supported by v6. You can try the v7 beta following the linked issue.

**Comment by chriszrc** [comment]
It's probably worth noting here, since this is what shows up in searches, that support for this was added in v7, and the original codesandbox has even been updated and shows it working:

https://codesandbox.io/s/react-map-gl-cooperativegestures-sxw8b?file=/src/index.js:696-715
