### ISSUE TITLE
clusterCountLayer transition lags behind clusterLayer on cluster click

### ISSUE THREAD

**Issue by maggievcody** [visgl/react-map-gl#1645]
#### Description

When a cluster is clicked, the `clusterCountLayer` seems to lag behind the `clusterLayer` a little, resulting in the text transition being delayed. I notice this occurs in the [cluster demo](https://visgl.github.io/react-map-gl/examples/clusters) as well.

Adjusting the viewport `transitionDuration` doesn't seem to help – I think something may be off about the individual layer transition durations or order in which they occur in. It would be nice if these layers transitioned simultaneously so the cluster count is not delayed.

<img width="924" alt="Screen Shot 2021-12-22 at 12 43 31 PM" src="https://user-images.githubusercontent.com/36513249/147140661-fd6c15e4-0c7e-47a9-a708-ff315ae8f41c.png">

<img width="924" alt="Screen Shot 2021-12-22 at 12 44 26 PM" src="https://user-images.githubusercontent.com/36513249/147140947-70b3672a-3eb6-44d8-ba6c-73188d36262d.png">

<img width="905" alt="Screen Shot 2021-12-22 at 12 43 58 PM 1" src="https://user-images.githubusercontent.com/36513249/147143625-952e126b-359a-4649-9f6e-b8e2c262592d.png">

#### Repro Steps

- Implement clustering using react-map-gl
- Click on cluster
- See text in `clusterCountLayer` lag behind `clusterLayer` transition

#### Environment (please complete the following information):

- Library Version: react-map-gl 6.1.14
- React Version: 17.0.2
- Browser Version: Chrome 96.0.4664.93
- OS: Mac OS 11.2.3 Big Sur

**Comment by Pessimistress** [comment]
The example ports [Mapbox GL JS's own example](https://docs.mapbox.com/mapbox-gl-js/example/cluster/). react-map-gl does not handle the layer rendering. You may want to report this to the mapbox-gl repo instead.

**Comment by maggievcody** [comment]
Will do! Thank you.
