### ISSUE TITLE
mapbox with ant-design-pro emitValidationErrors

### ISSUE THREAD

**Issue by hasanmumin** [visgl/react-map-gl#1648]
#### Description
I am trying use mapbox with ant-design-pro but there are some console errors.

#### Repro Steps

https://github.com/hasanmumin/ant-design-pro-mapbox
Mapbox code https://github.com/hasanmumin/ant-design-pro-mapbox/blob/master/src/pages/Welcome.tsx

#### Environment (please complete the following information):

- Library Version: ^6.1.18
- React Version: ^17.0.0
- Browser Version: Chrome 96.0.4664.110
- OS: Mac OS X 12.0.1

#### Logs
There are many console errors
- sources.earthquakes: unknown property "data-inspector-line" at Object.ai [as emitValidationErrors]
- sources.earthquakes: unknown property "data-inspector-column" at Object.ai [as emitValidationErrors]
- sources.earthquakes: unknown property "data-inspector-relative-path" at Object.ai [as emitValidationErrors]

etc

**Comment by Pessimistress** [comment]
The errors are not from this library. Your `PageContainer` is injecting props into `Source` and `Layer` that mapbox does not recognize. I suggest you ask in ant-design-pro's community how to block this behavior.
