### ISSUE TITLE
Increased memory usage when unmount/mount map components

### ISSUE THREAD

**Issue by Pessimistress** [visgl/react-map-gl#167]
One of my projects is experiencing crash due to high memory usage when the user repeatedly switch between map and non-map views. It seems that peak memory usage steadily increases each time the map is unmounted and then remounted. 

The `MapGL` component does call [remove()](https://www.mapbox.com/mapbox-gl-js/api/#Map#remove) of the MapboxGL API on `componentWillUnmount`. Maybe not all resources are released during this process?

I added a show/hide map button to the example app to demonstrate this behavior. On my box the peak memory usage goes up from 600M on load to 1.1G after 4-5 toggles: 
https://github.com/uber/react-map-gl/tree/perf-test

![screen shot 2017-01-03 at 4 26 56 pm](https://cloud.githubusercontent.com/assets/2059298/21628191/6071449e-d1d2-11e6-8802-1d42eac42eba.png)

Any ideas @lucaswoj @ibgreen @abmai ?

**Comment by abmai** [comment]
doing some digging around for this one now

**Comment by abmai** [comment]
looks like this is coming directly from mapbox-gl - this screenshot is from just toggling on/off rendering a mapbox-gl instance without doing anything else

![image](https://cloud.githubusercontent.com/assets/2263443/21781277/933de72a-d663-11e6-886b-b7d6ebfed6aa.png)

**Comment by ryanirilli** [comment]
Thanks for the investigation, has there been any activity or issue opened with mapbox-gl on this one?

**Comment by aryzing** [comment]
Yeah, we're running into the same issues. We have an app with several maps in different locations. Every time a map is loaded, memory consumption keeps increasing. The best we've been able to do is use the `reuseMaps` prop.

**Comment by aryzing** [comment]
@Pessimistress what PR was this resolved in?

**Comment by Pessimistress** [comment]
@aryzing This issue was referring to a no longer maintained version of this library and inactive for more than 2 years. The cause was determined to be inside mapbox-gl. If you are still experiencing this you may open a new issue in the Mapbox GL JS repo.
