### ISSUE TITLE
default component crashes in Safari/Chrome/Webview on iPhone

### ISSUE THREAD

**Issue by yryrgogo** [visgl/react-map-gl#1684]
#### Description

When I use the react-map-gl component (default exported InteractiveMap) from my iPhone browser, it crashes.
This does not happen when the app is operated from a PC browser under the same conditions.

This happens even in a simple SPA that just displays a map with react-map-gl.

When this error occurs, the only way to catch it is with ErrorBoundary, which forces the user to abort the operation.
This is fatal for my app. Is this a specification? Is it a bug?

#### Repro Steps

The only condition for this to occur is to pinch in, pinch out, or move continuously on the map. You don't have to move it more than necessary for it to occur, but if it doesn't, reload and try several times to get it to occur.
In my experience, the rate of occurrence is 20%.

I've deployed an SPA that just renders a map with react-map-gl. When I open this in my iPhone browser, I encounter a rendering that gives me an error 20% of the time. I think it is more likely to occur in Chrome than in Safari.
No special implementation has been done.

The error doesn't occur just by rendering, but it does occur after a certain amount of time of repetitive operations. (If the error doesn't occur within 5 seconds of starting the operation, it may be faster to reload.)

#### Environment (please complete the following information):

- Library Version: react-map-gl 6.1.18
- React Version: react 17.0.38
- Browser Version: Chrome 96.0.4664.116
- OS: iOS15.1（iPhone SE 2nd generation）

#### Logs

This log was retrieved from Chrome.

```
ERROR The above error occurred in the <ForwardRef> component:
div
Component@
Component
Container
```

**Comment by Pessimistress** [comment]
Do you experience this on https://visgl.github.io/react-map-gl/examples ?

**Comment by yryrgogo** [comment]
No, it did not happen in https://visgl.github.io/react-map-gl/examples ?
I figured that either the version of the application or the environment, or a combination of the two, may be affecting the problem.

Are there any other possibilities?

**Comment by Pessimistress** [comment]
See https://github.com/visgl/react-map-gl/tree/6.1-release/examples

This issue template is for reporting bugs in the library itself. If you believe this is a bug on our side, create a CodeSandbox that reproduces the issue. If you need help debugging your own project, please go to Discussions.

**Comment by yryrgogo** [comment]
Thank you. I will investigate the issue in more detail.
