### ISSUE TITLE
hash persisted on navigation to another page

### ISSUE THREAD

**Issue by massimopalmieri** [visgl/react-map-gl#1687]
#### Description

when `mapOptions.hash = true` and navigating to a new page the hash is persisted in the new url. The issue can't be reproduced when `mapbox-gl` is used directly without `react-map-gl`.

#### Repro Steps

- go to https://mapbox-hash-repro.vercel.app/
- the map will update the hash
- click on "link to another page" 
- expected behaviour: the url should be https://mapbox-hash-repro.vercel.app/other-page
- actual behaviour: the url is https://mapbox-hash-repro.vercel.app/other-page#0.9/34.5/0

#### Environment

- Library Version: react-map-gl 6.1.18
- Mapbox Version: mapbox-gl 2.6.1
- React Version: react 17.0.2
- Browser Version: Chrome 97.0.4692.71
- OS: Mac OS X 12.1

#### Logs

no errors or warnings

**Comment by Pessimistress** [comment]
This feature is not handled by react-map-gl. You may want to report it to the mapbox-gl repo.
