### ISSUE TITLE
blank map with gray background while using react-map-gl in production build (even after trying all 3 solutions from mapbox official)

### ISSUE THREAD

**Issue by iAmZubair00** [visgl/react-map-gl#1700]
#### Description

I am not able to display map properly in production, while using react-map-gl in create-react-app. App is working fine on localhost but it throws errors in the console while running in production. I have tried all the 3 solutions mentioned in official mapbox docs https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling

I first tried these solutions one by one separately, and then all 3 solutions simultaneously, but none of these 4 attempts worked.

I have attached the screenshot of console errors below along with live URL of my production site and github code.

Live URL: https://parking-app-fyp.vercel.app
github code: https://github.com/iAmZubair00/parking-app-fyp

#### Environment:

- react-map-gl 6.1.18
- mapbox-gl 2.6.1
- react 17.0.2

#### Logs
![console error in production](https://user-images.githubusercontent.com/87325230/150491514-2f563de9-20af-412d-b704-0941906c9fef.PNG)

### Code used for "3 tried solutions":

Loading and transpiling the Web Worker separately:
`import mapboxgl from "mapbox-gl";
// eslint-disable-next-line import/no-webpack-loader-syntax
import MapboxWorker from "worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker";
mapboxgl.workerClass = MapboxWorker.default;`

Excluding Mapbox GL JS explicitly from transpilation:
`module.exports = {
  babel: {
    loaderOptions: {
      ignore: ["./node_modules/mapbox-gl/dist/mapbox-gl.js"],
    },
  },
};`

Targeting transpilation to ES6 with browserslist:
`"browserslist": {
    "production": [
      ">0.2%, not dead, not ie 11, not chrome < 51, not safari < 10",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }`

**Comment by A-Tokyo** [comment]
Facing the same issue! I also tried the 3 solutions with no luck.

**Comment by Pessimistress** [comment]
To use craco you need to install it and use their scripts. https://www.npmjs.com/package/@craco/craco

There is already a pinned issue at https://github.com/visgl/react-map-gl/issues/1266. If you are not happy with the solution, take it to the mapbox-gl repo.

**Comment by iAmZubair00** [comment]
> To use craco you need to install it and use their scripts. https://www.npmjs.com/package/@craco/craco
> 
> There is already a pinned issue at #1266. If you are not happy with the solution, take it to the mapbox-gl repo.

I have installed craco by using "npm install craco", and I have already viewed your mentioned issue which has not solved my problem. They are suggesting a very strange solution there, to downgrade your react-map-gl to lower version!

**Comment by A-Tokyo** [comment]
@iAmZubair00 This worked for me https://github.com/visgl/react-map-gl/issues/1266#issuecomment-758139857. The map now loads. Hope it works for you!

**Comment by A-Tokyo** [comment]
Tempfix:


In the Map component, add:

```js
import mapboxgl from 'mapbox-gl/dist/mapbox-gl';
import MapboxWorker from 'mapbox-gl/dist/mapbox-gl-csp-worker';
mapboxgl.workerClass = MapboxWorker;
```

**Comment by iAmZubair00** [comment]
> Tempfix:
> 
> In the Map component, add:
> 
> ```js
> import mapboxgl from 'mapbox-gl/dist/mapbox-gl';
> import MapboxWorker from 'mapbox-gl/dist/mapbox-gl-csp-worker';
> mapboxgl.workerClass = MapboxWorker;
> ```

means this is the modified solution #1 (Loading and transpiling the Web Worker separately) ? right
and you have not used solution 2, and 3 in parallel with this solution?

**Comment by A-Tokyo** [comment]
@iAmZubair00 Correct

**Comment by iAmZubair00** [comment]
and working well in production?

**Comment by iAmZubair00** [comment]
> Tempfix:
> 
> In the Map component, add:
> 
> ```js
> import mapboxgl from 'mapbox-gl/dist/mapbox-gl';
> import MapboxWorker from 'mapbox-gl/dist/mapbox-gl-csp-worker';
> mapboxgl.workerClass = MapboxWorker;
> ```

I got some errors in the console and map did not load, even in the localhost after using the above solution

**Comment by A-Tokyo** [comment]
So the final solution becomes:

```js
import mapboxgl from 'mapbox-gl/dist/mapbox-gl';
import MapboxWorker from 'mapbox-gl/dist/mapbox-gl-csp-worker';
mapboxgl.workerClass = MapboxWorker.default;
```

**Comment by Pessimistress** [comment]
> I have installed craco by using "npm install craco"

I can see in your package.json you are still using `react-scripts build`. According to the craco documentation you need `craco build`.

**Comment by iAmZubair00** [comment]
> > I have installed craco by using "npm install craco"
> 
> I can see in your package.json you are still using `react-scripts build`. According to the craco documentation you need `craco build`.

But according to @A-Tokyo , it should now work without using craco!

**Comment by Pessimistress** [comment]
You do not need multiple solutions. Either one would work.

**Comment by iAmZubair00** [comment]
still getting same error in production, only change in the error is that variable 'y' is now variable 'm' which is missing!

**Comment by iAmZubair00** [comment]
> > I have installed craco by using "npm install craco"
> 
> I can see in your package.json you are still using `react-scripts build`. According to the craco documentation you need `craco build`.

changing scripts to use Craco, worked! 
Thanks, @Pessimistress

**Comment by iAmZubair00** [comment]
> > > I have installed craco by using "npm install craco"
> > 
> > 
> > I can see in your package.json you are still using `react-scripts build`. According to the craco documentation you need `craco build`.
> 
> changing scripts to use Craco, worked! I had to use craco version 5.0.0 which was compatible with react-scripts 5.0.0
Thanks, @Pessimistress
