### ISSUE TITLE
Navigation Control tooltips don't show with keyboard focus

### ISSUE THREAD

**Issue by nora-moseman** [visgl/react-map-gl#1711]
#### Description

The "Zoom in" and "Zoom out" buttons show explanatory tooltips when the user hovers over them with a mouse, but they do not show these tooltips when they receive keyboard focus. This is an accessibility issue for users who navigate the web using keyboard rather than mouse. 

#### Repro Steps

1. navigate on map using 'tab' key 
2. control buttons are highlighted but do not show the tooltips they show on hover

#### Environment (please complete the following information):

- Library Version: react-map-gl 5.2.2
- Mapbox Version: mapbox-gl 1.13.1 (?)
- React Version: 16.13.1
- Browser Version: 97.0.4692.99
- OS: Mac OS Monterey 12.1

**Comment by Pessimistress** [comment]
The native Mapbox GL JS library has the same behavior: https://docs.mapbox.com/mapbox-gl-js/example/navigation/

Please report this to the mapbox-gl-js repo.
