### ISSUE TITLE
[Bug] default maxPitch of 85 breaks usage with maplibre-gl@1.x.x

### ISSUE THREAD

**Issue by dreamorosi** [visgl/react-map-gl#1719]
### Description

The default `maxPitch` set to 85 in the `defaultProps` of the [map component](https://github.com/visgl/react-map-gl/blob/master/src/components/map.tsx#L43) conflicts with the apparent max pitch allowed by `maplibre-gl@1.x.x`.

A user using `react-map-gl` that doesn't explicitly set a `maxPitch<=60` when using `maplibre-gl@1.x.x` won't be able to render a map at all.

If instead `maxPitch<=60` is passed to the map component everything works as expected.

### Expected Behavior

Ideally set different `maxPitch` values depending on which version of `maplibre-gl` is being used.

If the above is too complicated, not feasible, or not desired then one of the two:
- Set default `maxPitch` to 60
OR
- Specify somewhere in the documentation that when using `maplibre-gl@1.x.x` this value must be `<=60`

If none of the above is in line with the project's scope/direction then perhaps specify that `maplibre-gl@1.x.x` is no longer supported.

### Steps to Reproduce

Install:
`npm i maplibre-gl@1.15.2 react-map-gl@7.0.1`

Then create a map using the [first example of the docs](http://visgl.github.io/react-map-gl/docs/get-started/get-started#example).

### Environment

- Framework version: 7.0.1
- Map library: maplibre-gl@1.15.2
- Browser: Safari
- OS: macOS

### Logs

Error: maxPitch must be less than or equal to 60 —

**Comment by Pessimistress** [comment]
I think setting maxPitch default to 60 is the easiest if we want to accommodate the most use cases. This is also an issue for mapbox-gl v1.x.

Happy to publish a patch if you open a PR.

**Comment by Pessimistress** [comment]
Published v7.0.2
