### ISSUE TITLE
[Bug] The State Management docs links to examples are broken

### ISSUE THREAD

**Issue by reymon359** [visgl/react-map-gl#1723]
### Description

The [State Management docs](https://visgl.github.io/react-map-gl/docs/get-started/state-management) links to examples are broken.

<img width="561" alt="Screenshot 2022-02-06 at 20 31 08" src="https://user-images.githubusercontent.com/31936665/152698123-59f99775-10f8-458a-a25a-9d3a1c223d5a.png">

<img width="588" alt="Screenshot 2022-02-06 at 20 27 43" src="https://user-images.githubusercontent.com/31936665/152697986-47bd5559-1f56-431e-a2ff-d21234334b71.png">
<img width="716" alt="Screenshot 2022-02-06 at 20 27 56" src="https://user-images.githubusercontent.com/31936665/152697988-e83d60c1-9543-4c7a-9073-e1c10549b81b.png">

### Expected Behavior

I expect the links to redirect correctly to the examples

### Steps to Reproduce

Go to [the docs](https://visgl.github.io/react-map-gl/docs/get-started/state-management) and click the links

### Environment

- Framework version: N/A
- Map library: N/A
- Browser: Brave
- OS: macOS Monterey 12.1

**Comment by Pessimistress** [comment]
Thanks for reporting. The links are now fixed.

**Comment by reymon359** [comment]
Thanks to you for fixing them so fast 🚀
