### ISSUE TITLE
[Bug] Popup onClose callback is called twice

### ISSUE THREAD

**Issue by fungiboletus** [visgl/react-map-gl#1725]
### Description

The `onClose` callback is called twice when a Popup is closed.

### Expected Behavior

The callback should be called only once.

### Steps to Reproduce

https://codesandbox.io/s/react-map-gl-boiler-plate-forked-16fiv

Close the popup, observe the two console statements.

### Environment

- Framework version: 7.0.2
- Map library: mapboxgl-13.0.2
- Browser: Safari
- OS: Mac

**Comment by Pessimistress** [comment]
Fixed in v7.0.3

**Comment by fungiboletus** [comment]
Thanks for the quick fix and release 🙂
