### ISSUE TITLE
[Bug] Popup onClose callback is called after onClick callbacks from markers

### ISSUE THREAD

**Issue by fungiboletus** [visgl/react-map-gl#1727]
### Description

When you want to open a Popup from a Marker click, you have to click twice if the Popup is already displayed. This is because the `onClose` callback on the popup is called after the `onClick` callback from anything inside the marker.

### Expected Behavior

If `closeOnClick` is enabled, the `onClose` callback should be called before the `onClick` callbacks.

### Steps to Reproduce

https://codesandbox.io/s/react-map-gl-boiler-plate-forked-tntej?file=/src/index.js

Click on the blue box. You have to click twice to make the popup appear again.

### Environment

- Framework version: 7.0.2
- Map library: mapbox-gl 1.3.12
- Browser: Safari
- OS: Mac

**Comment by Pessimistress** [comment]
I'm not sure I follow. Are you trying to tell the popup to both close (by setting `closeOnClick: true`) and open (by setting state) on click? Why should there be any particular order when this conflicting logic is applied?

**Comment by fungiboletus** [comment]
Yes, I think you understood correctly. I think the order I expected is more common and easier to deal with. I feel like a common use of markers and popups is to open a popup when you click on a marker, and close it if you click on nothing on the map.

If the order is not defined, I guess I could have an ugly hack around the events.

**Comment by Pessimistress** [comment]
The events you subscribed to are not fired by this library. `close` is fired by mapbox-gl and `click` is fired by React. `closeOnClick` is merely a convenience and if you don't like its behavior then you should listen to the click event on the map and handle it yourself.

**Comment by fungiboletus** [comment]
Alright. Do you know how one could implement the same example using `react-map-gl`  ? https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/ 

Listening to the click on the map is not very easy because the onClick callback on the map is called *after* the click callback of the marker. I could hack something using `setTimeout/setImmediate/requestAnimationFrame` to delay the opening of the popup, but that's not very nice.

**Comment by Pessimistress** [comment]
The example you link does not use the Marker control. You should check out Source and Layer components.

**Comment by fungiboletus** [comment]
True. It gives an idea of the behaviour I want to achieve though.

**Comment by thobhanifreddy** [comment]
@fungiboletus Just wondering if you were able to fix this?

**Comment by fungiboletus** [comment]
I don't remember very well, but looking at the current code I did change the logic around opening and closing the popups and it now doesn't use the events from react-map-gl.

**Comment by worc** [comment]
The event firing order is still broken even on react-map-gl@7.0.21. When re-opening a Popup, mapbox-gl will call an onClose handler _just after react-map-gl's popup opening lifecycle completes_. It "looks" like the popup never opens, but really it's just closing immediately after opening.

Reading all the other related threads and best guess is it seems like an issue somewhere between component unmounting and event propagation. It really feels like there's a second onClose call being held over from the previous event lifecycle. So you get a process that looks like: Open-Close-Unmount-_Close_.

That last close is held over until the next time the component is mounted, and you get stuck in a loop: Open-Mount-Render-_Heldover Close_-Unmount-_Holdover Close_...Open-Mount-Render-_Heldover Close_-Unmount-_Holdover Close_...etc

**Comment by codniel** [comment]
This might seem a bit dirty, but I was able to do a workaround to stop triggering the `onClose` callback.

```
return (
    <>
      <Marker
        latitude={latitude}
        longitude={longitude}
      >
        <div
          onClick={e => {
            e.stopPropagation()
            setOpen(true)
          }}
        >
         {... your custom marker here ...}
      </Marker>
      {open && (
        <Popup
          closeOnClick
          closeOnMove
          latitude={latitude}
          longitude={longitude}
          anchor="bottom"
          onClose={() => setOpen(false)}
        >
         {... your custom popup here ...}
        </Popup>
      )}
    </>
)
```

so by adding a div inside our Marker, we can now access the `stopPropagating()` event method on its `onClick`
