### ISSUE TITLE
[Bug] After updating to v7, the map is blank

### ISSUE THREAD

**Issue by mmykhaylov** [visgl/react-map-gl#1731]
### Description

I've updated my pet project to react-map-gl v7 and the map stopped working. The markers and DnD work as expected, but the tiles refuse to load. There are no errors in the console and I've followed the migration guide to the letter.

### Expected Behavior

The map loads the tiles

### Steps to Reproduce

https://codesandbox.io/s/cocky-brahmagupta-jfovg
Enter your mapbox API key and observe

### Environment

- Framework version: react-map-gl@7.0.2
- Map library: mapbox@2.7.9
- Browser: Firefox Dev Edition 97.0
- OS: macOS 12.2

**Comment by Pessimistress** [comment]
The default `mapStyle` has changed to an empty style, see https://visgl.github.io/react-map-gl/docs/upgrade-guide#map
