### ISSUE TITLE
[Bug] cursor is always grab

### ISSUE THREAD

**Issue by jellyedwards** [visgl/react-map-gl#1736]
### Description

Settings the map's `cursor` to `'pointer'` doesn't seem to have any effect and the cursor remains as `grab`.

### Expected Behavior

Map cursor should obey `cursor` property.

### Steps to Reproduce

https://codesandbox.io/s/heuristic-cerf-8mnk0 - it's the custom cursor example but I set cursor to `'pointer'`

### Environment

- Framework version: react-map-gl@7.0.4
- Map library: maplibre-gl
- Browser: Chrome 98.0.4758.82
- OS: Windows 10

**Comment by Pessimistress** [comment]
Fixed in 7.0.6.

**Comment by jellyedwards** [comment]
thanks
