### ISSUE TITLE
[Feat] allow Marker component to accept onClick prop

### ISSUE THREAD

**Issue by dreamorosi** [visgl/react-map-gl#1746]
### Target Use Case

At the moment the `Marker` component supports only `onDrag*` events, this is because the original mapbox-gl implementation doesn't expose a `click` event ([source](https://github.com/visgl/react-map-gl/discussions/1744#discussioncomment-2159245)).

Being able to set an `onClick` event directly on the `Marker` component would allow those who are not interested in creating their own custom pin icon to keep using the Marker component with default svg and make it interactive.

### Proposal

**Current Situation**
```js
<Marker><CustomerDefinedPinIcon onClick={handler}/></Marker>
```

**Proposed API**
```js
<Marker onClick={handleOnClick} color='palevioletred' />
```

**Comment by Pessimistress** [comment]
v7.0.7
