### ISSUE TITLE
[Bug] event.features is undefined (from Map.onClick callback)

### ISSUE THREAD

**Issue by bbar** [visgl/react-map-gl#1753]
### Description

The Map.onClick callback looks like this:

`onClick: (event: MapLayerMouseEvent) => void`

I'm using `<Source>` and `<Layer>` to display GeoJSON data, but when I click a feature, [event](https://visgl.github.io/react-map-gl/docs/api-reference/types#maplayermouseevent).features is undefined.

### Steps to Reproduce

Here's a Code Sandbox. Just enter an api token, click on a feature and take a look in the console.

https://codesandbox.io/s/crazy-breeze-5u8i7t?file=/src/App.js

### Environment

- Framework version: react-map-gl@7.0.6
- Map library: mapbox-gl@2.7.0
- Browser: Version 98.0.4758.80 (Official Build) (x86_64)
- OS: macOS 12.1

**Comment by bbar** [comment]
I left off `interactiveLayerIds`.

In this case, `interactiveLayerIds={['map-location']}`

Everything's working as expected.

**Comment by luskin** [comment]
@bbar that was the problem, thank you
