### ISSUE TITLE
[Feat] Expose MapRef via context in v7

### ISSUE THREAD

**Issue by khmm12** [visgl/react-map-gl#1754]
### Target Use Case

Having an ability to access map instance via context it's easy to create generic purpose hooks and components like clustering or to manipulate the map without passing map instance from the component which directly renders map element to descendants.

<details>
  <summary>Example</summary>

```ts
type MarkersProps = {
  entities: readonly Entity[]
}

function Markers(props: MarkersProps): ReactElement {
  const { entities } = props

  const map = useMap()

  const clusters = useClusters(entities, {
    createPoints,
    mapFeatures,
    reduceFeatures
  })

  const handleClusterExpand = useCallback(
    (lngLat: LngLat, zoom: number) =>
      map.easeTo({
        center: lngLat,
        zoom
      }),
    [map]
  )

  return (
    <>
      {clusters.map(cluster => {
        const [longitude, latitude] = cluster.geometry.coordinates

        return cluster.properties.cluster ? (
          <ClusterMarker longitude={longitude} latitude={latitude} onExpand={handleClusterExpand} />
        ) : (
          <Marker longitude={longitude} latitude={latitude} />
        )
      })}
    </>
  )
}
```

</details>

### Proposal

I suppose, `MapContext` is intended for private usage, so it can't be exposed as the solution.

`MapProvider` + `useMap` are intended to help with multiple maps access. Also `useMap` looks like a hook which is used to access to the current map instance (inside context), but behaves like a hook which is used to access to multiple map instances.

1. [No breaking changes] Introduce `useCurrentMap`
2. [Breaking changes] Rename `MapProvider` and `useMap` to `MapsProvider` and `useMaps` respectively, introduce new `useMap` hook.

**Comment by Pessimistress** [comment]
Thank you for bringing up this use case.

Alternatively, maybe we can work this functionality into the `useMap` hook:

- If a `MapProvider` is found, returns a dict of map refs in the context, plus a field `__current` which references the containing map
- If a `MapProvider` is not found, but called inside a descendent of a map, returns `{__current: MapRef}`
- Otherwise returns `null`

This way your component can always use `useMap().__current` regardless of the context.

**Comment by khmm12** [comment]
@Pessimistress 

I also had same thoughts. But from one side I'd avoid prefixed properties, because due to conventions they may seem either private or properties with which should be careful. From other side with property `current` there is should be runtime checking to avoid reserved identifier usage.

**Comment by Pessimistress** [comment]
See API proposal in PR: https://github.com/visgl/react-map-gl/pull/1763/files#diff-aaec30e4b70443802cd89a0e8e694652a694bfe407dc451f91cec1ce36f53ccb

**Comment by Pessimistress** [comment]
v7.0.8
