### ISSUE TITLE
[Bug] mapStyle crashing after update to react-map-gl v7.0

### ISSUE THREAD

**Issue by eduardomarr** [visgl/react-map-gl#1767]
### Description

i updated `react-map-gl` v6 to v7 and my mapstyle crashs when i move the viewport or zoom.

git to explain what's breaking:

https://user-images.githubusercontent.com/24718475/155229864-b8b9395f-860f-4480-aa52-6af5d770a3e6.gif

### Steps to Reproduce

```
 <Map
      {...viewport}
      initialViewState={{
        longitude: -47.56435063220633,
        latitude: -23.3638228918379,
        zoom: 3.5,
        bearing: -62.4
      }}
      minZoom={13}
      style={{ width: '60vw', height: '50vh' }}
      mapboxAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
      mapStyle={process.env.REACT_APP_MAPBOX_STYLE}
    />
    ```

### Environment

- Framework version: "react-map-gl": "^7.0.7",
- Map library: "mapbox-gl": "^2.6.1",
- Browser: Firefox, Chrome
- OS: macOS Monterey

**Comment by Pessimistress** [comment]
I'm not sure what you mean by "crashes", Map styles are not handled by this library and you should consider report any rendering issue to mapbox-gl.

**Comment by eduardomarr** [comment]
@Pessimistress the bug started after the update.
