### ISSUE TITLE
[Bug] Mapbox JS 2 Set terrain makes symbol layer and labels afloat at high pitch level

### ISSUE THREAD

**Issue by ShadowSonata** [visgl/react-map-gl#1775]
### Description

I was expecting to use mapbox terrain dem to show elevation at high pitch and found out the base map labels and my symbol layers were both off. Tried with the native mapbox JS library and everything works fine.

Remove `terrain` props from Map will resolve this issue.

This is using react-map-gl@7.0
![image](https://user-images.githubusercontent.com/28591411/155530308-69f4ed9c-bb6e-4c5d-bb54-0adad7ce8cf9.png)

This is using native mapbox JS with a simple wrapper in React
![image](https://user-images.githubusercontent.com/28591411/155530648-8bade958-57ac-412a-99e8-6aa744dd3247.png)

(* might not be too obvious but please compare the street names above, the first one has the labels floating in the air)

### Expected Behavior

Labels should be on the ground

### Steps to Reproduce

The one used with react-map-gl

https://codesandbox.io/s/react-map-gl-boiler-plate-forked-leu63d

The one used with native mapbox gl

https://codesandbox.io/s/react-map-gl-boiler-plate-forked-pb0z0w

**Need a mapbox token, add it to line 7/6**

### Environment

- Framework version: react-map-gl@7.0.2 & 7.0.7
- Map library: mapbox-gl@2.7.0
- Browser: Microsoft Edge 97.0; Safari 15.3
- OS: MacOS 12.2.1

**Comment by Pessimistress** [comment]
Thanks for the report. Fixed in 7.0.8.
