### ISSUE TITLE
[Bug] Mapboxgl does not dynamically render markers on a map

### ISSUE THREAD

**Issue by stebbinscp** [visgl/react-map-gl#1794]
### Description

https://codesandbox.io/s/lucid-leakey-hckm2k?file=/src/App.js

As seen in the code sandbox above, the when data is mapped into a function or const to create a marker for each piece of data, the markers are not created. However, when the data is inputted manually and written into every marker, it is rendered correctly

### Expected Behavior

6 bubbles of various size rendered on the map

### Steps to Reproduce

https://codesandbox.io/s/lucid-leakey-hckm2k?file=/src/App.js

### Environment

- Framework version:
- Map library:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
Your map function does not return anything.

```js

  {fullData.map((datum) => {
     // should be return MakeMarker(...)
       MakeMarker({ datum, pixelScale });
      })}
```

Issues are for bugs in the library, not your own application. Please use Discussions if you need help debugging.
