### ISSUE TITLE
[Bug] Cannot view full map when map as small dimensions

### ISSUE THREAD

**Issue by kaplantm** [visgl/react-map-gl#1795]
### Description

This is a bit similar to https://github.com/visgl/react-map-gl/issues/1134, but the responses their did not provide a clear solution for me.

I need to have a map size 280x160 pixels showing the whole globe, but i'm not able to do this - some of the globe is clipped.

### Expected Behavior

Should be able to zoom out to see entire world. Zoom should behave similar to other mapbox implementations.

### Steps to Reproduce

Code sandbox: https://codesandbox.io/s/cranky-dawn-kgvr7h?file=/src/App.js

### Environment

- Framework version: 7.0.9
- Map library: 
- Browser: Chrome
- OS: Mac

**Comment by Pessimistress** [comment]
react-map-gl is based on mapbox-gl, not Mapbox Studio. The wrapper does not handle any user input or impose its own zoom limitations. You can see the same behavior on this mapbox-gl example: https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

You may consider reporting this to the Mapbox GL JS repo instead.

**Comment by kaplantm** [comment]
Thanks, I [recreated this issue in the Mapbox GL JS repo](https://github.com/mapbox/mapbox-gl-js/issues/11575).
