### ISSUE TITLE
Moving layer of marker when map is bounding[Bug]

### ISSUE THREAD

**Issue by Pisyukaev** [visgl/react-map-gl#1805]
### Description

Hi there!
I trying to use `maxBounds` prop of Map component and it is work for the map, but it is don't work for layer of markers. I have no idea why...
![Маркер](https://user-images.githubusercontent.com/18371315/159018463-f36ff7a9-47f3-4ab0-b6c0-16210ada1477.gif)

### Expected Behavior

I expected layer of marker have been used `maxBounds` prop too.

### Steps to Reproduce

I make an example https://codesandbox.io/s/mapbox-marker-644o4u?file=/src/App.tsx

### Environment

- Framework version: 6.1.18(and older or younger)
- Map library: 1.13.2
- Browser: Chrome 99.0.4844.74 
- OS: Windows 10

**Comment by Pisyukaev** [comment]
Thanks! It's works if `bounds` small, for example `[[-10, -85], [10, 85]]`. For `bounds` equals `[[-179, -85], [179, 85]]` it's dosen't work =(( Maybe i do what wrong, I don't know...
And I found interesting moment: if draggble map longest to side, the map 'jumpimg' on other side. Attatched gif.
![Jumping map](https://user-images.githubusercontent.com/18371315/159117080-6f4d0001-bcdd-4bc3-9401-d624cb710607.gif)

**Comment by Pessimistress** [comment]
That's the same issue tracked by #1611
