### ISSUE TITLE
[Bug] Since react-map-gl version:^7.0.9 the map does not resize (always) when its container resizes

### ISSUE THREAD

**Issue by Derryrover** [visgl/react-map-gl#1807]
### Description

When the user uses the resize handle on the green outline box to make the green outline box smaller then the purple outline box naturally grows.
But the map that should fill 100% of its container (the purple outline box) does not grow together with the purple outline box.

See example repo here:
https://github.com/nens/react_map_gl-resize_bug

import ReactMapGL from 'react-map-gl';
import 'mapbox-gl/dist/mapbox-gl.css';

export const mapBoxAccesToken = "__your_token";

function App() {
  return (
    <div 
      className="App" 
      style={{
        height: "600px", 
        display: "grid", 
        gridTemplateColumns: "auto 1fr", 
        overflow: "hidden"
      }}
    >
      <div 
        style={{
          width: "120px", 
          resize: "horizontal", 
          overflow: "auto", 
          borderStyle: "solid", 
          borderWidth: "2px", 
          borderColor: "lime"
        }}
      />
      <div 
        style={{
          borderStyle: "solid", 
          borderWidth: "2px", 
          borderColor: "purple"
        }}
      >
        <ReactMapGL
          style={{
            width:"100%",
            height: "100%",
          }}
          mapboxAccessToken={mapBoxAccesToken}
          mapStyle={"mapbox://styles/nelenschuurmans/ck8sgpk8h25ql1io2ccnueuj6"}
        />
      </div>
    </div>
  );
}

export default App;
_______________________________________________________

{
  "name": "react_map_gl-resize_bug",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.2",
    "@testing-library/react": "^12.1.4",
    "@testing-library/user-event": "^13.5.0",
    "mapbox-gl": "^2.5.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-map-gl": "^7.0.9",
    "react-scripts": "5.0.0",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

### Expected Behavior

The map should always fit the purple outline container.

### Steps to Reproduce

See description

### Environment

- Framework version: react-map-gl ^7.0.9 , 
- Map library: mapbox-gl: ^2.5.0
- Browser: chrome, firefox
- OS: Ubuntu 20.04.4 LTS

### Logs

not that I can see

**Comment by Pessimistress** [comment]
Since 7.0 react-map-gl no longer implement its own layout logic. The behavior is consistent with the mapbox-gl library. mapbox-gl only auto resizes with  the window `resize` event.

You can use another library such as `react-virtualized-auto-sizer` to watch for div resize and call `mapRef.resize()` yourself.

**Comment by Derryrover** [comment]
Hi,

Thanks for the reaction and for building / maintaining this useful library!

I implemented a working solution with "react-virtualized-auto-sizer": "^1.0.6", and it works correct,
but the resize happens with only a few frames per second causing a "shaky" effect.
This was not the case previously with react-map-gl v6 own implementation.

I can agree with the logic of only implementing "original" mapboxGLJS features and not adding more logic.
Just for this usecase I would argue the old  solution in v6 was was easier on the eyes.

Or is there maybe something I could do better still?
Below my current solution.

kr Tom

<AutoSizer
        onResize={()=>{
          if (
            _mapRef && _mapRef.current && _mapRef.current.getMap 
          ) {
            window.setTimeout(()=>{
              const map: mapboxgl.Map = _mapRef.current.getMap();
              map.resize();
            },0); 
          }
        }}
      >
      {({height, width}) => (

      
      <ReactMapGL
        {...viewport}
        style={{
          width: width,
          height:height,
        }}
        ref={_mapRef}
....................

**Comment by Pessimistress** [comment]
https://codesandbox.io/s/inspiring-currying-w7rhvy?file=/src/index.js

**Comment by Derryrover** [comment]
Thanks, yes works. Turned out some existing functions and effects in my react component made the shacky effect worse, but runs smooth enough now !
