### ISSUE TITLE
[Feat] Custom control positions

### ISSUE THREAD

**Issue by remotezygote** [visgl/react-map-gl#1822]
### Target Use Case

Now that controls are the way to do overlays, it would be nice if, like the base mapbox lib, this library supported custom control positions. They exist at `map._controlPositions` and can be modified. Currently this library breaks when custom positions are used.

### Proposal

I would suggest setting the ControlPosition type to just be `String` rather than a map of possible values (since the possible values are not, in fact, static).

**Comment by Pessimistress** [comment]
Well, you are technically hacking it when you mutate `map._controlPositions`. I do think the types should follow the [documentaed public API](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addcontrol) only.

**Comment by remotezygote** [comment]
How do you suggest one put an overlay where they would like it then?

**Comment by remotezygote** [comment]
Here's where I've landed on this after thinking about your answer: the types should reflect the functionality of the underlying library. The underlying library is built to handle this (I believe intentionally), and so should this library.

**Comment by Pessimistress** [comment]
> How do you suggest one put an overlay where they would like it then?

Not sure what you mean by "overlay", but if you are referring to something that covers the whole canvas, I believe you can just add a div to the top-left container with the appropriate width and height.

> The underlying library is built to handle this (I believe intentionally)

Any underscored class fields are not intended for public use. If you think the base library should support this (or make it clear that they already do), you should ask Mapbox GL JS to add this to their API documentation.

**Comment by remotezygote** [comment]
Fork it is. Sucks.
