### ISSUE TITLE
[Bug] Unexpected token with create-react-app 4

### ISSUE THREAD

**Issue by thaddmt** [visgl/react-map-gl#1828]
### Description

When using `react-map-gl@7` with a create-react-app 4 application I am receiving errors about an unexpected token. I believe this is caused by the use of the optional chaining operator in the esm module distributed by `react-map-gl`.

Some quick searching shows some potential solutions to this include upgrading to create-react-app 5 or ejecting the application and transpiling `react-map-gl` but both solutions seem less than ideal.

```
Failed to compile.

./node_modules/react-map-gl/dist/esm/components/use-control.js 12:46
Module parse failed: Unexpected token (12:46)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
|     if (!map.hasControl(ctrl)) {
>       map.addControl(ctrl, (opts || onRemove)?.position);
|     }
|
```

### Expected Behavior

App should not fail to compile.

### Steps to Reproduce

1. Run create-react-app 4 (`create-react-app ./ --scripts-version 4.0.3`)
2. Install `react-map-gl@7`
3. Try importing map (`import Map from "react-map-gl"`)

### Environment

- Framework version: react-map-gl@7.0.10
- Map library: maplibre-gl@1
- Browser: Chrome 99.0
- OS: macOS 12.2.1

**Comment by Pessimistress** [comment]
This is discussed in https://github.com/visgl/react-map-gl/discussions/1791. The current transpilation settings intend to give the user the most control over the browser target. You can optionally import from `react-map-gl/dist/es5` if you are unable to change the build configuration.
