### ISSUE TITLE
[Bug] - Adding the sky to the map doesn't work when using Layers.

### ISSUE THREAD

**Issue by trainaterra** [visgl/react-map-gl#1832]
### Description

I'm using layers to apply the sky.
Flow example terrain: https://visgl.github.io/react-map-gl/examples/terrain

### Steps to Reproduce

This is my code. https://codesandbox.io/s/admiring-lamport-iqog5l?file=/src/App.js

### Environment

- Framework version: react-map-gl@7.0.1
- Map library: mapbox-gl@2.8.0
- Browser: ChromeVersion 100.0.4896.88 (Official Build) (x86_64)

**Comment by AnasChatoui** [comment]
<Source
          id="mapbox-dem"
          type="raster-dem"
          url="mapbox://mapbox.mapbox-terrain-dem-v1"
          tileSize={512}
          maxzoom={14}
        >
        <Layer {...skyLayer} />
        </Source>

**Comment by Pessimistress** [comment]
Fixed in v7.0.11

**Comment by trainaterra** [comment]
Thanks for everyone's support. 🙇
