### ISSUE TITLE
[Bug] Building extrusions render floating in the sky

### ISSUE THREAD

**Issue by designmatty** [visgl/react-map-gl#1835]
### Description

I'm using the Mapbox provided building extrusion layer in my custom map style. When the buildings are rendered on the map they appear to float above the surface instead of on the ground at their correct elevation. It becomes especially apparent once you change your viewport's pitch to 85, though it occurs at every pitch.

**Preview**
<img width="587" alt="image" src="https://user-images.githubusercontent.com/1928955/164282804-954e5b5b-3ee4-4e0e-b2b1-7f621d595779.png">

### Expected Behavior

**This is how the buildings render using the mapbox-gl-js api.**
<img width="928" alt="image" src="https://user-images.githubusercontent.com/1928955/164282729-6a4f2403-72fe-4169-89d1-4bd92f78e565.png">

### Steps to Reproduce

- [react-map-gl CodeSandbox](https://codesandbox.io/s/react-mapbox-27q3it)
- [mapbox-gl-js CodeSandbox](https://codesandbox.io/s/js-mapbox-i4w199?file=/index.js)
- [Custom mapbox style](https://api.mapbox.com/styles/v1/mwilliamsumbra/ckmqi0fdu14dr18syvfscw2nx.html?title=copy&access_token=pk.eyJ1IjoibXdpbGxpYW1zdW1icmEiLCJhIjoiY2trZm1qMThzMG82MjJ1cXR0NXN3NjNmeSJ9.LLkpB_D9SijsC8rB9v8jLg&zoomwheel=true&fresh=true#16.44/37.641451/-122.442503/326.9/85) used in both examples

There may be some rare occasions where the buildings will render normally (I haven't been able to regularly replicate this). In these circumstances, you may need to either zoom way out and back in, or navigate to an area with varying elevation.

### Environment

- Framework version: react-map-gl@7.0.10
- Map library: mapbox-gl@2.8.1
- Browser: Chrome 100.0.4896.88
- OS: Mac OS 12.3.1

**Comment by Pessimistress** [comment]
Try 7.0.11.

**Comment by designmatty** [comment]
Looks like it's fixed in 7.0.11. 👍
