### ISSUE TITLE
[Bug] Only number is a valid GeoJSON feature id type?

### ISSUE THREAD

**Issue by omasback** [visgl/react-map-gl#1839]
### Description

I have an onMouseEnter event listener on a map with a GeoJSON data source. When I give `string` id's to the features in the GeoJSON, the feature id's in the event listener are `undefined`. When I give `number` id's to the features in the GeoJSON, the id's are defined as the number I assigned. According to GeoJSON type definitions I'm using (@types/geojson), both strings and numbers should be valid

### Expected Behavior

Both strings and numbers should be valid feature id's

### Steps to Reproduce

Assign string feature id's and check them in an event handler

### Environment

- Framework version:  "react-map-gl": "^7.0.10",
- Map library: "mapbox-gl": "^2.8.1",
- Browser: Chrome latest
- OS: Mac latest

**Comment by Pessimistress** [comment]
This library is a wrapper of mapbox-gl. It does not handle any data type and styling on its own. You need to ask in the mapbox repo.
