### ISSUE TITLE
[Bug] Popup opens a closes inmediatelly

### ISSUE THREAD

**Issue by iserranoe** [visgl/react-map-gl#1847]
### Description

I want to show a popup when clicking on a marker; however, I can't see the popup as it opens and closes inmediately. I included a console.log in the onOpen and onClose callbacks to ensure the popup is actually being called. I saw this issue has been dealt in issue https://github.com/visgl/react-map-gl/issues/1825, but as it's closed I'd like to open again.

### Expected Behavior

I expect to see the popup when clicking on the market and removing the popup when clicking on the cross. 

### Steps to Reproduce

Here is my code, please fill in your own mapbox token: 
https://codesandbox.io/s/angry-ramanujan-diu22b?file=/src/App.js

### Environment

- Framework version: react@18.0.0
- Map library: react-map-gl@7.0.11, mapbox-gl@2.4.1
- Browser: Mozilla
- OS: Ubuntu 18.04.6 LTS - WSL2

### Logs

The are no error or warnings...

**Comment by Pessimistress** [comment]
https://github.com/visgl/react-map-gl/blob/bdfcfd2d6cfdc641cddb5337d7ed477e5c3c28d5/examples/controls/src/app.tsx#L31-36

**Comment by iserranoe** [comment]
Ok, thank you! It's working now.

**Comment by worc** [comment]
Unexpected, undocumented behavior looks like a bug to me.

**Comment by berkayoruc** [comment]
This solution is working for marker. Because markers are HTMLElements. If you try on layer, same behavior is continue

My code:
There is useState;
`const [popupInfo, setPopupInfo] = useState();`

onClick event is created with useCallBack;
```
const onClick = useCallback((e) => {
    const feature = e.features && e.features[0];
    if (feature) {
      e.target.flyTo({
        center: feature.geometry.coordinates,
        zoom: 15,
        pitch: 60,
        bearing: 40,
      });
      setPopupInfo({
        lon: feature.geometry.coordinates[0],
        lat: feature.geometry.coordinates[1],
        ...feature.properties,
      });
    }
  });
```
Finally onClick event is defined to map;
```
<Map
      ...
      mapStyle="mapbox://styles/mapbox/streets-v12"
      interactiveLayerIds={["stations"]}
      cursor={cursor}
      onMouseEnter={onMouse}
      onMouseLeave={onMouse}
      onClick={onClick}
      ...
```

**Comment by niva-dev** [comment]
@berkayoruc Issue with Layer fixes with `closeOnClick={false}` for Popup.
