### ISSUE TITLE
[Bug] Clicking on <Marker/> to open <Popup/> causes terrain layer to disappear

### ISSUE THREAD

**Issue by rmmartin02** [visgl/react-map-gl#1852]
### Description

Trying to combine these 2 examples:
https://github.com/visgl/react-map-gl/tree/7.0-release/examples/terrain
https://github.com/visgl/react-map-gl/tree/7.0-release/examples/controls

To display popups on a terrain map. The markers and popups appear fine, but when clicking a marker to open a popup the 3d terrain disappears and the map becomes flat. Terrain reappears if you pan, rotate, or zoom. It does NOT reappear if I close the popup or click on a different marker.

### Expected Behavior

Popup appears and terrain remains 3d

### Steps to Reproduce

Click on the blue marker

https://codesandbox.io/s/cranky-nova-x72xos?file=/src/index.js

### Environment

Framework version: react-map-gl@7.0.11
Map library: mapbox-gl@2.8.2
Browser: Chrome 100.0.4896.127
OS: iOS 12.0.1

### Logs

No errors or warnings

**Comment by Pessimistress** [comment]
This is fixed in 7.0.12.
