### ISSUE TITLE
[Bug] React v18 doesn't support implicit children for <MapProvider>

### ISSUE THREAD

**Issue by slaymance** [visgl/react-map-gl#1858]
### Description

The release of React v18 was accompanied by a major version release of the `@types/react` package which provides React typings in a Typescript application. In the latest version of `@types/react`, the `children` property in `React.FunctionalComponent` (or `React.FC` for short) is no longer implicit. This causes a type error when using the `<MapProvider>` component in a Typescript application that uses React v18.

### Expected Behavior

A Typescript React v18 application using `<MapProvider>` with child components should build without error.

### Steps to Reproduce

See the following code sandbox which uses `<MapProvider>` in a Typescript React v18 application:
https://codesandbox.io/s/practical-dijkstra-x3zu25?file=/src/App.tsx

Hovering over `<MapProvider>` shows the type error in question.
![Screen Shot 2022-05-16 at 10 11 07](https://user-images.githubusercontent.com/26472139/168647070-1615b447-2aea-4fd8-bbaa-21deda8f06b1.png)

### Environment

- Framework version: react-map-gl@7.0.12
- Map library: any
- Browser: Chrome 101.0
- OS: macOS Monterey 12.3.1
- React version: react@18.1.0
- @types/react version: @types/react@18.0.0

### Logs

```
TS2559: Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes'.
    4 | function Root() {
    5 |   return (
  > 6 |     <MapProvider>
      |      ^^^^^^^^^^^
    7 |       <Map id="myMapA" />
    8 |       <Map id="myMapB" />
    9 |       <NavigateButton />
```

**Comment by Pessimistress** [comment]
Fix landed in v7.0.13.
