### ISSUE TITLE
[Bug][React 18] Source "source-id" cannot be removed while layer "layer-id" is using it

### ISSUE THREAD

**Issue by fungiboletus** [visgl/react-map-gl#1861]
### Description

It is not possible to remove a source and its layer in React 18.

### Expected Behavior

It should be possible to remove a source.

### Steps to Reproduce

Check https://codesandbox.io/s/xenodochial-carson-itfpu5?file=/src/index.js

It uses React `18.1.0` and ReactMapGL `7.0.12`. You can observe the error in the console. The sandbox uses a local map style and react.strictmode to highlight the bug immediately, but the bug is also present when you try to remove a source from an user action.

### Environment

- Framework version: react-amp-gl@7.0.12
- React: `18.1.0` **⬅️ it's important**
- Map library: mabox-gl@2.7.0 and earlier
- Browser: Tested on Safari and Edge
- OS: Mac

### Logs

Error: Source "source-id" cannot be removed while layer "layer-id" is using it.

**Comment by Pessimistress** [comment]
Just to clarify, by "in React 18" do you mean "in strict mode in React 18"?

**Comment by fungiboletus** [comment]
> Just to clarify, by "in React 18" do you mean "in strict mode in React 18"?

No, I can reproduce the issue without the strict mode. I used the strict mode in my reproduction case because the bug it triggered very easily in strict mode but I can add a reproduction case without the strict mode as well if you prefer.

**Comment by Pessimistress** [comment]
This should be fixed by v7.0.14.

**Comment by fungiboletus** [comment]
Thanks a lot! I confirm it is fixed.
