### ISSUE TITLE
[Bug] Adding mapbox-gl styles hides html overlay

### ISSUE THREAD

**Issue by cherealnice** [visgl/react-map-gl#1867]
### Description

Hi,

I have been working with an HTML overlay and trying to figure out why it wasn't showing up. I finally realized that the issue is triggered when I add in the mapbox-gl styles. I tried both with ES6 import and with stylesheet link, and both cause the issue. Is this a react-map-gl issue?

### Expected Behavior

HTML overlays should not disappear when adding mapbox-gl styles.

### Steps to Reproduce

NOTE: You need to add a token to `TOKEN`

Code sandbox: https://codesandbox.io/s/optimistic-pond-56i1xz?file=/src/App.tsx

Notice that when the mapbox-styles are added (they are currently commented out at the top of App.tsx), the HTML overlay disappears. 

### Environment

- Framework version: react-map-gl@7.0.12
- Map library: mapbox-gl@2.8.2
- Browser: Brave 1.36.117
- OS: OSX 12.0.1

**Comment by Pessimistress** [comment]
Remove `position: 'absolute'` from your overlay content then you can see it's at the top right corner. Controls by default are added to the top right, see [addControl](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addcontrol).

Set `position` to `'top-left'` if you want it to appear on the top left: https://visgl.github.io/react-map-gl/docs/api-reference/use-control#signature

The bug template is for reporting bugs in the library. Please use discussions if you need help debugging your own application.
