### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by janschaible** [visgl/react-map-gl#1869]
### Description

when passed as a prop mapboxAccessToken does not work
only when the token is set as env REACT_APP_MAPBOX_ACCESS_TOKEN the token is accepted

### Steps to Reproduce

import './App.css';
import { useRef } from 'react';
import Map from 'react-map-gl';

const initialViewState = {
  latitude: 37.7751,
  longitude: -122.4193,
  zoom: 11,
  bearing: 0,
  pitch: 0
};

function App() {
  const mapRef = useRef()

  return (
    <Map
      ref={mapRef}
      initialViewState={initialViewState}
      style={{width: 600, height: 400}}
      mapStyle="mapbox://styles/mapbox/streets-v9"
      mapboxAccessToken='valid token in here'
    />
  );
}

export default App;

### Environment

- Framework version: react-map-gl@7.0.13
- Browser:firefox 100.0.2
- OS:ubuntu 22.04

**Comment by Pessimistress** [comment]
Please create a code sandbox that reproduces your issue.
