### ISSUE TITLE
[Bug] GeolocateControl doesn't change its icon after rejecting location

### ISSUE THREAD

**Issue by uig-julia** [visgl/react-map-gl#1870]
### Description

https://docs.mapbox.com/mapbox-gl-js/example/locate-user/

In this example when user rejects using location GeolocateControl changes icon and get blocked immediately 

When using your package I have to refresh page to get my GeolocateControl blocked

### Expected Behavior

Icon changes and button gets blocked

### Steps to Reproduce

https://codesandbox.io/s/zealous-stallman-5riomv

1. Open in new tab (without rejected/accepted location permission)
2. Click on GeolocateControl
3. Reject getting your location
4. Icon on control doesn't change
5. Refresh page -> icon is changed

### Environment

- Framework version: react-map-gl@7.0.2
- Map library: mapbox-gl@2.7.1
- Browser: Chrome Version 101.0.4951.64 (Official Build) (arm64)
- OS: macOS 12.1

**Comment by Pessimistress** [comment]
The mapbox example that you link to has `trackUserLocation` set to `true`. If you do the same in your sandbox it will show the same behavior.

The GeolocateControl is just a wrapper of the native class. It does not implement any tracking or UI logic on its own.
