### ISSUE TITLE
[Bug] width/height missing in viewState in v7

### ISSUE THREAD

**Issue by SiiiTschiii** [visgl/react-map-gl#1874]
### Description

When upgrading from react-map-gl 6.1.2 to 7.0.15 I noticed that viewState (former viewport) does not set the width and height fields anymore. 

Example:
`viewState: {
bearing: 0
latitude: 37.748139987393245
longitude: -96.56619495616025
padding: {top: 0, bottom: 0, left: 0, right: 0}
pitch: 0
zoom: 3
}
`

I am not sure if this is a bug or expected changes with the upgrade to v7. However for my use case, which worked with v6.1.2, I require the height and width of the map in order to compute a bounding box for server side clustering. e.g. I want to be able to do:

```
      import {getBounds} from '@math.gl/web-mercator';
      import {WebMercatorViewport} from '@math.gl/web-mercator';
      ...
      const viewport = new WebMercatorViewport(viewState);
      const bounds = getBounds(viewport);
```
but for this to work WebMercatorViewport expects width and height field to be part of viewState. 

### Expected Behavior

`viewState: {
width: 900,
height: 400,
latitude: 37.748139987393245
longitude: -96.56619495616025
zoom: 3
...
}
`

### Steps to Reproduce

v7.0.15:
* Use https://github.com/visgl/react-map-gl/tree/v7.0.15/examples/clusters
* Add your MAPBOX_TOKEN in `src/app.tsx`
* Add the following or something equivalent to inspect the viewState `src/app.tsx`: `Line 48: onMove={(evt) => console.log(evt.viewState)}`

v6.1.2:
* Run https://github.com/visgl/react-map-gl/tree/v6.1.2/examples/clusters
* Add your MAPBOX_TOKEN in `src/app.js`
* Inspect viewport in Chrome dev tool REACT component view or also print it with `onViewportChange=(viewport) => console.log(viewport)}`.

### Environment

- Framework version: npm 8.1.1
- Map library: v7.0.15
- Browser: Chrome Version 101.0.4951.64 (Official Build) (64-bit)
- OS: Linux Ubuntu 20.04.4

**Comment by Pessimistress** [comment]
This is not a bug, see https://visgl.github.io/react-map-gl/docs/api-reference/types#viewstate

You should use `mapRef.current.getBounds()`.

**Comment by SiiiTschiii** [comment]
Thanks for your prompt answer. This is what I need. Just a small correction for other people stumbling over it. It is:
```
mapRef.current.getMap().getBounds()
```
