### ISSUE TITLE
[Bug] Typings for ViewState Require all parameters

### ISSUE THREAD

**Issue by jh0274** [visgl/react-map-gl#1881]
### Description

Using the type ViewState from react-map-gl results in VScode errors because all parameters are required.  

export type ViewState = {
  /** Longitude at map center */
  longitude: number;
  /** Latitude at map center */
  latitude: number;
  /** Map zoom level */
  zoom: number;
  /** Map rotation bearing in degrees counter-clockwise from north */
  bearing: number;
  /** Map angle in degrees at which the camera is looking at the ground */
  pitch: number;
  /** Dimensions in pixels applied on each side of the viewport for shifting the vanishing point. */
  padding: PaddingOptions;
};

### Expected Behavior

I don't believe that bearing/pitch/padding should be required parameters

### Steps to Reproduce

import ViewState as type and try to pass it as a prop with an initial state that only defines longitude/latitude/zoom parameters

### Environment

- Framework version: Remix
- Map library: maplibre
- Browser: Brave
- OS: Monterey

### Logs

Argument of type '{ longitude: number; latitude: number; zoom: number; }' is not assignable to parameter of type 'ViewState | (() => ViewState)'.
  Type '{ longitude: number; latitude: number; zoom: number; }' is missing the following properties from type 'ViewState': bearing, pitch, paddingts(2345)

**Comment by Pessimistress** [comment]
This is not a bug. The props `longitude`, `latitude`, `pitch` etc. on the Map component are all optional. Do not use `viewState` if you do not wish to control all aspects of the camera. Follow examples in http://visgl.github.io/react-map-gl/docs/get-started/state-management.

**Comment by jh0274** [comment]
@Pessimistress Thank you! I know understand TypeScript better than I used to.
