### ISSUE TITLE
[Bug] Custom overlay example does not work when used in expo app

### ISSUE THREAD

**Issue by igor-spare** [visgl/react-map-gl#1884]
### Description

I was playing with [Custom Overlay example](https://github.com/visgl/react-map-gl/tree/master/examples/custom-overlay). However the container appears to be below the map when using in Expo project. It is seems like a bug here.

<img width="1458" alt="Screen Shot 2022-06-09 at 12 20 09 PM" src="https://user-images.githubusercontent.com/100310216/172927285-e3810012-0d91-4a21-8287-e99b2bb2ceef.png">

### Expected Behavior

I expected the same behavior in Expo applications as in plain React applications when using a browser to launch the Expo app

### Steps to Reproduce

1. Create expo project using the following [guideline](https://docs.expo.dev/get-started/create-a-new-app/)  and running `expo init my-app` then `cd my-app`
2. Copy paste files from [this example](https://github.com/visgl/react-map-gl/tree/master/examples/custom-overlay) https://github.com/visgl/react-map-gl/blob/master/examples/custom-overlay/src/app.tsx 
https://github.com/visgl/react-map-gl/blob/master/examples/custom-overlay/src/custom-overlay.tsx
https://github.com/visgl/react-map-gl/blob/master/examples/custom-overlay/src/control-panel.tsx
https://github.com/visgl/react-map-gl/blob/master/examples/.data/us-election-2016.json
3. Run `npm i`
4. Run `expo start`

### Environment

- Framework version: react-map-gl@7.0.0
- Map library: mapbox-gl@2.0.0
- Browser: Chrome 102.0.5

**Comment by Pessimistress** [comment]
Can you upgrade to the latest release? There have been multiple fixes regarding terrain.

**Comment by igor-spare** [comment]
Thank you for the quick response!
Here is the package.json. Seems like the  "react-map-gl": "^7.0.15" is the last one.
```
{
  "name": "expomapcheck",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~45.0.0",
    "expo-status-bar": "~1.3.0",
    "react-dom": "17.0.1",
    "react-native": "0.68.2",
    "react-native-web": "0.17.7",
    "d3-shape": "^3.1.0",
    "react": "^17.0.0",
    "react-map-gl": "^7.0.15",
    "mapbox-gl": "^2.7.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.66.13",
    "typescript": "~4.3.5"
  },
  "private": true
}
```

**Comment by Pessimistress** [comment]
https://visgl.github.io/react-map-gl/docs/get-started/get-started#styling
