### ISSUE TITLE
[Bug] Terrain makes camera shake

### ISSUE THREAD

**Issue by vincent-lecrubier-skydio** [visgl/react-map-gl#1885]
### Description

The official mapbox terrain example allows to pan the camera around smoothly:

https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/

But the react-map-gl example makes the camera shake, following the terrain:

https://visgl.github.io/react-map-gl/examples/terrain

### Expected Behavior

No shaking when panning above terrain, like in https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/

### Steps to Reproduce

Go on https://visgl.github.io/react-map-gl/examples/terrain and move the map

### Environment

- Framework version:
- Map library:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
This should be fixed in 7.0.16.
