### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by marksmall** [visgl/react-map-gl#1886]
### Description

When adding any `Control` to a DeckGL/Map setup, I am seeing an error in the console

```
TypeError Cannot destructure property 'mapLib' of 'object null' as it is null.
```

### Expected Behavior

I expect to see a map, with whatever `Control`, I use, displayed on the map, in the location specified.

### Steps to Reproduce

You can see a [codesandbox](https://codesandbox.io/s/deck-gl-mapbox-example-jx5uw6) highlighting the problem experienced. Just Uncomment any `Control` and it's import, refresh the view and you will see the error.

### Environment

- Framework version: react-map-gl@7.0.15
- Map library: deck.gl@8.7.11
- Browser: Chromium 102.0.5005.61
- OS: Debian Linux (SID)

### Logs

```
TypeError Cannot destructure property 'mapLib' of 'object null' as it is null.
```

**Comment by Pessimistress** [comment]
v7 does not work with `DeckGL`'s `ContextProvider`, see https://visgl.github.io/react-map-gl/docs/upgrade-guide#upgrading-to-v70

**Comment by marksmall** [comment]
Sorry @Pessimistress , you've closed this before I had a chance to clarify. 

Are you saying we cannot use `react-map-gl v7` with `deck.gl 8.7`? The sandbox had some commented out code, so easy to think the `ContextProvider` was being used, however, that is not true, so had nothing to do with the error I was reporting. I had already looked at that upgrade guide and was the reason I had commented out the `ContextProvider`. I have boiled down the sandbox to just the code to highlight my problem.

**Comment by marksmall** [comment]
Okay, for any others that may come across this, having played around with it some more it does look like in fact the 2 versions don't work together. When `ContextProvider` was stated, I read that as the `MapProvider`, which I had commented out. Downgrading `react-map-gl` to v6.1.19 did indeed let me use all the controls I was after.
