### ISSUE TITLE
[Bug] v7 is incompatible with react-map-gl-draw 1.0.3

### ISSUE THREAD

**Issue by jsancho** [visgl/react-map-gl#1892]
### Description

When using version `7.0.15` with `react-map-gl-draw @ 1.0.3` the map fails to render and crashes with a 
>TypeError: Cannot read properties of undefined (reading 'Consumer')

Here's a sandbox with the minimal steps to reproduce.
https://codesandbox.io/s/nostalgic-framework-pyfqer

I originally reported the issue on the react-map-gl-draw repo.
Since I've also noticed that when downgrading react-map-gl to a v5/v6, both libraries seem too interact fine again.
I'm wondering if it would be possible to introduce directly from `react-map-gl` a certain level of backwards compatibility.

https://github.com/uber/nebula.gl/issues/769

thanks

### Expected Behavior

to be able to plug the latest react-map-gl-draw plugin

### Steps to Reproduce

https://codesandbox.io/s/nostalgic-framework-pyfqer

### Environment

- Framework version: react-map-gl @ 7.0.15
- Map library: mapbox-gl@2.8.2
- Browser: Chrome 102
- OS: Windows 11

### Logs

TypeError: Cannot read properties of undefined (reading 'Consumer')
Editor.render
C:/source/src/mode-handler.tsx:462
459 | }
460 |
461 | render() {
462 | return (
| ^ 463 | <MapContext.Consumer>
464 | {(context) => {
465 | this._context = context;

**Comment by Pessimistress** [comment]
This is not a bug. It is not possible to support react-map-gl-draw in its current state because the resources that the other library depends on no longer exist in v7.

Is there a reason you have to upgrade to v7 if you need react-map-gl-draw?

**Comment by knutmarius** [comment]
@jsancho , I saw this just a bit too late, I'm afraid. I've already gone through the hassle of upgrading to v7, only to find that it makes the module that uses react-map-gl-draw explode.. I really don't want to go back to v6, because I did the upgrade as part of a bigger refactoring. Could you be so helpful to shed some light on the work you needed to do to port your app to use mapbox-gl-draw? Thanks in advance

**Comment by jsancho** [comment]
> @jsancho , I saw this just a bit too late, I'm afraid. I've already gone through the hassle of upgrading to v7, only to find that it makes the module that uses react-map-gl-draw explode.. I really don't want to go back to v6, because I did the upgrade as part of a bigger refactoring. Could you be so helpful to shed some light on the work you needed to do to port your app to use mapbox-gl-draw? Thanks in advance

Not a problem, here's a sandbox that I created at the time using react-map-gl v7 and the official mapbox-gl-draw plugin.
https://codesandbox.io/s/plain-v7-map-with-editor-pyfqer

hope that helps

**Comment by knutmarius** [comment]
@jsancho Cheers, mate! That's perfect! I will follow your pattern and get rid of react-map-gl-draw.

**Comment by engelzero** [comment]
> > @jsancho , I saw this just a bit too late, I'm afraid. I've already gone through the hassle of upgrading to v7, only to find that it makes the module that uses react-map-gl-draw explode.. I really don't want to go back to v6, because I did the upgrade as part of a bigger refactoring. Could you be so helpful to shed some light on the work you needed to do to port your app to use mapbox-gl-draw? Thanks in advance
> 
> Not a problem, here's a sandbox that I created at the time using react-map-gl v7 and the official mapbox-gl-draw plugin. https://codesandbox.io/s/plain-v7-map-with-editor-pyfqer
> 
> hope that helps

How would you gain access to the editorRef for draw control and set default feature collection on map? I.e. 
```
  <DrawControl
          onCreate={onDrawUpdate}
          onUpdate={onDrawUpdate}
          onDelete={onDrawDelete}
          onLoad=(() => { setFeature(feature) }}
```

**Comment by timminata** [comment]
> > > @jsancho , I saw this just a bit too late, I'm afraid. I've already gone through the hassle of upgrading to v7, only to find that it makes the module that uses react-map-gl-draw explode.. I really don't want to go back to v6, because I did the upgrade as part of a bigger refactoring. Could you be so helpful to shed some light on the work you needed to do to port your app to use mapbox-gl-draw? Thanks in advance
> > 
> > 
> > Not a problem, here's a sandbox that I created at the time using react-map-gl v7 and the official mapbox-gl-draw plugin. https://codesandbox.io/s/plain-v7-map-with-editor-pyfqer
> > hope that helps
> 
> How would you gain access to the editorRef for draw control and set default feature collection on map? I.e.
> 
> ```
>   <DrawControl
>           onCreate={onDrawUpdate}
>           onUpdate={onDrawUpdate}
>           onDelete={onDrawDelete}
>           onLoad=(() => { setFeature(feature) }}
> ```

@engelzero 
Did you manage to find an answer? I have been working with that sandbox as a base and have since resolved two issues:
1. You need access to the ref to be able to implement most functionality
2. The callbacks passed are attached when the Draw component is created, and thus if any data changes that affects your callback you are now acting on stale data (classic React pitfall that seems to get me everytime 😢)

I'll share a sandbox a bit later with these changes!

**Comment by engelzero** [comment]
@timminata See following - managed to access draw control ref with the following. you can call draw.add / set after map.onload or with props. See docs: https://visgl.github.io/react-map-gl/docs/api-reference/use-control

```
  let draw = useControl<MapboxDraw>(
    () => new MapboxDraw(props),
    ({ map }: { map: MapRef }) => {
      map.on('draw.create', props.onCreate)
      map.on('draw.update', props.onUpdate)
      map.on('draw.delete', props.onDelete)

      if (coordinates) {
        draw.set(routeData)
      }

      map.on('load', function () {
        // const feature = { type: 'Point', coordinates: [0, 0] }
        console.log('on map load')
        if (routeData) {
          const feature = simplify(routeData, 0.001)
          draw.add(feature)
          // draw.changeMode('draw_line_string')
          console.log('all feautures', draw.getAll())
        }
      })
    },
    ({ map }: { map: MapRef }) => {
      map.off('draw.create', props.onCreate)
      map.off('draw.update', props.onUpdate)
      map.off('draw.delete', props.onDelete)
    },
    {
      position: props.position
    }
  )

  return null
}
```

**Comment by timminata** [comment]
@engelzero ok nice, I ended up with something similar for adding the initial data after looking at what you did. I'm also using a ForwardRef so that I can change the draw mode from outside the component. You can then pass in a ref and use it as needed.

```
const DrawControl = React.forwardRef<MapboxDraw, DrawControlProps>(
  (props, ref) => {
    const { onCreate, onUpdate, initialFeatures } = props;

    const mapRef = useMap();
    useEffect(() => {
      mapRef.current?.on('draw.create', onCreate);

      return () => {
        mapRef.current?.off('draw.create', onCreate);
      };
    }, [onCreate]);

    useEffect(() => {
      mapRef.current?.on('draw.update', onUpdate);

      return () => {
        mapRef.current?.off('draw.update', onUpdate);
      };
    }, [onUpdate]);

    useControl<MapboxDraw>(
      () => {
        const mapboxDraw = new MapboxDraw({
          styles: [...drawStyles],
          ...props,
        });

        (ref as React.MutableRefObject<MapboxDraw>).current = mapboxDraw;
        return mapboxDraw;
      },
      () => {
        // Add initial features on load
        if (!!initialFeatures) {
          const editorRef = (ref as React.MutableRefObject<MapboxDraw>).current;
          initialFeatures.forEach(feature => {
            editorRef.add(feature);
          });
        }
      },
      () => {
        // Unload - need to keep this here even though it is currently not doing anything due to useControl method signature
      },
      {
        position: props.position,
      }
    );

    return null;
  }
);
```

**Comment by tordans** [comment]
FYI, there is another nice solution to the `ref`-topic at https://github.com/visgl/react-map-gl/discussions/2053#discussioncomment-4225133
