### ISSUE TITLE
[Feat] TS. Set ViewState padding prop to optional

### ISSUE THREAD

**Issue by Venikeee1** [visgl/react-map-gl#1898]
### Target Use Case

Currently when I am using controlled Map. I have to pass viewState with `padding` prop because of TS lint
```js
{
...,
    padding: {
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    }
}
```

### Proposal

Set `padding` to optional type and add default value for it if it is not provided. In many cases user don't want to control padding dynamically.

**Comment by Pessimistress** [comment]
Can you provide a code sample of how you are trying to use it?

**Comment by Venikeee1** [comment]
```ts
export type ViewState = {
  longitude: number;
  latitude: number;
  zoom: number;
  bearing: number;
  pitch: number;
  padding: PaddingOptions;
};
```
I meant make `padding` prop optional.

**Comment by Pessimistress** [comment]
You can type `initialViewState` as `Partial<ViewState>` if you insist. It is not supposed to be `ViewState`, see https://visgl.github.io/react-map-gl/docs/api-reference/map#initialviewstate. The `ViewState` type is used by [Events](https://visgl.github.io/react-map-gl/docs/api-reference/types#viewstatechangeevent) and it is important that we type it as it is.

**Comment by Venikeee1** [comment]
Ok.
