### ISSUE TITLE
is there a  'moveend' event handler like in Mapboxgl?

### ISSUE THREAD

**Issue by ZhenanH** [visgl/react-map-gl#190]
the current mapboxgl instance seems only register 'move' event.

**Comment by ZhenanH** [comment]
moveend behave the same as move, which is not correct

**Comment by bstaats** [comment]
Any solution to monitoring when the map is being dragged? Setting onLoad on InteractiveMap to register the event listeners `move` and `moveend` causes them to be fired at the same time so `moveend` is not useful to know when someone stopped dragging.

```
const onLoad = event => {
  event.target.on('move', () => console.log('moving'));
  event.target.on('moveend', () => console.log('stop'));
}
```

**Comment by ilionic** [comment]
Based on mapbox examples https://www.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/ `moveend` is working fine. Is there workaround yet?

**Comment by Pessimistress** [comment]
4.0.0's [onViewportChange](https://uber.github.io/react-map-gl/#/Documentation/api-reference/interactive-map?section=callbacks) callback is invoked with a second argument including the following flags:

- inTransition
- isDragging
- isPanning
- isRotating
- isZooming

**Comment by ilionic** [comment]
Thanks, it's solving the issue partially. I'd prefer to have explicit `moveend / dragend` indicating user interaction. ( usecase - `fitBounds` VS user interaction - both triggering `onViewportChange` but need different logic for every case )
At the moment partially solved it with custom rxjs debouncing.

**Comment by layik** [comment]
@ilionic would you kindly share your solution of that `rxjs debouncing`?

I like to make a final call the API once I know at least there is a 1sec silence.

**Comment by ilionic** [comment]
@layik using `redux` just dispatching action (i.e. `UPDATE_VIEWPORT`) from React component with mapbox instance ( `_updateViewport`)
with [redux-observable](https://redux-observable.js.org/) epics it looks something like:

```
export const updateViewportEpic = (action$: Observable<Action>) =>
  action$.pipe(
    ofType('UPDATE_VIEWPORT'),
    debounceTime(400),
    switchMap(({ payload }) => {
      // your logic here
      // ...
```

**Comment by saadsaifse** [comment]
This problem is still there. `moveend` behaves as `move`

**Comment by Pessimistress** [comment]
The `moveend` behavior can be simulated by listening to `onInteractionStateChange`.

**Comment by saadsaifse** [comment]
@Pessimistress that indeed did the job. Can confirm that this worked

```typescript
onInteractionStateChange={(s) => {
  if (s.isDragging || s.inTransition || s.isRotating || s.isZooming)
    return;
 // Perform your operation. In my case I update the URL.
  updateURL(state.viewport as ViewportProps);
}}
```
