### ISSUE TITLE
[Bug] wrong type for anchor on MarkerProps

### ISSUE THREAD

**Issue by dennemark** [visgl/react-map-gl#1901]
### Description

`<Marker anchor={"center"} />` expects center to be an Anchor type, which is a class. But in the description of the property it states, it needs a string with values of "center", "bottom" etc.

```
(property) anchor?: Anchor | undefined
A string indicating the part of the Marker that should be positioned closest to the coordinate set via Marker.setLngLat. Options are 'center', 'top', 'bottom', 'left', 'right', 'top-left', 'top-right', 'bottom-left', and 'bottom-right'.

@default

"center"
Type 'string' is not assignable to type 'Anchor'.ts(2322)
```

### Expected Behavior

I believe the Anchor type needs to be of PositionAnchor, which is a union type of the literal positions.
It is at this position:
https://github.com/visgl/react-map-gl/blob/8db441cb36c04e806c2e00b3c3840621fa01c5f5/src/components/marker.ts#L11

### Steps to Reproduce

`<Marker anchor={"center"} />`

### Environment

- Framework version: react-map-gl@7.0.7
- Map library: maplibre-gl@latest
- Browser: Chrome
- OS: Win

**Comment by Pessimistress** [comment]
`Anchor` is defined here: https://unpkg.com/browse/@types/mapbox-gl@2.7.3/index.d.ts#L177

See https://codesandbox.io/s/snowy-feather-r1puhf?file=/src/App.tsx

**Comment by Pessimistress** [comment]
The type definition looks exactly the same as that of mapbox-gl.

**Comment by dennemark** [comment]
@Pessimistress the type definition of maplibre-gl uses `PositionAnchor` which equals mapbox-gl `Anchor`. So they are the same. But since react-map-gl points to `Anchor` it does not get the `PositionAnchor` type of maplibre-gl. Instead it uses the `Anchor` type of symbols, which is a class.

**Comment by Pessimistress** [comment]
I have a hard time following you. `Anchor` is not a class. Can you create a code sandbox?

**Comment by dennemark** [comment]
@Pessimistress 
Unfortunately I cannot reproduce the issue in codesandbox, since I cannot use maplibre-gl instead of mapbox-gl.
In my package.json i am loading maplibre-gl via: `"mapbox-gl": "npm:maplibre-gl@latest"`.

Now react-map-gl `<Marker anchor={myAnchor} />` expects `myAnchor` to be of type `Anchor`.
Using `mapBOX-gl` it points to the correct type, which is a string of "center" etc.
Usin `mapLIBRE-gl` however, it points to the wrong type. Instead of pointing to `PositionAnchor` which equals mapBOX `Anchor`, it points to this: https://github.com/maplibre/maplibre-gl-js/blob/028344137fe1676b50b8da2729f1dcb5c8b65eac/src/symbol/anchor.ts

Since it is an issue of using mapLIBRE-gl, I am not sure, if it actually can or should be solved by react-map-gl.

**Comment by Pessimistress** [comment]
Well yes, that would break it. Please follow the documentation to use maplibre.

https://visgl.github.io/react-map-gl/docs/get-started/get-started#using-with-a-mapbox-gl-fork

**Comment by dennemark** [comment]
Thanks, I will try! I think I had some issues with this approach, since I was using craco for some custom configuration. Maybe it works now using vitejs.
Thanks for your efforts!
