### ISSUE TITLE
[Bug] can´t find a way to access to the map reference

### ISSUE THREAD

**Issue by raulrod16124** [visgl/react-map-gl#1903]
### Description

I'm using the **useControl hook** to create custom map controls and draw a polygon into the map to select vehicles. The problem comes when I try to access the reference of the **MapboxDraw** to clear the map selection without using the trash icon. 

I found no way to do it, so I did the hack below to get it:

`const editor = map["_controls"][2] as MapboxDraw;`

But obviously, this is not the correct way. 

### Steps to Reproduce

I made a conde sandbox, based on your example from the documentation, to reproduce what I want to do in my project:

https://codesandbox.io/s/react-map-gl-testing-reference-access-xfq8hd?file=/src/MapView.tsx

What I want is to be able to click on a button and access the **MapboxDraw** methods through a reference.

### Environment

- Framework version: react-map-gl v7.0.15
- Map library: @mapbox/mapbox-gl-draw v1.3.0
- Browser: Chrome
- OS: Window

**Comment by Pessimistress** [comment]
`useControl` returns the control instance: https://visgl.github.io/react-map-gl/docs/api-reference/use-control#signature

What is the bug you are reporting? Please use Discussions to get help with your own application.

**Comment by kauly** [comment]
@Pessimistress  the bug is clear to me. Apparently, there is no way to get the draw instance, it's a simple task using the pure JS library. I also wanna the instance but to load features, did you find another way @raulrod16124 ?
