### ISSUE TITLE
[Bug] Typescript error: Layer requires an id property

### ISSUE THREAD

**Issue by fknop** [visgl/react-map-gl#1908]
### Description

When using TypeScript, TS complains that `Layer` requires an `id` property, even though an auto-generated one is created for us [here](https://github.com/visgl/react-map-gl/blob/master/src/components/layer.ts#L82). I've provided a codesandbox with the issue

### Expected Behavior

Typescript doesn't complain about a missing `id`

I believe that to Omit the `id` from unions, we need to use something like this https://github.com/microsoft/TypeScript/issues/39556#issuecomment-656925230

### Steps to Reproduce

https://codesandbox.io/s/smoosh-microservice-pdf9f8?file=/src/App.tsx

<img width="567" alt="image" src="https://user-images.githubusercontent.com/6775689/177034303-9d39d454-6ff1-48dc-9217-113ce835e976.png">

### Environment

- Framework version: v7
- Map library: mapbox-gl
- Browser: Any
- OS: Any

**Comment by fknop** [comment]
This seems to be related to `strictNullChecks`

**Comment by Pessimistress** [comment]
Published 7.0.17
