### ISSUE TITLE
Running map.queryTerrainElevation was broken in 7.0.16 update [Bug]

### ISSUE THREAD

**Issue by joshreed** [visgl/react-map-gl#1915]
### Description

So I have a situation where querying the elevation profile along a line is an important use-case. I realized that my app was no longer returning the elevation data, and after some digging, I realized that it was broken by the update of `react-map-gl` from version `7.0.15` to `7.0.16`. I'm reasonably certain that this PR was the root cause: https://github.com/visgl/react-map-gl/pull/1894

After analyzing that PR, and some trial-and-error, I figured out that I could hack it to get it to work by setting the `map.transform.elevation` to `map.painter.transform.elevation` and run the `map.queryTerrainElevation`. Subsequently I reset the `map.transform.elevation` to its value prior to my changing it, just to "clean up" my hack. However, I would expect my hack to not be needed. 

### Expected Behavior

I would expect [map.queryTerrainElevation](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#queryterrainelevation) to return a non-null elevation value if a terrain layer/source is set on the map without having to perform any additional work to hack it.

### Steps to Reproduce

Here's an example of the bug, with the `react-map-gl` library set to 7.0.17. 

https://codesandbox.io/s/queryterrainelevation-bug-demo-lxofwe

Note: Toggle the library to `7.0.15` and see that it's working as expected, and therefore the bug was introduced in 7.0.16.

### Environment

- Framework version: react-map-gl@7.0.16
- Map library: mapbox-gl@2.9.1
- Browser: Chrome 102.0.5005.61
- OS: MacOS 11.6.5

**Comment by Pessimistress** [comment]
Thank you for reporting. Fixed in v7.0.18.

**Comment by joshreed** [comment]
Thanks for addressing it! I appreciate it.

**Comment by vbud** [comment]
This appears to have regressed again, I'm not sure when. The same hack @joshreed used still works.

**Comment by vbud** [comment]
Nevermind, I think I understand now. I'm supposed to use `queryTerrainElevation` on the map ref instead of the mapbox map instance.

It might be nice to mention this in the docs, I'll make a PR for that.
