### ISSUE TITLE
[Feat] Pass lat/lng/zoom to the onError handler whenever possible

### ISSUE THREAD

**Issue by NameFILIP** [visgl/react-map-gl#1916]
### Target Use Case

This would help developers to reproduce the error once it is detected in the logs.

### Proposal

Currently, onError handler receives 2 arguments: `(error, layer)`.
I suggest adding a third one that would contain `longitude, latitude, zoom`.

**Comment by NameFILIP** [comment]
I also reported a similar issue for `deck.gl`: https://github.com/visgl/deck.gl/issues/7140

**Comment by Pessimistress** [comment]
Here is the documentation for [onError](https://visgl.github.io/react-map-gl/docs/api-reference/map#onerror). It simply forwards mapbox-gl's `error` event. You can use `MapRef.getCenter()` and `MapRef.getZoom()` to get the current camera state.
