### ISSUE TITLE
[Feat] Autocomplete Address

### ISSUE THREAD

**Issue by redimongo** [visgl/react-map-gl#1918]
### Target Use Case

Would be nice to have this feature work with.
https://docs.mapbox.com/mapbox-search-js/tutorials/add-address-autofill-with-react/

### Proposal

Address the ability to auto complete addresses for forms.

**Comment by Pessimistress** [comment]
What exactly do you need that does not work right now?

**Comment by redimongo** [comment]
I want to be able to allow a user to type in an address and it auto completes the address, I then want ti be able to use that address and split it into address Line 1, Address Line 2, State, County, Country, Postcode.

**Comment by Pessimistress** [comment]
What stops you from copying the example that you linked?
