### ISSUE TITLE
Support `initialViewState.bounds` in reused maps

### ISSUE THREAD

**Issue by shishkin** [visgl/react-map-gl#1921]
It seems that setting `initialViewState.bounds` doesn't always work with reused maps. I have a sporadic issue that sometimes the map will center on a region used in a previous page (in a Next.js app). That happens after wildly clicking back and forth between pages and also using browser back button. But it's not consistently reproducible.

I tried `useEffect` to call `fitBounds`, but the `mapRef` is not available at that point and is `null`. I tried to call `fitBounds` inside `onLoad` callback and that resulted in a weird visible jump, where the map showed 0,0 first and then jumped to the desired region.

And yes, I read about controlled state management http://visgl.github.io/react-map-gl/docs/get-started/state-management#controlled-map. However, I would like to just set the bounds instead of center and zoom.

_Originally posted by @shishkin in https://github.com/visgl/react-map-gl/discussions/1914_

**Comment by Pessimistress** [comment]
Fixed in v7.0.18

**Comment by shishkin** [comment]
Thanks for a quick fix @Pessimistress!

One thing I've noticed is that `queryRenderedFeatures` returns `undefined` when being called from map's `onLoad`. How can I get the rendered features from sources ensuring bounds view state?
