### ISSUE TITLE
[Bug] Popup opens with part of the popup going off the bottom of the map when anchor is unset and popup is more than half the height of the map.

### ISSUE THREAD

**Issue by chilli-andrew** [visgl/react-map-gl#1925]
### Description

I have created a custom popup that in cases is more than half the height of the map. When the popup is opened by clicking on a marker, if the marker is below the middle of the map but the popup does not have space to fit above the marker (i.e. the popup is would take up more vertical space than is available above the marker) the popup opens below the marker and the bottom portion of the popup is not visible as it extends below the bottom of the map and screen. Is there a way to get the popup to display next to or even over the marker by still remain within the visible bounds of the map?

### Expected Behavior

I would expect that the popup should adjust and display beside or over the marker but still within the bounds of the map until such  point that the map is smaller than the popup.

### Steps to Reproduce

Display a map with a marker on the map. Add a popup that opens when the marker is clicked making sure the content of the marker is more than half the vertical height of the map. Move the marker to a position just below the vertical center of the map. Open the popup.  

### Environment

- Framework version: "react-map-gl": "~7.0.15",
- Map library: "maplibre-gl": "~2.1.9"
- Browser: Edge and Chrome
- OS: Windows

**Comment by Pessimistress** [comment]
react-map-gl does not contain the logic to position a popup. It simply wraps the Popup control of mapbox-gl.

If the behaviors are different between react-map-gl and mapbox-gl, please create a CodeSandbox to reproduce. Otherwise I suggest you report the issue to the mapbox-gl repo.

**Comment by chilli-andrew** [comment]
Thanks for the feedback. Much appreciated.
