### ISSUE TITLE
[Bug] Layers not visible in globe projection with initial zoom > 6

### ISSUE THREAD

**Issue by TheKeenestKeen** [visgl/react-map-gl#1930]
### Description

Initial zoom greater than 6 does not show layers unless we zoom out and then back in when using the globe projection

### Expected Behavior

Layers rendered

### Steps to Reproduce

https://codesandbox.io/s/eloquent-curran-369y7k

### Environment

- Framework version:"7.0.18"
- Map library:"^2.9.2"
- Browser:Chrome
- OS:macOS 12.3.1

**Comment by maheshgudisa** [comment]
Hey, you should specify layer id's that you want to interact in interactiveLayerIds paramerter in the Map component like this <Map interactiveLayerIds=[layer1.id, layer2.id]> </Map>

**Comment by pierceglennie** [comment]
I have this same issue with layers not appearing when the globe projection is used and initial zoom is greater than 6. @maheshgudisa suggested solution does not fix it – here's the same sandbox with that applied:

https://codesandbox.io/embed/blue-voice-nfpmp0?fontsize=14&hidenavigation=1&theme=dark

The layers work correctly if the globe projection line is commented out.

**Comment by Pessimistress** [comment]
Fixed in v7.1.3
