### ISSUE TITLE
[Bug] unexpected viewState when I use custom mapStyle in Map

### ISSUE THREAD

**Issue by anne030303** [visgl/react-map-gl#1941]
### Description

When I use the custom mapStyle which was set by Mapbox Studio, and set all 0 in `initialViewState`, the view will show "Default map position" in Mapbox Studio whether it is locked or not.

### Expected Behavior

Show exact ViewState when I set all 0 in `initialViewState`

### Steps to Reproduce

My Code Sandbox
https://codesandbox.io/s/dark-moon-qq3234?file=/src/index.js

### Environment

- Framework version:react-map-gl@7.0.0
- Map library: mapbox-gl@2.0.0
- Browser: Chrome 103.0.5060.134
- OS: iOS 12.4

**Comment by Pessimistress** [comment]
This is a behavior of mapbox-gl, not this library. `initialViewState` is used when the Map instance is created (component mount). The map style is loaded later, and it's up to mapbox-gl whether it affects the camera position.

I suggest you consult the Mapbox Studio documentation how to unset the default position.

**Comment by anne030303** [comment]
Thanks! Because it happened after I updated react-map-gl to v7, I considered that the problem is relevant to this library. I tried to unset the default position, but it was still wrong. Now my solution is to avoid `initialViewState` having all 0.

**Comment by Pessimistress** [comment]
> Because it happened after I updated react-map-gl to v7, I considered that the problem is relevant to this library.

v7.0 made many breaking changes, most importantly the behavior of this library is now expected to be consistent with mapbox-gl. It would only be a bug if something happening with react-map-gl does not happen when using only mapbox-gl, unless documented.

See https://visgl.github.io/react-map-gl/docs/upgrade-guide#upgrading-to-v70
