### ISSUE TITLE
[Bug] Mapbox-gl-draw vertex don't work

### ISSUE THREAD

**Issue by 383bd03d** [visgl/react-map-gl#1947]
### Description

In globe projection draw polygon mode click don't work on start point to close polygon

### Steps to Reproduce

<Map
      projection="globe"
      mapboxAccessToken={process.env.NEXT_PUBLIC_MAPBOX_TOKEN}
      mapStyle="mapbox://styles/mapbox/satellite-v9"
      initialViewState={{ bounds, bearing: -15 }}
      ref={mapRef}
      onLoad={onLoad}
      onResize={onResize}
      onMoveEnd={onMoveEnd}
      fog={{
        "color": "#000000",
        "space-color": "#000000",
        "high-color": "#000000",
        "horizon-blend": 1,
        "star-intensity": 0,
      }}
   />

useEffect(() => {
    if(!map) return;

    const Draw = new MapboxDraw({
      defaultMode: 'draw_polygon',
      controls: {
        polygon: true
      },
      touchEnabled: false
    });

    map.addControl(Draw);

    return () => map.removeControl(Draw)

  }, [map])

### Environment

- Framework version:
- Map library:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
I cannot see how this is related to this library from your description. You should report the bug to mapbox-gl-draw.
