### ISSUE TITLE
[Feat] Refresh source to visualize updated data

### ISSUE THREAD

**Issue by wmonecke** [visgl/react-map-gl#1964]
### Target Use Case

We are getting updates via a websocket and depending on these updates we must refresh the map (i.e. invalidate a cache and re request the tiles for said layer).

This is very similar like this SO question: https://stackoverflow.com/questions/63963704/refreshing-a-source-in-order-to-update-the-visualized-data

However, I dont see way of doing something like

map.getSource('myvectortiles').setTiles(..) with react-map-gl to force the map to refetch the tiles.

How can we achieve this?

Thank you!

Steps to Reproduce
Display a map, update data in the BE, try to refresh the tiles.

Environment
Map library:
"react-map-gl": "^7.0.18",
"mapbox-gl": "^2.7.0",
Browser: Chrome
OS: MacOS
Logs
No responseWebSocket

### Proposal

Add a way to force refetch data for the Source component

**Comment by Pessimistress** [comment]
>  I dont see way of doing something like map.getSource('myvectortiles').setTiles(..) with react-map-gl to force the map to refetch the tiles.

Use https://visgl.github.io/react-map-gl/docs/api-reference/source and change the `tiles` prop.
