### ISSUE TITLE
onClick event on Popup also fires onClick event on ReactMapGL

### ISSUE THREAD

**Issue by ssenapati-cs** [visgl/react-map-gl#1978]
### Description

If we specify an **onClick** function on `ReactMapGL`, and then have a `Popup` component as a child, any onClick function in the Popup component is still firing the **onClick** function on `ReactMapGL`.

Even after using props on `Popup` component such as captureScroll, captureDrag, captureClick, captureDoubleClick after referring to https://github.com/visgl/react-map-gl/pull/377, it still does not resolve the issue.

I've looked through the examples and documentation without luck.

Version used,
-----------------
"react-map-gl": "^6.1.19",

Please find a fix or workaround for it. And I am not completely sure, Why the event.stopPropagation() does not work?

### Steps to Reproduce

N/A

### Environment

- Framework version: "react-map-gl": "^6.1.19"
- Map library:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
v6 is no longer actively maintained. Please use the latest release.
