### ISSUE TITLE
[Bug] setFeatureState doesn't affect any styles

### ISSUE THREAD

**Issue by Creaa** [visgl/react-map-gl#1985]
### Description

Hello, 

I am trying to change the layer color on hover. 

I set `interactiveLayerIds` as id my layer. 

Event handler: 

```
 const onMouseHandler = (event) => {
    const featureId = event.features[0]?.properties?.id;
    event.target.setFeatureState({ source: 'grouped-countries', id: 'ARE' //any id doesn't work }, { select: false });
  };
```
  
  Layer settings: 
  
```
  const highlightedCountriesLayer = {
    id: 'grouped-geojson-layer-fill',
    layerdId: 'grouped-geojson-layer-fill',
    type: 'fill',
    layout: {},
    beforeId: 'country-label',
    paint: {
      'fill-color': ['case', ['boolean', ['feature-state', 'select'], true], '#5cc3e6', '#188cb3'],
    },
  };
```

Root structure: 

```
        <Source id='grouped-countries' type='geojson' data={filteredCountries}>
          <Layer {...highlightedCountriesLayer} />
          <Layer {...highlightedCountriesBorderLayer} />
        </Source>
```

So, I can log `setFeatureState` but nothing happened...

I'd appreciate note, what am I doing wrong. 

### Expected Behavior

Layer fill should change color on state change

### Steps to Reproduce

1. Set structure as above. 
2. Trigger the event and try to set setFeatureState
3. Nothing should happen

### Environment

- Framework version: "^7.0.19"
- Map library: "^2.10.0"
- Browser: Newest Chrome
- OS: Mac OS

### Logs

There is no logs.

**Comment by Pessimistress** [comment]
This library is merely a wrapper of mapbox-gl. It does not contain any implementation of feature states or layer styles. If the feature you are using does not behave the same when you use react-map-gl and mapbox-gl, please provide a CodeSandbox that reproduce it. Otherwise I suggest you consult Mapbox's documentation.

**Comment by Creaa** [comment]
So if I understand you correctly - there is nothing wrong in fact, that library doesn't update layer styles regarding featureState you provided by API? 

I guess hmm, it's pretty basic stuff to change the color of a layer on hover, so if you suggest using mapbox-gl, so what's the purpose of that specific library?

**Comment by Pessimistress** [comment]
All I'm saying is that there is nothing in this library that blocks your from doing this. If it's not working in your case, most likely you are not calling the method or setting your layer style correctly. I can't tell from the little snippet that you shared.

**Comment by Creaa** [comment]
For someone who also has problem with that: 

Somehow ID on the top level must be integer. 
For me string didn't work...

**Comment by bernatfortet** [comment]
for whomever might be looking. Now you can use promoteId, and use a string as the feature id
