### ISSUE TITLE
[Bug] mapRef.fitBounds doesn't respect minZoom

### ISSUE THREAD

**Issue by nwesthoff** [visgl/react-map-gl#1994]
### Description

When using `mapRef.fitBounds(bounds)` and setting `minZoom` option, I expect the map to fly to the given bounds, but never crossing the specified zoom level. 

I'm getting a locations' bounding box, which I want to zoom in on, but never closer than zoom level "x".

https://user-images.githubusercontent.com/7780722/191261920-1fac7d65-f1a8-45af-b029-a36912cfc408.mp4

Please refer to [Codesandbox](https://codesandbox.io/s/bug-fitbounds-minzoom-3iwcti?file=/src/MapActions.tsx) reproduction, and click "fly to location" button. It's using maplibre-gl to avoid sharing tokens, but the same problem occurs when using mapbox-gl.

Ps. since the `minZoom` option is typed on `fitBounds` I'm assuming this is a bug. Please consider this a feature request if this is not intended use. 

### Steps to Reproduce

Cal fitBounds with minZoom option, like so: 
```js
const { mapRef } = useMap();
// stuff
const bounds = [
    {
        "lat": 52.3630883,
        "lon": 4.6179566
    },
    {
        "lat": 52.363145,
        "lon": 4.6179952
    }
]
mapRef.fitBounds(bounds, { minZoom: 20 });
```

### Environment

- Framework version: react-map-gl@7.0.19
- Map library: maplibre-gl@2.1.9
- Browser: Chrome 105
- OS: MacOS 12.3 Monterey

**Comment by Pessimistress** [comment]
> but never crossing the specified zoom level

Sounds to me you want maxZoom, not minZoom.

Either way, you are calling a mapbox-gl API. If you think there is a bug, you need to report it to the Mapbox GL JS repo.
