### ISSUE TITLE
Why do not support onMouseEnter and onMouseLeave

### ISSUE THREAD

**Issue by lsbFlying** [visgl/react-map-gl#1996]
### Target Use Case

<Map
    // No effect
    onMouseEnter={(e) => {
      e.target.getCanvas().style.cursor = "pointer";
    }}
    // No effect
    onMouseLeave={(e) => {
      e.target.getCanvas().style.cursor = "unset";
    }}
    // Effective
    // onMouseOver={(e) => {
    //   e.target.getCanvas().style.cursor = "pointer";
    // }}
    // Effective
    // onMouseOut={(e) => {
    //   e.target.getCanvas().style.cursor = "unset";
    // }}
>
...
</Map>

### Proposal

You can not support onMouseEnter and onMouseLeave, but why support Over&Out, I just don't understand

**Comment by Pessimistress** [comment]
Please, read the documentation. If you have trouble understanding it, go to Discussions.
