### ISSUE TITLE
Enable setTerrain()

### ISSUE THREAD

**Issue by anna-visarsoft** [visgl/react-map-gl#2018]
### Target Use Case

Hi! Is here any way to use `setTerrain` function? It will help to toggle view between 2d and 3d.

### Proposal

now `setTerrain` function is disabled for use. Can you enable it?
<img width="441" alt="image" src="https://user-images.githubusercontent.com/94357041/196704405-c10d871e-4c67-41a0-802a-b12fe278d86b.png">

**Comment by Pessimistress** [comment]
Use the [terrain](https://visgl.github.io/react-map-gl/docs/api-reference/map#terrain) prop.
