### ISSUE TITLE
[Feat] Support get instance of Marker, Popup etc.

### ISSUE THREAD

**Issue by yunsii** [visgl/react-map-gl#2031]
### Target Use Case

I want to custom close button in Popup, but can't get instance of Popup to close it.

### Proposal

Like Map component, enable user to get instance by React.Ref.

**Comment by yunsii** [comment]
Maybe I should `return null` to close Popup according to https://github.com/mapbox/mapbox-gl-js/issues/3858#issuecomment-269035067 😂

Anyway, allow user get instance of component is more flexible.

**Comment by hussamkhatib** [comment]
This is supported in version >=7.1.0
https://visgl.github.io/react-map-gl/docs/api-reference/popup#methods
