### ISSUE TITLE
[Bug] reuseMaps does not work properly with useMap hook

### ISSUE THREAD

**Issue by 2Up1Down** [visgl/react-map-gl#2034]
### Description

There seems to be an issue/bug with the reuseMaps property of the Map component.

with the reuseMaps=false: 
this is the default behaviour from the map component and it works as intended when switching between HomePage and ReuseFalsePage{

with reuseMaps=true: 
when switching between the home page and the reuse-true page its not working correctly. On every second render from the reuse-true page, the map object is undefined.

### Expected Behavior

with reuseMaps=true;
the map object should not be undefined

### Steps to Reproduce

I created a sandbox example with next js.
https://codesandbox.io/s/nextjs-mapbox-usemap-bug-gx6p7m

The example consists of three pages:
HomePage
ReuseTruePage
ReuseFalsePage

When switching between the HomePage and ReuseFalsePage everything is fine.

<img width="544" alt="Screenshot 2022-11-03 at 18 40 51" src="https://user-images.githubusercontent.com/39255639/199795479-96b311ab-f1ac-4014-bc47-6f285b791b8a.png">

The bug can be reproduced when switching between the HomePage and the ReuseTruePage. On every second render the map object results to undefined.
<img width="550" alt="Screenshot 2022-11-03 at 18 41 22" src="https://user-images.githubusercontent.com/39255639/199795536-6be0f28c-bfca-4a99-99e6-7839986a86d1.png">

This is especially weird, as the onMapLoadedHandler where the map object is used, is only executed on the onLoad event from the Map component.

onLoad:
Called after all necessary resources have been downloaded and the first visually complete rendering of the map has occurred.

### Environment

See dependencies from sandbox
    "next": "12.1.0",
    "mapbox-gl": "^2.7.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-map-gl": "^7.0.19"

**Comment by Pessimistress** [comment]
`useMap().map` is assigned in between your `onLoad` callback being defined and being called. Your callback is holding onto a `map` value that is old.

**Comment by 2Up1Down** [comment]
Hi Pessimistress, I'm not sure if I understood you correctly, but I gave it a second try.

This time I extracted the onMapLoadedHandler with the argument of the current map. However the the result remains the same. On every second load the map remains undefined.

[https://codesandbox.io/s/nextjs-mapbox-usemap-bug-v2-schzwr?file=/components/map-view.js](https://codesandbox.io/s/nextjs-mapbox-usemap-bug-v2-schzwr?file=/components/map-view.js)

**Comment by Pessimistress** [comment]
Think of it this way, `load` is a mapbox-gl event and it is triggered outside of the React lifecycle. Therefore you can't expect that all React hooks are updated inside the callback.

You can either do it the callback way:

```js
onLoad={(event => {
  const map = event.target
  map.flyTo(...)
}}
```

Or the React way:

```js
const {map} = useMap()

useEffect(() => {
  if (map) {
    map.flyTo(...)
  }
}, [map])
```
