### ISSUE TITLE
[Bug] onContextMenu fire also onClick

### ISSUE THREAD

**Issue by eliaoucohen72** [visgl/react-map-gl#2041]
### Description

onContextMenu fire also onClick

### Steps to Reproduce

1- Right click on the map with the
2- Print in the console the event
3- You can see that left and right clicks are fired

### Environment

- Framework version: react-map-gl@6.1.18
- Map library: mapbox-gl@2.4.1
- Browser: Chrome 107
- OS: Windows 11

![github](https://user-images.githubusercontent.com/34001081/201069226-79d65311-97b3-40f9-8abb-82f5f482792b.gif)

NOTE:
I can use onMouseDown and the property rightButton; but the bug with the right click event stays.

**Comment by Pessimistress** [comment]
v6 is no longer actively maintained. You can filter out the right clicks in onClick by examining the event properties.

**Comment by eliaoucohen72** [comment]
I have upgraded to v7, thanks.
