### ISSUE TITLE
[Bug] - not a bug just documentation issue

### ISSUE THREAD

**Issue by fshahmt** [visgl/react-map-gl#2057]
### Description

Hello,

The documentation has a misspelling https://visgl.github.io/react-map-gl/docs/get-started/tips-and-tricks#finding-out-if-a-point-is-within-the-current-viewport

I know it's not a bug but this led to me wasting 2 hours on google and trying to figure out what I am doing wrong.

return (lat >= bounds._sw.lat && lat <= bounds._nw.lat && lng >= bounds._sw.lng && lng <= bounds._nw.lng); 
this should be 
return (lat >= bounds._sw.lat && lat <= bounds._ne.lat && lng >= bounds._sw.lng && lng <= bounds._ne.lng);

Amazing library bdw, had a great time using it

### Steps to Reproduce

Please fix the documentation.

### Environment

- Framework version:
- Map library:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
#2012
