### ISSUE TITLE
Broken with React 18 NavigationControl  "Uncaught TypeError: Cannot read properties of null (reading 'bearing')"

### ISSUE THREAD

**Issue by rullymartanto** [visgl/react-map-gl#2068]
### Description
![image](https://user-images.githubusercontent.com/5577057/207000146-55a8a36e-bbfa-4bd2-b438-87bd4efc6977.png)

### Steps to Reproduce

`import { NavigationControl } from 'react-map-gl';`

### Environment

Library Version: 6.1.19
Mapbox Version: 2.3.0
React Version: 18
OS: Windows

**Comment by Pessimistress** [comment]
v6.x is no longer actively maintained.
