### ISSUE TITLE
Broken with React 18 NavigationControl Click not working

### ISSUE THREAD

**Issue by rullymartanto** [visgl/react-map-gl#2069]
### Description

I just use this https://visgl.github.io/react-map-gl/examples/controls
and implement on react 18 and the navigation event is not working

![image](https://user-images.githubusercontent.com/5577057/207031670-61d6c622-baf2-4084-b236-5b6a11fdc8a1.png)

### Steps to Reproduce

`import Map, {
  Marker,
  Popup,
  NavigationControl,
  FullscreenControl,
  ScaleControl,
  GeolocateControl
} from 'react-map-gl';
  <DeckGL  height="100%"
        width="100%"
        viewState={viewport}
        controller={true}
        pickingRadius={5}>
<Map
          initialViewState={{
            latitude: 40,
            longitude: -100,
            zoom: 3.5,
            bearing: 0,
            pitch: 0
          }}
          mapStyle="mapbox://styles/mapbox/dark-v9"
          mapboxAccessToken={MAPBOX_KEY}
        >
          <GeolocateControl position="top-left" />
          <FullscreenControl position="top-left" />
          <NavigationControl position="top-left" />
          <ScaleControl />
        </Map></DeckGL>`

### Environment

Library Version: 7.0.20
Mapbox Version: 2.11.1
React Version: 18

**Comment by Pessimistress** [comment]
The examples on the website use React 18. Please use Discussions if you need help debugging your own application.
