### ISSUE TITLE
[Bug] ReuseMaps does not destroy its children

### ISSUE THREAD

**Issue by evrazi** [visgl/react-map-gl#2071]
### Description

Maps that have reuseMaps="true" do not destroy its children

### Expected Behavior

Maps that have reuseMaps="true" destroy their children like in v6 of react-map-gl

### Steps to Reproduce

https://codesandbox.io/s/flamboyant-browser-9j9clt?file=/src/Map.js

### Environment

- Framework version: "react-map-gl": "^7.0.20",
- Map library: "mapbox-gl": "^2.9.1",
- Browser: Chrome 108.0
- OS:

**Comment by lh0x00** [comment]
I tried solving it at #2092.

**Comment by Pessimistress** [comment]
Fix landed in v7.0.21
