### ISSUE TITLE
[Bug] Popup does not move at the same speed when the map is moving

### ISSUE THREAD

**Issue by MoustafaWehbe** [visgl/react-map-gl#2078]
### Description

When I open the popup and drag the map quickly, the popup seems to move with slight delay. Check the video attached at the bottom of the issue.
**Code:**
```
import MapGL, { Popup } from "react-map-gl";

const onMove = useCallback((evt: ViewStateChangeEvent) => setViewState(evt.viewState), []);

<MapGL
    {...viewState}
    mapboxAccessToken={ACCESS_TOKEN}
    style={{ width: '100vw', height: "100vh" }}
    minZoom={2.2}
    maxZoom={5}
    preserveDrawingBuffer={true}
    hash={true}
    onClick={onMapClick}
    ref={mapRef}
    interactiveLayerIds={interactiveClimateLayerIds}
    onMove={onMove}
    mapStyle={"mapbox://styles/mapbox/streets-v9"}
    clickTolerance={1}
>
  <Popup
    latitude={latitude}
    longitude={longitude}
    closeButton
    closeOnClick={false}
    onClose={onClose}
    anchor="top"
    showClickArea={true}
    maxWidth="none"
    >
    {...content}
  </Popup>
</MapGL>
```

### Expected Behavior

The popup should not move while dragging the map.

### Steps to Reproduce

1- click to open the Popup
2- click and drag the map to move around
3- the popup seems to move with a slight delay (especially if you drag quickly). It seems to not move at the same speed as the map.

### Environment

- Framework version: react-map-gl@7.0.20
- Map library: mapbox-gl@2.11.1
- Browser: Chrome 98.0
- OS: IOS 15.1

### Logs

https://user-images.githubusercontent.com/18680770/207644275-f4926470-d11a-4429-b4f2-265c259504df.mov

**Comment by scsskid** [comment]
This is a shortcoming of mapbox-gl, I'm facing the same problem.
