### ISSUE TITLE
[Bug] Drag very choppy on iphone when built with capacitor

### ISSUE THREAD

**Issue by frank-besson** [visgl/react-map-gl#2084]
### Description

When trying to upgrade from react-map-gl 6.1.16 -> 7.0.20, I've noticed that when dragging and releasing the map, I instantly land at end of the swipe. As in the map doesn't "glide" for any period of time once I take my finger off the screen. The second my thumb leaves the phone, the map lands at the destination if that makes sense (see screen recording).

The map works great on my computers web browser, but not on my phone.

This is how I am defining my map component...
```
<Map
    reuseMaps={true}
    initialViewState={initialViewState}
    {...settings}
    width='100%'
    height='100%'
    mapboxAccessToken={MAPBOX_TOKEN}
    mapStyle={MAPBOX_URL}
    minZoom={13}
    ref={map}
    asyncRender={true}
    // onMoveStart={handleMarkerDismiss}
>
```

https://user-images.githubusercontent.com/32044707/207963078-5eb07149-1457-4b54-89f9-fc897079655e.mov

### Expected Behavior

Expecting a smooth glide after swiping the map, similar to what can be seen on my computer's web browser.

### Steps to Reproduce

```
import React, { useState, useRef } from 'react';

import Map from 'react-map-gl';
import mapboxgl from 'mapbox-gl';

// https://github.com/visgl/react-map-gl/issues/126
// https://stackoverflow.com/questions/66476925/unexpected-in-worker-loadermapbox-gl-dist-mapbox-gl-csp-worker
// eslint-disable-next-line import/no-webpack-loader-syntax
mapboxgl.workerClass = require('worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker').default;

const MAPBOX_TOKEN = process.env.REACT_APP_MAPBOX_TOKEN;
const MAPBOX_URL = process.env.REACT_APP_MAPBOX_URL

const initialViewState = {
    latitude: 40.737219,
    longitude: -73.992731,
    zoom: 9,
    // bearing: 0,
    // pitch: 50
};

const MapReactGl = (props) => {
    const map = useRef(null);
    const [settings, setSettings] = useState({
        scrollZoom: true,
        boxZoom: true,
        dragRotate: true,
        dragPan: true,
        keyboard: true,
        doubleClickZoom: true,
        touchZoomRotate: true,
        touchPitch: true,
        minZoom: 13,
        // maxZoom: 20,
        minPitch: 0,
        maxPitch: 85
    });

    return (
        <div style={{height: '100%', width:'100%'}}>
            <Map
                reuseMaps={true}
                initialViewState={initialViewState}
                {...settings}
                width='100%'
                height='100%'
                mapboxAccessToken={MAPBOX_TOKEN}
                mapStyle={MAPBOX_URL}
                minZoom={13}
                ref={map}
                asyncRender={true}
                // onMoveStart={handleMarkerDismiss}
            >

            </Map>
        </div>
    )

}

export { MapReactGl };
```

### Environment

- Framework version: react-map-gl@7.0.20
- Map library: mapbox-gl@2.11.1
- Browser: Chrome 108.0
- OS: iOS 16.2

**Comment by Pessimistress** [comment]
Do you experience this with https://visgl.github.io/react-map-gl/examples ? If not, please create a Code Sandbox.

**Comment by frank-besson** [comment]
@Pessimistress indeed I do! In fact I see this with [the following example](https://github.com/visgl/react-map-gl/blob/master/examples/get-started/basic/app.js) - although I am using "@capacitor/core": "^4.5.0" in order to install the react app onto my iOS device

**Comment by Pessimistress** [comment]
Sorry I am not familiar with capacitor, and it's not something libraries particularly optimize for. react-map-gl v7 comparing to v6 is a much thinner layer on top of mapbox-gl/maplibre. There isn't a lot of place we can look in this code base that could cause a performance degradation.

If you can identify the root cause, I'm happy to release a patch, but I don't personally have time to investigate.

**Comment by frank-besson** [comment]
Turns out, that this issue is not related to react-map-gl, but rather with mapbox itself. I see the same behavior with capacitor and mapbox when not using the react-map-gl package

**Comment by frank-besson** [comment]
Final update - turns out I just didn't realize that I had "reduce motion" enabled on my iphone. Disabling this resolved the issue
