### ISSUE TITLE
When following the Get Started example on the latest version [Bug]

### ISSUE THREAD

**Issue by ChristopherLyon** [visgl/react-map-gl#2087]
### Description

Unhandled Runtime Error when following Get Started documentation.

### Steps to Reproduce

Follow Get Started 

### Environment

- Framework version:
- Map library: Latest
- Browser: Tauri
- OS: Windows

### Logs

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading '0')

Call Stack
Object.nu [as transformMat4$1]
node_modules\mapbox-gl\dist\mapbox-gl.js (31:217750)
Ko.pointRayIntersection
node_modules\mapbox-gl\dist\mapbox-gl.js (36:362112)
Qf.pointCoordinate
node_modules\mapbox-gl\dist\mapbox-gl.js (32:51022)
Ko.pointCoordinate
node_modules\mapbox-gl\dist\mapbox-gl.js (36:363103)
Ko.pointCoordinate3D
node_modules\mapbox-gl\dist\mapbox-gl.js (36:363179)
Ko.pointLocation3D
node_modules\mapbox-gl\dist\mapbox-gl.js (36:361737)
Map.unproject
node_modules\mapbox-gl\dist\mapbox-gl.js (36:461597)
new cr
node_modules\mapbox-gl\dist\mapbox-gl.js (36:383156)
ur.mouseover
node_modules\mapbox-gl\dist\mapbox-gl.js (36:384579)
$r.handleEvent
node_modules\mapbox-gl\dist\mapbox-gl.js (36:410007)

**Comment by Pessimistress** [comment]
If you wish to report a bug, please create a Code Sandbox.

**Comment by sdonys** [comment]
I had the same issue, you should provide a mapboxAccessToken. 

```
return <Map
    mapboxAccessToken='SomeAccessToken'
    initialViewState={{
      longitude: -100,
      latitude: 40,
      zoom: 3.5
    }}
    style={{width: 600, height: 400}}
    mapStyle="mapbox://styles/mapbox/streets-v9"
  />;
```
