### ISSUE TITLE
Direct way to store polygons in Databases [Feat]

### ISSUE THREAD

**Issue by SoulPancake** [visgl/react-map-gl#2094]
### Target Use Case

I want to be able to use the draw polygon example in my Projects but I don't know what is a good way to store it in a database, I would request for a feature and data encoding for these polygons in such a way that I can easily add it to a db table.

### Proposal

We can think of some sort of encoding or representation of the Polygons and then sending that as a callback after one polygon is created or deleted, and also some sort of a unique ID or standard encoding might help. Not sure about the computational geometry that we can use in this, But This might be pretty useful for people.

**Comment by SoulPancake** [comment]
This is kind of an approach that I could try out myself : 

const polygonData = [[[-122.420679, 37.772537], [-122.420679, 37.772537], [-122.420679, 37.772537]]];
const polygonDataString = JSON.stringify(polygonData);
const polygonDataBuffer = Buffer.from(polygonDataString);

And use this , But is there a smarter , better way to achieve this?

**Comment by mrNuTz** [comment]
There is Googles Polyline Encoding for a series of coordinates, it is explained here https://developers.google.com/maps/documentation/utilities/polylinealgorithm

**Comment by SoulPancake** [comment]
Thanks @mrNuTz
