### ISSUE TITLE
[Bug]Close button not clickable in react-map-gl wrapped in deck.gl

### ISSUE THREAD

**Issue by pascal-codetaal** [visgl/react-map-gl#2098]
### Description

I have created a CodeSandbox at the following link: https://codesandbox.io/s/weathered-fire-msfj4c?file=/src/App.js

I am using react-map-gl in conjunction with deck.gl, but I have noticed that the close button in react-map-gl is not clickable. This is likely because react-map-gl is wrapped inside deck.gl.

I have tried several different approaches to fix this issue, but have not had success. I would greatly appreciate any help in resolving this issue.

I have also created an example without deck.gl, and this one works like expected.
https://github.com/visgl/react-map-gl/issues/2098

### Expected Behavior

The close button should be clickable and should close the map.

### Steps to Reproduce

1. Go to the CodeSandbox link provided above.
2. Click the close button in the top right corner of the popup.
3. The popup stays open.

### Environment

deck.gl: 8.8.20
react-map-gl: 7.0.20

**Comment by Pessimistress** [comment]
Please go to the deck.gl repo if you have any questions about usage with deck.gl.

https://github.com/visgl/deck.gl/issues/5189
