### ISSUE TITLE
[Bug] Zooming is extremely slow on `5.3.21`

### ISSUE THREAD

**Issue by NameFILIP** [visgl/react-map-gl#2103]
### Description

Zooming in/out (using mouse wheel or trackpad) is extremely slow on `5.3.21`.

Note: Adding `transitionDuration={0}` fixes the issue.

### Steps to Reproduce

1. Open and zoom: https://codesandbox.io/s/billowing-shape-3ppjyl?file=/src/App.js
2. Comment/Uncomment `transitionDuration={0}` and try zooming again.

### Environment

- Framework version: 5.3.21
- Map library: ^1.0.0
- Browser: Chrome 108.0.5359.124
- OS: 13.1

**Comment by Pessimistress** [comment]
v5 is no longer actively maintained. Performance issue is one of the reasons we moved to v7.

**Comment by NameFILIP** [comment]
Looks like the issue is caused by adding transition properties to the `_onWheel` handler. Would it make sense to remove them to make this version at least useable?
