### ISSUE TITLE
[Bug] Moving Markers on Zoom

### ISSUE THREAD

**Issue by yiziz** [visgl/react-map-gl#2114]
### Description

```json
"mapbox-gl": "^2.12.0",
"react-map-gl": "^7.0.21"
```

added this to my app js file
`import 'mapbox-gl/dist/mapbox-gl.css';`

but when i zoom in and out the markers don't stay in the same location

https://user-images.githubusercontent.com/1268502/215385873-c086237a-9ffa-4182-9888-a8479e4b5719.mov

### Expected Behavior

i expect the markers to anchor at the same location independent of zoom level

### Steps to Reproduce

```
<Map
        initialViewState={{
          latitude: 40.7213068,
          longitude: -73.9584482,
          zoom: 13,
        }}
        style={{width: 800, height: 480}}
        mapStyle="mapbox://styles/mapbox/streets-v12"
      >
        {courts.map((c: any) => {
          const { lat, lng } = c.coordinates;
          return (
            <Marker
              key={c.id}
              longitude={lng}
              latitude={lat}
              anchor="bottom"
            >
            </Marker>
          );
        })}
      </Map>
```

i had to use an older version of mapbox-gl so the map would show up without using a map token
https://codesandbox.io/s/recursing-cori-egyy6k?file=/src/index.js

1. zoom in and out and see that the marker is not consistently in the same location on the map

### Environment

- Framework version: ^7.0.21
- Map library: ^2.12.0
- Browser: Chrome
- OS: Mac OS Ventura

**Comment by yiziz** [comment]
note: i think this bug appears when the `Marker` `anchor` attribute is a string that is not `"center"`

**Comment by tarmooo** [comment]
For me it seems like styles are just off, check Marker styles and see if it's container height is same as pin height. had to manualy set marker style height prop same as pin height:
`<Marker anchor="bottom"style={{ zIndex: 10, cursor: 'pointer', height: 20 }}>
<Pin />
</Marker>`

**Comment by kennyhei** [comment]
Had the exact same issue and for me the bug was mysteriously fixed by setting Marker's `anchor` attribute to `top-left`

**Comment by yiziz** [comment]
> Had the exact same issue and for me the bug was mysteriously fixed by setting Marker's `anchor` attribute to `top-left`

yes - https://github.com/visgl/react-map-gl/issues/2114#issuecomment-1408005083

**Comment by kennyhei** [comment]
> > Had the exact same issue and for me the bug was mysteriously fixed by setting Marker's `anchor` attribute to `top-left`
> 
> @kennyhei , setting it to `top-left` doesn't seem to work in the sandbox i posted in my description. what is your environment?

Framework version: 7.0.21
Map library: 2.12.1
Browser: Chrome
OS: Mac OS Monterey

**Comment by jonaslb** [comment]
I believe I'm seeing the same bug as described here, but exacerbated to a comedic extent.

Create a new react app with `create-react-app`, install react-map-gl 7.0.21 and mapbox-gl 2.13.0 and replace `App.js` with the following:

```javascript
import './App.css';
import Map, { Marker } from 'react-map-gl';

function App() {
  return (
      <Map
        initialViewState={{
          longitude: -30,
          latitude: -30,
          zoom: 2,
          pitch: 0,
          bearing: 0
        }}
        style={{width: "800px", height: "500px"}}
        mapboxAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
        mapStyle={"mapbox://styles/mapbox/light-v11"}
      >
        <Marker longitude={0} latitude={0} anchor="center">
          <span>X</span>
        </Marker>
      </Map>
  );
}

export default App;
```

The result is that not only is the "X" in a completely different place than specified, it jumps thousands of kilometers when you zoom. I'd be interested to hear if any of you think this is a different bug though or if something is "done wrong" above.

**Comment by yiziz** [comment]
@Pessimistress are you saying the code will render `anchor="bottom"` correctly if I provide my own marker?

**Comment by asotog** [comment]
still happening to me

**Comment by corentin-ach** [comment]
For me it works by adding `anchor="bottom"`
With `"react-map-gl": "^7.1.5"`

**Comment by TobiasKC** [comment]
> For me it works by adding `anchor="bottom"` With `"react-map-gl": "^7.1.5"`

Can confirm this fixed it for me, changing from 'top' on same react-map-gl version.

**Comment by FelixOchoa** [comment]
Entiendo que es necesario utilizar la configuración css de MapBox.

`import 'mapbox-gl/dist/mapbox-gl.css';`

Es necesario añadir esto en tu componente para que funcione correctamente el marcador.

**Comment by bhutoria** [comment]
yes, like @FelixOchoa said, you have to 

import 'mapbox-gl/dist/mapbox-gl.css';
this will solve the problem

**Comment by graffkevin** [comment]
hello old post but just ensure you have your projection set. If you let projection undefined I think it recompute it on zoom / moving on map. It work for me

```TS
import MapboxMap, { MapRef, Marker, Popup } from "react-map-gl";
<MapboxMap
  ref={mapRef}
  cooperativeGestures={coopGestures}
  doubleClickZoom={dblZoom}
  mapStyle={coreStyle}
  projection={projection ? projection : "mercator"}
````
