### ISSUE TITLE
[Bug] Popup css styles broken from v6 -> v7

### ISSUE THREAD

**Issue by wafisher** [visgl/react-map-gl#2116]
### Description

The fonts/styling on popups is different in v7 than v6.

This is because in v6, there is a `<div class=overlays>` to which all popups belong. In v7, those same popups belong to `<div class=mapboxgl-map>`, which brings a whole set of CSS style inheritances from the Mapbox css file (`mapbox-gl.css`).

We can see this new behavior [in a Mapbox example](https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/) and [in a react-map-gl one](https://visgl.github.io/react-map-gl/examples/controls).

Our old popups had larger text, now they default to Mapbox CSS font styling, which we don't like.

<img width="180" alt="image" src="https://user-images.githubusercontent.com/3514570/215942600-d7a6ebb3-fb6b-49cb-ba0a-72cd8115b42d.png">
<img width="192" alt="image" src="https://user-images.githubusercontent.com/3514570/215942631-8d94aa00-fcfa-41eb-a0fa-678b3838f3a6.png">

Not sure what the official solution should be, but it's a bit of a breaking change and should be documented in the upgrade process with recommendations. Suggestions?

### Steps to Reproduce

Try this page for new (undesirable) behavior: https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/

### Environment

- Framework version: 7.0.21
- Map library: mapbox-gl
- Browser: Chrome
- OS: Mac

**Comment by Pessimistress** [comment]
The move to Mapbox native control implementations is one of the key points in the upgrade guide. Your css should not have targeted a class (`overlay`) that was not documented anyways. If you want to style your popup content by class, just wrap it in your own:

```js
<Popup>
  <div className="xxx">
    {content}
  </div>
</Popup>
```
