### ISSUE TITLE
[Bug] Cooperative Gestures isn't reactive

### ISSUE THREAD

**Issue by chriszrc** [visgl/react-map-gl#2120]
### Target Use Case

If you dynamically provide the value of true/false to the cooperativeGestures prop, the map doesn't actually update the behavior. [EDIT] I see now that this prop isn't part of the reactive list. Can it be?

### Proposal

It should be reactive because I would like to update the value based on screen size, and screens can be resized by users dynamically. 

### Steps to Reproduce

https://codesandbox.io/s/react-map-gl-cooperativegestures-forked-5w0hpd?file=/src/index.js

### Environment

- Framework version: react-map-gl@7.0.21
- Map library: mapbox-gl@2.12.1
- Browser: Chrome
- OS:

**Comment by Pessimistress** [comment]
https://visgl.github.io/react-map-gl/docs/api-reference/map#other-options

> Props in this section are not reactive. They are only used once when the Map instance is constructed.

**Comment by chriszrc** [comment]
@Pessimistress I updated to be a feature request

**Comment by Pessimistress** [comment]
There is no Mapbox API to change this option after the map is constructed. If you insist on changing it, then create a new Map component with a different key.

**Comment by chriszrc** [comment]
Ok. I can see it is possible, but the property is marked private:

https://jsfiddle.net/3bzvua0r/6/
