### ISSUE TITLE
[Bug] GeolocateControl :disabled attribute not being applied

### ISSUE THREAD

**Issue by yiziz** [visgl/react-map-gl#2130]
### Description

When geolocation permissions is denied, the geolocation button in the map is not disabled. This occurs when going to a website that has already denied geolocation permissions and when a user clicks on the geolocate button for the first time and denies geolocate permissions.

Sometimes, this works correctly in Chrome, sometimes it does not. I have never seen it work correctly in Chrome, Firefox, and Safari (and in their private modes) at the same time.

https://user-images.githubusercontent.com/1268502/221729070-ce442831-a46a-4c86-8b1f-97862b7cedd7.mov

### Expected Behavior

The button should appear disabled when going to a website that has already denied geolocation permissions. The button should appear disabled after a user denies geolocation permissions

### Steps to Reproduce

For each browser type, For a website that has disabled geolocation permissions and for one that doesn't yet, Go to the website, if geolocation is denied, the geolocate button should be disabled. If geolocation is permitted, clicking on the button and then denying geolocation permissions should disabled the button.

https://codesandbox.io/s/loving-zeh-8tnkm0

### Environment

- Framework version: ^7.0.21
- Map library: ^2.12.0
- Browser: Chrome, Firefox, Safari (and their private modes)
- OS: MacOS

**Comment by Pessimistress** [comment]
Set `trackUserLocation` like https://docs.mapbox.com/mapbox-gl-js/example/locate-user/ and it will work. This component is merely a React wrapper of mapbox's GeolocateControl and does not handle any events on its own. If you think there is a bug you may want to report it to mapbox-gl.
