### ISSUE TITLE
[Bug] GeolocateControl can't be disabled

### ISSUE THREAD

**Issue by ThomasG77** [visgl/react-map-gl#2131]
### Description

I go to https://visgl.github.io/react-map-gl/examples/controls and I click on Geolocate control. It asks for geolocation. I allow it. It flies to my location. When I try to click again to disable the geolocation, it's not possible to hide the current marker position. The surprising fact for me is that when location is activated, there is no icon change. See demo

![react-unable-to-deactivate-geolocate-control](https://user-images.githubusercontent.com/642120/222124802-f22cb8c9-7d36-4a3e-96d1-45a46dd46046.gif)

### Expected Behavior

I would expect a behaviour similar to https://maplibre.org/maplibre-gl-js-docs/example/locate-user/

![maplibre-able-to-deactivate-geolocate-control-resize](https://user-images.githubusercontent.com/642120/222124938-1a6e3ff3-52b3-4365-aa0f-dbfa4f43ade4.gif)

### Steps to Reproduce

Do like in the GIF

### Environment

- Framework version: current one
- Map library: current one
- Browser: Chrome 110
- OS: Ubuntu 18.04

**Comment by Pessimistress** [comment]
Set `trackUserLocation` like the Mapbox example if you want the same behavior. Without the option the location is only retrieved once and there is no "stop."

**Comment by ThomasG77** [comment]
Thanks. Sorry for the noise!
