### ISSUE TITLE
[Bug] Crash in maplibre-gl in GeolocateControl when mapStyle fails to load

### ISSUE THREAD

**Issue by bgeihsgt** [visgl/react-map-gl#2152]
### Description

I filed a PR originally against `maplibre-gl`, but after discussing with them, because this is based on `react-map-gl` calling private APIs, it felt more appropriate to file it here. Here's that issue for reference: https://github.com/maplibre/maplibre-gl-js/issues/2357

Please note that we don't have a consistent repro for this, but we have seen this crash occur in our production error logging.

react-map-gl versoin: 7.0.21
maplibre-gl-js version: 2.4.0

browser: Safari/Mobile Safari

### Expected Behavior

Gracefully handling this failure instead of crashing

### Steps to Reproduce

We don't have a live repro because it requires a specific intermittent failure mode. But here is what we're seeing:

Our error log crashes with:

```UnhandledPromiseRejectionWarning: TypeError: undefined is not an object (evaluating 'this._map._getUIString')```

This is happening inside `_setupUI` within maplibre-gl's GeolocateControl. (Our code uses a structure like `<Map><GeolocateControl /></Map>` ). Each error log we see is accompanied by a failure to load api.maptiler.com map style JSON that we're passing to the `Map` `mapStyle` property.

In inspecting through the react-map-gl code, I noticed this code snippet:

https://github.com/visgl/react-map-gl/blob/v7.0.21/src/components/geolocate-control.ts#L80-L85

It looks like this is firing, but `this._map` is not defined in maplibre's `GeolocateControl`, presumably because of the style load failure.

### Environment

- Framework version: 7.0.21
- Map library: mablibre-gl 2.4.0
- Browser: Safari/Mobile Safari
- OS: MacOS/iOS

**Comment by bgeihsgt** [comment]
Note we could trivally add a check for `gc._map` as a stopgap solution here, but I wasn't sure if that would work consistently across all map providers. Thanks.

**Comment by Pessimistress** [comment]
Responded to the maplibre thread: https://github.com/maplibre/maplibre-gl-js/issues/2357#issuecomment-1502147196

Feel free to reopen if the maplibre update does not fix your issue.
