### ISSUE TITLE
[Bug] onClick, onMouseEnter and onMouseLeave doesn't work as expected on v7.0.22

### ISSUE THREAD

**Issue by massimopalmieri** [visgl/react-map-gl#2157]
### Description

I upgraded from v7.0.21 to v7.0.22 and the map onClick handler doesn't seem to behave as expected

### Steps to Reproduce

this is the reproduction with v7.0.21
https://stackblitz.com/edit/react-ts-dlkyvx?file=MapView.tsx,Layer.tsx,package.json

when clicking on a feature the map flies to the clicked feature

this is exactly the same code with v7.0.22
https://stackblitz.com/edit/react-ts-8fmcek?file=MapView.tsx,Layer.tsx,package.json

you can see that onMouseEnter and onMouseLeave also don't work as expected

### Environment

- Framework version: react-map-gl@7.0.22
- Map library:  mapbox-gl@2.13.0
- Browser: Google Chrome Version 111.0.5563.146 (Official Build) (arm64)
- OS: MacOS Venture 13.2.1

**Comment by Pessimistress** [comment]
Try v7.0.23.
