### ISSUE TITLE
[RFC] v7.1 Changes

### ISSUE THREAD

**Issue by Pessimistress** [visgl/react-map-gl#2161]
### Target Use Case

The next minor release

## Dependency

In v7.0, if `Map` is used with a forked library such as `maplibre-gl`, bundlers still require a package named `mapbox-gl` to be installed. This is because the `mapLib` prop is default to `import('mapbox-gl')`, which prompts the bundler to look for this dependency. This has caused confusion among users. It is currently addressed in the [documentation](https://github.com/visgl/react-map-gl/blob/7.0-release/docs/get-started/get-started.md#using-with-a-mapbox-gl-fork) by installing an empty placeholder.

To move away from this implicit behavior, I'm proposing to drop `mapbox-gl` as a hard dependency. Which involves:
- Making `Map` component's `mapLib` a required prop - this will be a breaking change for `mapbox-gl` users.
- Making `mapbox-gl` an optional peerDependency leveraging [peerDependencyMeta](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependenciesmeta).
- Adding `maplibre-gl` as an optional peerDependency.

## TypeScript

`mapbox-gl` and `maplibre-gl` have diverged further since the initial release of v7.0. Using `@types/mapbox-gl` as the type definition for both fails to address the difference.

Moving forward, the `Map` component will take a genric type e.g. `Map<MapboxMap>` or `Map<MaplibreMap>`. This will allow `maplibre-gl` users to leverage native types and more gracefully handle the divergence between the two libraries.

**Comment by HarelM** [comment]
Thanks for pushing forward the Maplibre support! If there are any issues which needs to be addressed in Maplibre as part of this change please let us know and we'll be happy to help out!

**Comment by ibgreen** [comment]
This makes sense, the empty mapbox package install solution seemed very technical.

I am sure you have lots of thoughts, but naively it seems that might start to make sense to consider moving this repo to a "monorepo", publishing two modules, one per basemap library:
- e.g. `react-map-gl` and `react-maplibre-gl`, 
- (and perhaps a common helper module `react-map-gl-utils` with common code.) 
- That would allow these basemap specific modules to take advantage of the base map library typings more fully. 

We could let the feature richness in each module vary with the support we got from each base map developer.

**Comment by Pessimistress** [comment]
`v7.1.0-beta.1` is published.

See the [upgrade guide](https://github.com/visgl/react-map-gl/blob/master/docs/upgrade-guide.md#upgrading-to-v71) if you wish to take it for a spin.

**Comment by KiwiKilian** [comment]
The `source` prop on `Layer` is now required in TypeScript, is this intended as part of the RFC?

**Comment by Pessimistress** [comment]
@KiwiKilian This hasn't changed from v7.0, but I do agree that the `source` prop should not be required (technically only when `Layer` is rendered as a child of `Source`, but TypeScript cannot check for that).

**Comment by Pessimistress** [comment]
`v7.1.0-beta.3` is published. Examples on the master branch are now using v7.1. If no other issues come up we will release to production next week.

**Comment by Pessimistress** [comment]
`v7.1.0` is now available. Please open a new issue if you run into any problems!
