### ISSUE TITLE
[Bug] Map resizing breaks with maplibre-gl@next and `reuseMaps` after map instance is reused

### ISSUE THREAD

**Issue by viliket** [visgl/react-map-gl#2166]
### Description

**Background**

Upcoming maplibre-gl next major version 3 ([maplibre-gl@3.0.0-pre.5](https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md#300-pre5)) introduced the following breaking change: https://github.com/maplibre/maplibre-gl-js/pull/2157
> [Breaking] Resize map when container element is resized. the resize related events now has different data associated with it (https://github.com/maplibre/maplibre-gl-js/pull/2157)
Previously the originalEvent field was the reason of this change, for example it could be a resize event from the browser
Now it is ResizeObserverEntry, see more https://developer.mozilla.org/en-US/docs/web/api/resizeobserverentry

Basically, now in maplibre-gl Map constructor, it sets up a ResizeObserver to observe the map container element (see relevant line here <https://github.com/maplibre/maplibre-gl-js/blob/78af21d750494e8cee5e256c300589cf9ff25d6b/src/ui/map.ts#L484>).
```
...
this._resizeObserver.observe(this._container);
...
```

**The bug**

The above breaking change in maplibre-gl causes a bug when using it as react-map-gl's as `mapLib` **when `reuseMaps` option is set** on the react-map-gl Map because the react-map-gl's static method [`Mapbox.reuse`](https://github.com/visgl/react-map-gl/blob/master/src/mapbox/mapbox.ts#L471) does not instruct the maplibre-gl's Map instance's `_resizeObserver` to observe the new container when the old maplibre-gl Map instance is reused.

Because of this bug, after the old maplibre-gl Map instance is reused again in a new container, the map (canvas) is no longer resized when its container resizes.

See the following gif visualizing the bug:

![react-map-gl-maplibre-resize-bug](https://user-images.githubusercontent.com/25618592/233766743-af2bb3a7-bfdc-4b8c-9223-7b336418aed2.gif)

In the gif above, you can see that when the map is loaded (and used) the first time (when user navigates to "Page 1") the map resizing works properly when the container is resized. However, after the user navigates back to "Home" page and then again to "Page 1" the react-map-gl reuses the same map instance under the hood and the map no longer resizes properly when the container is resized (because the ResizeObserver is not properly observing the new container).

**Proposed fix**

Because of the breaking change introduced in the upcoming maplibre-gl v3, react-map-gl needs to update the static method [`Mapbox.reuse`](https://github.com/visgl/react-map-gl/blob/master/src/mapbox/mapbox.ts#L471 to properly instruct the reused maplibre-gl's Map instance's `_resizeObserver` to stop observing the previous container and begin observing the new container, i.e.,

`src/mapbox/mapbox.ts`

```js
...
export default class Mapbox {
  static reuse(props: MapboxProps, container: HTMLDivElement) {
    ...
    const oldContainer = map.getContainer();
    ...
    // Step2: replace the internal container with new container from the react component
    // @ts-ignore
    map._container = container;

    // New code:
    if (map._resizeObserver) {
      // maplibre-gl Map uses ResizeObserver to observe when its container resizes
      // Tell the ResizeObserver to unobserve currently observed elements and observe the new container
      map._resizeObserver.disconnect(); // or instead: map._resizeObserver.unobserve(oldContainer);
      map._resizeObserver.observe(container);
    }

    ...
  }
}
...
```

### Expected Behavior

The map (canvas) should resize properly when using latest maplibre-gl@next as the `mapLib` of the react-map-gl Map with the `reuseMaps` set and when reusing the same map instance.

### Steps to Reproduce

See the following Code Sandbox to reproduce the behavior also visualized in the earlier gif <https://codesandbox.io/s/late-fire-ykw04b>.
1. Navigate to "Page 1".
2. Try resizing the view. You should see that the map is properly being resized based on its container.
3. Navigate to "Home".
4. Navigate again to "Page 1".
5. Try resizing the view. You should see that the map is no longer properly being resized.

### Environment

- Framework version: react-map-gl@7.0.23
- Map library: maplibre-gl@3.0.0-pre.5
- Browser: Chrome 112.0 / Firefox 111.0
- OS: Windows 10 (also reproduced on Android 13 Chrome)

**Comment by Pessimistress** [comment]
Would you open a PR for the proposed change?
