### ISSUE TITLE
[Bug] unable to run with CRA

### ISSUE THREAD

**Issue by martinjuhasz** [visgl/react-map-gl#2167]
### Description

I'm using CRA with `react-app-rewired` and somehow when deploying `react-map-gl` it fails to load the tiles.
The error i see is
```
An error occurred while parsing the WebWorker bundle. This is most likely due to improper transpilation by Babel; please see https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling 4c2326de-1504-4cf4-913b-8260437c626e:1:37
ReferenceError: y is not defined
```

So it seems that CRA is transpiling `mapbox-gl`. If i read correctly here, `react-map-gl` should take care that his doesn't happen. I tried differnt things to exclude it, but without luck.

Any idea why this could happen? I have no imports of `mapbox-gl` directly in my code, only using `react-map-gl`.

Any help appreciated

### Expected Behavior

`mapbox-gl` should not be transpiled when using `create-react-app`

### Steps to Reproduce

I tried reproducing this behaviour in a sandbox, but that didn't work

### Environment

- Framework version: react-map-gl@7.0.21
- Map library: mapbox-gl@2.14.1
- Browser: any
- OS: any

**Comment by Pessimistress** [comment]
#1266

**Comment by martinjuhasz** [comment]
oh, well, this issue totally went by my search terms. thanks for this!
