### ISSUE TITLE
[Bug] Zoom-dependant styling ignored

### ISSUE THREAD

**Issue by abenrob** [visgl/react-map-gl#2185]
### Description

When applying a zoom-based functional expression for styles, there is no change when zooming.

### Expected Behavior

A paint style such as 

```js
"circle-radius":  [
  'interpolate',
  ['linear'],
  ['zoom'],
  6, 2,
  15, 6
]
```

Should result in the circle radius being 2 at z6, scaling linearly to 6 at z15.

### Steps to Reproduce

https://stackblitz.com/edit/react-mapbox-deckgl-77utkc?file=src%2FApp.js

### Environment

- Framework version: 7.0.25
- Map library: maplibre-gl 3.0.0
- Browser: firefox 113.0.1 (64-bit)
- OS: macOS Monterey v12.5

**Comment by Pessimistress** [comment]
This library does not handle rendering. Please report any bugs to the base map's repo.
