### ISSUE TITLE
[Bug] text-field appears to be completely broken

### ISSUE THREAD

**Issue by andokai** [visgl/react-map-gl#2203]
### Description

I'm trying to add a text label to a GeoJSON feature but as soon as I add `text-field` to the `layout` object the map crashes. 

### Expected Behavior

I expect text-field to work as described in the docs and shown in the examples.

### Steps to Reproduce

https://codesandbox.io/s/cool-waterfall-c3xr92?file=/src/index.js

This is a slightly updated version of the earthquake example. See how it all renders fine, but when the `text-field` prop is uncommented, the map crashes with `Error {message: 'Unimplemented type: 3'}`.

### Environment

- Framework version: react-map-gl@7.0.25
- Map library: mapbox-gl@1.13.3 and also maplibre@3.0.1
- Browser: Chrome 114.0 & Safari 16.5
- OS: macOS Ventura 13.4

### Logs

`Error {message: 'Unimplemented type: 3'}`

**Comment by Pessimistress** [comment]
Rendering is not implemented by this library. You should report any issue you have to mapbox-gl.

**Comment by andokai** [comment]
Apologies
