### ISSUE TITLE
[Bug] Bounds of type mapboxgl.LngLatBounds when used with mapLibre

### ISSUE THREAD

**Issue by marekherda** [visgl/react-map-gl#2214]
### Description

Hello and thank you for this awesome library!

I am using react-map-gl with mapLibregl in the following way:
```
<Map
         zoom={zoom}
         initialViewState={viewState}
         mapLib={maplibregl}
         mapStyle="mapbox://styles/mapbox/satellite-streets-v11"
         transformRequest={transformRequest}
         onMove={(event: ViewStateChangeEvent) => {
             const bounds = event.target.getBounds();
             dispatch(mapMoved(bounds));
         }}
/>
```

The issue I'm facing is that the `bounds` are of type `mapboxgl.LngLatBounds` even though I'm using mapLibre. `mapMoved` function is expecting `bounds` of type `LngLatBounds` from maplibre-gl.

### Expected Behavior

`bounds` type is LngLatBounds from maplibre library (`import { LngLatBounds } from 'maplibre-gl';`)

### Steps to Reproduce

Use `getBounds()` method when using `<Map mapLib={malibregl} />`

### Environment

- Framework version: 7.0.25
- Map library: mapLibre
- Browser: Chrome
- OS: Ubuntu

**Comment by Pessimistress** [comment]
Can you try v7.1.0-beta? https://github.com/visgl/react-map-gl/blob/master/docs/upgrade-guide.md
