### ISSUE TITLE
[Bug] TS errors using mapbox-gl after upgrade to 7.1.2

### ISSUE THREAD

**Issue by ssaornil** [visgl/react-map-gl#2226]
### Description

After upgrading to 7.1.2 (from 7.0.25) there are a lot of type errors. It looks like the mapbox version types include references to maplibre.

### Expected Behavior

No type errors when using the mapbox types.

### Steps to Reproduce

I prepared a [codesandbox](https://codesandbox.io/s/react-map-gl-types-4hj3rz?file=/src/App.tsx) with an example using a few components where you'll see several type errors in the props.

If you look at the errors you'll see they are all referring to maplibre types.

### Environment

- Framework version: react-map-gl@7.1.0
- Map library: mapbox-gl@2.15.0

**Comment by JakeSaterlay** [comment]
Did you come across a fix for these? I am having a similar issue, particularly on `LayerProps` and the `mapStyle` prop on the map, which you have included in your example

**Comment by ssaornil** [comment]
The problem for the style specification is caused by [this line](https://github.com/visgl/react-map-gl/blob/16f886054892a0027d43077eb4bd13db66a5df93/src/types/style-spec.ts#L23)

I guess that should be imported differently depending on whether we use mapbox or maplibre.

I didn't work on a fix. For now we are "skipping" all TS checks for the offenders in our code.

**Comment by Pessimistress** [comment]
Fixed in v7.1.4.
