### ISSUE TITLE
[Bug] Layers don't render on certain map styles from v7.1

### ISSUE THREAD

**Issue by HelloTiago** [visgl/react-map-gl#2228]
### Description

First of all, just wanted to say thanks for your work on this, it's been very helpful!

After updating to react-map-gl 7.1.2 I noticed that layers added using the `<Layer>` component stopped showing up on the map when using certain map styles.

For example with `mapbox://styles/mapbox/streets-v9` everything loads perfectly but when I use `mapbox://styles/mapbox/streets-v12` or `mapbox://styles/mapbox/light-v11` the layers don't show up anymore.

v7.0.21 and earlier versions don't have this problem.

### Expected Behavior

The layers should show up on every map style.

### Steps to Reproduce

- Open https://codesandbox.io/s/busy-cherry-p9jtr9?file=/src/index.js
- Set the access token
- Switch between `streets-v12` and `streets-v9` and notice the "Mapbox DC" / "Mapbox SF" labels on the map.

### Environment

- Framework version: react-map-gl@7.1.2
- Map library: mapbox-gl@2.15.0
- Browser: Brave Version 1.52.130 Chromium: 114.0.5735.198 (arm64)
- OS: macOS Ventura 13.4.1

**Comment by Pessimistress** [comment]
v7.1 removed default props on `<Map>` and always use the base library's defaults.
streets-v12 uses globe projection, see https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
There is a standing bug where symbols are not rendered correctly in globe mode at certain zoom levels.

You can work around it by explicitly setting `projection="mercator"` on the map.

**Comment by HelloTiago** [comment]
Setting the projection worked perfectly. Thank you for the fast response!

**Comment by Pessimistress** [comment]
Fixed in v7.1.3.
