### ISSUE TITLE
[Bug] Types: `MapLayerMouseEvent`: `event.lngLat` types are missing `toArray()`

### ISSUE THREAD

**Issue by tordans** [visgl/react-map-gl#2239]
I had the following code in `7.0.23`.  Which – I guess – used those types (?) https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L1649-L1671 which expose the `toArray` method. As does maplibre with https://github.com/maplibre/maplibre-gl-js/blob/main/src/geo/lng_lat.ts#L97-L99

```
  const handleClick = (event: MapLayerMouseEvent) => {
    const clickedPoint = point(event.lngLat.toArray())
    console.log(clickedPoint)
  }
```

Now, after updating to `7.1.2` I get the error …

>⚠ Error (TS2339)  | 
>Property toArray does not exist on type 

<img width="793" alt="image" src="https://github.com/visgl/react-map-gl/assets/111561/61ea1281-efbc-44ba-8140-bd2f6bb7f43e">

---

I can jump to https://github.com/visgl/react-map-gl/blob/master/src/types/events.ts#L1 in VS Code which imports the `LngLat` from `./common`. And when I follow this in Github, I see https://github.com/visgl/react-map-gl/blob/master/src/types/common.ts (unfortunately, when using VS Code to open common.js, I only see `export {}; //# sourceMappingURL=common.js.map` which is not that helpful but probably a different issue…)

However, the interface in https://github.com/visgl/react-map-gl/blob/master/src/types/common.ts#L11-L14 is not in line with the Types given by the first [two](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L1649-L1671) [links](https://github.com/maplibre/maplibre-gl-js/blob/main/src/geo/lng_lat.ts#L97-L99). The react-map-gl interface does not have the toArray() helper.

---

Workaround: `point([event.lngLat.lng, event.lngLat.lat])`

**Comment by Pessimistress** [comment]
Fixed in v7.1.4.
