### ISSUE TITLE
Circle Layer works, but Fill or Line layer does not. Can't display polygons on the map. [Bug]

### ISSUE THREAD

**Issue by GiovanniIncammicia** [visgl/react-map-gl#2242]
### Description

I have a simple map where I want to display a few polygons from geojson data. Here is my code:
[https://sharetext.me/npepoog4pl](https://sharetext.me/npepoog4pl)

I use this mapstyle: mapbox://styles/mapbox/streets-v11

I can see the point, but not the polygon. I'm sure the coordinates are correct, because I copied them from a polygon I drawn directly on the map with @mapbox/mapbox-gl-draw.

I tried commenting out the different layers and changing the configuration a bit, but I can't display the polygon in any way.

### Expected Behavior

I expected to see the point AND the polygon. I only see the point.

### Steps to Reproduce

- create a React project with the code above
- add the necessary props to the Map component (mapStyle and mapboxAccessToken)
- run the code

### Environment

- Framework version: next: 13.4.10, react: 18.2.0
- Map library: mapbox-gl: 2.15.0, react-map-gl: 7.1.2,
- Browser: Chrome
- OS: Windows 11

**Comment by Pessimistress** [comment]
Same as #2228?

**Comment by GiovanniIncammicia** [comment]
Hi, thank you for the quick response. That looks very promising, I tried switching between the map styles and applying
`projection={{ name: 'mercator' }}`
to my code, but still doesn't work. :(
