### ISSUE TITLE
[Bug] Exported `MapGeoJSONFeature` and `MapLayerMouseEvent.features` mismatch for maplibre

### ISSUE THREAD

**Issue by KiwiKilian** [visgl/react-map-gl#2266]
### Description

When using maplibre the type `MapGeoJSONFeature` is exported from `react-map-gl/src/types/common.ts` as:
```ts
export type MapGeoJSONFeature = GeoJSON.Feature<GeoJSON.Geometry> & {
  layer: any;
  source: string;
  sourceLayer: string;
  state: {[key: string]: any};
};
```

 The `MapLayerMouseEvent` features `MapGeoJSONFeature` are typed from `maplibre-gl/dist/maplibre-gl.d.ts`:
 ```ts
export type MapGeoJSONFeature = GeoJSONFeature & {
	layer: DistributiveOmit<LayerSpecification, "source"> & {
		source: string;
	};
	source: string;
	sourceLayer?: string;
	state: {
		[key: string]: any;
	};
};
```

### Expected Behavior

The types should match. Will this be fixed by #2263?

### Steps to Reproduce

https://codesandbox.io/s/react-map-gl-mapgeojsonfeature-h698nj?file=/src/index.tsx:608-636

### Environment

- Framework version: react-map-gl@7.1.4
- Map library: maplibre-gl@3.3.0

**Comment by Pessimistress** [comment]
Try v7.1.5.

**Comment by KiwiKilian** [comment]
Looks good 🙏!
