### ISSUE TITLE
Polyline not being render on production server [Bug]

### ISSUE THREAD

**Issue by hyderly** [visgl/react-map-gl#2273]
### Description

We're building a truck routing application based on ReactJS. We're using react-map-gl and mapbox-gl for maps and rending polyline in it. We're using PTV api's for generating polyline which is a 3rd party api's. In our case, everything working very fine in local runtime and production as well, but the polyline is not being rendered in the production server. In our case, the polyline always be very long like city to city or country or country. Our production server for Reactjs is Netlify.

There is not error on console from mapbox or react-map-gl and polyline from PTV working as well.

### Expected Behavior

Polyline should be render on production server as well.

### Steps to Reproduce

 <Map
    height="100%"
    width="100%"
    mapStyle={mapStyle}
    {...intialView}
    onMove={evt => setInitalView(evt.viewport)}
    transformRequest={(url, resourceType) => getTransformRequest(url, resourceType)}
    mapboxAccessToken={process.env.REACT_APP_MAPBOX_ACCESS_TOKEN}
  >
  
      {
        points1 && <Source id="geojson-line-1" type="geojson" data={points1}>
        <Layer
          id="polyline-layer-1"
          type="line"
          paint={{
            'line-color': 'green',
            'line-width': 4,
          }}
        />
      </Source>
      }

      {
        points2 && <Source id="geojson-line-2" type="geojson" data={points2}>
        <Layer
          id="polyline-layer-2"
          type="line"
          paint={{
            'line-color': 'red',
            'line-width': 4,
          }}
        />
      </Source>
      }
      

      

    {renderMarkers()}
    <NavigationControl style={navControlStyle}/>
  
    <FullscreenControl/>
    
  </Map>

### Environment

Packages with versions:
"mapbox-gl": "^1.13.2" and  "react-map-gl": "^7.0.25",

Browser: 
Laster Chrome version.

Frontend Server:
Netlify

**Comment by Pessimistress** [comment]
The code you shared is insufficient to reproduce your problem. I also want to point out that this library is merely a wrapper of mapbox-gl and does not do any rendering itself.

Unless you have a clear idea where the bug is, or have the full code/deployment setup that can be use to reproduce your issue, I suggest you move this to Discussions.

**Comment by hyderly** [comment]
> geojson

That's totally unresponsive reply. I think the problem is cleared above. There is no error on local runtime and on builds well but polyline not being rendering on with builds, I think the main problem is with versions.
