### ISSUE TITLE
[Bug] 3D glob view randomly pops up when switching map style

### ISSUE THREAD

**Issue by neelduttahere** [visgl/react-map-gl#2288]
### Description

Using the `<Map/>` component from `react-map-gl` inside `<DeckGL/>`. I am dynamically changing the input for `mapStyle` prop in `<Map/>` component, and it works. However, when at zoom levels between 0 - 5,  switching map styles causes the map to get transformed into a globe. 

### Expected Behavior

The map should remain in it's default projection.

### Steps to Reproduce

Below is my code: 

``` js
<Map
    mapboxAccessToken={import.meta.env.VITE_MAPBOX_TOKEN}
    mapStyle={mapStyle.style}
    attributionControl={false}
 />
```

Here `mapStyle.style` can be a local or redux state. To reproduce, I would suggest using redux, though that will not make a difference.

Steps to reproduce:

1. Zoom out to a zoom level between 0-5
2. Programmatically update state `mapStyle.style`, to change mapbox style via user interaction event (can be a toggle switch, button, anything)
3. The map turns from an orthographic projection to a 3D globe.

### Environment

- Framework version: 7.1.3
- Map library: Mapbox
- Browser: Tested on all
- OS: Tested on Windows, Mac & Linux

**Comment by Pessimistress** [comment]
The default projection is defined by the map style. Some map styles use globe projection, as you can see [here](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/).

If you still think there is a bug, please report:
- the map styles that you are using
- the exact version of react-map-gl and mapbox-gl that you have installed

**Comment by neelduttahere** [comment]
Hey @Pessimistress ,
Changing the projection settings for the styles I am using, from Mapbox studio did the trick, by default they were set to Globe projection. Thanks for the info though!
