### ISSUE TITLE
[Bug] useControl not working correctly in strict mode

### ISSUE THREAD

**Issue by Alexnortung** [visgl/react-map-gl#2289]
### Description

the `useControl` hook creates the control twice when using strict mode.

It seems like [an incorrect use of `useMemo`](https://github.com/visgl/react-map-gl/blob/163e07d48dcf5f27ce9031ed7c9456e552e850dd/src/components/use-control.ts#L35C29-L35C29)

### Expected Behavior

I would expect the hook to correctly remove the control on unmount.

### Steps to Reproduce

https://codesandbox.io/s/cranky-dust-t7l97m?file=/src/index.js

### Environment

- Framework version: ^18
- Map library: ^7.1.0
- Browser: Firefox
- OS: NixOS

**Comment by Pessimistress** [comment]
`useControl` calls `map.removeControl` on unmount, which is the correct behavior for strict mode. Some native controls, such as GeolocateControl in your example, do not properly remove their async operation callbacks on removal. See https://github.com/visgl/react-map-gl/blob/7.1-release/src/components/geolocate-control.ts#L46
