### ISSUE TITLE
Nextjs error

### ISSUE THREAD

**Issue by 1mehdifaraji** [visgl/react-map-gl#2311]
### Description

React map gl won't run on next js and produces an error message :

```TypeError: Cannot read properties of undefined (reading '0')```

Here is [CodeSandbox](https://codesandbox.io/p/sandbox/github/visgl/react-map-gl/tree/7.0-release/examples/get-started/nextjs?file=%2Fpackage.json%3A1%2C1)

### Steps to Reproduce

[https://codesandbox.io/p/sandbox/github/visgl/react-map-gl/tree/7.0-release/examples/get-started/nextjs?file=%2Fpackage.json%3A1%2C1](https://codesandbox.io/p/sandbox/github/visgl/react-map-gl/tree/7.0-release/examples/get-started/nextjs?file=%2Fpackage.json%3A1%2C1)

### Environment

- Framework version:  react-map-gl@7.0.0
- Map library: mapbox-gl@2.0.0
- Browser: Edge
- OS: MacOS 13

**Comment by Pessimistress** [comment]
I don't see that error in your sandbox. Do you mind posting the full error stack?

**Comment by 1mehdifaraji** [comment]
@Pessimistress Well I'd like to know why you couldn't see the error but here is the screenshot :

![Screenshot 1402-08-17 at 20 24 18](https://github.com/visgl/react-map-gl/assets/63982703/f40d5a38-0de6-44b2-a385-177907d01649)

**Comment by Pessimistress** [comment]
Are you only seeing these errors in CodeSandbox? Your project seems identical to https://github.com/visgl/react-map-gl/tree/master/examples/get-started/nextjs and I can run the example locally without any issue.

**Comment by 1mehdifaraji** [comment]
@Pessimistress Seems like the issue was the missing  mapbox token , It would be great If the error message was something like `Missing token` . I included the mapbox token and it works perfectly fine on my local machine and codesandbox .

**Comment by Pessimistress** [comment]
Since I can't reproduce your issue, I can only comment that Mapbox does print an error message when the token is invalid.
