### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'point')

### ISSUE THREAD

**Issue by force9493** [visgl/react-map-gl#2336]
### Description

I have installed react-map-gl and maplibre-gl in my react project.
I displayed map correctly. Also, I zoomed the map and moved several times.
In this case, I can get the following errors.

![Screenshot at Jan 08 09-03-42](https://github.com/visgl/react-map-gl/assets/54977839/0705f583-9c6b-4ed0-8ba0-cad6753e3ede)

How can I fix this error?

### Expected Behavior

When I use mapbox-gl and react-map-gl, there are no such errors. I want to get the same result when using maplibre-gl as well.

### Steps to Reproduce

This is the source code that I used.

import Map from 'react-map-gl/maplibre';
const MapContainer = () => {
    ...
    
    return (
        <Map 
              mapStyle={mapStyle}
              initialViewState={{
                latitude: initViewport.latitude,
                longitude: initViewport.longitude,
                zoom: initViewport.zoom,
                pitch: initViewport.pitch,
                bearing: initViewport.bearing,
              }}
              maxBounds={initViewport.maxBounds}
              maxZoom={initViewport.maxZoom}
              minZoom={initViewport.minZoom} />
    );
};

### Environment

Framework version: react-map-gl@7.1.7
Map library: maplibre-gl@3.3.1
Browser: Chrome 98.0
OS: Windows, Mac

**Comment by force9493** [comment]
Hi, everyone.
Please help me if you have ever met this error.

**Comment by Pessimistress** [comment]
We cannot reproduce your issue with the code provided, please create a sandbox.

Issues are for reporting bugs in this library. If you are not sure where the problem is, use Discussions.

**Comment by force9493** [comment]
@Pessimistress Thanks for your reply.
You can easily test in the following codesandbox URL (https://codesandbox.io/p/sandbox/react-map-gl-maplibre-gl-forked-rqy9f9). Please check that and tell me your suggestion.
When zooming the buildings(especially cornors) of the map, you can see the following errors.

![image](https://github.com/visgl/react-map-gl/assets/54977839/1c595088-3787-46b0-a6af-7cd47012852d)

**Comment by Pessimistress** [comment]
Thanks. I can reproduce the error, but as far as I can tell the error originates in maplibre-gl's renderer. You can try your map style with maplibre-gl directly (without React) and if the issue persists, you should report it to Maplibre.
