### ISSUE TITLE
[Bug] Quickly double-clicking on maps prevents zooming in

### ISSUE THREAD

**Issue by gemueselasagne** [visgl/react-map-gl#2339]
### Description

Map stays at same zoom level when trying to quickly zoom in with quick back-to-back double-clicks

https://github.com/visgl/react-map-gl/assets/10177993/0282730b-c2d7-4963-8697-209887008b28

### Expected Behavior

Quickly double-clicking on a map should zoom into the map even if an initiated zoom is still animating. Behaviour just like e.g. Google Maps

### Steps to Reproduce

Double-click quickly in any map e.g. here: https://visgl.github.io/react-map-gl/examples/layers

### Environment

- Framework version: LATEST
- Map library: LATEST
- Browser: Safari
- OS: macOS 14.2.1

**Comment by Pessimistress** [comment]
This library is a wrapper of the map library, it does not handle any user inputs. You should ask in mapbox-gl's repo.
