### ISSUE TITLE
Updating the accessToken doesn't update the API call and crash

### ISSUE THREAD

**Issue by JoseLuisGJ** [visgl/react-map-gl#2340]
### Description

I'm trying to update the `accessToken` `username` and `customStyleID` props to the `Map` object, seems that last two are updated and it makes the call to the API with the updated values, but seems whenever I try to update the `accessToken` it always uses the first value provided and throws an error crashing the map rendering.

<img width="846" alt="Screenshot 2024-01-12 at 14 08 59" src="https://github.com/visgl/react-map-gl/assets/3108788/537f6ca7-2f4c-4abf-81c1-4d60ac2db461">

### Expected Behavior

I'm trying to allow users to provide their own credentials `accessToken` `username` and `customStyleID` in order to update on the fly the values to the already existing map.

### Steps to Reproduce

https://github.com/JoseLuisGJ/figmap/tree/managing-accessToken

### Environment

- Framework version: react-map-gl@5.2.9
- Browser: Figma Plugin

### Logs

First trace are the states values in React, and the the API call doesn't update the `accessToken` whereas it does with `username` and `customStyleID`
<img width="1301" alt="Screenshot 2024-01-12 at 14 19 52" src="https://github.com/visgl/react-map-gl/assets/3108788/75cc950c-6140-4645-8c48-cf14fcc03d52">

**Comment by Pessimistress** [comment]
From the Map component documentation:

> ... props in this section are not reactive. They are only used once when the Map instance is constructed.

https://visgl.github.io/react-map-gl/docs/api-reference/map#other-options

If you have an advanced scenario you may be able to handle it with `transformRequest` instead.
