### ISSUE TITLE
[Bug] Can't set configuration property for map

### ISSUE THREAD

**Issue by ShafSpecs** [visgl/react-map-gl#2341]
### Description

I am having trouble setting config presets for mapbox standard style, an issue apparently not found in `mapbox-gl`. Was wondering how to merge the two together

### Expected Behavior

Using `mapbox-gl` example, I should be able toset properties via:
```ts
map.on('style.load', () => {
  map.setConfigProperty('basemap', 'lightPreset', 'night')
})
```
but right now, I can't access the `config` or `imports` property of map styles

https://docs.mapbox.com/mapbox-gl-js/example/set-config-property/

### Steps to Reproduce

- Load up standards map (`mapbox://styles/mapbox/standard``)
- Attempt to set style config via the `map`

### Environment

- Framework version: 7.1.7
- Map library: Mapbox
- Browser: Chrome
- OS: Windows

**Comment by Pessimistress** [comment]
#2254
