### ISSUE TITLE
[Bug] ssr support missing example to await for geocoder results

### ISSUE THREAD

**Issue by wibed** [visgl/react-map-gl#2354]
### Description

ssr support works fine for mapboxgl

yet an example for ssr support on geocoder results is missing out 

### Steps to Reproduce

-

### Environment

- Framework version:
- Map library:
- Browser:
- OS:

**Comment by Pessimistress** [comment]
Issues are for reporting bugs in the library. Use Discussions if you need help with its usage.

**Comment by wibed** [comment]
please kindly reopen. bugs are not exclusive to the library it includes documentation and examples aswell.

**Comment by wibed** [comment]
i worked around it by 
- ditching the suggestion wrapper (`display: none`)
- storing results in a state in parent (pass it to geocoder by using `onResults` function)
- add custom dropdown and use mapRef.flyTo to link your results to any center
