### ISSUE TITLE
[Bug] incompatible dom objects within the react landscape

### ISSUE THREAD

**Issue by wibed** [visgl/react-map-gl#2358]
### Description

afaik geocoder produces an wrapped input htmlelement which i am unable to convert into a viable react.element.

i tried something along those lines:

```tsx

        const geocoderNode: HTMLElement = ctrl.onAdd(mapboxMap)

        const geocoderInputChildren = Array.from(geocoderNode.children).filter(el => el.tagName.toLowerCase() === "input")
        if (geocoderInputChildren.length === 0) { throw new Error("missing input element") }
        const geocoderInput: HTMLInputElement = geocoderInputChildren[0] as HTMLInputElement

        const geocoderInputNode = React.createElement(
          geocoderInput.tagName.toLowerCase(),
          { class: geocoderInput.className, type: "text", placeholder: "Search", ariaLabel: "Search" }
        )

        const GeocoderNode: JSX.Element = React.createElement(
          geocoderNode.tagName.toLowerCase(), 
          { className: geocoderNode.classList },
          geocoderInputNode
        )
```

but done this way any connection to the events are lost.

only when i use above example like this i am able to keep the events
```tsx
        ...
        const geocoderNode: HTMLElement = ctrl.onAdd(mapboxMap)
        containerNode.appendChild(geocoderNode)
        ...
```

which breaks compatibility with react and its virtual dom.

how can i work around this to keep functionality and react compatibility?

why bother? you might ask.
id like to control the results from the input element via react-hook-form but unable to do so due to lack of compatibility.

### Expected Behavior

to have compatible dom objects

### Steps to Reproduce

-

### Environment

- Framework version:
- Map library:
- Browser:
- OS:

**Comment by wibed** [comment]
i have all these events within the browser:
![image](https://github.com/visgl/react-map-gl/assets/69305089/6d6be86e-0ea6-4cbc-bea2-c67e444fd8d7)


yet cant make out a single one within programatically
id access them like this
```tsx
        const geocoderNode = ctrl.onAdd(mapboxMap)
        // START INSPECTION HERE BUT...
        const geocoderInputChildren = Array.from(geocoderNode.children).filter(el => el.tagName.toLowerCase() === "input")
        if (geocoderInputChildren.length === 0) { throw new Error("missing input") }
        const geocoderInput= geocoderInputChildren[0]
        // ...CANT FIND ANY EVENTS PROGRAMMATICALLY
        containerNode.appendChild(geocoderNode)
```

what could be the reason
i am trying to copy the events over from a htmlelement into a compatible react element
i tried using the following 
```tsx
        const geocoderInputNode = React.createElement(
          geocoderInput.tagName.toLowerCase(),
          { className: geocoderInput.className, type: "text", placeholder: "Search", "aria-label": "Search" }
        )

        const GeocoderNode: JSX.Element = React.createElement(
          geocoderNode.tagName.toLowerCase(), 
          { className: geocoderNode.classList },
          geocoderInputNode
        )
```

expected to be successfull but ended up with these events instead
![image](https://github.com/visgl/react-map-gl/assets/69305089/1c0462c1-fb8d-4d0f-a897-793da2664478)

**Comment by Pessimistress** [comment]
What does this have to do with react-map-gl?

**Comment by wibed** [comment]
> What does this have to do with react-map-gl?

react-map-gl promises compatibility with react, appendChild is not a react function.
the useControl function does not expose the geocoder component in a react friendly manner it seems.

**Comment by Pessimistress** [comment]
react-map-gl is a wrapper of the base library, i.e. mapbox-gl and maplibre-gl. Geocoder is not part of the base library. There is no magic function that turns any random third party plugin into a React component. If you wish to implement your own React wrapper for geocoder, you are welcome to open a thread in Discussions, but this is outside of the scope of the library itself.
