### ISSUE TITLE
Need PerspectiveEnabled fitBounds method

### ISSUE THREAD

**Issue by MarshallChen** [visgl/react-map-gl#236]
In my use case I have to set MapGL viewport props dynamically by data, also when the data changed I want to change the map center (lng, lat) and zoom level automatically. is there have some calculate functions can I use? I looked around but can't find any proper way to do this. Any suggestions?

**Comment by ibgreen** [comment]
>  is there have some calculate functions can I use? 

@MarshallChen Depends on your needs. react-map-gl exports a `fitBounds` function but it only handles the flat (non-perspective) case. There is also the viewport-mercator-project module that react-map-gl relies on for most of its calculations.

**Comment by MarshallChen** [comment]
Yes! The return of `fitBounds` function is exactly what I need, thanks!

**Comment by MarshallChen** [comment]
I searched around and found [this question on stackoverflow](http://stackoverflow.com/questions/43713462/mapbox-gl-js-adjust-visible-area-bearing-to-a-given-line-for-a-given-pitch) asked few days ago, and indeed the answer is exactly want I need! Now I want to make sure is does `viewport-mercator-project` has the same ability, or I have to deal with those bunch of mathematic functions by my self like the answer does?

**Comment by ibgreen** [comment]
> Now I want to make sure is does viewport-mercator-project has the same ability, or I have to deal with those bunch of mathematic functions by my self like the answer does?

@MarshallChen Unfortunately mercator-viewport-project does not currently have this function. We always intended for mercator-viewport-project to offer this function, but we haven't gotten around to it. We'd welcome a PR...

That's a great SO article by the way, thanks for linking.

**Comment by wuweiweiwu** [comment]
@ibgreen Can I pick this issue up? 👍

**Comment by ibgreen** [comment]
@wuweiweiwu - Absolutely, go for it!

**Comment by vtambourine** [comment]
@ibgreen is this issue still in "help wanted" state?

**Comment by Pessimistress** [comment]
v7.0 now exposes the native `Map.fitBounds` method.
