### ISSUE TITLE
[Bug] [docs] Link to MapLibre API docs are broken

### ISSUE THREAD

**Issue by jamesscottbrown** [visgl/react-map-gl#2373]
### Description

The `react-map-gl` docs have a number of links to the `MaplibreGL JS` docs, which are now broken (this [GitHub search](https://github.com/search?q=repo%3Avisgl%2Freact-map-gl%20https%3A%2F%2Fmaplibre.org%2Fmaplibre-gl-js-docs&type=code) shows many, but not necessarily all, of them).

For example, this link: https://maplibre.org/maplibre-gl-js-docs/api/markers/

Has moved to: https://maplibre.org/maplibre-gl-js/docs/API/classes/Marker

### Expected Behavior

I expect links from the documentation to the MapLibre docs to work.

### Steps to Reproduce

1. Open this page of the docs: https://visgl.github.io/react-map-gl/docs/api-reference/marker

2. Click on the `Maplibre` link in 

> React component that wraps the base library's Marker class ([Mapbox](https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker) | [Maplibre](https://maplibre.org/maplibre-gl-js-docs/api/markers/#marker))

### Environment

N/A

**Comment by graue** [comment]
These links look still broken [on the website](https://visgl.github.io/react-map-gl/docs/api-reference/map#other-options), despite the fix having been merged into this codebase.
