### ISSUE TITLE
[Bug] Missing tiles breaks Layer props update

### ISSUE THREAD

**Issue by vnugent** [visgl/react-map-gl#2394]
### Description

I'm displaying custom tiles, a pmtiles file generated by Tippecanoe with max zoom = 8.  Without overzoom setting, `Source.maxzoom=8` I'm getting 404 errors at zoom level > 8, which breaks the Layer.visibility prop update logic.

```javascript
<Map ...>
  <Source 
    id='my-source'
    type='vector'
    tiles='https://my-tile-server.com/areas/{z}/{x}/{y}.pbf'
    maxzoom={8} // removing this will cause 404, bre
  >
    <Layer
      id='my-layer'
      layout={{ visible: visibleFlag ? 'visible' : 'none' }}
    /> 
  </Source>
</Map>
```

When tiles are not found, the toggle button no longer works.  I need to zoom/pan the map.

<img width="927" alt="Screenshot 2024-05-22 at 12 18 34 PM" src="https://github.com/visgl/react-map-gl/assets/3805254/1aa77ca1-01e1-4cf8-97fa-a6af563ad45c">

### Expected Behavior
Since I can't easily catch exceptions generated by the tile requests, the Layer prop should handle the exception.

### Steps to Reproduce

To reproduce you'll need a custom tile url with data capped at a zoom level.
https://codesandbox.io/p/sandbox/react-map-gl-404-props-4gn8cz

### Environment

- Framework version:  Next 13.5.6
- Map library: maplibre-gl 4.1.1, react-map-gl 7.1.7
- Browser: all
- OS: all

**Comment by Pessimistress** [comment]
Tile loading and rendering are not implemented in this library. You should report the bug to Maplibre instead.
