### ISSUE TITLE
Smooth easing on zoom

### ISSUE THREAD

**Issue by tomsiwik** [visgl/react-map-gl#241]
In my usecase the animation is chopped while zooming in. Currently mapbox-gl implements smooth easing on zoom events: https://www.mapbox.com/mapbox-gl-js/examples/

Highly appreciated feature if implemented :)

Related to: 
https://github.com/mapbox/mapbox-gl-js/pull/3189/commits/ecaba7508aaed9ee617ac1dc9ca2106e5e8c4063#diff-91ad654374133c7bf9558652da3838c1

**Comment by nicbor** [comment]
+1. It would be nice if react-ma-gl had smoothing on zoom, and mouse-drag "throwing" like mapbox-gl-gs.

**Comment by Bubbleinpit** [comment]
+1. This is such a natural requirement.

**Comment by julians** [comment]
+1

**Comment by chrtze** [comment]
Maybe you could try to set the `transitionDuration` and `transitionInterpolator` property on the Map component:

`<ReactMapGL transitionDuration={1000} transitionInterpolator={new FlyToInterpolator()}>`

Source: https://uber.github.io/react-map-gl/#/Documentation/api-reference/interactive-map?section=transitions

**Comment by tomsiwik** [comment]
@chrtze thanks for the suggestion. I think this might work. However I'm currently on a different project unrelated to map-gl. In an upcoming project or when I find some time I will use your idea.

**Comment by ugur47** [comment]
+1

**Comment by axleun** [comment]
+1 maps are so smooth on mapbox, why is it so slow on react-maps-gl?

**Comment by Bubbleinpit** [comment]
Sadly I think it's hopeless to get a smooth zoom using react-map-gl in the future. Because it's philosophy is to be "stateless". [It is designed to be a stateless component.](https://uber.github.io/react-map-gl/docs/get-started/state-management)

**Comment by Pessimistress** [comment]
This will be addressed in v5.3/v6.1. Currently available in `6.1.0-beta.1`.
