### ISSUE TITLE
Create Security Policy

### ISSUE THREAD

**Issue by bensternthal** [visgl/react-map-gl#2421]
### Description

As part of project graduation, every OpenJS project must have a security policy.

Minimal guidelines can be found [here](https://github.com/openjs-foundation/cross-project-council/blob/main/PROJECT_SECURITY_REPORTING.md) and project owners are encouraged to use GitHub's native [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) features that can be found under the "security" tab.

### Steps to Reproduce

N/A

### Environment

N/A

**Comment by chrisgervang** [comment]
https://github.com/visgl/react-map-gl/security/policy
