### ISSUE TITLE
Popup is not displayed after upgrading to v.7

### ISSUE THREAD

**Issue by an-dekhtyar** [visgl/react-map-gl#2432]
### Description

![Снимок экрана от 2024-10-10 13-08-44](https://github.com/user-attachments/assets/02eb973b-3214-4de1-9192-5bba8bcac6cf)

After update libs 
"mapbox-gl": "3.7.0",
"react-map-gl": "7.1.7",

The popup is no longer displayed on the map. Popup without any special styles. Text. At the input it receives longitude and latitude offset and anchor. But in the structure it’s like outside the browser window. I created a Marker next to it with the same coordinates and props. It is displayed correctly.

### Steps to Reproduce

create popup

### Environment

- Framework version:  "react": "18.2.0",
- Map library: "react-map-gl": "7.1.7", "mapbox-gl": "3.7.0",
- Browser: chrome
- OS: linux

**Comment by Pessimistress** [comment]
https://visgl.github.io/react-map-gl/docs/get-started#styling

**Comment by elC0mpa** [comment]
I have the same problem with the same version and I included the styles in this way:
`import "maplibre-gl/dist/maplibre-gl.css";`

`  return (
    <div className="w-full h-[560px]">
      <Map
        ref={mapRef}
        onLoad={onMapLoaded}
        mapStyle={`https://maps.geo.us-east-1.amazonaws.com/maps/v0/maps/${process.env.NEXT_PUBLIC_MAP_NAME}/style-descriptor?key=${process.env.NEXT_PUBLIC_MAP_API_KEY}`}
        scrollZoom={false}
      >
        {!!popupData ? (
          <Popup
            longitude={popupData.element.longitude}
            latitude={popupData.element.latitude}
            anchor="bottom"
            // onClose={() => setPopupData(undefined)}
          >
            <InventoryWorkshopPopup
              element={popupData.element}
              type={popupData.type}
            />
          </Popup>
        ) : null}
        {inventoryMarkers}
        {workshopMarkers}
      </Map>
    </div>
  );
}`

The first time I click the marker the popupShows
But after that it doesnǘt show anymore

Any idea?
