### ISSUE TITLE
ImageOverlay

### ISSUE THREAD

**Issue by mmoutenot** [visgl/react-map-gl#284]
It seems like a basic image overlay would suit the needs of some users. After looking through the existing overlays, I think it would be a simple wrapper around `CanvasOverlay` that renders an image into the canvas context.

This seems like a basic use case, but I can't find anything mentioning ot in the code or issues. Will likely try to implement if no existing work has been done.

**Comment by abmai** [comment]
@mmoutenot seems like a good idea! We're moving away from supporting more than a couple of core overlays in `react-map-gl` itself - so this is probably not the best place for it. You're welcome to create your own module, though, and we will look into linking to it from here. @ibgreen thoughts?

**Comment by ibgreen** [comment]
I think we could accept a contribution in the examples folder, but not as part of the main react-map-gl library.

Our long-term focus on overlay development is deck.gl. I believe that there is a bitmap-layer among the sample layers in deck.gl.

**Comment by Pessimistress** [comment]
https://docs.mapbox.com/mapbox-gl-js/example/image-on-a-map/
