### ISSUE TITLE
Docs issues

### ISSUE THREAD

**Issue by mcnuttandrew** [visgl/react-map-gl#335]
Love the the refresh of the docs! Couple of things i noticed while poking around

- It looks like the page https://uber.github.io/react-map-gl/#/Documentation/mapbox/mapbox-api doesn't point anywhere?
- On mobile, the ux of opening the docs menu and trying to view the contents of a subsection, take you to the subsection and closes the menu is annoying
- Feels weird that there are two github icons links in the top bar, like it feels noisy? I guess I would expect to either use mapboxes icon or not have the link to mapbox on a top level?
![screen shot 2017-07-28 at 4 12 33 pm](https://user-images.githubusercontent.com/6854312/28739408-aee9b848-73af-11e7-8c28-136166122bb9.png)

**Comment by abmai** [comment]
Hi Andrew :p! Thanks for the feedback! We'll remove the mapbox api link for now - I don't think it's necessary. I agree on the icons, will give a few things a try, along with the mobile issue.

**Comment by ibgreen** [comment]
We'll look at this as part of transitioning the docs to our common doc framework.
