### ISSUE TITLE
react-map-gl not rendering in express-react-views

### ISSUE THREAD

**Issue by jhnferraris** [visgl/react-map-gl#353]
I have this react component to render the StaticMap as shown in [Uber Static Map doc](https://uber.github.io/react-map-gl/#/Documentation/api-reference/static-map) in an [Express-React-Views Stack](https://github.com/reactjs/express-react-views).

```
map.jsx
---
var React = require('react');
var DefaultLayout = require('./layouts/default');
import StaticMap, {Marker} from 'react-map-gl';

var mapboxApiAccessToken = process.env.MapboxAccessToken;

class Map extends React.Component {
  render() {
    return (
        <StaticMap latitude={37.78} longitude={-122.41} zoom={8}  
width={1200}
        height={703} mapStyle={'mapbox://styles/mapbox/dark-v9'} 
mapboxApiAccessToken={mapboxApiAccessToken}>
            <Marker latitude={37.78} longitude={-122.41} offsetLeft=
{-20} offsetTop={-10}>
          <div>You are here</div>
        </Marker>
      </StaticMap>
    );
  }
}

module.exports = Map;
```

However, when I try to checkout the local site all I can see is this:

![screen shot 2017-09-01 at 7 35 30 pm](https://user-images.githubusercontent.com/3207153/29968907-55106cb0-8f50-11e7-899e-40f324013658.png)

Am I missing something here?

**Comment by ibgreen** [comment]
@jhnferraris

Some first thoughts:

You have a valid mapbox token in your environment variable right?  Though even if you don't the marker should still show...

Also, I believe `StaticMap` is a named export, i.e.
`import StaticMap, {Marker} from 'react-map-gl';`
=>
`import {StaticMap, Marker} from 'react-map-gl';`

By using the default export you are getting the `InteractiveMap`, although that should be OK for the example, they take the same props.

**Comment by jhnferraris** [comment]
@ibgreen

Yes I already have a valid mapbox token. I tried changing how I import StaticMap and marker but still no joy.

**Comment by ibgreen** [comment]
looks like `express-react-view` does server side React rendering? That might interfere with a WebGL based map - although one would expect the marker to still work.

No errors in the console?

Just making sure that you are aware that we have stand alone examples like [`controls`](https://github.com/uber/react-map-gl/tree/master/examples/controls). These are intended to be copied by users and used as a working starting point for apps. Admittedly these examples are not server-side rendered.
