### ISSUE TITLE
How can I add a mapbox geocoder?

### ISSUE THREAD

**Issue by Stupidism** [visgl/react-map-gl#481]
https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/

**Comment by Pessimistress** [comment]
We have no plan to support the Mapbox Geocoder control at the moment.

**Comment by SamSamskies** [comment]
@Stupidism I made a React wrapper for mapbox-gl-geocoder so that you can easily add it to your react-map-gl map. https://github.com/SamSamskies/react-map-gl-geocoder

**Comment by Stupidism** [comment]
@SamSamskies Cool, thanks a lot!

**Comment by SamSamskies** [comment]
@Stupidism no problem. If you have any problems with it, please log an issue. Thanks.

**Comment by Ahmad-Saleem** [comment]
Plz, how i can get object that i searched for ?
@SamSamskies

**Comment by SamSamskies** [comment]
@Ahmad-Saleem here's the API docs for MapboxGeocoder https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md. I think the results event handler may be what you are looking for.

If you have specific questions about my react-map-gl-geocoder component, please raise an issue there (https://github.com/SamSamskies/react-map-gl-geocoder/issues).
