### ISSUE TITLE
fill-pattern doesn't seem to work

### ISSUE THREAD

**Issue by daumann** [visgl/react-map-gl#519]
Has this feature ever been tested? None of my tests worked.

You should be able to easily reproduce it by using this example (and adapting it to react-map-gl code:

[fill-pattern jsffidle example](https://jsfiddle.net/z73Lywrv/)

**Comment by Pessimistress** [comment]
@daumann Is this still an issue with the latest release?

**Comment by daumann** [comment]
@Pessimistress I will test with the latest release this evening.
