### ISSUE TITLE
Override MapControls but keep page scroll works

### ISSUE THREAD

**Issue by igorlesnenko** [visgl/react-map-gl#531]
I'm trying to enable map zoom only if user holds `ctrl` key or zooming with 2 fingers.
Similar to `gestureHandling: 'cooperative'` in google maps

For that I have extended MapControls:

```js
import { experimental } from 'react-map-gl';

export default class MyMapControls extends experimental.MapControls {
  _onWheel(event) {
    if (event.srcEvent.ctrlKey) {
      event.preventDefault();
      return super._onWheel(event);
    }
  }

  _onPan(event) {
    if (
      event.pointerType === 'mouse' ||
      (event.pointerType === 'touch' && event.pointers.length === 2)
    ) {
      return this._onPanMove(event);
    }
  }
}
```

It works but breaks page scroll when mouse or finger is on map.
Any suggestions?

**Comment by Pessimistress** [comment]
Try set `touchAction: 'pan-y'`? See https://github.com/uber/react-map-gl/issues/506

**Comment by igorlesnenko** [comment]
@Pessimistress Thanks, looks like all above works with version 3.3.0. `touchAction: 'pan-y'` is needed too.

**Comment by igorlesnenko** [comment]
Is there way to dynamically change `touchAction: 'pan-y'` from MapControls?
