### ISSUE TITLE
onLoad function not firing until window has focus

### ISSUE THREAD

**Issue by CaptainLexington** [visgl/react-map-gl#537]
In our app, if you begin to load the page, and then focus on another window, the map's `onLoad` function is not triggered until after the window has focus again. This seems to be related to an error that we encounter that style diffing doesn't work if the page loads while the app does not have focus - the initial style for the map hasn't finished loading while the diffing happens.

```
TypeError: Cannot read property 'type' of undefined

updateStyleSource
node_modules/react-map-gl/dist-es6/utils/style-utils.js:73

  70 | var newSource = update.source.toJS();
  71 | if (newSource.type === 'geojson') {
  72 |   var oldSource = map.getSource(update.id);
> 73 |   if (oldSource.type === 'geojson') {
  74 |     // update data if no other GeoJSONSource options were changed
  75 |     var oldOpts = oldSource.workerOptions;
  76 |     // GeoJSONSource class scales user options before assigning to workerOptions
```

I can't get this error to replicate in the ReactMapGL examples on the site, so I recognize this might not be an error with the library itself, but I am at a loss for any other place in the community to turn. Does anybody know what might be causing this issue?

**Comment by renemeye** [comment]
Same problem here.
On reloading the page if it is in background, the error described above does happen for us too.
This seems also to happen on first page load.

**Comment by Pessimistress** [comment]
We don't have any control over when Mapbox fires its `load` event, though the style diffing implementation has been a source of pain recently. Targeting v4.0, we are removing our style diffing and use Mapbox's native implementation instead, see https://github.com/uber/react-map-gl/pull/559. 

I can publish this change in an alpha release if you are interested.
