### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by JamesSingleton** [visgl/react-map-gl#568]
Hi All,

Out of curiosity can react-map-gl be rendered server side? I am in a position that the website I am working on must be rendered server side due to SEO reasons. However, we want to have a map to plot points and be interactive with. Looking over the documents (maybe I am missing something) there isn't a server side rendered example.

**Comment by Pessimistress** [comment]
react-map-gl does support server side rendering, though mapbox-gl does not. So the container divs will be rendered, but no map canvas.

**Comment by JamesSingleton** [comment]
@Pessimistress ,

So how would one get map tiles if the map canvas isn't rendered and make the map interactive?

**Comment by Pessimistress** [comment]
Assuming the same JavaScript is evaluated on both server and client - on the server, where WebGL is not available, creation of `mapboxgl.Map` is skipped.

**Comment by JamesSingleton** [comment]
So basically we would have to Server Side render react-map-gl and then have some sort of client side rendering for the map itself? Also, is there an example anywhere of SSR react-map-gl? If not, that would be a nice example to have due to a lot of sites having to SSR due to SEO reasons but still wanting a map.

**Comment by Pessimistress** [comment]
You don't have to do anything special to make an app using react-map-gl SSR compatible. Your client-side DOM structure will show immediately, but the map itself won't be available till the script is loaded.

**Comment by JamesSingleton** [comment]
So using react-map-gl with something like next.js is completely feasible? Then where would the script to load the map come into play? I am trying to make the user experience as fast as possible but at the same time taking SEO implications of a SPA into consideration.

**Comment by Pessimistress** [comment]
We use SSR extensively for internal applications, and react-map-gl works well in that context. Unfortunately the solution is not open sourced and quite complex.

I have not worked with next.js before. It looks quite flexible to me. At this point I can't imagine anything preventing you from using them together.

**Comment by Pessimistress** [comment]
Re: a SSR example

Depends on how much code is required to get it working. I do think adding a test case for the SSR context is beneficial, though it doesn't make sense to add it as an "example" if the setup is complex and has nothing to do with the module itself. Does next.js have a starter template that I can plug into?

**Comment by JamesSingleton** [comment]
Got it, I guess my disconnect is 

> You don't have to do anything special to make an app using react-map-gl SSR compatible. Your client-side DOM structure will show immediately, but the map itself won't be available till the script is loaded.

Where would the `script` come into play?

As for Next.js https://github.com/zeit/next.js/#how-to-use shows how to get started, there isn't really a starter template unless you go off of https://github.com/zeit/next.js/tree/canary/examples

If using straight up express for SSR is more practical, that would be nice as well.

**Comment by tstirrat15** [comment]
@JamesSingleton the issue is that the code that renders the map tiles and provides map functionality is very heavily tied to the browser and its APIs, and there's a number of reasons why you wouldn't be able to figure out what the map would look like until the content is off your server and on the client's browser (e.g. how big should the map be? how big is the user's screen?).

There's nothing in the implementation of this library that prevents you from rendering a `<ReactMapGL />` on the backend, but it's just going to be a placeholder div until the frontend browser-specific code begins to execute.

There's also nothing in this library that expresses preference for one server-side rendering method over another. Next is full SSR framework, but something like [react-ssr-boilerplate](https://github.com/luangjokaj/react-ssr-boilerplate) would work just as well.

**Comment by dalipkumar703** [comment]
I am facing same issue with SSR. showing nothing to me and no error on console.

**Comment by intuity-hans** [comment]
I guess the fastest way would be using the map in a client-component which will then be rendered just on the client.
