### ISSUE TITLE
Using custom map tiles

### ISSUE THREAD

**Issue by kennetpostigo** [visgl/react-map-gl#588]
Hey! Taking react-map-gl for a spin and I found a few things:
- Passing a custom map tile string to `mapStyles` prop seems to not render any tiles, tried from a tile server and localhost tile server
- Passing a mapStyles object leads to the "container" value being undefined. Even when passing in the DeckGL element id of `'deckgl-wrapper'`

**Comment by Pessimistress** [comment]
@kennetpostigo 
Re: custom map style string - please share a code sample of your implementation.
deck.gl questions will be better answered in the deck.gl repo.

**Comment by peetjvv** [comment]
@kennetpostigo , have you managed to get the custom map tiles working? I've tried to implement custom map tiles in my map styles before, but haven't had much luck.

**Comment by kennetpostigo** [comment]
@peetjvv no I haven't, still seems broken for me. @Pessimistress I will post a code sample soon
