### ISSUE TITLE
Error once tried to change state of viewport on IE11

### ISSUE THREAD

**Issue by nok91** [visgl/react-map-gl#590]
**This is my state:**

>  state = {
>         mapStyle: 'mapbox://styles/xxxxx-nxx/xxxxxxxxxxxxxx',
>         viewport: {
>             longitude: -7.4869,
>             latitude: 54.9570,
>             zoom: 4.8,
>             bearing: 0,
>             pitch: 0,
>             width: 500,
>             height: 500,
>             maxZoom: 6
>         },
>         popupInfo: null,
>         popupsInfo: [],
>         MarkerToggleClasses: []
>     };

**This the component:**
>   <MapGL  {...viewport} .../>

On other browsers (Obv Chrome, Firefox, Microsoft Edge, Opera..) it is working fine, Only IE11 is generating this error all time I try to change the state of the viewport...

**Error:**
> TypeError: Object expected
> MapState
> C:/.../node_modules/react-map-gl/dist/esm/utils/map-state.js:1

>    "react-map-gl": {
>       "version": "3.3.4",

**Comment by Pessimistress** [comment]
This issue was referencing a version that is no longer maintained. Please open a new issue if it can be reproduced with the latest release.
