### ISSUE TITLE
Declarative mapbox style components

### ISSUE THREAD

**Issue by dhdemerson** [visgl/react-map-gl#624]
I'm working on a project that involves significant manipulation of the Mapbox style object. I came up with some helper components that make working with the style object more declarative. Would there be any interest in adding something like this to the project? The implementation I currently have looks like this:
```   
<ReactMapGL
  ref={map => (this.map = map)}
  mapStyle={this.state.style}
>

    <MapboxStyle
      onChange={style => this.setState({style})}
      baseStyle={MAP_STYLE}
      map={this.map}
    >

          <MapboxSource
            id=“my-tile-source”
            type="raster"
            tiles={tilesArray}
          />

          <MapboxLayer
            id=“my-tile-layer”
            type="raster"
            source=“my-tile-source
            layout={{
              visibility: tileLayer.visibility,
            }}
          />

    </MapboxStyle>
</ReactMapGL>
```
Any interest in something like this? Any potential problems I might not be aware of?

**Comment by Pessimistress** [comment]
`Source` and `Layer` components are added as of v5.1.
