### ISSUE TITLE
Initial bearing change in Firefox will crash react-map-gl

### ISSUE THREAD

**Issue by goldpbear** [visgl/react-map-gl#630]
Hello, thanks for making this utility!

I've been experiencing an issue in Firefox. I've found that if your very first interaction with a `react-map-gl` map in Firefox is a bearing change, the entire page will crash. This behavior is evident on the example map: https://uber.github.io/react-map-gl/#/Examples/dynamic-styling (tested using Firefox 62.0.3 on MacOS High Sierra 10.13.6). This problem doesn't seem to affect Chrome or Safari.

If first, however, you pan the map, any subsequent bearing changes are handled normally.

The error that comes back from Mapbox on the bearing change failure is:

```
Error: "Pixel project matrix not invertible"
```

In my own testing it looks like the value for `bearing` that comes out of the `onViewportChange` callback is `NaN`, though beyond that I'm not sure what the cause might be.

**Comment by Pessimistress** [comment]
I am unable to reproduce this (FF 62.0.3 and macOS 10.13.6). Can you describe the steps you are taking?

**Comment by goldpbear** [comment]
It's a little touchy, but I can produce this behavior in FF by:

* loading a fresh copy of https://uber.github.io/react-map-gl/#/Examples/dynamic-styling
* before any other interaction on the page, holding Ctrl and attempting to rotate the map with the mouse or trackpad

With a bit more time maybe I can take a screen capture of the behavior that demonstrates the interaction. But if others can't reproduce this then it might be something in my local environment, in which case I apologize for the distraction!

**Comment by Pessimistress** [comment]
I can reproduce it now.

Here's what's happening with Firefox and MacOS: if you hold down ctrl and start dragging, a `contextmenu` event is fired instead of `pointerdown` event. Curiously, if you press down the right mouse button, both `contextmenu` and `pointerdown` events are fired.

This behavior results in Hammerjs producing `deltaX: NaN, deltaY: NaN`s in its event object.

Rotating with Shift/Cmd keys works without any issue.

I feel that this should be filed as a Firefox bug.

**Comment by goldpbear** [comment]
Interesting-- thanks a lot for looking into it. Yeah, it sounds like a lower-level issue where a `pointerdown` event that should be fired is not.

For now one can just guard against `NaN` values in the `bearing` prop I suppose.
