### ISSUE TITLE
Fullscreen missing in Navigation Controls

### ISSUE THREAD

**Issue by daraclare** [visgl/react-map-gl#668]
Hi, and thanks for a great library 😄I'm currently implementing navigation for a map, but reading the [docs](https://github.com/uber/react-map-gl/blob/9a8cf1df6e6ea0bf090ab62fd021f849ed2a557a/docs/components/navigation-control.md) for nav controls, it seems fullscreen has not been implemented, is this something that is coming soon?

**Comment by macobo** [comment]
Really excited to see the PR on this @xintongxia and @Pessimistress! Looking forward to next release.
