### ISSUE TITLE
react-virtualized-auto-sizer error

### ISSUE THREAD

**Issue by gunnartorfis** [visgl/react-map-gl#686]
I'm using Bugsnag which repeatedly reports quite a lot of type errors from react-virtualized-auto-sizer. react-map-gl is the only package I'm using that uses react-virtualized-auto-sizer so I thought issuing this here is the right place. I haven't been able to reproduce the error myself so I'm not familar with the error's severity. 

The stacktrace (node_modules/react-virtualized-auto-sizer/dist/index.esm.js:65HTMLDivElement.s):
**TypeError** e.target.className.indexOf is not a function
```
var scrollListener = function scrollListener(e) {
    // Don't measure (which forces) reflow for scrolls that happen inside of children!
    if (e.target.className.indexOf('contract-trigger') < 0 && e.target.className.indexOf('expand-trigger') < 0) {
        return;
    }
```

This is happening on all the major browsers and operating systems, desktop and mobile.

**Comment by Pessimistress** [comment]
- You may want to report react-virtualized-auto-resizer bugs at https://github.com/bvaughn/react-virtualized-auto-sizer/
- Do you see the same error on our [docs website](https://uber.github.io/react-map-gl/#/Examples/dynamic-styling)?
- `className` is universally supported: https://developer.mozilla.org/en-US/docs/Web/API/Element/className
