### ISSUE TITLE
Draw a circle on a marker

### ISSUE THREAD

**Issue by altrang** [visgl/react-map-gl#712]
Hello , I m new to this library and i couldnt find what i m looking for in the docs.
I have a map with a Marker and i would like to draw a circle with my marker as center with a certain radius. 
My marker is a bus stop and the circle should show users a certain radius in meter
If anyone has clue on that 
Thanks

**Comment by xintongxia** [comment]
There is [Marker](https://github.com/uber/react-map-gl/blob/master/examples/main/views/marker.js) example and [Custom Overlay](https://github.com/uber/react-map-gl/blob/master/examples/main/views/custom-overlay.js) example in the repo.

Also you can check [Marker](https://uber.github.io/react-map-gl/#/Documentation/api-reference/marker), [Custom Overlay](https://uber.github.io/react-map-gl/#/Documentation/advanced/custom-overlays) and other docs.

**Comment by xintongxia** [comment]
Yes. Something like the following.

```
 <MapGL ...>
   <Marker ... />
   <CircleOverlay .../>   
 </MapGL>
```

For the implementation of the circle, you can draw it on canvas (refer [Custom Overlay](https://uber.github.io/react-map-gl/#/Documentation/advanced/custom-overlays), [Canvas Overlay](https://uber.github.io/react-map-gl/#/Documentation/api-reference/canvas-overlay)).

Or alternatively you can use deck.gl (refer [DeckGL Overlay](https://github.com/uber/react-map-gl/blob/master/examples/deckgl-overlay/view.js), [DeckGL Scatterplot Layer](http://deck.gl/#/documentation/deckgl-api-reference/layers/scatterplot-layer)).

```
<MapGL ...>
  <DeckGL>
    {...viewport}
    layers={[
      new ScatterplotLayer({
        data: [...],
        ...,
      })
    ]}
  />
</MapGL>
```

**Comment by altrang** [comment]
thanks a lot for your answers !

**Comment by tsaiDavid** [comment]
@dmi3y - might be relevant for you

**Comment by derwaldgeist** [comment]
Also missing this in the standard library. This was all so easy with Leaflet...

**Comment by derwaldgeist** [comment]
I just found a simple workaround to do this: 

1. Create a GeoJSON polygon that mimics the shape of the circle, using [@turfjs/circle](https://www.npmjs.com/package/@turf/circle)
1. Add this GeoJSON to a custom layer
1. Add this layer to your map
