### ISSUE TITLE
Discussion: integration with mapbox-gl-draw

### ISSUE THREAD

**Issue by macobo** [visgl/react-map-gl#725]
My workplace recently replaced google maps with react-map-gl. We've had great success - user engagement with the map has shot through roof thanks to new functionality made easy by this wonderful library.

However, the last large piece holding us back is editing and creating polygons on the map. Seems the most mature tool in the mapbox ecosystem for this is https://github.com/mapbox/mapbox-gl-draw, but we've had trouble integrating the library with react-map-gl. 

In our app, we store the (dynamic) mapStyle in redux, and gl-draw makes the map application to become really unresponsive. The problem comes from that mapbox-gl-draw [is managing internal layers](https://github.com/mapbox/mapbox-gl-draw/blob/5b2280817c901d93b05c937a7bdb2efb8afefe0c/src/setup.js#L82-L107), is trying to [update map styles dynamically](https://github.com/mapbox/mapbox-gl-draw/blob/5b2280817c901d93b05c937a7bdb2efb8afefe0c/src/render.js#L44-L69) via the vanilla mapbox API. This obviously clashes with react-map-gl's approach, causing one library to add layers and sources and the other to remove in an eternal tug-of-war.

I wanted to ask for advice - how would you go about integrating the two libraries? I'm interested in spending some development time making it possible and share with others. Internally we've thought about proxying `addSource`, `addLayer`, `getSource().setData` methods and redirecting them to our redux store, but wondering if there's better methods to use here. 

Linking a related discussion: #450

**Comment by ibgreen** [comment]
> Seems the most mature tool in the mapbox ecosystem for this is [mapbox/mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw),

Small plug: We use [nebula.gl](http://www.nebula.gl/) for geospatial editing. Haven't compared it recently to mapbox-gl-draw, so can't really say how the two solutions compare. nebula.gl does bring in deck.gl so it is likely the bigger dependency.

> mapbox-gl-draw [is managing internal layers](https://github.com/mapbox/mapbox-gl-draw/blob/5b2280817c901d93b05c937a7bdb2efb8afefe0c/src/setup.js#L82-L107), is trying to [update map styles dynamically](https://github.com/mapbox/mapbox-gl-draw/blob/5b2280817c901d93b05c937a7bdb2efb8afefe0c/src/render.js#L44-L69) via the vanilla mapbox API. This obviously clashes with react-map-gl's approach,

As I recall, react-map-gl doesn't do too much with the styles except some diffing and passing them on. Maybe we could just support setting style to `null` in which case we wouldn't touch/update styles in the react render cycle but instead let the user manage it with the "imperative" mapbox style APIs.

I'd personally prefer a lightweight "enabler" like that, rather than add too much complex logic to react-map-gl itself.

**Comment by xintongxia** [comment]
We did something similar in other project. Here is a short demo. Will this cover your use cases if this polygon editing overlay on the Map? 

![polygon](https://user-images.githubusercontent.com/2927808/52594685-647fcc80-2e4c-11e9-8232-11994c23d29b.gif)

**Comment by macobo** [comment]
Thanks for the quick answers!

@ibgreen we'll take another look. nebula did look like overkill dependency-wise, but it looks like a stable solution

@xintongxia That looks pretty much exactly what we're looking for. Would you mind sharing the code backing this? :)

**Comment by xintongxia** [comment]
Discussed with @Pessimistress, we could add a polygon editing overlay in `react-map-gl`. But it is probably going to take a while (maybe 2 - 3 weeks) to get it done.

**Comment by rob137** [comment]
FWIW I am experiencing the same issues.  mapbox-gl-draw would be great for our use-case, but it slows down react-map-gl too much.  mapbox-gl-draw also seems to behave strangely with click events - in some instances clicking controls/shapes also selects the map itself. (E.g. attempting to resize a polygon will cause the map to pan, double clicking controls will cause the map to zoom in.)

**Comment by goldpbear** [comment]
We've found ourselves in the same position as @macobo-- `react-map-gl` has significantly streamlined our mapping application, but we need to clear the drawing hurdle. `nebula.gl` is intriguing but we'd prefer not to add `deck.gl` just for drawing support.

For us, @xintongxia's demo above is also exactly the kind of functionality we're looking for. Maybe I missed it, but is the source code for that demo available somewhere? Or maybe it's easier to wait for an editing overlay to be added?

Thanks!

**Comment by rob137** [comment]
@goldpbear +1.  Would also love to be able to add/delete lines & notes to maps.

**Comment by HamidAghdaee** [comment]
+ 1

**Comment by rob137** [comment]
It appears that react-mapbox-gl / react-mapbox-gl-draw work together ok ([example](https://app.landexplorer.cc)), so we are exploring that for the time being.  But we'd rather use react-map-gl if possible.

**Comment by Pessimistress** [comment]
@macobo @goldpbear Please help review and provide feedback for https://github.com/uber/react-map-gl/issues/734

**Comment by rob137** [comment]
Possibly of interest: 
https://github.com/urbica/react-map-gl-draw/

**Comment by macobo** [comment]
@xintongxia I see some stuff has been happening on the background, any updates?

**Comment by xintongxia** [comment]
@macobo 

`react-map-gl-draw` library is still under development, the API is gong to change in next month.

But if you would like to give a try, here is the example [code](https://github.com/uber/nebula.gl/tree/master/examples/react-map-gl-draw).

It currently support drawing points, lines, and polygons.

**Comment by xintongxia** [comment]
@macobo 

I have released a [`react-map-gl-draw`](https://github.com/uber/nebula.gl/tree/master/modules/react-map-gl-draw) library, here is an example using it with react-map-gl.

Example code [draw-polygon](https://github.com/uber/react-map-gl/tree/master/examples/draw-polygon)

Also here is the sandbox [example](https://codesandbox.io/embed/elated-framework-9l6lv)

**Comment by daniela-green** [comment]
hey @xintongxia :)
Can you please give an example of how to catch events of **finish** dragging feature? 
when i drag a polygon, i only see that "movePosition" events is being fired, and dont see finishMovePositionEvent.
Thanks
