### ISSUE TITLE
Screenshots without preserveDrawingBuffer?

### ISSUE THREAD

**Issue by daumann** [visgl/react-map-gl#726]
As I understand, **preserveDrawingBuffer** comes with a hefty performance penalty (especially on mobile). Is there any way we can take screenshots without having to set preserveDrawingBuffer = true?

**Comment by Pessimistress** [comment]
It is possible, if you take the screenshot immediately after render (on `render` event) and before the buffers swap.

**Comment by daumann** [comment]
@Pessimistress thanks for picking this up. Do you mean on first load? I would like to have the user  to be able to take a screenshot at any time, even after 15min into the experience.

**Comment by Pessimistress** [comment]
`render` is fired whenever the map redraws, from e.g. new data or user interaction. You can also trigger a redraw by calling `map.triggerRepaint()`.

**Comment by daumann** [comment]
@Pessimistress so you mean firing the "takeScreenshot()" function directly from the render function? Or another lifecycle function?

**Comment by daumann** [comment]
@Pessimistress 
Here is some code I tested with:

// function which attempts to take screenshot
```
  takeScreenshot = () => {
    if(!this.map) return
    const screenshotElement = document.getElementById('screenshotPlaceholder')
    const img  = this.map.getMap().getCanvas().toDataURL();
    const width = screenshotElement.offsetWidth
    const height = screenshotElement.offsetHeight
    const imgHTML = `<img src="${img}", width=${width}, height = ${height}/>`
    screenshotElement.innerHTML = ''
    screenshotElement.innerHTML = imgHTML;
  }
```

// a button which onClick changes a boolean and forces rerender
` <button onClick={() => {  takeScreenshot = true; this.forceUpdate()  }} type="button">Take Screenshot</button>`

Then I tried calling takeScreenshot directly inside the render() lifecycle function:
```
render () {
    if (drawP) {
      drawP = false
      this.takeScreenshot()
    }
...
```
This didn't worl (blank screenshot as a result), so I tried putting that call in the componentDidUpdate lifecycle function:
```
  componentDidUpdate = () => {
    if (drawP) {
      drawP = false
      this.takeScreenshot()
    }
  }
```

Both result in a blank screenshot (fully transparent).

I veriefied that takeScrenshot() works (if called on INITIAL (first time) render).
Any ideas how else to make this work?

**Comment by Pessimistress** [comment]
I was referring to the `render` event of the Map instance:

```js
  takeScreenshot = () => {
    if(!this.map) return
    const mapboxMap = this.map.getMap()
    mapboxMap.once('render', () => {
      const img = mapboxMap.getCanvas().toDataURL()
      // do your thing
    });
  }
```
