### ISSUE TITLE
Map onClick event not triggering properly on Chrome when embedded with an iframe with a remote source

### ISSUE THREAD

**Issue by murej** [visgl/react-map-gl#729]
Hey,
I have an app running perfectly, apart from one scenario:
_When you click on the map the onClick event doesnt't trigger correctly on Chrome 71 when embedded with an iframe with a remote source._

It works fine running locally with an embedded local source and it works perfectly on Safari 12 and Firefox 65 and on Safari on iOS 12.1.2.

It triggers window.onclick and App.onclick (root component) events properly, it just doesn't execute the onClick callback function when passed on to `<ReactMapGL onClick={fn} />`.

There seems to be some sort of a timing issue, since it does trigger with a very fast click (ie. tapping on my MacBook Pro touchpad, but not when clicking on it or holding it longer), but again only in the described scenario.

See it here: https://chi-evidence-finder.now.sh
See it embedded here: https://www.homelessnessimpact.org/evidence-finder

I'm scratching my head, are there any known bugs with Chrome and/or iframes and/or MapboxGL and/or react-map-gl? Or any ideas how to solve this?

Thanks!

**Comment by Tomcatus** [comment]
Hey @murej I came across a similar issue myself and am struggling to solve it. Did you somehow manage to fix yours? And if so, what have you done to achieve it? Thanks in advance.

**Comment by kurtlippert** [comment]
Hey @murej and @Tomcatus,

I'm on a team evaluated this tech and this issue might be relevant to our use case. Are you both still seeing this issue? Looks like there hasn't been movement on this in a while

**Comment by Pessimistress** [comment]
Can you try v7.0?
