### ISSUE TITLE
Offline Features

### ISSUE THREAD

**Issue by lhorus** [visgl/react-map-gl#732]
The plugin - as far as I can tell - does not support the offline handlers - loading and manipulating offline maps. Is this feature planned?

**Comment by Pessimistress** [comment]
react-map-gl is a wrapper of mapbox-gl. If this is a feature supported by Mapbox, please link to the API documentation. If this is a feature request, you need to ask in the mapbox-gl-js repo.

**Comment by lhorus** [comment]
Hi there @Pessimistress ,

Indeed it is, here is the [documentation link](https://docs.mapbox.com/help/troubleshooting/mobile-offline/).

**Comment by Pessimistress** [comment]
The link is for Mapbox's iOS and Android SDKs, not Mapbox GL JS.

**Comment by macobo** [comment]
@lhorus react and react native are different beasts.

- React (as usually referred to) is a javascript library, built for building applications in your browser using the dom.
- React native is a native mobile application building framework which works like react, but runs directly on your mobile. https://facebook.github.io/react-native/

The two libraries are quite similar (on purpose), but there's significant difference in their architecture. Random libraries in one don't support the other.
