### ISSUE TITLE
Is there any way to select particular area on map (draw a rectangle) and get latitude and longitude of all the points covered by rectangle?

### ISSUE THREAD

**Issue by hip1310** [visgl/react-map-gl#765]
We have a specific need in our app that use should be able to select the area on map, and based on selected area we need to filter results being displayed on map. So need to have longitude and latitude of all the points covered by selected area on map.

Any help would be appreciated

**Comment by mayteio** [comment]
Turf.js might be able to help you. It has tools for drawing geojson objects onto a map, as well as checking whether a point is within a polygon. Mapbox also has queryRenderedFeatures with will grab everything in view so you're not dissecting all your data each time.
