### ISSUE TITLE
Not able to implement Cluster!

### ISSUE THREAD

**Issue by debotos** [visgl/react-map-gl#766]
Is there is any way to implement cluster in this library? I am not getting any documentation about it.
Like here, https://docs.mapbox.com/mapbox-gl-js/example/cluster/
I also want to show a popup when clicking on a particular marker at the low level(zoom in).

**Comment by mlg87** [comment]
[#507](https://github.com/uber/react-map-gl/issues/507#issuecomment-424860068)
