### ISSUE TITLE
Click on control-panel propagates the event on map

### ISSUE THREAD

**Issue by apizzoleo** [visgl/react-map-gl#771]
Hi,
I tried it too on the examples, when I click on the control panel it also triggers the onClick method of the Map.
I tried to define control panel as an  extension of BaseControl and I added captureClick, but nothing changed.
What did I do wrong?

**Comment by davidnmora** [comment]
I have the same issue. My only solution is to create a React reference to the control panel and then make that panel a child of another non-map-nested DOM node. (see code below. This solution I got from the `react-map-gl-geocoder` examples (granted you have to go to the source to see the actual binding to the container node)

```javascript
<div {...ArrowKeysReact.events} tabIndex="0">
				<div
					ref={this.geocoderContainerRef}
					className="nav-bar"
				>
				</div>
				<ReactMapGL
					ref={this.mapRef}
					{...settings}
					{...viewport}
					mapStyle={mapStyle}
					onViewportChange={this._onViewportChange}
					onClick={this._onHover}
					onTransitionStart={() => this._isTransitioning = true}
					onTransitionEnd={() => {
						this._isTransitioning = false
						this._updateURLWithCurrentState()
					}}
					panend={() => console.log('pan end')}
					mapboxApiAccessToken={MAPBOX_TOKEN}
				>
					<Geocoder
						containerRef={this.geocoderContainerRef}
						mapRef={this.mapRef}
						onResult={this.handleOnResult}
						onViewportChange={this._onViewportChange}
						mapboxApiAccessToken={MAPBOX_TOKEN}
						position="top-right"
						country='US'
						placeholder="Search an address, zip, or city"
					/>
					
				</ReactMapGL>
			</div>
```

**Comment by xintongxia** [comment]
@apizzoleo 

> I tried to define control panel as an extension of BaseControl and I added captureClick, but nothing changed.

You need set the `_containerRef` to your control panel component.

https://github.com/uber/react-map-gl/blob/master/docs/advanced/custom-components.md#_containerref

**Comment by Robert-OP** [comment]
Hi, same behavior on controls or elements on top of the map - when I use [<GeolocateControl>](https://uber.github.io/react-map-gl/docs/api-reference/geolocate-control) and double click on it, it zoom into the map. 

Also, you can see the behavior in the [examples](https://uber.github.io/react-map-gl/examples/draw-polygon) by double clicking either on the draw polygon control (left-top corner) or the box element (right-top corner) as in the image below.

**Question:** Any ideas on how to fix this behavior? (not having the map trigger that zoom / onClick event)

Sorry, but it is not that obvious [from the custom component](https://github.com/uber/react-map-gl/blob/master/docs/advanced/custom-components.md#_containerref) on how to implement.

Cheers!
![image](https://user-images.githubusercontent.com/16807022/76215067-3bc43500-620e-11ea-8358-39138361ffe3.png)

**Comment by Pessimistress** [comment]
This has been fixed in the latest website.
