### ISSUE TITLE
Map Pitch/Tilt Control Not Working on Mobile

### ISSUE THREAD

**Issue by ctaylor4874** [visgl/react-map-gl#779]
The map seems to lose the two-finger drag pitch/tilt controls on mobile.  Any ideas on how I can get this functionality back for the Mapbox map?

**Comment by Pessimistress** [comment]
Set `touchRotate` prop to `true`.

**Comment by mayteio** [comment]
@Pessimistress that turns on *rotation* but not pitch, i.e. from bird's eye view to horizon view.

I am wondering the same question!

**Comment by Pessimistress** [comment]
@mayteio how do you change pitch with mapbox-gl on mobile?

**Comment by mayteio** [comment]
I don't think you can. Only programatically, or by writing your own gesture handler.

**Comment by Pessimistress** [comment]
Three-finger swipe will be used to change pitch in v5.3/v6.1. Currently available in `6.1.0-beta.1`.
