### ISSUE TITLE
Geolocate control not showing user location by default

### ISSUE THREAD

**Issue by scott-mcnulty** [visgl/react-map-gl#782]
The GeolocateControl component is not showing the user location dot by default as specified in the [docs](https://github.com/uber/react-map-gl/blob/4.1-release/docs/components/geolocate-control.md) 

I only got it to appear when setting trackUserLocation to true (kept all other prop values as default). Tested with the example supplied in the documentation linked above.

react-map-gl version: 4.1.2

**Comment by moyaying** [comment]
Any idea how to do?  I have the same problem.

**Comment by JeffAbney** [comment]
+1 Anybody know?

**Comment by Pessimistress** [comment]
4.1.2 is no longer maintained. I cannot reproduce this issue with the latest release.
