### ISSUE TITLE
Map does not load or display anything in Electron

### ISSUE THREAD

**Issue by felipellrocha** [visgl/react-map-gl#785]
Hey, y'all.

I've been playing with the library this afternoon. I supplied my component with all of its props but nothing gets displayed. Anyone know what might be wrong?

```
<StaticMap
            width={400}
            height={400}
            zoom={8}
            onLoad={(a) => console.log('loaded', a)}
            onError={(e) => console.log('error!', e)}
            latitude={37.805}
            longitude={-122.447}
            mapStyle="mapbox://styles/mapbox/dark-v9"
            mapboxApiAccessToken='...'
          />
```

I get no errors, or anything, so I have no idea what is going wrong. Trying to render this map on an Electron app.

**Comment by matthiasak** [comment]
I have the same issue - using a pretty bare app right now with fuseb-box+typescript, not network requests are firing off to MapBox so I feel like the MapBox sdk isn't being initiatlized or anything

**Comment by Pessimistress** [comment]
Can you try run the basic example here: https://github.com/uber/react-map-gl/tree/4.1-release/examples/exhibit-webpack

**Comment by fudanglp** [comment]
same here. webpack example works in Chrome, not working in Electron

**Comment by saschahofmann** [comment]
After two days of playing around with different electron-react boilerplates and _react-map-gl_, we finally found the issue creating the problem described  above for us. 
In our _webpack.config.js_ we had a line to exclude node modules from being bundled:
`externals: [...Object.keys(dependencies || {})]`
Apparently, _react-map-gl_ expect to be bundled (?) so we excluded it from the array:
`externals: [...Object.keys(dependencies || {}).filter(x => x !== 'react-map-gl')]` and voila we get the map in our electron map.

**Comment by fudanglp** [comment]
@saschahofmann 
Hope this works, i'll test it later. thx!

**Comment by Omrna** [comment]
its not working for me :(

**Comment by MD-AZMAL** [comment]
i am having the same issue, the webpack workaround doesn't help

**Comment by chingmunn** [comment]
My app was created using CRA and I did not want to eject the app to edit the webpack settings. My workaround was to revert to a version of react-map-gl that uses mapbox-gl v1.

**Comment by jvidulich** [comment]
For anyone else that comes across this issue within electron and the webpack config above isn't helping - your CSP also matters!! 

react-map-gl uses webworkers, if you don't have a workers allowed in your CSP for your electron main browserWindow, the map will not load!
