### ISSUE TITLE
Markers don't stick to Map when maxBounds are set

### ISSUE THREAD

**Issue by mihaibogdan** [visgl/react-map-gl#786]
Hi guys,

I have some markers on a map, and maxBounds set to [[-180, -85], [180, 85]]. The problem is when the map reaches the bounds, the markers still move with the cursor. Any thoughts?

![maxBounds-issue](https://user-images.githubusercontent.com/6225068/58015083-0295c980-7b03-11e9-90f4-96047d07980c.gif)

**Comment by xintongxia** [comment]
`react-map-gl` has a `onViewportChange` callback you can listen to and decide where you would like to put the marker.

https://github.com/uber/react-map-gl/blob/master/docs/components/interactive-map.md#onviewportchange-function

**Comment by Pessimistress** [comment]
@mihaibogdan you cannot use maxBounds because react-map-gl is not using mapbox-gl-js's built-in interaction handling logic. To constrain the map bounds you should do something like

```js
_onViewportChange = (viewport) => {
  const oldViewport = this.state.viewport;
  if (Math.abs(oldViewport.longitude - viewport.longitude) > 180) {
    // wrapped around the 180th meridian
    return;
  }
  this.setState({viewport});
}
```

**Comment by dankremniov** [comment]
That is what worked well for me to achieve `maxBounds` functionality with this library:

```
export const isOutOfMaxBounds = (latitude, longitude, maxBounds) => {
    const [[swLng, swLat], [neLng, neLat]] = maxBounds;

    return longitude < swLng || longitude > neLng || latitude < swLat || latitude > neLat;
};

const onViewportChange = newViewport => {
    if (
        !isOutOfMaxBounds(
            newViewport.latitude,
            newViewport.longitude,
            MAX_BOUNDS, // your max bounds
        )
    ) {
        setViewport(newViewport);
    }
};
```

`isOutOfMaxBounds` is basically a copy of what is used under the hood in `mapbox-gl-js`: https://github.com/mapbox/mapbox-gl-js/blob/12991995fa1bb62c5ecdb0282c7c142578b897e5/src/ui/control/geolocate_control.js#L164

**Comment by kieranongh** [comment]
> 
> 
> That is what worked well for me to achieve `maxBounds` functionality with this library:
> 
> ```
> export const isOutOfMaxBounds = (latitude, longitude, maxBounds) => {
>     const [[swLng, swLat], [neLng, neLat]] = maxBounds;
> 
>     return longitude < swLng || longitude > neLng || latitude < swLat || latitude > neLat;
> };
> 
> const onViewportChange = newViewport => {
>     if (
>         !isOutOfMaxBounds(
>             newViewport.latitude,
>             newViewport.longitude,
>             MAX_BOUNDS, // your max bounds
>         )
>     ) {
>         setViewport(newViewport);
>     }
> };
> ```
> 
> `isOutOfMaxBounds` is basically a copy of what is used under the hood in `mapbox-gl-js`: https://github.com/mapbox/mapbox-gl-js/blob/12991995fa1bb62c5ecdb0282c7c142578b897e5/src/ui/control/geolocate_control.js#L164

This helped me in the right direction, but this implementation actually blocks the center from hitting the bounds and not the actual boundaries

This is what I came up with
```javascript
import { WebMercatorViewport } from 'react-map-gl'

export const isOutOfMaxBounds = (nextSW, nextNE, maxBounds) => {
  const [[maxSWLng, maxSWLat], [maxNELng, maxNELat]] = maxBounds
  const [nextSWLng, nextSWLat] = nextSW
  const [nextNELng, nextNELat] = nextNE

  return (
    nextSWLng < maxSWLng || nextSWLat < maxSWLat || nextNELng > maxNELng || nextNELat > maxNELat
  )
}

const onViewportChange = newViewport => {
  const merc = new WebMercatorViewport(newViewport)
  // fetch the lat/lng of the edges of the viewport
  // measured from topLeft
  const newSouthWest = merc.unproject([0, newViewport.height])
  const newNorthEast = merc.unproject([newViewport.width, 0])
  if (!isOutOfMaxBounds(newSouthWest, newNorthEast, MAX_BOUNDS)) {
    setViewport(newViewport)
  }
}
```
