### ISSUE TITLE
Popup during animation position using absolute positioning instead of translate

### ISSUE THREAD

**Issue by bartolkaruza** [visgl/react-map-gl#790]
Looking at the performance of react-map-gl compared to a similar map using vanilla mapbox-gl-js, we noticed there is a difference in the way the popup positioning is handled between the two. On a vanilla mapbox-gl-js map, the popup position is moved using translate, which is cheaply updated during map animation:
![popupanimation-mapboxgljs](https://user-images.githubusercontent.com/1605731/58081025-96739e00-7bb4-11e9-8609-1c6b7d3cd284.gif)

The react-map-gl popup is moved using absolute positioning, incurring a performance hit compared to translating:
![popupanimation-react-map-gl](https://user-images.githubusercontent.com/1605731/58081082-b2773f80-7bb4-11e9-8137-0e25eb589355.gif)

Is there a particular reason why the top/left positioning is used instead of translate? It seems to be at a [high price](https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/) performance wise.

**Comment by Pessimistress** [comment]
There was a discussion a while ago: https://github.com/uber/react-map-gl/pull/379 I'm happy to revisit this issue.

**Comment by Pessimistress** [comment]
Closing - popups are using `translate` instead of `top`/`left` as of v5
