### ISSUE TITLE
Element type of onViewportChange is invalid.

### ISSUE THREAD

**Issue by cola119** [visgl/react-map-gl#796]
Hello, I'm using react-map-gl in typescript.  
I think the type of `onViewportChange` should be `(viewState: ViewState) => void;` and `ViewState` is 
```typescript
interface ViewState {
    latitude: number;
    longitude: number;
    zoom: number;
    bearing?: number;
    pitch?: number;
    altitude?: number;
}
```

But I found `viewport` has more elements than `ViewState` as follows.

```typescript
<ReactMapGL
    width="100wh"
    height="100vh"
    mapboxApiAccessToken={mapboxConfig.token}
    onViewportChange={viewport => console.log(viewport)}
/>
```
![image](https://user-images.githubusercontent.com/22386678/58363552-0ea5d080-7ee1-11e9-8613-47302b4155e6.png)

Please survey. And I am sorry if I made a mistake.

**Comment by ali-rival** [comment]
These are all in `ViewportProps`:

**Comment by Pessimistress** [comment]
There is no official typescript support as of v5.2. Please contact the author of the type definition that you are using.
