### ISSUE TITLE
zoomIn / resetNorth does not trigger onViewportChange

### ISSUE THREAD

**Issue by juliuslipp** [visgl/react-map-gl#814]
So I want to create my own NavigationControl for the map. I want to use map.resetNorth(), map.zoomIn(), etc..

`updateViewport = viewport => {
    this.setState(state => ({ viewport: { ...state.viewport, ...viewport } }));
  };
`

`<MapGL
       ref={this.mapRef} 
       onViewportChange={this.updateViewport}>...`

`<Button onClick={() => this.mapRef.current.getMap().zoomIn()}/>`

The viewport of the actual map changes but it ignores my onViewportChange prop and I can't set the viewport (state) of my component according to the actual map component (so markers/clusters are calculated wrong).

**Comment by Pessimistress** [comment]
If it's not behaving as expected, share your code snippet and version of react-map-gl.

**Comment by Pessimistress** [comment]
react-map-gl does not listen to native `mapboxgl.Map` camera events. The camera should always be controlled via React props. If you want to reset north, you may change `state.viewport`:

```js
// reset north
this.setState({
  viewport: {...this.state.viewport, bearing: 0}
});
```
