### ISSUE TITLE
Invalid events breaking component

### ISSUE THREAD

**Issue by tim-codes** [visgl/react-map-gl#822]
Very rarely (1/1000) move events will have invalid co-ordinates. This throws an error inside `web-mercator-viewport` library where it asserts `Number.isFinite(x|y)`. We have been testing this issue for a couple of weeks now and we can reproduce consistently.

When we were testing on `v4.x` this was considerably more frequent (1/250 event), this was improved by upgrading to `v5.0` which we are now using in production.

I previously attempted to debug this by handling the invalid event in our custom map controller and providing some sensible default co-ordinates in this scenario, however this didn't seem to have any effect and the error was still thrown.

**Comment by Pessimistress** [comment]
What browser are you using?

**Comment by tim-codes** [comment]
We have managed to reproduce this on multiple devices and browsers.

**Comment by Pessimistress** [comment]
We have dropped the custom event handling code in v7.0. Reopen if it remains an issue.
