### ISSUE TITLE
Pinch zoom often does not trigger on android phones

### ISSUE THREAD

**Issue by simon-norman** [visgl/react-map-gl#831]
On android phones, doing a pinch zoom often doesn't trigger any events (IE interactionStateChange). This happens after a zoom has just been done, which suggests it might be something to do with the map re-rendering after the first zoom and blocking new gestures. 

IE:

1. You do a zoom by pinching the screen
2. You immediately do another zoom, and it is completely unresponsive, with no interactionStateChange or ViewStateChange being triggered.

**Comment by derwaldgeist** [comment]
Noticed the same here. Pinch zoom is pretty unreliable on a Galaxy S10.

**Comment by Bodhivb** [comment]
This problem is solved for me after release this version `react-map-gl@5.2.5` See problem: [issues/1054]( https://github.com/visgl/react-map-gl/issues/1054)
