### ISSUE TITLE
Combining mapStyle prop with @deck.gl/mapbox

### ISSUE THREAD

**Issue by mayteio** [visgl/react-map-gl#848]
I believe this is a react-map-gl issue, not a deck.gl issue. Please correct me if I'm wrong.

I am trying to pass a `new MapboxLayer()` into react-map-gl `mapStyle.layers`, however, it seems the normalizeStyles util is throwing an error because "custom" is not in the list of accepted types (and it's looking for a source).

[Demo](https://codesandbox.io/s/naughty-sun-v4tlc)

Is this currently possible?

**Comment by Pessimistress** [comment]
I believe `map.addLayer` is the only way to add custom layers.
