### ISSUE TITLE
Cannot add custom layer

### ISSUE THREAD

**Issue by jvntf** [visgl/react-map-gl#849]
**Version**: 5.0.0
**Problem**: I am unable to add a custom layer to a map (using StaticMap) inside of a DeckGL framework. I get an error that a `source` must be specified and that `type: custom` is not supported

```
class threeJSModel{
        constructor(){
          this.id='custom_layer';
          this.type='custom';
          this.renderingMode = '3d'
        }
        onAdd(map, gl) {
            //create 3JS scene here
        }

        render(gl, matrix) {
            //render the scene
        }
    }
```

and then I add it to the map as follows: 

```
const mapStyle = defaultMapStyle
      .set('layers', defaultMapStyle.get('layers').push(fromJS(new threeJSModel())))
this.setState({mapStyle})
```

```
<StaticMap
             ref = {this._mapRef}
             reuseMaps
             mapStyle={this.state.mapStyle}
             preventStyleDiffing={true}
             mapboxApiAccessToken={MAPBOX_TOKEN}
           />
        }
```

**Comment by mayteio** [comment]
Hey, it appears this is the same issue I was having yesterday! #848 

Glad it's not just me.

**Comment by jvntf** [comment]
hey @mayteio I have had some success with `getMap().addLayer()` to add my custom layer. It seems like `react-map-gl` doesn't directly support custom layers but you can access the mapbox-gl api this way and add your layer. It's not clean but seems ok for now

**Comment by mayteio** [comment]
Thanks @jvntf, I too have had the method mentioned working. I'd like to combine mapStyle (so I can make updates via redux) and the custom layers. I'm imagining if I use `map.addLayer()` then update the mapStyle object, the layer will disappear. Could be wrong though - will have a fiddle.

**Comment by ptbrowne** [comment]
Related to https://github.com/visgl/react-map-gl/pull/1851
