### ISSUE TITLE
How can I change the style (overflow) of the div .overlays?

### ISSUE THREAD

**Issue by Oxygen66** [visgl/react-map-gl#853]
Hi,

I would like to change css properties and more particularly "overflow: hidden" in the ".overlays" class.
This value is directly put in css-inline in the div:
![Capture d’écran 2019-07-25 à 15 53 59](https://user-images.githubusercontent.com/6073308/61880055-76ce5e00-aef4-11e9-8dde-288b038f0897.png)

This property is defined without being able to change it in the variable CONTAINER_STYLE (static-map.js, L.51):

```
const CONTAINER_STYLE = {
  position: 'absolute',
  width: '100%',
  height: '100%',
  overflow: 'hidden'
};

```

Thank you.

**Comment by mayteio** [comment]
Hey, excuse the simple solution, but couldn't you just add some css?

```css
.mapboxgl-map > div > .overlays { overflow: scroll }
```

**Comment by Oxygen66** [comment]
Hey ! 

@mayteio , we can't  here because we have css inline. Actualy, we just can override it with `!important` in scss file.

Maybe the uber team can make this property configurable? @uber/react-map-gl
