### ISSUE TITLE
Grey map box refference error

### ISSUE THREAD

**Issue by ipnuds** [visgl/react-map-gl#864]
problem:

I'm using react-map-gl version 5.0.8, on ssr boilerplate https://github.com/Brigad/ssr-starter-pack.
the map not appear just grey.
![Screen Shot 2019-08-13 at 13 30 54](https://user-images.githubusercontent.com/5379215/62920083-dd95b780-bdce-11e9-8da9-837c3cce008b.png)

on the console

![Screen Shot 2019-08-13 at 13 33 31](https://user-images.githubusercontent.com/5379215/62920146-0f0e8300-bdcf-11e9-8373-6cfa1c8ddd9c.png)

 function mr(t) {
        return "object" == (typeof t === 'undefined' ? 'undefined' : _typeof(t)) && null !== t && !Array.isArray(t);
    }

**Comment by Pessimistress** [comment]
We cannot help you debug minified code. Please share your source if you need help debugging.
