### ISSUE TITLE
TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by samueljshih** [visgl/react-map-gl#881]
Hello!

I am getting this type error that occurs infrequently on certain pageloads:

![Screen Shot 2019-09-06 at 10 26 08 AM](https://user-images.githubusercontent.com/3914560/64447787-038e3f00-d091-11e9-8cf5-7028dc557a91.png)

Seems to happen more on Mobile Safari and Windows Chrome. I'm guessing it could be that somehow the center point isn't getting correctly retrieved from a touch event? 

Code snippet of ReactMapGL usage:

![Screen Shot 2019-09-06 at 10 35 10 AM](https://user-images.githubusercontent.com/3914560/64448214-063d6400-d092-11e9-9891-3a16275b0c6c.png)

Any ideas on why this would be happening? Thank you!

**Comment by Pessimistress** [comment]
We have seen it on some devices... How often are you seeing this? It should be sufficient to just add a sanity check for `offsetCenter`? @xintong

**Comment by nonoumasy** [comment]
same here...
<img width="1440" alt="Screen Shot 2020-11-24 at 7 37 09 AM" src="https://user-images.githubusercontent.com/6312676/100115880-e9708600-2e27-11eb-9c85-450fbe9f6d7f.png">
```
<ReactMapGL
                {...viewport}
                mapboxApiAccessToken={process.env.REACT_APP_MAPBOX_TOKEN}
                mapStyle="mapbox://styles/mapbox/light-v9"
                onViewportChange={viewport => setViewport(viewport)}>

                {props.event.map(item => (
                        <Marker
                            key={item._id}
                            longitude={item.eventLongitude}
                            latitude={item.eventLatitude}
                            offsetLeft={-20} offsetTop={-10}>
                            <div>askldflkdflajsfl</div>
                        </Marker>
                    ))
                }
            </ReactMapGL>
            {/* <div style={{ position: 'absolute', right: 0}}>
                <NavigationControl />
            </div>
            <div style={{ position: 'absolute', right: 0 }}>
                <FullscreenControl />
            </div> */}
```
