### ISSUE TITLE
Markers: onDragEnd not fired in browsers' desktop mode

### ISSUE THREAD

**Issue by derwaldgeist** [visgl/react-map-gl#889]
I've implemented a draggable marker. It works well if the browser is set to "mobile" mode in the developer tools.

However, if I view the page with the (regular) desktop display, the Marker won't fire onDragEnd and thus jumps back to its original position (because the view-port isn't been updated).

Tested with Chrome and Firefox on macOS.

**Comment by valdote** [comment]
I have the same problem, I have no problem when I use the touch mode but when I use the mause it doesn't always let me drag it

**Comment by valdote** [comment]
I have the same problem, I have no problem when I use the touch mode but when I use the mouse, it doesn't always let me drag it

**Comment by Pessimistress** [comment]
Can you reproduce the issue on [this example](https://uber.github.io/react-map-gl/#/Examples/draggable-marker)?

**Comment by semy** [comment]
@Pessimistress This should not be closed, the bug still exists.

**Comment by Pessimistress** [comment]
@semy The issue was inactive for 9 months. I cannot reproduce the issue unless someone provides more information than "it doesn't work."

**Comment by semy** [comment]
@Pessimistress Okay tested it a little bit...

If you use `<svg ...>...</svg>` inside the marker it works. If you use `<img ... />` it does not work.

Does this helps?

**Comment by Pessimistress** [comment]
@semy Have you set the [draggable](https://html.spec.whatwg.org/multipage/dnd.html#the-draggable-attribute) attribute to `false`? This library cannot override default browser behavior.
