### ISSUE TITLE
Display driving directions

### ISSUE THREAD

**Issue by anil32** [visgl/react-map-gl#982]
how can I add display driving directions like  https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/    ?   I only see  Is it possible to display routes
#591 at issues but it is not enough for me , I need more detail.

**Comment by aasutossh** [comment]
Have you managed to solve this? @anil32

**Comment by Pessimistress** [comment]
You can call `addControl` via the [getMap](http://visgl.github.io/react-map-gl/docs/api-reference/static-map#getmap) API.
