### ISSUE TITLE
Right click twice grabs map outside of the component (safari)

### ISSUE THREAD

**Issue by laserchicken** [visgl/react-map-gl#986]
Hey, I found a weird issue which seems to be present only in safari (I'm on 13.0.3).
If you right-click twice somewhere outside the map component, it grabs the map and allows you to move it (see below).

![Large GIF (1320x1000)](https://user-images.githubusercontent.com/5850443/72151455-8eb57380-33a8-11ea-9748-38c30ec1b998.gif)

You can reproduce it on https://uber.github.io/react-map-gl/#/Examples/custom-cursor.

Thanks!

**Comment by Pessimistress** [comment]
This is no longer an issue in v7.0.
