### ISSUE TITLE
New container style for marker is breaking marker rotation applied using css transform

### ISSUE THREAD

**Issue by konstantinoskouk90** [visgl/react-map-gl#989]
Recently updated to `v5.2.1.` from `v5.1.1.`

[This](https://github.com/uber/react-map-gl/pull/949/commits/4b11b0477f5831c61eb1a3d51f2f2f10d8da7a8f) commit, a marker component improvement has introduced `transform` as a way to set the longitude and latitude of a marker on the map. However this doesn't allow for transform to be used as a class now, as it gets overrode by the new inline css in the commit mentioned above.

The code used to look like this:

```
const containerStyle = {
  position: 'absolute',
  left: x,
  top: y,
  cursor: draggable ? (dragPos ? 'grabbing' : 'grab') : 'auto'
};
```

Now it looks like this:

```
const containerStyle = {
  position: 'absolute',
  left: 0,
  top: 0,
  transform,
  cursor: draggable ? (dragPos ? 'grabbing' : 'grab') : 'auto'
};
```

When dynamically appending a class such as `transform: rotate-${bearing}` to rotate the marker, the styles are never applied because transform is applied inline and overrides everything else. The only way to override is to dynamically append the rotation property to the already existing transform value, after the DOM renders, which I find quite risky and expensive.

Would you consider offering the ability to add your own custom rotation via a prop for markers? For example via a prop called `bearing` or `rotate`? Or maybe another way to make something like this work?

Generally inline styling isn't that big an issue, but due to the nature of the transform property (needing all values when assigned first time round), this is unfortunately causing issues when rotating.

**Comment by Pessimistress** [comment]
The original design is that you should style the child component of `Marker`, not `Marker` itself, since we do need full control of the container styles in order to position it correctly.

We could consider adding a `style` prop to all control components and incorporate them during render. This might introduce even more new edge cases though.
